package com.grcarmenaty.lifegame.domain.dialogue.lines

import com.grcarmenaty.lifegame.domain.dialogue.*

/**
 * Coach — tactical-sports stance. Voice: reps, plays, film, W's.
 * Whitelisted for lapse + attention-loss callouts.
 */
internal object CoachLines {

    private const val A = "COACH"

    val all: List<DialogueLine> = listOf(

        // -------- OPENER --------
        DialogueLine("co_first_ever", A, "First day on the team. Let's set a baseline. Go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation)),
        DialogueLine("co_morning", A, "Morning. Here's the slate. Pick your target.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "co_greet", cooldownPicks = 3),
        DialogueLine("co_morning_early", A, "Early call. First on the field is half the game. Warm up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "co_greet", cooldownPicks = 3),
        DialogueLine("co_afternoon", A, "Halftime check. Score's not on the board yet. Make a play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "co_greet", cooldownPicks = 3),
        DialogueLine("co_evening", A, "Fourth quarter. Don't coast — close out clean.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "co_greet", cooldownPicks = 3),
        DialogueLine("co_night_late", A, "Late tape session. Either watch the film or get sleep — both are training.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "co_greet", cooldownPicks = 3),
        DialogueLine("co_after_lapse", A, "Off day yesterday. Today's the run. Let's go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("co_post_apotheosis", A, "That's a W. Bank it. Tomorrow we raise the bar.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h)),
        DialogueLine("co_wishes_pending", A, "Recovery's earned. Use it. Don't bank it stale.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "co_wish_nudge", cooldownPicks = 4),
        DialogueLine("co_streak", A, "Three days locked in. This is when it gets real. Stay.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "co_streak", cooldownPicks = 5),

        // -------- OPENER · day of week --------
        DialogueLine("co_monday", A, "Game week. Practices count double. Show up to all of them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "co_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK),
        DialogueLine("co_friday", A, "Last practice of the week. Don't phone it in — game day's only as good as the prep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "co_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK),
        DialogueLine("co_weekend", A, "Off-day work. Easy reps. Active recovery beats lying flat.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "co_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY),

        // -------- OPENER · per-level --------
        DialogueLine("co_level_1_reached", A, "Rookie tier. Promotion is real — earn the next one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "co_level_xform", cooldownPicks = 999),
        DialogueLine("co_level_2_reached", A, "Starter status. You're on the roster they actually play. Don't fumble it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "co_level_xform", cooldownPicks = 999),
        DialogueLine("co_level_3_reached", A, "Captain material now. People are looking at how you train.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "co_level_xform", cooldownPicks = 999),
        DialogueLine("co_level_4_reached", A, "Hall of Fame range. Doesn't mean retire. Means raise the floor for the rest of us.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "co_level_xform", cooldownPicks = 999),

        // -------- OPENER · attention loss --------
        DialogueLine("co_attention_loss_mild", A, "Lost some yards. Not the game. Next play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "co_atten_loss", cooldownPicks = 2),
        DialogueLine("co_attention_loss_hard", A, "Rough week of film. We're back to fundamentals. One rep. Then the next.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "co_atten_loss", cooldownPicks = 2),

        // -------- OPENER · holidays --------
        DialogueLine("co_sant_jordi", A, "Sant Jordi. Tradition's good for the squad. Buy the book, run the rep, then go enjoy it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "co_holiday", cooldownPicks = 1),
        DialogueLine("co_la_merce", A, "Mercè week. Light load, then enjoy the city. We don't break rhythm — we just adjust it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "co_holiday", cooldownPicks = 1),
        DialogueLine("co_sant_joan", A, "Sant Joan. Late night incoming. Front-load the work. Tomorrow's a recovery day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "co_holiday", cooldownPicks = 1),
        DialogueLine("co_diada", A, "Diada. Off-day. Active recovery — one easy rep counts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "co_holiday", cooldownPicks = 1),
        DialogueLine("co_nadal", A, "Christmas. Family time wins. Pick the smallest possible rep, log it, then go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "co_holiday", cooldownPicks = 1),
        DialogueLine("co_cap_d_any", A, "New season. Same fundamentals. Don't reinvent — just show up tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "co_holiday", cooldownPicks = 1),

        // -------- OPENER · birthday + personal date --------
        DialogueLine("co_birthday", A, "Birthday. Lighter session. Cake counts as carbs. Tomorrow we run.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "co_birthday", cooldownPicks = 1),
        DialogueLine("co_personal_date", A, "You flagged today: {label}. Roster adjusted. Take what you need.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "co_personal", cooldownPicks = 1),

        // -------- COMPLETION --------
        DialogueLine("co_complete_1", A, "Rep counted. Reset. Go again.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("co_complete_2", A, "Tight execution. Stack another.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("co_complete_3", A, "Good rep. Now do it better.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("co_complete_first_today", A, "Opening drive. We're on the board.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "co_first_today", cooldownPicks = 6),
        DialogueLine("co_complete_second_today", A, "Second possession. Build the lead.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "co_2_today", cooldownPicks = 6),
        DialogueLine("co_complete_third_today", A, "Three drives. Tempo is yours. Press it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "co_3_today", cooldownPicks = 6),
        DialogueLine("co_complete_fourth_today", A, "Four. You're not the underdog anymore. Play like it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "co_4_today", cooldownPicks = 6),
        DialogueLine("co_complete_fifth_today", A, "Five. Game's in hand. Don't run up the score — protect the lead.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "co_5_today", cooldownPicks = 1),

        // -------- APOTHEOSIS --------
        DialogueLine("co_apotheosis_1", A, "You closed it out. Promotion earned.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("co_apotheosis_2", A, "Game over — championship behavior.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("co_apotheosis_3", A, "Tape's going in the highlight reel. Next assignment?",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("co_apotheosis_first_ever", A, "First W. Frame it; talk about it; chase the next one.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1)),
        DialogueLine("co_apotheosis_at_level_2", A, "You're a starter now. Treat practice that way.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "co_apotheosis_levelband", cooldownPicks = 3),
        DialogueLine("co_apotheosis_at_level_3", A, "Veteran tier. You set the standard — raise it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "co_apotheosis_levelband", cooldownPicks = 3),
        DialogueLine("co_apotheosis_at_level_4", A, "Top of the league. Now the only opponent is who you were yesterday.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "co_apotheosis_levelband", cooldownPicks = 3),

        // -------- NUDGE --------
        DialogueLine("co_nudge_morning", A,
            "Morning. Game plan. Pick your target.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "co_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("co_nudge_afternoon_zero", A,
            "Clock check. Zero on the board. Run a play.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "co_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("co_nudge_evening", A,
            "Final quarter. One rep before the buzzer.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "co_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("co_nudge_lapse", A,
            "Off day yesterday. Today's the run. Let's go.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("co_nudge_attention_loss", A,
            "Bad film week. We don't fix it with a press conference. One rep. Now.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "co_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true),
    )
}
