package com.grcarmenaty.lifegame.domain.dialogue.lines

import com.grcarmenaty.lifegame.domain.dialogue.DialogueLine

/**
 * Flat corpus aggregated from per-archetype line files. Loaded once at
 * app start as a `val`. Lint enforces id uniqueness; engine sees a
 * single read-only list.
 */
object DialogueCorpus {
    val all: List<DialogueLine> = listOf(
        DrillSergeantLines.all,
        OracleLines.all,
        GentleMentorLines.all,
        TricksterLines.all,
        StoicLines.all,
        CheerleaderLines.all,
        PoetLines.all,
        TherapistLines.all,
        CoachLines.all,
        HermitLines.all,
        // v0.0.12 themed packs. Each pack mirrors the base archetype's
        // structure (60 lines) with theme-specific vocabulary; the
        // engine filters by `DialogueLine.theme`.
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantExerciseLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantSleepLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantNutritionLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantHydrationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantTidynessLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantFinancesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantCareerLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantLearningLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantWritingLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantMeditationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantLoveLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantFamilyLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantFriendshipLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantGratitudeLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantHobbiesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantOutdoorsLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantDigitalLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantAdminLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantRecoveryLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .DrillSergeantBoundariesLines.all,
        // Gentle Mentor themed packs.
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorExerciseLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorSleepLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorNutritionLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorHydrationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorTidynessLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorFinancesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorCareerLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorLearningLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorWritingLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorMeditationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorLoveLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorFamilyLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorFriendshipLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorGratitudeLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorHobbiesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorOutdoorsLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorDigitalLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorAdminLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorRecoveryLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .GentleMentorBoundariesLines.all,
        // Oracle themed packs.
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleExerciseLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleSleepLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleNutritionLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleHydrationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleTidynessLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleFinancesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleCareerLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleLearningLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleWritingLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleMeditationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleLoveLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleFamilyLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleFriendshipLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleGratitudeLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleHobbiesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleOutdoorsLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleDigitalLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleAdminLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleRecoveryLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .OracleBoundariesLines.all,
        // Stoic themed packs.
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicExerciseLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicSleepLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicNutritionLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicHydrationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicTidynessLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicFinancesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicCareerLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicLearningLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicWritingLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicMeditationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicLoveLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicFamilyLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicFriendshipLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicGratitudeLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicHobbiesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicOutdoorsLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicDigitalLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicAdminLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicRecoveryLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .StoicBoundariesLines.all,
        // Cheerleader themed packs.
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderExerciseLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderSleepLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderNutritionLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderHydrationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderTidynessLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderFinancesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderCareerLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderLearningLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderWritingLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderMeditationLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderLoveLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderFamilyLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderFriendshipLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderGratitudeLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderHobbiesLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderOutdoorsLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderDigitalLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderAdminLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderRecoveryLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .CheerleaderBoundariesLines.all,
        // Trickster themed packs.
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .TricksterExerciseLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .TricksterSleepLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .TricksterNutritionLines.all,
        com.grcarmenaty.lifegame.domain.dialogue.lines.themed
            .TricksterHydrationLines.all,
    ).flatten()
}
