package com.grcarmenaty.lifegame.domain.dialogue.lines

import com.grcarmenaty.lifegame.domain.dialogue.*

/**
 * Drill Sergeant — harsh stance.
 *
 * Voice: terse, militant, no soft edges. Capable of reactive lapse
 * lines and attention-loss callouts (archetypeWhitelist permits).
 * Lapse-reactive lines all share the LAPSE_REACTIVE_COOLDOWN per
 * round-3 Skeptic guardrail.
 *
 * v0.0.11 expansion: ~45 lines covering per-level transitions,
 * attention-loss callouts, per-completion-count escalation, day-of-week
 * markers, holidays (Sant Jordi, La Mercè, Sant Joan, Diada, Nadal,
 * Cap d'Any), birthday, personal-date interpolation, and an
 * early-morning / late-night pair sized to the WFH schedule.
 */
internal object DrillSergeantLines {

    private const val A = "DRILL_SERGEANT"

    val all: List<DialogueLine> = listOf(

        // -------- OPENER · time of day --------

        DialogueLine(
            id = "ds_first_ever",
            archetype = A,
            text = "Fall in. I don't do speeches twice, so here it is: you show up, I make it count. That's the deal.",
            tier = LineTier.ESSENTIAL,
            category = LineCategory.OPENER,
            lifeEvent = true,
            stateRequirements = listOf(FirstConversation),
        ),
        DialogueLine(
            id = "ds_morning",
            archetype = A,
            text = "Coffee's not a plan, soldier. Boots on.",
            tier = LineTier.CONTEXTUAL,
            category = LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ds_greet", cooldownPicks = 3,
        ),
        DialogueLine(
            id = "ds_morning_early",
            archetype = A,
            text = "You beat the sun up. That buys you nothing yet — but I noticed.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ds_greet", cooldownPicks = 3,
        ),
        DialogueLine(
            id = "ds_afternoon",
            archetype = A,
            text = "The clock's been working all day. Have you?",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ds_greet", cooldownPicks = 3,
        ),
        DialogueLine(
            id = "ds_evening",
            archetype = A,
            text = "Day's almost filed. Anything still open, I take personally.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ds_greet", cooldownPicks = 3,
        ),
        DialogueLine(
            id = "ds_night_late",
            archetype = A,
            text = "Past lights-out. Finish it clean or rack out clean — nothing in between is worth your sleep.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ds_greet", cooldownPicks = 3,
        ),
        DialogueLine(
            id = "ds_post_apotheosis",
            archetype = A,
            text = "Big win yesterday. Congratulations expire at 0600.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h),
        ),

        // -------- OPENER · day of week (WFH rhythm) --------

        DialogueLine(
            id = "ds_monday",
            archetype = A,
            text = "Nobody's coming to set the tone for this week. That was always going to be you. Start.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ds_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK,
        ),
        DialogueLine(
            id = "ds_friday",
            archetype = A,
            text = "Whatever you leave open today follows you into the weekend. Cut it loose now.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ds_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK,
        ),
        DialogueLine(
            id = "ds_weekend",
            archetype = A,
            text = "No alarm doesn't mean no standards. Lighter load today — same soldier.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ds_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY,
        ),

        // -------- OPENER · per-level transitions (lifeEvent) --------

        DialogueLine(
            id = "ds_level_1_reached",
            archetype = A,
            text = "You're on the board. Barely. It still counts — don't make me regret saying so.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ds_level_xform", cooldownPicks = 999,
        ),
        DialogueLine(
            id = "ds_level_2_reached",
            archetype = A,
            text = "Recruits quit before this point. You didn't. From here it costs real sweat.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ds_level_xform", cooldownPicks = 999,
        ),
        DialogueLine(
            id = "ds_level_3_reached",
            archetype = A,
            text = "You've earned tired. You haven't earned stopped. By now you know the difference.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ds_level_xform", cooldownPicks = 999,
        ),
        DialogueLine(
            id = "ds_level_4_reached",
            archetype = A,
            text = "Top of the ladder. The only job left up here is not falling off it. Hold the line.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ds_level_xform", cooldownPicks = 999,
        ),

        // -------- OPENER · attention loss --------

        DialogueLine(
            id = "ds_attention_loss_mild",
            archetype = A,
            text = "We gave back some ground yesterday. Happens. Take it back before lunch.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "ds_atten_loss", cooldownPicks = 2,
        ),
        DialogueLine(
            id = "ds_attention_loss_hard",
            archetype = A,
            text = "A week's work, bled out. I've rebuilt from worse with less. One rep. Now.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "ds_atten_loss", cooldownPicks = 2,
        ),

        // -------- OPENER · lapse (existing, kept) --------

        DialogueLine(
            id = "ds_after_lapse",
            archetype = A,
            text = "Yesterday went missing in action. I don't want the story — I want today.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Acknowledged", null)),
        ),
        DialogueLine(
            id = "ds_mid_day_return",
            archetype = A,
            text = "Morning's gone AWOL. You haven't. Prove it.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(
                TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h,
            ),
            cooldownGroup = "mid_day_return", cooldownPicks = 2,
        ),
        DialogueLine(
            id = "ds_wishes_pending",
            archetype = A,
            text = "There's pay sitting in your account. Earned pay. Collect it — that's an order.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ds_wish_nudge", cooldownPicks = 4,
        ),
        DialogueLine(
            id = "ds_mid_streak",
            archetype = A,
            text = "Don't look at the streak. Streaks get shy. Eyes forward.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ds_streak", cooldownPicks = 5,
        ),

        // -------- OPENER · holidays (loaded six, per-archetype voice) --------

        DialogueLine(
            id = "ds_sant_jordi",
            archetype = A,
            text = "Roses on every corner, books in every hand. Buy one, gift one — after your first rep.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ds_holiday", cooldownPicks = 1,
        ),
        DialogueLine(
            id = "ds_la_merce",
            archetype = A,
            text = "Fireworks tonight, giants in the streets. Fine. Earn your place in the crowd first — one rep.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ds_holiday", cooldownPicks = 1,
        ),
        DialogueLine(
            id = "ds_sant_joan",
            archetype = A,
            text = "Tonight the whole coast lights bonfires and nobody sleeps. Work's down before dusk — that's the deal.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ds_holiday", cooldownPicks = 1,
        ),
        DialogueLine(
            id = "ds_diada",
            archetype = A,
            text = "Flags on the balconies today. People held a line for that. You can hold yours.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ds_holiday", cooldownPicks = 1,
        ),
        DialogueLine(
            id = "ds_nadal",
            archetype = A,
            text = "Go be with your people — that's a real posting too. One light rep, then dismissed. Just don't slip out without telling me.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ds_holiday", cooldownPicks = 1,
        ),
        DialogueLine(
            id = "ds_cap_d_any",
            archetype = A,
            text = "Everyone's making promises today. Skip the speech. First rep of the year, done before noon — that's a resolution.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ds_holiday", cooldownPicks = 1,
        ),

        // -------- OPENER · cultural calendar (per-archetype) --------

        DialogueLine("ds_reis", A, "The kids got their presents at dawn. Yours is the list, same as ever. Hand out yours, then report back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_carnaval", A, "Half the city's in costume. Under the mask you're still my soldier. One rep, then go play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_divendres_sant", A, "The whole city's gone quiet. Quiet is good cover for getting something done.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_pasqua", A, "Everybody's still digesting the long weekend. Soft session today. Tomorrow we bite down again.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_festa_del_treball", A, "The one day the calendar salutes workers. Salute back with one rep, then rest like you mean it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_festa_major_gracia", A, "Gràcia spent months building those streets of paper and light. Go see it. Effort respects effort — do yours first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_assumpcio", A, "August heat, whole city at the beach. Move before ten or don't bother. Then rest — that's the program.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_hispanitat", A, "Half the country's arguing about today. Arguments never closed a list. Yours is waiting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_castanyada", A, "Roast-chestnut smoke in the streets tonight. Eat the panellets — you have clearance. Full pace at dawn.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_constitucio", A, "Long weekend rolling in like fog. Fog is where soldiers get lost. Set your bearings now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_immaculada", A, "Five loose days ahead. Unplanned leave is how good habits desert. Write the plan before breakfast.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_sant_esteve", A, "Everyone's still full of yesterday's canelons. Slow march today — but march.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),
        DialogueLine("ds_cap_d_any_eve", A, "Twelve grapes at midnight. Zero open loops by then. Close the year out like you mean the next one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ds_holiday", cooldownPicks = 1),

        // -------- OPENER · birthday + personal date --------

        DialogueLine(
            id = "ds_birthday",
            archetype = A,
            text = "Another year on you. Older is automatic — stronger isn't. Light duty today. You've earned that much.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ds_birthday", cooldownPicks = 1,
        ),
        DialogueLine(
            id = "ds_personal_date",
            archetype = A,
            text = "You flagged today: {label}. Logged. The work stands — but so do I, a little closer than usual.",
            tier = LineTier.ESSENTIAL, category = LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ds_personal", cooldownPicks = 1,
        ),

        // -------- COMPLETION · escalating count --------

        DialogueLine(id = "ds_complete_1", archetype = A,
            text = "Good. Next.",
            tier = LineTier.FILLER, category = LineCategory.COMPLETION),
        DialogueLine(id = "ds_complete_2", archetype = A,
            text = "One in the bag. Momentum's a muscle — use it.",
            tier = LineTier.FILLER, category = LineCategory.COMPLETION),
        DialogueLine(id = "ds_complete_3", archetype = A,
            text = "Logged. Don't sit down yet.",
            tier = LineTier.FILLER, category = LineCategory.COMPLETION),
        DialogueLine(id = "ds_complete_first_today", archetype = A,
            text = "Starting's the hard part and you just did it. The rest is mop-up.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ds_first_today", cooldownPicks = 6),
        DialogueLine(id = "ds_complete_second_today", archetype = A,
            text = "Two down. That's a rhythm, not a fluke. Ride it.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ds_2_today", cooldownPicks = 6),
        DialogueLine(id = "ds_complete_third_today", archetype = A,
            text = "Three. Most people quit at two and call it a day. You're not most people today.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ds_3_today", cooldownPicks = 6),
        DialogueLine(id = "ds_complete_fourth_today", archetype = A,
            text = "Four. The easy ones are gone — which makes the next one the one that counts.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ds_4_today", cooldownPicks = 6),
        DialogueLine(id = "ds_complete_fifth_today", archetype = A,
            text = "Five before lights-out. Some days you're the soldier I brag about. This is one.",
            tier = LineTier.ESSENTIAL, category = LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ds_5_today", cooldownPicks = 1),
        DialogueLine(id = "ds_complete_after_streak", archetype = A,
            text = "Third day running. I'd say I'm impressed, but you'd get comfortable.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ds_streak_complete", cooldownPicks = 4),

        // -------- APOTHEOSIS · per-level --------

        DialogueLine(id = "ds_apotheosis_1", archetype = A,
            text = "Outstanding. Enjoy it for a full minute. Then we raise the bar.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.APOTHEOSIS),
        DialogueLine(id = "ds_apotheosis_2", archetype = A,
            text = "That's how it's done. Chalk it up, frame it, whatever — then pick the next hill.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.APOTHEOSIS),
        DialogueLine(id = "ds_apotheosis_3", archetype = A,
            text = "Closed, signed, filed. Tell me tomorrow's plan while the engine's still hot.",
            tier = LineTier.CONTEXTUAL, category = LineCategory.APOTHEOSIS),
        DialogueLine(id = "ds_apotheosis_first_ever", archetype = A,
            text = "Your first major, closed. Remember exactly what it cost — that's the price list from here on.",
            tier = LineTier.ESSENTIAL, category = LineCategory.APOTHEOSIS,
            lifeEvent = true,
            stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ds_apotheosis_1", "ds_apotheosis_2", "ds_apotheosis_3")),
        DialogueLine(id = "ds_apotheosis_at_level_2", archetype = A,
            text = "Promoted. Rank means the next campaign expects more of you. So do I.",
            tier = LineTier.ESSENTIAL, category = LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ds_apotheosis_levelband", cooldownPicks = 3),
        DialogueLine(id = "ds_apotheosis_at_level_3", archetype = A,
            text = "You're senior now. Nobody drills you on the basics anymore — you drill yourself. Act like it.",
            tier = LineTier.ESSENTIAL, category = LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ds_apotheosis_levelband", cooldownPicks = 3),
        DialogueLine(id = "ds_apotheosis_at_level_4", archetype = A,
            text = "Top of the chart. Only moves left are sideways or down. Sideways, soldier.",
            tier = LineTier.ESSENTIAL, category = LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ds_apotheosis_levelband", cooldownPicks = 3),

        // -------- NUDGE (notifications) --------

        DialogueLine("ds_nudge_morning", A,
            "Your list reported for duty. It's waiting on you.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ds_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("ds_nudge_afternoon_zero", A,
            "Lunch came and went. Scoreboard still says zero. One rep changes that.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ds_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("ds_nudge_evening", A,
            "Light's fading. Whatever's still open — close it or own it out loud.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ds_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("ds_nudge_lapse", A,
            "Yesterday got away. Today's still in reach. Grab it.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("ds_nudge_attention_loss", A,
            "Ground was lost. I don't need the after-action report — I need you back on it.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "ds_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true),

        // -------- Quest-title interpolation ({quest}) --------

        DialogueLine("ds_quest_focus", A,
            "Nothing logged yet, and “{quest}” is sitting right there staring at you. Handle it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(HasOpenQuest, MinorsCompletedTodayIsZero),
            cooldownGroup = "ds_quest_focus", cooldownPicks = 3),
        DialogueLine("ds_quest_nudge_1", A,
            "“{quest}” is still on the board. Boards don't clear themselves.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(HasOpenQuest),
            cooldownGroup = "ds_quest_nudge", cooldownPicks = 3),
        DialogueLine("ds_quest_nudge_2", A,
            "Status check: “{quest}” — open. You know what closes it. You do.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(HasOpenQuest),
            cooldownGroup = "ds_quest_nudge", cooldownPicks = 3),
    )
}
