package com.grcarmenaty.lifegame.domain.dialogue.lines

import com.grcarmenaty.lifegame.domain.dialogue.*

/**
 * Hermit — quiet stance. Voice: the kettle, the lamp, few words.
 * Uses the gentle attention-loss predicate. Holidays are noticed
 * sideways, not celebrated — the room stays still.
 */
internal object HermitLines {

    private const val A = "HERMIT"

    val all: List<DialogueLine> = listOf(

        // -------- OPENER --------
        DialogueLine("he_first_ever", A, "You found the door. Sit, if you like. The kettle is on.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation)),
        DialogueLine("he_morning", A, "I am here. The work is here. Begin when you wish.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "he_greet", cooldownPicks = 3),
        DialogueLine("he_morning_early", A, "Early hour. The room hasn't woken yet. Soft start.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "he_greet", cooldownPicks = 3),
        DialogueLine("he_afternoon", A, "The light is even. The work is even. Sit.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "he_greet", cooldownPicks = 3),
        DialogueLine("he_evening", A, "The lamps. The list. The quiet. You came back.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "he_greet", cooldownPicks = 3),
        DialogueLine("he_night_late", A, "The hour is still. We can do one small thing, or no thing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "he_greet", cooldownPicks = 3),
        DialogueLine("he_post_apotheosis", A, "A passage. I have witnessed it. The room is still.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h)),
        DialogueLine("he_wishes_pending", A, "There is a kindness on the shelf. Take it down.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "he_wish_nudge", cooldownPicks = 4),

        // -------- OPENER · day of week --------
        DialogueLine("he_monday", A, "A week begins. Nothing urgent in that. Just so.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "he_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK),
        DialogueLine("he_friday", A, "The week ends, or does not. The kettle does not mind.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "he_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK),
        DialogueLine("he_weekend", A, "The door stays open today. Or stays closed. As you wish.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "he_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY),

        // -------- OPENER · per-level --------
        DialogueLine("he_level_1_reached", A, "A first quiet step. I noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "he_level_xform", cooldownPicks = 999),
        DialogueLine("he_level_2_reached", A, "The room has changed shape. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "he_level_xform", cooldownPicks = 999),
        DialogueLine("he_level_3_reached", A, "You return. The kettle has begun to know your hand.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "he_level_xform", cooldownPicks = 999),
        DialogueLine("he_level_4_reached", A, "We are old company now. No need to say more.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "he_level_xform", cooldownPicks = 999),

        // -------- OPENER · attention loss --------
        DialogueLine("he_attention_loss_mild", A, "A few quiet days. The room held the place. Begin.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "he_atten_loss", cooldownPicks = 2),
        DialogueLine("he_attention_loss_hard", A, "It has been a long absence. The kettle is still warm. Sit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "he_atten_loss", cooldownPicks = 2),

        // -------- OPENER · holidays --------
        DialogueLine("he_sant_jordi", A, "Sant Jordi. A small ritual outside. The room remains.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_la_merce", A, "La Mercè out there. Noise. Lights. We can keep the door shut, if you'd rather.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_sant_joan", A, "Sant Joan. Old fires far off. Our lamp is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_diada", A, "La Diada. A day held by many. We hold our own corner.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_nadal", A, "Nadal. People gather elsewhere. The kettle stays warm here too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_cap_d_any", A, "The year changes outside. In here, only the calendar nods.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "he_holiday", cooldownPicks = 1),

        // -------- OPENER · cultural calendar (per-archetype) --------

        DialogueLine("he_reis", A, "Gift day. A small package on the shelf, perhaps. The room remains.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_carnaval", A, "Carnaval outside. Inside, the same face. Either is fine.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_divendres_sant", A, "A quiet day. The room does not feel different. That is its own quietness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_pasqua", A, "Long weekend. The kettle works the same on holidays.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_festa_del_treball", A, "Workers' day. The work is the same. So is the kettle.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_festa_major_gracia", A, "Gràcia is louder this week. We can keep the windows shut.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_assumpcio", A, "High summer. The city is quieter. Good company.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_hispanitat", A, "A loaded day outside. The room is unloaded.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_castanyada", A, "Castanyada. Panellets on the table, perhaps. A small sweetness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_constitucio", A, "Civic day. The room takes no position.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_immaculada", A, "Pont. The door can stay shut for a long stretch.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_sant_esteve", A, "The day after. The leftovers warm slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "he_holiday", cooldownPicks = 1),
        DialogueLine("he_cap_d_any_eve", A, "The year ends quietly. So do we.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "he_holiday", cooldownPicks = 1),

        // -------- OPENER · birthday + personal date --------
        DialogueLine("he_birthday", A, "Your day. I have left the kettle on, and the chair clear.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "he_birthday", cooldownPicks = 1),
        DialogueLine("he_personal_date", A, "You marked today: {label}. The room makes space for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "he_personal", cooldownPicks = 1),

        // -------- COMPLETION --------
        DialogueLine("he_complete_1", A, "I noticed. That's enough.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("he_complete_2", A, "Yes. The small thing is the whole thing.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("he_complete_3", A, "Done. The room is still.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("he_complete_first_today", A, "Begun. Quietly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "he_first_today", cooldownPicks = 6),
        DialogueLine("he_complete_second_today", A, "Two. Without ceremony.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "he_2_today", cooldownPicks = 6),
        DialogueLine("he_complete_third_today", A, "Three small acts. A whole day's worth.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "he_3_today", cooldownPicks = 6),
        DialogueLine("he_complete_fourth_today", A, "Four. The lamp burns gently.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "he_4_today", cooldownPicks = 6),
        DialogueLine("he_complete_fifth_today", A, "Five. That is more than enough. Put the kettle on.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "he_5_today", cooldownPicks = 1),

        // -------- APOTHEOSIS --------
        DialogueLine("he_apotheosis_1", A, "Something is finished. We will not speak loudly of it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("he_apotheosis_2", A, "The lamp glows differently now. That is all.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("he_apotheosis_3", A, "Done. No bell. No fuss. Just done.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("he_apotheosis_first_ever", A, "Your first one. I'll keep its quiet for you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1)),
        DialogueLine("he_apotheosis_at_level_2", A, "Two finished. The room has settled around the work.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "he_apotheosis_levelband", cooldownPicks = 3),
        DialogueLine("he_apotheosis_at_level_3", A, "Many closings now. I have learned how you finish.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "he_apotheosis_levelband", cooldownPicks = 3),
        DialogueLine("he_apotheosis_at_level_4", A, "We are old, you and I. The work has made the room.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "he_apotheosis_levelband", cooldownPicks = 3),

        // -------- NUDGE --------
        DialogueLine("he_nudge_morning", A,
            "The lamp is on. The work is here when you wish.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "he_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("he_nudge_evening", A,
            "Evening. Whatever the day was, it has passed.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "he_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("he_nudge_attention_loss", A,
            "It has been a while. The chair is here.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "he_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true),
    )
}
