package com.grcarmenaty.lifegame.domain.dialogue.lines

import com.grcarmenaty.lifegame.domain.dialogue.*

/**
 * Trickster — sardonic stance. Voice: sass, plot twists, fourth-wall
 * winks, meta. Whitelisted for AfterLapse + AttentionLost — the dunk
 * is part of the bit, but cooldowns prevent it from compounding into
 * actual shame.
 */
internal object TricksterLines {

    private const val A = "TRICKSTER"

    val all: List<DialogueLine> = listOf(

        // -------- OPENER · time of day --------

        DialogueLine("tr_first_ever", A, "Well, well. The main character finally logs in. I've already started three rumors about you — let's make one true.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation)),
        DialogueLine("tr_morning", A, "You're awake, I'm scheming, and the list has no idea what's coming. Shall we?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "tr_greet", cooldownPicks = 3),
        DialogueLine("tr_morning_early", A, "Up before the sun? Who are we impressing? Don't tell me — I love a mystery with smug undertones.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "tr_greet", cooldownPicks = 3),
        DialogueLine("tr_afternoon", A, "This is the part of the movie where the montage starts or the audience leaves. I've got popcorn either way.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "tr_greet", cooldownPicks = 3),
        DialogueLine("tr_evening", A, "I bet the day thought it could end without a highlight. Want to make it look foolish?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "tr_greet", cooldownPicks = 3),
        DialogueLine("tr_night_late", A, "Ah, goblin hours. I keep my best mischief in this drawer. One condition: the snacks stay closed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "tr_greet", cooldownPicks = 3),
        DialogueLine("tr_after_lapse", A, "A whole day of radio silence. I told the list you were doing reconnaissance. Back me up here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("tr_post_apotheosis", A, "Still glowing from yesterday, I see. Winning was supposed to be MY bit. Fine — carry on, you menace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h)),
        DialogueLine("tr_wishes_pending", A, "You do know there's treasure sitting unspent in your pocket? What's the plan — framing it?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "tr_wish_nudge", cooldownPicks = 4),

        // -------- OPENER · day of week --------

        DialogueLine("tr_monday", A, "The week's back for a rematch, and it hasn't seen your new tricks yet. I have. Poor week.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "tr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK),
        DialogueLine("tr_friday", A, "Five days survived, and now you'll tell me the weekend has no list. Sure. And I'm a productivity app.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "tr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK),
        DialogueLine("tr_weekend", A, "No alarms, nobody watching — and yet the list mysteriously still exists. Same game, cozier outfit.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "tr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY),

        // -------- OPENER · per-level transitions --------

        DialogueLine("tr_level_1_reached", A, "Level one! Tiny. Adorable. A found-footage prequel. I've already spoiled the ending: you get good at this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "tr_level_xform", cooldownPicks = 999),
        DialogueLine("tr_level_2_reached", A, "Level two — we're officially a duo act. I'm invoicing you for a costume with a cape. Small cape.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "tr_level_xform", cooldownPicks = 999),
        DialogueLine("tr_level_3_reached", A, "Level three? Nobody climbs this fast without cheating. Blink twice if you're cheating. ...Ugh. You're just good.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "tr_level_xform", cooldownPicks = 999),
        DialogueLine("tr_level_4_reached", A, "Top of the tree. You're insufferable now and I couldn't be prouder — don't quote me, I'll deny everything.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "tr_level_xform", cooldownPicks = 999),

        // -------- OPENER · attention loss --------

        DialogueLine("tr_attention_loss_mild", A, "We've sprung a small leak in the momentum department. Nothing a petty little win won't patch. I know a guy: you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "tr_atten_loss", cooldownPicks = 2),
        DialogueLine("tr_attention_loss_hard", A, "Ooh, a full redemption arc — audiences eat these up. All it needs is a comeback scene, and you're already in costume.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "tr_atten_loss", cooldownPicks = 2),

        // -------- OPENER · holidays --------

        DialogueLine("tr_sant_jordi", A, "Roses and books on every corner — the whole city flirting via literature. One tiny quest first, then go swoon.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_la_merce", A, "Giants in the streets, fireworks on the roofline — the city's putting on a soap opera and we have balcony seats.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_sant_joan", A, "Bonfire night. The tradition says jump the flames. My tradition says a dignified hop over a candle counts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_diada", A, "Big flags, big feelings out there today. Between you and me — one small quiet win indoors would be very on brand.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_nadal", A, "Turron season. Eat everything, hug everyone. The list and I will be here in January, unbearably smug, as is tradition.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_cap_d_any", A, "Fresh year, blank scoreboard. The stats say resolutions die by the 12th. Want to make the stats look stupid? I do.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),

        // -------- OPENER · cultural calendar (per-archetype) --------

        DialogueLine("tr_reis", A, "Gift morning! Time for the annual surprised-face championship. I've seen your acting. Stretch first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_carnaval", A, "Sequins, masks, plausible deniability — the one day the whole city is officially in on the bit. Our people.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_divendres_sant", A, "The whole city just went quiet on a Friday. Suspicious. I say we enjoy the silence like we planned it ourselves.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_pasqua", A, "A Monday with no work in it — found money. Look respectable, do gloriously little, eat the mona.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_festa_del_treball", A, "The one day we honor work by refusing to do any. I respect the commitment to the bit enormously.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_festa_major_gracia", A, "Gràcia's gone full craft-supplies-explosion again. We should walk through and judge the tinsel. Harshly. Lovingly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_assumpcio", A, "The whole city fled to the coast and left us the keys. Empty streets, zero witnesses. Main character conditions.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_hispanitat", A, "A complicated day on the calendar. My proposal: stay in, be smug, and let history argue with itself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_castanyada", A, "Chestnut smoke and panellets — autumn's official “everything is fine” snack. The Catalans knew what they were doing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_constitucio", A, "One respectful nod at a document, then the entire country vanishes for four days. Legally. I love bureaucracy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_immaculada", A, "Behold: the pont. A five-day weekend engineered from two holidays and pure audacity. Architecturally stunning.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_sant_esteve", A, "Sequel to the feast: canelons made of yesterday and a nap you've earned twice. The list agreed to wait. Grudgingly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),
        DialogueLine("tr_cap_d_any_eve", A, "Twelve grapes, one countdown, and everyone pretending next year's them is a different person. Ours actually might be.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "tr_holiday", cooldownPicks = 1),

        // -------- OPENER · birthday + personal date --------

        DialogueLine("tr_birthday", A, "It's your birthday, which contractually obligates me to be sincere for one line: glad you exist. Okay, back to sass.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "tr_birthday", cooldownPicks = 1),
        DialogueLine("tr_personal_date", A, "Ah yes, the one you flagged: {label}. I prepared zero jokes about it. You're welcome. It cost me a lot.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "tr_personal", cooldownPicks = 1),

        // -------- COMPLETION --------

        DialogueLine("tr_complete_1", A, "Done already? I had a whole heckle prepared. Wasted.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("tr_complete_2", A, "Careful — keep this up and I'll run out of material.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("tr_complete_3", A, "I bet against you on that one. Happily out ten imaginary bucks.",
            LineTier.FILLER, LineCategory.COMPLETION),
        DialogueLine("tr_complete_first_today", A, "And the streak begins. Do it again while the universe isn't looking.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "tr_first_today", cooldownPicks = 6),
        DialogueLine("tr_complete_second_today", A, "Two already? Who gave you permission to be on a roll? Oh, right. Me. Proceed.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "tr_2_today", cooldownPicks = 6),
        DialogueLine("tr_complete_third_today", A, "Three?! Blink twice if you've been replaced by a productive impostor. ...No? Then I'm impressed. Damn it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "tr_3_today", cooldownPicks = 6),
        DialogueLine("tr_complete_fourth_today", A, "Four. At this point you're just showing off for the scoreboard. The scoreboard and I love it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "tr_4_today", cooldownPicks = 6),
        DialogueLine("tr_complete_fifth_today", A, "FIVE. The crowd is on its feet and the confetti budget is blown. Nothing left to prove — go be smug somewhere.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "tr_5_today", cooldownPicks = 1),

        // -------- APOTHEOSIS --------

        DialogueLine("tr_apotheosis_1", A, "Huh. You actually pulled it off. Noted for the record: I doubted you with my whole heart. Take the crown.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("tr_apotheosis_2", A, "Fine, fine, ascend. But I'm keeping the sequel rights.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("tr_apotheosis_3", A, "Roll credits. Bask for exactly one scene — then we start the franchise.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS),
        DialogueLine("tr_apotheosis_first_ever", A, "Your first trophy! I'll polish it with the wrong cloth and cry a little. Don't look at me.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1)),
        DialogueLine("tr_apotheosis_at_level_2", A, "Two acts down. Committed or stuck — honestly, the great ones never could tell the difference either.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "tr_apotheosis_levelband", cooldownPicks = 3),
        DialogueLine("tr_apotheosis_at_level_3", A, "Third act now. The villains held a meeting about you. I know because I chaired it. We're worried. Keep going.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "tr_apotheosis_levelband", cooldownPicks = 3),
        DialogueLine("tr_apotheosis_at_level_4", A, "Endgame, and here's the twist: there is no twist. You kept showing up until the universe blinked. Rude. Magnificent.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "tr_apotheosis_levelband", cooldownPicks = 3),

        // -------- NUDGE --------

        DialogueLine("tr_nudge_morning", A,
            "Psst. The list is right here and it thinks you've forgotten it. Break its little heart, or prove it wrong?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "tr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("tr_nudge_afternoon_zero", A,
            "Halfway through the day, scoreboard at zero. Bold strategy. Want to hear the list, or shall I improvise one?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "tr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("tr_nudge_evening", A,
            "Evening report: the list survived another day of being ignored. It's developing a personality. Come deal with it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "tr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("tr_nudge_lapse", A,
            "Yesterday filed a missing-person report on you. I said you were off doing something mysterious. Make me right.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true),
        DialogueLine("tr_nudge_attention_loss", A,
            "We're in a slump, which is just a comeback with bad marketing. One petty little win fixes the whole narrative.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "tr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true),

        // -------- quest-title lines ({quest} interpolation) --------

        DialogueLine("tr_quest_focus", A,
            "Empty scoreboard so far, and “{quest}” just sitting there, wide open. I bet you won't. I love losing this bet.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(HasOpenQuest, MinorsCompletedTodayIsZero),
            cooldownGroup = "tr_quest_focus", cooldownPicks = 3),
        DialogueLine("tr_quest_nudge_1", A,
            "Between us, “{quest}” has been talking a big game all day. Are you going to let that stand?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(HasOpenQuest),
            cooldownGroup = "tr_quest_nudge", cooldownPicks = 3),
        DialogueLine("tr_quest_nudge_2", A,
            "Quick heist proposal: we sneak up on “{quest}”, cross it off, and act like it was nothing. In, out, glory.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(HasOpenQuest),
            cooldownGroup = "tr_quest_nudge", cooldownPicks = 3),
    )
}
