package com.grcarmenaty.lifegame.domain.catalog

import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_DAILY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_MONTHLY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_ONE_OFF
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_WEEKLY

/**
 * Admin & life logistics. Paperwork, appointments, what you've been
 * putting off. Six majors, each with six repeating minors (sensible
 * cadence) and six one-off minors (harder, higher weight).
 *
 * Fragments are lower-case completion clauses with no trailing period;
 * the daemon's archetype frame wraps them at completion time.
 */
internal object AdminQuests {
    val majors = listOf(
        CatalogMajor(
            templateId = "admin.inbox",
            title = "Tame the paperwork pile",
            fragment = "the pile that loomed is gone",
            repeating = listOf(
                CatalogMinor("admin.inbox.r.openmail", "Open one piece of post", "one envelope is dealt with",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("admin.inbox.r.sort", "Sort the to-deal-with tray", "the tray is in order",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.inbox.r.file", "File three documents away", "three papers found their home",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.inbox.r.shred", "Shred what you no longer need", "the dead paper is gone",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.inbox.r.reply", "Answer one email you've avoided", "the avoided reply is sent",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("admin.inbox.r.scan", "Scan one document to keep", "the record is saved safely",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.inbox.r.label", "Label one folder clearly", "another folder makes sense now",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.inbox.r.deskclear", "Clear the desk surface of paper", "the desk is paper-free again",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.inbox.r.action", "Action one item off the tray", "one task left the tray for good",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("admin.inbox.r.recycle", "Recycle the junk that came in", "the junk went straight out",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.inbox.r.bills", "Check for any bill in the pile", "no bill is hiding in the stack",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.inbox.r.note", "Jot one to-do from the post", "the task is captured, not lost",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("admin.inbox.o.system", "Set up a filing system that works", "everything now has a place",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.inbox.o.backlog", "Clear the whole backlog tray", "the backlog is finally empty",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.inbox.o.digitise", "Digitise your key documents", "the important papers are backed up",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.inbox.o.unsubpost", "Stop the junk mail at source", "the junk stops arriving now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.inbox.o.shredday", "Spend an afternoon shredding the old", "years of dead paper, gone in a day",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.inbox.o.binder", "Build a household-records binder", "the household has its own ledger now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.inbox.o.gotopaperless", "Switch every bill to paperless", "the post stops piling up at the source",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.inbox.o.archivebox", "Box and label the long-term archive", "the old records are stored and findable",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.inbox.o.emailbacklog", "Clear a years-old email backlog", "the ancient inbox is finally empty",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.inbox.o.naming", "Set a consistent file-naming scheme", "everything is named the same way now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.inbox.o.weeklyhabit", "Run a weekly paperwork hour for a month", "four weeks of staying on top of it",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.inbox.o.purge", "Throw out a whole drawer of dead paper", "a drawer of clutter is gone for good",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "admin.appointments",
            title = "Book what you've been avoiding",
            fragment = "the appointments you dreaded are on the calendar",
            repeating = listOf(
                CatalogMinor("admin.appointments.r.callone", "Make one phone call you've put off", "the call you dreaded is made",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.appointments.r.list", "Write down what needs booking", "the list of bookings is real now",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.appointments.r.confirm", "Confirm an upcoming appointment", "the date is locked in",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.appointments.r.calendar", "Put one thing in the calendar", "it's written where you'll see it",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("admin.appointments.r.prep", "Gather what you'll need for an appointment", "you're ready to walk in prepared",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.appointments.r.followup", "Chase one thing that stalled", "the stalled thing is moving again",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.appointments.r.email", "Send one booking email", "the request is out the door",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.appointments.r.reschedule", "Reschedule something instead of skipping", "you moved it rather than dropped it",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.appointments.r.reminder", "Set a reminder for a booking", "the date won't slip past you",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.appointments.r.questions", "Write down questions for a visit", "you'll remember what to ask",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.appointments.r.attend", "Show up to one booked thing", "you walked in as planned",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.appointments.r.research", "Find the right place to book with", "you know who to call now",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("admin.appointments.o.dentist", "Finally book the dentist", "the long-overdue chair is booked",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.appointments.o.checkup", "Schedule the check-up you've skipped", "the check-up is on the books",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.appointments.o.optician", "Book the eye test you keep delaying", "your eyes get their overdue look",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.appointments.o.clearqueue", "Book three appointments in one sitting", "three dreaded calls, all done at once",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.appointments.o.specialist", "Sort the referral you've been avoiding", "the referral is finally in motion",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.appointments.o.car", "Book the car service that's overdue", "the car gets its overdue care",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.appointments.o.bloodwork", "Get the blood test you've delayed", "the test you avoided is done",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.appointments.o.dermatologist", "Get that mole or skin thing looked at", "the worry got a proper look",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.appointments.o.haircut", "Finally sort the long-overdue haircut", "the chair you kept skipping is booked",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.appointments.o.allbooked", "Get a whole year of check-ups booked", "a year of care is on the calendar",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.appointments.o.therapy", "Book the support you've been meaning to", "you reached out and made the call",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.appointments.o.vet", "Sort the pet's overdue appointment", "the animal gets its overdue care",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "admin.renewals",
            title = "Get your renewals in order",
            fragment = "nothing important is about to lapse",
            repeating = listOf(
                CatalogMinor("admin.renewals.r.checkdates", "Check one document's expiry", "you know when it runs out",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.remind", "Set a reminder for a deadline", "the deadline won't catch you out",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.review", "Review one bill or contract", "you read what you're actually paying for",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.compare", "Compare a renewal against alternatives", "you checked you're not overpaying",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.cancel", "Cancel something you don't use", "one needless cost is gone",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.update", "Update an out-of-date detail", "the record matches reality now",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.calendar", "Add one expiry to the calendar", "the date is somewhere you'll see it",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.read", "Read one renewal letter properly", "you know what they're actually offering",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.autorenew", "Check one auto-renewal you forgot", "the silent charge is accounted for",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.photocopy", "Save a copy of a key document", "the document has a backup now",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.list", "Add an upcoming renewal to the list", "another expiry is written down",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.renewals.r.quote", "Get one fresh quote for comparison", "you have a number to compare against",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("admin.renewals.o.passport", "Renew the passport before it lapses", "the passport is good for years again",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.renewals.o.licence", "Sort the licence renewal", "the licence is current again",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.renewals.o.insurance", "Review all your insurance once", "you know exactly what you're covered for",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.renewals.o.tracker", "Build a renewals tracker", "every expiry lives in one place now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.renewals.o.switch", "Switch a provider to a better deal", "you moved and saved real money",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.renewals.o.warranties", "Gather your warranties in one folder", "the warranties are findable now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.renewals.o.idcard", "Renew the ID card before it expires", "the card is valid for years again",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.renewals.o.reminders", "Set reminders for every renewal at once", "nothing can lapse without warning now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.renewals.o.consolidate", "Move renewals to a single date", "the renewals cluster on one day now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.renewals.o.shopall", "Reprice every recurring contract you hold", "every contract was tested against the market",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.renewals.o.membership", "Sort the membership you keep forgetting", "the lapsed membership is current again",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.renewals.o.vehicle", "Sort the vehicle tax and inspection", "the car is legal and current again",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "admin.money",
            title = "Get the money admin done",
            fragment = "the money side is in order",
            repeating = listOf(
                CatalogMinor("admin.money.r.check", "Check your account balance", "you looked, and you know",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.money.r.receipts", "File one receipt where it belongs", "the receipt is logged",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.money.r.statement", "Read one statement line by line", "the statement holds no surprises",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.money.r.budget", "Update one line of the budget", "the budget reflects this week",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.money.r.paybill", "Pay one bill on time", "the bill is settled, not late",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.money.r.queryone", "Question one charge you don't recognise", "the odd charge is explained",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.money.r.save", "Move a little into savings", "a bit more is set aside",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.money.r.logspend", "Log one day's spending", "the day's outgoings are tracked",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("admin.money.r.noimpulse", "Skip one impulse purchase", "the impulse was let go",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.money.r.category", "Review spending in one category", "you saw where that money goes",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.money.r.roundup", "Tidy one corner of the finances", "another money corner is in order",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("admin.money.o.taxes", "File the tax return early", "the return is done and dusted",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.money.o.directdebits", "Audit every direct debit", "every outgoing is one you chose",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.money.o.statements", "Reconcile a year of statements", "a whole year is accounted for",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.money.o.fund", "Set up an automatic savings transfer", "saving happens without you thinking",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.money.o.claim", "Claim something you're owed", "the money owed to you is on its way",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.money.o.pension", "Check your pension or savings setup", "you know where your future money sits",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.money.o.emergencyfund", "Build a starter emergency fund", "you have a cushion if things go wrong",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.money.o.budgetbuild", "Build a budget you'll actually follow", "the money has a plan you trust",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.money.o.debtplan", "Make a plan to clear a debt", "the way out of the debt is mapped",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.money.o.creditcheck", "Pull and read your credit report", "you know how you look on paper",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.money.o.negotiate", "Negotiate one bill down", "you talked a cost down",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.money.o.invest", "Open and fund an investment account", "your money has somewhere to grow now",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "admin.home",
            title = "Fix the small broken things",
            fragment = "the little nagging faults are mended",
            repeating = listOf(
                CatalogMinor("admin.home.r.onefix", "Mend one small broken thing", "one nagging fault is fixed",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.bulb", "Replace a dead bulb or battery", "the light works again",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.list", "Add a job to the fix-it list", "the job is captured, not forgotten",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.home.r.tighten", "Tighten or oil something that's loose", "the rattle is gone",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.supplies", "Restock one household essential", "you won't run out of it",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.testalarm", "Test the smoke alarm", "the alarm still has your back",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.declutterspot", "Clear one cluttered surface", "another surface is clear again",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.filter", "Clean or change a filter", "the filter is fresh again",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.wipe", "Wipe down a neglected spot", "the grime gave way",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.checkdamp", "Check for damp or leaks", "nothing is quietly going wrong",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.home.r.sharpen", "Maintain one tool or appliance", "the tool works like it should",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("admin.home.o.tradesperson", "Get a tradesperson in for the big job", "the job too big for you is booked",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.home.o.kit", "Assemble a basic toolkit", "you can fix things yourself now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.home.o.deepfix", "Finish the project you abandoned", "the half-done thing is whole",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.home.o.declutter", "Clear out one full cupboard", "the cupboard breathes again",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.home.o.donate", "Take a load to be donated", "what you don't need goes to who does",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.home.o.safety", "Do a home safety check-round", "the home is checked and sound",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.home.o.paint", "Repaint a tired wall or room", "the room looks cared for again",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.home.o.deepclean", "Deep-clean one whole room", "the room is properly clean for once",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.home.o.maintenance", "Build a seasonal maintenance plan", "the home upkeep has a rhythm now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.home.o.emergencykit", "Assemble a home emergency kit", "you're ready if something goes wrong",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.home.o.improve", "Finish a real improvement project", "the home is better than you found it",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.home.o.garage", "Clear and organise the storage space", "the chaos cupboard is usable again",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "admin.future",
            title = "Sort the grown-up basics",
            fragment = "the things adults put off are handled",
            repeating = listOf(
                CatalogMinor("admin.future.r.onestep", "Take one step on a big task", "the big task moved an inch",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("admin.future.r.gather", "Gather one needed document", "another paper is in hand",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.research", "Read up on one thing you'll need to decide", "you understand it a little better",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.contacts", "Update one important contact detail", "the record can reach you",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.ask", "Ask someone who knows for advice", "you stopped guessing and asked",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.note", "Note a decision before you forget the reasons", "the reasoning is on paper",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.breakdown", "Break a big task into smaller steps", "the mountain is a set of steps now",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.deadline", "Set a date for one looming task", "the vague thing has a deadline now",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.draft", "Draft one form or letter", "the draft is started, not dreaded",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.checkprogress", "Review how a long task is going", "you know where the big thing stands",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("admin.future.r.fifteen", "Spend fifteen minutes on the hard thing", "the hard thing got its quarter hour",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("admin.future.o.will", "Sort a basic will", "your wishes are written down properly",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.future.o.emergency", "Build an emergency-info folder", "someone could step in if needed",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.future.o.passwords", "Leave a way into your accounts for family", "the digital keys won't die with you",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.future.o.register", "Register for the thing you've meant to", "you're finally on the list",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("admin.future.o.advisor", "Sit down with a professional once", "you got proper guidance at last",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.future.o.bigtask", "Finish the dreaded grown-up task", "the thing you most avoided is done",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.future.o.poweratorney", "Sort a power of attorney", "someone you trust can act for you now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.future.o.beneficiaries", "Update every beneficiary you've named", "the right people are named everywhere",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.future.o.healthwishes", "Write down your care wishes", "your wishes are clear if it ever matters",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.future.o.lifeadmin", "Run a full life-admin audit", "the whole picture is laid out at last",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("admin.future.o.qualify", "Apply for the qualification you keep delaying", "the application is finally in",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("admin.future.o.bigdecision", "Make the big decision you've been dodging", "the choice you avoided is made",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
    )
}
