package com.grcarmenaty.lifegame.domain.catalog

import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_DAILY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_MONTHLY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_ONE_OFF
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_WEEKLY

/**
 * Career & craft. Six majors, each with six repeating minors (sensible
 * cadence) and six one-off minors (harder, higher weight).
 *
 * Fragments are lower-case completion clauses with no trailing period;
 * the daemon's archetype frame wraps them at completion time.
 */
internal object CareerQuests {
    val majors = listOf(
        CatalogMajor(
            templateId = "career.deepwork",
            title = "Protect time for deep work",
            fragment = "the real work is getting the hours it needs",
            repeating = listOf(
                CatalogMinor("career.deepwork.r.block", "Hold one deep-work block", "the deep block held",
                    CADENCE_DAILY, weight = 2),
                CatalogMinor("career.deepwork.r.phoneaway", "Put the phone out of reach", "the distraction is across the room",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("career.deepwork.r.singletask", "Work on one thing at a time", "you held a single thread",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("career.deepwork.r.startfirst", "Start with the hard task", "the hard thing got the fresh mind",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("career.deepwork.r.shutdown", "Close the day with a shutdown ritual", "the workday has a clean ending",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("career.deepwork.r.notabs", "Resist opening the inbox first thing", "you guarded the morning",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("career.deepwork.o.space", "Set up a distraction-free workspace", "the space is built for focus",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.deepwork.o.block3", "Sustain a three-hour focus session", "three unbroken hours of real work",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.deepwork.o.deepday", "Run a full day of deep work", "a whole day given to the craft",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("career.deepwork.o.blocker", "Set up website and app blockers", "the rabbit holes are fenced off",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("career.deepwork.o.boundaries", "Negotiate focus time with your team", "the calendar protects your craft",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.deepwork.o.shipbig", "Ship a project built in deep work", "deep work put something into the world",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "career.skill",
            title = "Sharpen a core skill of your trade",
            fragment = "you are better at your craft than you were",
            repeating = listOf(
                CatalogMinor("career.skill.r.practice", "Deliberate practice session", "the practice is in",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("career.skill.r.study", "Study how a master does it", "you learned from someone better",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("career.skill.r.drill", "Drill a fundamental", "the basics got a little more solid",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("career.skill.r.reflect", "Note what you learned today", "the lesson is written down",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("career.skill.r.feedback", "Ask for feedback on one thing", "you invited an honest look",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.skill.r.stretch", "Try a technique just past your reach", "you worked at the edge of your skill",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("career.skill.o.course", "Complete a course in your craft", "the course is finished, the skill earned",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("career.skill.o.mentor", "Find a mentor in your field", "someone wiser is in your corner",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.skill.o.teach", "Teach the skill to someone else", "you proved it by passing it on",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.skill.o.project", "Finish a hard portfolio project", "the difficult project is done",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("career.skill.o.assess", "Get an honest skill assessment", "you know exactly where you stand",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("career.skill.o.cert", "Earn a credential in the skill", "the mastery is on paper now",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "career.portfolio",
            title = "Build a body of work to show",
            fragment = "there is real work to point to now",
            repeating = listOf(
                CatalogMinor("career.portfolio.r.make", "Make something small and finish it", "another finished piece exists",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("career.portfolio.r.document", "Document a piece of your work", "the work is captured properly",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.portfolio.r.share", "Share something you made", "you put the work where eyes can find it",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.portfolio.r.refine", "Polish an existing piece", "the work is a notch sharper",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.portfolio.r.collect", "Save a finished thing to the portfolio", "the body of work grew",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.portfolio.r.studynotes", "Study a portfolio you admire", "you learned how good work is shown",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("career.portfolio.o.site", "Build your portfolio site", "the portfolio has a home online",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("career.portfolio.o.case", "Write a full case study", "one project is told start to finish",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.portfolio.o.signature", "Finish a signature piece", "you have a piece that defines you",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("career.portfolio.o.curate", "Curate your best five pieces", "the strongest work leads the way",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("career.portfolio.o.publish", "Publish the portfolio publicly", "the work is out in the open",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.portfolio.o.feature", "Get a piece featured somewhere", "the work was chosen by someone else",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "career.network",
            title = "Grow your professional standing",
            fragment = "your name carries further now",
            repeating = listOf(
                CatalogMinor("career.network.r.reach", "Reach out to one person in your field", "another connection is made",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.network.r.engage", "Comment thoughtfully on others' work", "you joined the conversation",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("career.network.r.help", "Help a peer with something", "you gave before you asked",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.network.r.follow", "Follow up on a warm contact", "the thread didn't go cold",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.network.r.read", "Read what's moving in your field", "you kept current with the craft",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("career.network.r.share", "Share something useful publicly", "you added value where people watched",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("career.network.o.profile", "Polish your professional profile", "your public face does you justice",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("career.network.o.event", "Attend an industry event", "you stood in the room with your peers",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.network.o.talk", "Give a talk or run a session", "you spoke and the room listened",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("career.network.o.coffee", "Have five real informational chats", "five conversations that opened doors",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.network.o.write", "Publish an article in your field", "your thinking is on record now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.network.o.community", "Join and contribute to a community", "you have a community behind you",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "career.direction",
            title = "Get clear on where you're headed",
            fragment = "the path ahead has shape now",
            repeating = listOf(
                CatalogMinor("career.direction.r.review", "Review your week's progress", "the week is honestly assessed",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.direction.r.priority", "Name your top priority for the day", "the day has a clear point",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("career.direction.r.journal", "Reflect on what's energising you", "you noticed what's worth more of you",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("career.direction.r.research", "Research a role or path you're curious about", "you learned more about a possible future",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.direction.r.align", "Check one task against your goals", "the work and the goal still line up",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("career.direction.r.declutter", "Say no to one thing off-path", "you protected your direction",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("career.direction.o.vision", "Write a one-year vision", "where you're going is on paper",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.direction.o.goals", "Set three concrete career goals", "the goals are sharp and named",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("career.direction.o.review", "Do an honest self-review", "you faced the full picture",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.direction.o.conversation", "Have the career talk with your manager", "the conversation is finally had",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("career.direction.o.explore", "Shadow or try a different path", "you tested the road not taken",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.direction.o.plan", "Draft a plan to your next step", "the route to the next step is mapped",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "career.craft",
            title = "Raise the quality of your work",
            fragment = "you hold your work to a higher bar now",
            repeating = listOf(
                CatalogMinor("career.craft.r.review", "Review your own work critically", "you looked at it with clear eyes",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("career.craft.r.refine", "Take one thing past good enough", "you pushed past good enough",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("career.craft.r.learnref", "Study an example of excellence", "you saw what great looks like",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.craft.r.checklist", "Run your quality checklist", "nothing slipped through",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("career.craft.r.cleanup", "Clean up your tools and files", "the workshop is in order",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("career.craft.r.detail", "Sweat one small detail others skip", "the small thing was done right",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("career.craft.o.standard", "Write down your standard of done", "your bar for quality is explicit now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("career.craft.o.toolset", "Master a tool that levels you up", "the tool is now an extension of you",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("career.craft.o.critique", "Submit work for a tough critique", "you took the hard feedback head-on",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.craft.o.remake", "Redo an old piece to your new standard", "the old work meets your new bar",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.craft.o.process", "Document your best working process", "the way you do it well is captured",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("career.craft.o.flagship", "Deliver a piece you're proud of", "you made something you'd sign",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
    )
}
