package com.grcarmenaty.lifegame.domain.catalog

import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_DAILY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_MONTHLY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_ONE_OFF
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_WEEKLY

/**
 * Body & exercise. Six majors, each with six repeating minors (sensible
 * cadence) and six one-off minors (harder, higher weight).
 *
 * Fragments are lower-case completion clauses with no trailing period;
 * the daemon's archetype frame wraps them at completion time.
 */
internal object ExerciseQuests {
    val majors = listOf(
        CatalogMajor(
            templateId = "exercise.run10k",
            title = "Run a 10k",
            fragment = "the ten kilometres are yours",
            repeating = listOf(
                CatalogMinor("exercise.run10k.r.easyrun", "Easy jog", "the easy miles are in",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.run10k.r.longrun", "Weekly long run", "the long run is done",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 2),
                CatalogMinor("exercise.run10k.r.intervals", "Interval session", "the intervals are behind you",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 2),
                CatalogMinor("exercise.run10k.r.stretch", "Post-run stretch", "you cooled down properly",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.run10k.r.steps", "Hit 8k steps", "the steps add up",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.run10k.r.logpace", "Log your pace", "the numbers are written down",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("exercise.run10k.o.5k", "Run a non-stop 5k", "five clean kilometres, unbroken",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.run10k.o.7k", "Push past 7k", "seven kilometres behind you",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.run10k.o.shoes", "Get fitted for running shoes", "your feet are properly shod",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.run10k.o.race", "Sign up for a 10k race", "the start line is booked",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.run10k.o.sub60", "Run 10k under an hour", "ten kilometres under the hour",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.run10k.o.hill", "Conquer a hill route", "the hill didn't win",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "exercise.strength",
            title = "Build a strength base",
            fragment = "you are stronger than you were",
            repeating = listOf(
                CatalogMinor("exercise.strength.r.lift", "Lifting session", "the work sets are done",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 2),
                CatalogMinor("exercise.strength.r.warmup", "Warm up properly", "the joints are ready",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.strength.r.protein", "Hit your protein target", "the body is fed to build",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.strength.r.core", "Ten minutes of core", "the middle held",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("exercise.strength.r.log", "Log your lifts", "the numbers are recorded",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.strength.r.sleep", "Sleep eight hours", "the body got to recover",
                    CADENCE_DAILY, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("exercise.strength.o.bw", "Squat your bodyweight", "the bar matched you and lost",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.strength.o.pullup", "Do your first strict pull-up", "you pulled your own weight up",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.strength.o.plan", "Write a 12-week program", "the plan is on paper",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.strength.o.deadlift", "Deadlift 1.5x bodyweight", "the floor gave you the bar",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.strength.o.form", "Film and fix your form", "the technique is honest now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.strength.o.pushups", "Do 30 push-ups unbroken", "thirty, no rest",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "exercise.movedaily",
            title = "Move every day for a month",
            fragment = "the streak is unbroken",
            repeating = listOf(
                CatalogMinor("exercise.movedaily.r.walk", "Take a 20-minute walk", "you got moving",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.movedaily.r.stairs", "Take the stairs", "you chose the climb",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.movedaily.r.stretchbreak", "Stretch break at your desk", "the stiffness eased",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.movedaily.r.steps", "Reach 7k steps", "the day's steps are met",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.movedaily.r.mobility", "Five-minute mobility flow", "the body is oiled",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.movedaily.r.outside", "Get outside once", "the air did its work",
                    CADENCE_DAILY, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("exercise.movedaily.o.streak30", "Hit a 30-day streak", "thirty days, not one missed",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.movedaily.o.class", "Try a new movement class", "you walked into the unfamiliar",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.movedaily.o.10k", "Walk 10k steps in a day", "ten thousand, in one day",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.movedaily.o.hike", "Take a half-day hike", "the trail is behind you",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.movedaily.o.standdesk", "Set up a standing desk", "your work no longer sits you down",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.movedaily.o.deskfree", "Spend a whole day off the chair", "you stayed on your feet",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "exercise.mobility",
            title = "Touch your toes again",
            fragment = "the body bends where it wouldn't",
            repeating = listOf(
                CatalogMinor("exercise.mobility.r.hamstring", "Hamstring stretch", "the backs of the legs let go",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.mobility.r.hips", "Hip-opener routine", "the hips opened",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("exercise.mobility.r.spine", "Spinal mobility flow", "the spine moved freely",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.mobility.r.shoulders", "Shoulder dislocates", "the shoulders rolled clean",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.mobility.r.ankles", "Ankle mobility drill", "the ankles found their range",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.mobility.r.breath", "Two minutes of breathing into the stretch", "you breathed it deeper",
                    CADENCE_DAILY, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("exercise.mobility.o.toes", "Touch your toes flat-backed", "palms to the floor at last",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.mobility.o.splitprog", "Start a splits progression", "the long road to the splits begins",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.mobility.o.squat", "Hold a deep squat for two minutes", "two minutes at the bottom",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.mobility.o.bridge", "Press up into a back bridge", "the spine arched and held",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.mobility.o.yoga", "Finish a 30-day yoga course", "thirty days on the mat",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.mobility.o.assess", "Get a movement assessment", "the weak links are named",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "exercise.endurance",
            title = "Cycle 100 km",
            fragment = "a hundred kilometres rolled out beneath you",
            repeating = listOf(
                CatalogMinor("exercise.endurance.r.commute", "Ride instead of drive", "the wheels did the commuting",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.endurance.r.long", "Weekend long ride", "the long ride is logged",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 2),
                CatalogMinor("exercise.endurance.r.cadence", "Cadence drill", "the legs spun smooth",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("exercise.endurance.r.fuel", "Practise on-bike fuelling", "you ate while moving",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("exercise.endurance.r.maintain", "Check tyres and chain", "the machine is ready",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("exercise.endurance.r.zone2", "Easy zone-2 spin", "the base miles are in",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("exercise.endurance.o.40", "Ride 40 km in one go", "forty kilometres, one sitting",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.endurance.o.70", "Ride 70 km", "seventy kilometres done",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.endurance.o.century", "Complete the 100 km ride", "the full century is behind you",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.endurance.o.climb", "Take on a mountain climb", "the col is conquered",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.endurance.o.gear", "Service the bike fully", "the bike is race-ready",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.endurance.o.event", "Enter a sportive", "your number is pinned on",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "exercise.bodyweight",
            title = "Master the bodyweight basics",
            fragment = "your body answers to you now",
            repeating = listOf(
                CatalogMinor("exercise.bodyweight.r.pushups", "Push-up sets", "the push-ups are done",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.bodyweight.r.squats", "Air-squat sets", "the legs put in the reps",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.bodyweight.r.plank", "Hold a plank", "the core held the line",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.bodyweight.r.hang", "Dead hang from a bar", "the grip got stronger",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("exercise.bodyweight.r.lunges", "Walking lunges", "the lunges are logged",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("exercise.bodyweight.r.dips", "Bench or bar dips", "the dips are done",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("exercise.bodyweight.o.pullup", "First unassisted pull-up", "chin over the bar, no help",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.bodyweight.o.pistol", "Hold a pistol squat", "you stood up on one leg",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.bodyweight.o.handstand", "Kick up to a wall handstand", "the world turned upside down and held",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("exercise.bodyweight.o.plank3", "Hold a three-minute plank", "three minutes, unshaking",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("exercise.bodyweight.o.lsit", "Hold an L-sit for ten seconds", "ten seconds of held tension",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("exercise.bodyweight.o.pushup50", "Do 50 push-ups in a day", "fifty, across the day",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
    )
}
