package com.grcarmenaty.lifegame.domain.catalog

import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_DAILY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_MONTHLY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_ONE_OFF
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_WEEKLY

/**
 * Family & kin. Six majors, each with six repeating minors (sensible
 * cadence) and six one-off minors (harder, higher weight).
 *
 * Fragments are lower-case completion clauses with no trailing period;
 * the daemon's archetype frame wraps them at completion time.
 */
internal object FamilyQuests {
    val majors = listOf(
        CatalogMajor(
            templateId = "family.parents",
            title = "Stay close to your parents",
            fragment = "the line to your parents stays open",
            repeating = listOf(
                CatalogMinor("family.parents.r.call", "Call a parent", "the call was made",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("family.parents.r.text", "Send a parent a quick note", "they heard from you",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("family.parents.r.photo", "Share a photo from your week", "a glimpse of your life reached them",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.parents.r.ask", "Ask them about their day", "you turned the question to them",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.parents.r.help", "Help with one small thing", "the small task is off their list",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("family.parents.r.patience", "Hear an old story patiently", "you let them tell it again",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("family.parents.o.visit", "Visit them in person", "you showed up at the door",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.parents.o.record", "Record a story from their past", "the memory is saved in their voice",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.parents.o.thank", "Thank them for something specific", "the old debt was named with thanks",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.parents.o.teachtech", "Teach them something they've wanted to learn", "the thing they struggled with is easier now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("family.parents.o.hardtalk", "Have the honest conversation you've put off", "the held-back words are spoken",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("family.parents.o.daytrip", "Take them on a day out", "the day belonged to them",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "family.siblings",
            title = "Reconnect with a sibling",
            fragment = "you and your sibling found each other again",
            repeating = listOf(
                CatalogMinor("family.siblings.r.message", "Message your sibling", "the thread is alive again",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.siblings.r.call", "Have a proper call", "you actually talked",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("family.siblings.r.meme", "Share something that made you think of them", "the small in-joke landed",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("family.siblings.r.check", "Check in on how they're really doing", "you asked past the surface",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("family.siblings.r.support", "Cheer on something they're doing", "you showed up in their corner",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.siblings.r.remember", "Recall a good shared memory together", "the old days were warm again",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("family.siblings.o.trip", "Plan a trip just the two of you", "the sibling trip is on the books",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.siblings.o.mend", "Mend an old falling-out", "the rift is finally closing",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("family.siblings.o.tradition", "Start a tradition between you", "the new ritual belongs to you both",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("family.siblings.o.gift", "Send a gift for no reason", "the surprise reached them",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("family.siblings.o.project", "Take on a shared project", "you built something together",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.siblings.o.openup", "Tell them something you've never shared", "the new honesty is between you",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "family.kids",
            title = "Be present for your kids",
            fragment = "your children had your full attention",
            repeating = listOf(
                CatalogMinor("family.kids.r.play", "Play on their terms", "you followed their lead",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("family.kids.r.read", "Read or talk at bedtime", "the day closed gently with them",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("family.kids.r.listen", "Really listen to their day", "you heard the whole story",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("family.kids.r.phonedown", "Be screen-free during their time", "your attention was undivided",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("family.kids.r.praise", "Notice an effort, not just a result", "you caught them trying",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("family.kids.r.meal", "Share a meal at the table", "the table held the family",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("family.kids.o.oneonone", "Give each child a solo day", "each one got you to themselves",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.kids.o.adventure", "Take them somewhere new", "the new place is a shared memory now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.kids.o.teach", "Teach them a skill you love", "you passed something of yours on",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.kids.o.apologise", "Apologise to them when you got it wrong", "you modelled the apology",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("family.kids.o.tradition", "Build a family tradition", "the ritual is theirs to keep",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("family.kids.o.letter", "Write each child a letter to keep", "the words are saved for them to find",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "family.elders",
            title = "Honour the elders",
            fragment = "the older generation knows they're held",
            repeating = listOf(
                CatalogMinor("family.elders.r.call", "Call a grandparent or elder", "the call brightened their day",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("family.elders.r.errand", "Run an errand for them", "the chore is handled",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("family.elders.r.visit", "Drop by for a short visit", "they had company",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 2),
                CatalogMinor("family.elders.r.listen", "Ask about their younger years", "the old stories came alive",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("family.elders.r.help", "Help with a device or form", "the modern hassle is solved",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.elders.r.bring", "Bring something they'd enjoy", "the small treat made them smile",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("family.elders.o.history", "Record the family history with them", "the lineage is written down",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("family.elders.o.recipe", "Learn a family recipe from them", "the recipe lives on in your hands",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.elders.o.album", "Make a photo album together", "the memories are gathered in one place",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("family.elders.o.outing", "Take them on a meaningful outing", "the day out was theirs",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.elders.o.help", "Sort out something they've worried about", "the worry is off their shoulders",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.elders.o.gather", "Bring the generations together", "the whole family was in one room",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "family.home",
            title = "Build a warm home life",
            fragment = "home feels like somewhere everyone wants to be",
            repeating = listOf(
                CatalogMinor("family.home.r.dinner", "Eat together at the table", "the family broke bread together",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("family.home.r.share", "Share highs and lows of the day", "everyone got to be heard",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("family.home.r.chore", "Do a shared chore without being asked", "the load was quietly lightened",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("family.home.r.thanks", "Thank someone at home", "the gratitude was said at home",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("family.home.r.game", "Play a game together", "the laughter filled the room",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.home.r.repair", "Smooth over a household tension", "the friction at home eased",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("family.home.o.meeting", "Hold a family meeting", "everyone had a seat at the table",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.home.o.tradition", "Start a weekly family night", "the standing night is set",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("family.home.o.chores", "Agree on a fair chore split", "the load is shared on purpose now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.home.o.project", "Take on a home project together", "you made the place yours together",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.home.o.feast", "Host a family feast", "the table was full and loud",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.home.o.values", "Write your family's shared values", "the values are named together",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "family.extended",
            title = "Tend the wider family",
            fragment = "the wider clan feels tied together again",
            repeating = listOf(
                CatalogMinor("family.extended.r.cousin", "Reach out to a cousin or relative", "a distant thread was tugged warm",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.extended.r.group", "Send something to the family group", "the group chat felt your presence",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.extended.r.birthday", "Mark a relative's special day", "their day didn't pass unnoticed",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.extended.r.check", "Check in on a relative going through it", "you didn't leave them alone in it",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.extended.r.news", "Share family news around", "the news travelled the family",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("family.extended.r.welcome", "Welcome a newer member warmly", "they felt part of it",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("family.extended.o.reunion", "Organise a family reunion", "the clan is gathering",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("family.extended.o.tree", "Map out the family tree", "the branches are charted",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.extended.o.mend", "Reach across an old family divide", "the long silence was broken",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("family.extended.o.visit", "Visit a relative you rarely see", "you closed the distance in person",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.extended.o.host", "Host relatives for a stay", "your door was open to them",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("family.extended.o.archive", "Gather old family photos to share", "the shared past is collected",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
    )
}
