package com.grcarmenaty.lifegame.domain.catalog

import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_DAILY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_MONTHLY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_ONE_OFF
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_WEEKLY

/**
 * Friendship & community. Six majors, each with six repeating minors
 * (sensible cadence) and six one-off minors (harder, higher weight).
 *
 * Fragments are lower-case completion clauses with no trailing period;
 * the daemon's archetype frame wraps them at completion time.
 */
internal object FriendshipQuests {
    val majors = listOf(
        CatalogMajor(
            templateId = "friendship.closefew",
            title = "Tend your closest friendships",
            fragment = "your closest people feel kept",
            repeating = listOf(
                CatalogMinor("friendship.closefew.r.text", "Send a friend a thoughtful text", "the message reached them warm",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("friendship.closefew.r.call", "Call a close friend", "you actually heard their voice",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.closefew.r.checkin", "Ask how a friend is really doing", "you asked past the small talk",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.closefew.r.share", "Share a moment from your day", "you let them into the ordinary stuff",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("friendship.closefew.r.celebrate", "Cheer on a friend's win", "their good news got your applause",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.closefew.r.remember", "Follow up on something they told you", "you remembered, and it showed",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.closefew.r.meme", "Send something that made you think of them", "a small thing said you thought of them",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("friendship.closefew.r.plan", "Float a plan to see them soon", "a next meeting got a shape",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.closefew.r.compliment", "Tell a friend what you value in them", "the unspoken regard got said",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.closefew.r.listen", "Hear a friend out without fixing it", "you just listened, no advice",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.closefew.r.photo", "Share an old photo of you two", "a shared memory surfaced again",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.closefew.r.checkplans", "Confirm an upcoming plan together", "the plan got its final yes",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("friendship.closefew.o.trip", "Plan a trip with a close friend", "the trip together is booked",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.closefew.o.mend", "Repair a friendship that drifted", "the drift is being closed",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.closefew.o.showup", "Show up for a friend in a hard time", "you were there when it counted",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.closefew.o.tradition", "Start a standing ritual together", "the recurring plan is set",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.closefew.o.deep", "Have a real heart-to-heart", "the honest conversation happened",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.closefew.o.help", "Help a friend with something big", "you carried the heavy thing with them",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.closefew.o.weekend", "Spend a whole weekend with a friend", "the long unhurried time happened",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.closefew.o.forgive", "Let go of an old grudge with a friend", "the old resentment is set down",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.closefew.o.gift", "Give a friend a meaningful gift", "the gift said what you couldn't",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.closefew.o.project", "Take on a shared project together", "the joint undertaking is begun",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.closefew.o.honest", "Tell a friend a hard truth kindly", "the difficult thing was said with care",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.closefew.o.memory", "Make a memory you'll both keep", "a moment worth remembering was made",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "friendship.newpeople",
            title = "Make a new friend",
            fragment = "a new friendship has its first roots",
            repeating = listOf(
                CatalogMinor("friendship.newpeople.r.hello", "Strike up a conversation", "you said the first hello",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.newpeople.r.followup", "Follow up after meeting someone", "you kept the thread going",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.newpeople.r.show", "Show up somewhere people gather", "you put yourself in the room",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 2),
                CatalogMinor("friendship.newpeople.r.question", "Ask someone a real question", "you went past the surface",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.newpeople.r.remember", "Remember a new person's name and detail", "the detail stuck with you",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.newpeople.r.invite", "Extend a low-stakes invitation", "the invite is out there",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.newpeople.r.smile", "Be the first to be warm", "you offered the first warmth",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("friendship.newpeople.r.common", "Find something in common with someone", "a shared thread turned up",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.newpeople.r.compliment", "Give a stranger an easy compliment", "a small kindness opened a door",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.newpeople.r.regular", "Become a regular somewhere", "a familiar place knows your face",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.newpeople.r.swap", "Swap numbers with someone new", "a new contact is saved",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.newpeople.r.openup", "Share something real about yourself", "you let a new person see you",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("friendship.newpeople.o.group", "Join a regular group or club", "you signed on to keep coming back",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.newpeople.o.coffee", "Ask a new acquaintance for coffee", "the first proper meet-up is set",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.newpeople.o.class", "Take a class to meet people", "you walked into a room of strangers",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.newpeople.o.host", "Host a small low-key gathering", "your place held new company",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.newpeople.o.event", "Go to an event alone and stay", "you stayed and talked, alone or not",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.newpeople.o.reconnect", "Reconnect with someone you lost touch with", "the old contact is warm again",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.newpeople.o.activity", "Take up a social hobby from scratch", "you joined a whole new circle",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.newpeople.o.dinner", "Invite a new friend to a meal", "the first proper meal together happened",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.newpeople.o.volunteer", "Meet people through volunteering", "new faces came with the good work",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.newpeople.o.travelpal", "Befriend someone while travelling", "a stranger abroad became a friend",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.newpeople.o.deepen", "Turn an acquaintance into a real friend", "the surface tie grew roots",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.newpeople.o.networkfun", "Go to a meetup in a new interest", "you showed up where your interest lives",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "friendship.showup",
            title = "Become someone who shows up",
            fragment = "your friends know they can count on you",
            repeating = listOf(
                CatalogMinor("friendship.showup.r.reply", "Reply instead of leaving it on read", "you closed the open loop",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("friendship.showup.r.keepplans", "Keep the plans you made", "you didn't flake this time",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 2),
                CatalogMinor("friendship.showup.r.offer", "Offer help before being asked", "you saw the need and stepped in",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.showup.r.checkin", "Check in on someone quiet lately", "you noticed the silence",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.showup.r.thanks", "Thank a friend for being in your life", "the gratitude was spoken",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.showup.r.listen", "Listen without making it about you", "you held space for them",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("friendship.showup.r.ontime", "Arrive on time for a friend", "you respected their time",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.showup.r.remember", "Remember a date that matters to them", "their day didn't slip past you",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.showup.r.followthrough", "Do the thing you promised", "the promise turned into a deed",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 2),
                CatalogMinor("friendship.showup.r.present", "Put the phone away when together", "you gave undivided attention",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("friendship.showup.r.askhow", "Ask what they actually need", "you found out before assuming",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.showup.r.smalltask", "Quietly handle a small thing for them", "you eased one burden unprompted",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("friendship.showup.o.crisis", "Drop everything for a friend in crisis", "you were there in the worst of it",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.showup.o.milestone", "Travel for a friend's big milestone", "you crossed the distance for their day",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.showup.o.apology", "Apologise for a time you let someone down", "the old letdown is owned",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.showup.o.surprise", "Plan a surprise for a friend", "the surprise is in motion",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.showup.o.favour", "Do a genuinely inconvenient favour", "you helped when it cost you something",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.showup.o.celebrate", "Throw a celebration for someone", "their moment got the fuss it deserved",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.showup.o.move", "Help a friend move house", "you hauled boxes when it mattered",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.showup.o.hospital", "Visit a friend who's unwell", "you came when they were down",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.showup.o.advocate", "Stand up for a friend when it's hard", "you took their side out loud",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.showup.o.lend", "Lend real help with money or work", "you backed them with more than words",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.showup.o.witness", "Be present for a friend's hardest day", "you stood beside them through it",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.showup.o.reliable", "Become the friend people call first", "you earned being the first call",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "friendship.gather",
            title = "Bring people together",
            fragment = "you made a room full of your people",
            repeating = listOf(
                CatalogMinor("friendship.gather.r.invite", "Invite friends to something", "the invitation went out",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.gather.r.organise", "Nudge a plan into existence", "the vague idea became a date",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.gather.r.introduce", "Introduce two people who'd click", "you connected two of your people",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.gather.r.checkgroup", "Keep the group chat alive", "the group felt your spark",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.gather.r.suggest", "Suggest a get-together this week", "the plan is on the table",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.gather.r.confirm", "Pin down a wobbly plan", "the maybe became a yes",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.gather.r.remind", "Remind people of the upcoming plan", "no one forgot the date",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.gather.r.welcome", "Make sure no one's left out", "everyone in the room felt included",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.gather.r.spark", "Bring up something fun in the chat", "the group felt a little livelier",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.gather.r.followup", "Thank people after a gathering", "the good time got its thanks",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.gather.r.casual", "Propose a low-effort hangout", "an easy plan got floated",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.gather.r.photos", "Share the photos after a get-together", "the memories got passed around",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("friendship.gather.o.dinner", "Host a dinner for friends", "the table was full of your people",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.gather.o.tradition", "Start a recurring meet-up", "the standing get-together exists now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.gather.o.trip", "Organise a group trip", "the group trip is happening",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.gather.o.game", "Run a games or movie night", "the night brought everyone in",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.gather.o.reunion", "Reunite an old group of friends", "the scattered crew came back together",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.gather.o.party", "Throw a proper party", "the party filled the place",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.gather.o.potluck", "Run a potluck where everyone brings a dish", "the shared table came together",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.gather.o.bigbash", "Plan a milestone celebration", "the big occasion got its event",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.gather.o.retreat", "Organise a weekend away for the group", "the whole crew got a getaway",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.gather.o.bridge", "Merge two friend groups for one night", "two circles met under one roof",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.gather.o.themed", "Throw a themed gathering people remember", "the night had a flavour all its own",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.gather.o.outing", "Take the group on a day out", "everyone got out together for the day",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "friendship.community",
            title = "Belong to your community",
            fragment = "you're woven into the place you live",
            repeating = listOf(
                CatalogMinor("friendship.community.r.greet", "Greet a neighbour by name", "the neighbourhood felt friendlier",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("friendship.community.r.local", "Support a local spot", "you put your time into the place",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.community.r.help", "Lend a neighbour a hand", "the neighbourly favour was done",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.community.r.attend", "Show up to a community event", "you were part of it",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 2),
                CatalogMinor("friendship.community.r.contribute", "Add to a shared local effort", "you pulled your weight for the group",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.community.r.notice", "Notice someone who could use a hello", "no one near you went unseen",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.community.r.recommend", "Recommend a local spot to someone", "a good local place got passed on",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.community.r.tidy", "Pick up litter on your street", "the block looked a little cared for",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.community.r.market", "Shop at the local market", "you fed the neighbourhood economy",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.community.r.share", "Share something useful with neighbours", "the shared thing made the rounds",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.community.r.chat", "Have a real chat with a regular", "a familiar face became a person",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.community.r.thank", "Thank someone who keeps the area running", "the quiet local labour got noticed",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("friendship.community.o.volunteer", "Start volunteering somewhere local", "you signed on to give time",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.community.o.join", "Join a local group or board", "you took a seat in the community",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.community.o.organise", "Organise a community gathering", "the neighbourhood came together",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.community.o.meet", "Meet the neighbours properly", "the strangers next door are people now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.community.o.cause", "Throw yourself into a local cause", "you stood up for something near home",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.community.o.mentor", "Offer to mentor someone", "you made yourself available to help",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.community.o.host", "Host a block or building gathering", "your neighbours met over your invite",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.community.o.fund", "Raise money for a local need", "the neighbourhood pitched in together",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.community.o.skill", "Teach a free local workshop", "you gave the neighbourhood a skill",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.community.o.fix", "Fix something broken in a shared space", "the common space works again",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.community.o.welcome", "Welcome a newcomer to the area", "the new arrival felt at home sooner",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.community.o.tradition", "Start a recurring neighbourhood event", "the area has a date of its own now",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "friendship.distance",
            title = "Keep far-away friends close",
            fragment = "distance stopped meaning silence",
            repeating = listOf(
                CatalogMinor("friendship.distance.r.voice", "Send a voice note to a distant friend", "your voice crossed the miles",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.distance.r.update", "Share a real update on your life", "they're still in the loop",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.distance.r.ask", "Ask a far friend how they really are", "the distance didn't dull the care",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.distance.r.send", "Send something that reminded you of them", "the small token bridged the gap",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.distance.r.timezone", "Catch a friend across the time zones", "you found the window to talk",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.distance.r.remember", "Mark a far friend's important day", "their day reached you even far off",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.distance.r.photo", "Send a photo of your everyday", "they saw a slice of your day",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.distance.r.reply", "Answer a far friend's message promptly", "the reply didn't sit for days",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.distance.r.recommend", "Share a show or book to enjoy apart", "you found something to share across the miles",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.distance.r.memory", "Reminisce about an old shared time", "an old memory got relived together",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
                CatalogMinor("friendship.distance.r.plan", "Float an idea of meeting up", "a future reunion got a first mention",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("friendship.distance.r.goodmorning", "Send a far friend a thinking-of-you note", "a small hello crossed the distance",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("friendship.distance.o.videocall", "Set up a long overdue video call", "you finally saw their face",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.distance.o.visit", "Plan a visit to a far-off friend", "the visit is on the calendar",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.distance.o.standing", "Set up a standing call schedule", "the recurring call is locked in",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.distance.o.letter", "Send a real letter or package", "the parcel is in the post to them",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.distance.o.meethalf", "Plan to meet somewhere in the middle", "the meet-in-the-middle is set",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.distance.o.reconnect", "Rekindle a long-quiet friendship", "the long silence is broken",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.distance.o.host", "Host a far friend for a stay", "they slept under your roof at last",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.distance.o.gift", "Mail a surprise gift abroad", "the surprise crossed the border to them",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.distance.o.watchparty", "Watch something together at a distance", "you shared a screen across the miles",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("friendship.distance.o.reunion", "Gather scattered friends in one place", "the spread-out crew converged once",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("friendship.distance.o.tradition", "Set up a yearly long-distance ritual", "a standing yearly date is born",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("friendship.distance.o.scrapbook", "Make a shared keepsake of your friendship", "the friendship has something to hold",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
    )
}
