package com.grcarmenaty.lifegame.domain.catalog

import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_DAILY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_MONTHLY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_ONE_OFF
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_WEEKLY

/**
 * Relationships & love. Six majors, each with six repeating minors
 * (sensible cadence) and six one-off minors (harder, higher weight).
 *
 * Fragments are lower-case completion clauses with no trailing period;
 * the daemon's archetype frame wraps them at completion time.
 */
internal object LoveQuests {
    val majors = listOf(
        CatalogMajor(
            templateId = "love.closer",
            title = "Grow closer to your partner",
            fragment = "the two of you are nearer than before",
            repeating = listOf(
                CatalogMinor("love.closer.r.checkin", "Ask how their day really went", "you actually asked",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.closer.r.text", "Send a thoughtful text", "the message landed warm",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("love.closer.r.appreciate", "Name one thing you appreciate", "the gratitude was said out loud",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("love.closer.r.phonedown", "Put the phone away together", "the screens stayed dark",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.closer.r.affection", "Offer an unhurried hug", "the embrace wasn't rushed",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.closer.r.listen", "Listen without fixing", "you let them be heard",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("love.closer.o.weekend", "Plan a weekend away together", "the getaway is booked",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.closer.o.letter", "Write them a love letter", "the words are on paper for them",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.closer.o.hardtalk", "Have the conversation you've been avoiding", "the hard thing got said",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("love.closer.o.rituals", "Agree on a weekly ritual together", "the standing date is set",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.closer.o.surprise", "Plan a surprise they'd love", "the surprise is ready",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.closer.o.future", "Talk honestly about the future", "the road ahead is named together",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "love.datelife",
            title = "Revive your date life",
            fragment = "the spark has somewhere to go again",
            repeating = listOf(
                CatalogMinor("love.datelife.r.plan", "Plan one proper date", "the date is on the calendar",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("love.datelife.r.dressup", "Make an effort for an evening in", "the night felt special",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("love.datelife.r.cook", "Cook a meal together", "the kitchen was shared",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("love.datelife.r.walk", "Take an evening walk together", "the walk gave you each other",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("love.datelife.r.noscreens", "Share a screen-free meal", "the table belonged to the two of you",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("love.datelife.r.ask", "Ask a question you've never asked", "you learned something new about them",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("love.datelife.o.newplace", "Try a restaurant neither of you knows", "the new place is yours now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.datelife.o.class", "Take a class together", "you learned something side by side",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.datelife.o.recreate", "Recreate your first date", "the beginning came round again",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.datelife.o.dance", "Go dancing together", "the dance floor held you both",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.datelife.o.overnight", "Book a night away, just the two of you", "the room is reserved",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("love.datelife.o.adventure", "Do something a little daring together", "you faced the unfamiliar as a pair",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "love.dating",
            title = "Date with intention",
            fragment = "you put yourself out there honestly",
            repeating = listOf(
                CatalogMinor("love.dating.r.reach", "Reach out to someone you like", "the message was sent",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("love.dating.r.reply", "Reply to your matches kindly", "the conversations are tended",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("love.dating.r.openline", "Open with a real question", "you asked something that mattered",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("love.dating.r.reflect", "Note what you actually want", "the wants are clearer",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("love.dating.r.boundary", "Honour one of your boundaries", "the line held",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 2),
                CatalogMinor("love.dating.r.selfdate", "Take yourself somewhere good", "you enjoyed your own company",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("love.dating.o.profile", "Write an honest dating profile", "the profile finally sounds like you",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.dating.o.firstdate", "Go on a first date", "you showed up and stayed",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.dating.o.askout", "Ask someone out directly", "the question is out of your mouth",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("love.dating.o.values", "List your non-negotiables", "the deal-breakers are named",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.dating.o.secondchance", "Give a kind second date a chance", "you didn't write them off too fast",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.dating.o.closure", "Close out a connection that isn't right", "you ended it cleanly and kindly",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "love.repair",
            title = "Repair a strained bond",
            fragment = "the rift is smaller than it was",
            repeating = listOf(
                CatalogMinor("love.repair.r.softstart", "Start a touchy talk gently", "you led with softness",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 2),
                CatalogMinor("love.repair.r.repairs", "Make a small repair after friction", "the small wound was tended",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("love.repair.r.thanks", "Thank them for something real", "the thanks was specific",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("love.repair.r.assume", "Assume the best for one beat", "you gave them the benefit",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.repair.r.pause", "Take a breath before reacting", "you paused instead of firing",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.repair.r.affection", "Offer warmth even mid-disagreement", "the warmth survived the argument",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("love.repair.o.apology", "Make the apology you owe", "the apology is honestly made",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("love.repair.o.forgive", "Forgive something you've held", "you set the grudge down",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("love.repair.o.counsel", "Book a couples' session", "the appointment is made",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.repair.o.needs", "Say plainly what you need", "your need is on the table",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.repair.o.listenday", "Spend an hour just hearing them out", "you let them say all of it",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.repair.o.reset", "Agree on a fresh start together", "the slate is cleaned on purpose",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "love.intimacy",
            title = "Deepen everyday intimacy",
            fragment = "the closeness is woven into ordinary days",
            repeating = listOf(
                CatalogMinor("love.intimacy.r.eyecontact", "Hold their gaze for a moment", "the look was held",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.intimacy.r.share", "Share something you felt today", "you let yourself be seen",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.intimacy.r.touch", "Offer affectionate touch", "the closeness was physical",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.intimacy.r.compliment", "Give a genuine compliment", "the praise was true",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("love.intimacy.r.checkneeds", "Ask what they need today", "you made room for their needs",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("love.intimacy.r.gratitude", "Tell them why you're glad they're here", "the gladness was spoken",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("love.intimacy.o.fears", "Share a fear you've kept private", "the private fear is no longer alone",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("love.intimacy.o.lovemap", "Ask the big questions about their world", "you mapped their inner life a little more",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.intimacy.o.languages", "Learn each other's love languages", "you know how the other receives love",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.intimacy.o.desires", "Talk openly about what you each want", "the wants are spoken, not guessed",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.intimacy.o.unplugged", "Spend a full day unplugged together", "the whole day was just the two of you",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.intimacy.o.story", "Tell each other your origin stories again", "the old stories were told anew",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "love.selfworth",
            title = "Love yourself first",
            fragment = "you treat yourself as worth loving",
            repeating = listOf(
                CatalogMinor("love.selfworth.r.kindword", "Speak to yourself kindly", "the inner voice was gentle",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.selfworth.r.need", "Honour one of your own needs", "your need was met",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("love.selfworth.r.boundary", "Say no to something draining", "you kept your own line",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 2),
                CatalogMinor("love.selfworth.r.joy", "Do one thing purely for joy", "the joy was for you alone",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("love.selfworth.r.reflect", "Note one thing you did well", "you gave yourself the credit",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("love.selfworth.r.rest", "Let yourself rest without guilt", "the rest was taken cleanly",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("love.selfworth.o.list", "Write down what you bring to a relationship", "your worth is named on paper",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.selfworth.o.pattern", "Name a pattern you want to leave behind", "the old pattern is named to break it",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("love.selfworth.o.solodate", "Take yourself on a real solo date", "you romanced your own company",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("love.selfworth.o.therapy", "Start working with a therapist", "the first session is booked",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("love.selfworth.o.forgiveself", "Forgive yourself for a past relationship", "you laid down the old blame",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("love.selfworth.o.standards", "Write the standards you'll hold to", "your standards are clear and yours",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
    )
}
