package com.grcarmenaty.lifegame.domain.catalog

import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_DAILY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_MONTHLY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_ONE_OFF
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_WEEKLY

/**
 * Meditation & stillness. Six majors, each with six repeating minors (sensible
 * cadence) and six one-off minors (harder, higher weight).
 *
 * Fragments are lower-case completion clauses with no trailing period;
 * the daemon's archetype frame wraps them at completion time.
 */
internal object MeditationQuests {
    val majors = listOf(
        CatalogMajor(
            templateId = "meditation.daily",
            title = "Sit every day",
            fragment = "sitting is simply part of your day now",
            repeating = listOf(
                CatalogMinor("meditation.daily.r.sit", "Sit for ten minutes", "the ten minutes are kept",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.daily.r.morning", "Sit before the day starts", "you sat before the rush",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.daily.r.breath", "Take ten slow breaths", "the breaths are counted out",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.daily.r.posture", "Settle into a steady posture", "the body found its seat",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.daily.r.evening", "Sit briefly before bed", "the day was let go quietly",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.daily.r.log", "Note how the sit went", "the sit is noted",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.daily.r.timer", "Set a timer and sit till it sounds", "you sat the whole timer out",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.daily.r.return", "Gently return when the mind wanders", "you came back without scolding",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.daily.r.sameTime", "Sit at the same time each day", "the hour held steady",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.daily.r.candle", "Light something to mark the start", "the small ritual opened the sit",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.daily.r.short", "Sit even on a busy day", "the busy day still made room",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 2),
                CatalogMinor("meditation.daily.r.review", "Look back over the month's sits", "the month of sitting was reviewed",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("meditation.daily.o.streak", "Sit every day for a month", "thirty days on the cushion, unbroken",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.daily.o.cushion", "Set up a sitting spot", "you have a place to sit",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.daily.o.thirty", "Sit for thirty minutes", "half an hour of stillness held",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.daily.o.nophone", "Sit with the phone in another room", "you sat with nothing to reach for",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.daily.o.dawn", "Sit at dawn", "you met the day's first light sitting",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.daily.o.hundred", "Reach a hundred sits", "a hundred sits stand behind you",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.daily.o.week", "Sit every day for a week", "seven days kept in a row",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.daily.o.travel", "Keep the sit while travelling", "you sat far from home",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.daily.o.app", "Set up a practice you can lean on", "the practice has its own support now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.daily.o.sick", "Sit through a low day", "you sat even when it was hard",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.daily.o.outdoor", "Sit outdoors for the first time", "you sat under open sky",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.daily.o.fifty", "Reach fifty sits", "fifty sits stand behind you",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "meditation.breath",
            title = "Learn to work with the breath",
            fragment = "the breath is a place you can return to",
            repeating = listOf(
                CatalogMinor("meditation.breath.r.count", "Count the breath to ten", "the count held to ten",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.breath.r.box", "Do a round of box breathing", "the breath went square and slow",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.breath.r.belly", "Practise belly breathing", "the belly did the breathing",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.breath.r.long", "Lengthen the out-breath", "the out-breath stretched long",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.breath.r.pause", "Use one breath to reset midday", "one breath set the day right",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.breath.r.notice", "Notice the breath without changing it", "you watched it breathe itself",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.breath.r.sigh", "Take a slow physiological sigh", "the double breath let go of tension",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.breath.r.nose", "Breathe only through the nose", "the breath stayed soft and nasal",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.breath.r.fourseven", "Try a four-seven-eight round", "the counted breath slowed you down",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.breath.r.morning", "Open the morning with three breaths", "the day began on the breath",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.breath.r.alternate", "Practise alternate-nostril breathing", "the breath moved side to side",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.breath.r.review", "Notice which technique helped this week", "you learned what your breath needs",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("meditation.breath.o.learn", "Learn three breathing techniques", "three ways to breathe are yours",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.breath.o.twenty", "Do twenty minutes of breathwork", "twenty minutes with the breath alone",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.breath.o.calm", "Calm yourself with breath under stress", "the breath steadied you when it mattered",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.breath.o.guided", "Follow a long guided session", "you went the whole way with a guide",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.breath.o.class", "Attend a breathwork class", "you learned to breathe alongside others",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.breath.o.teach", "Teach the breath to someone anxious", "you handed your calm to someone",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.breath.o.book", "Read a book on the breath", "you learned the why behind it",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.breath.o.sleep", "Use the breath to fall asleep", "the breath carried you under",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.breath.o.panic", "Breathe through a wave of panic", "the breath held when fear rose",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.breath.o.cold", "Pair breathwork with a cold plunge", "you met the cold on the breath",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.breath.o.daily", "Keep breathwork daily for two weeks", "a fortnight on the breath, unbroken",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.breath.o.record", "Track how the breath shifts your mood", "the pattern of breath and mood is clear",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "meditation.presence",
            title = "Bring presence to daily life",
            fragment = "you meet your ordinary days awake",
            repeating = listOf(
                CatalogMinor("meditation.presence.r.meal", "Eat one meal without screens", "the meal had your attention",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.presence.r.walk", "Take a mindful walk", "the walk was actually walked",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.presence.r.task", "Do one chore with full attention", "the chore had all of you",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.presence.r.pause", "Pause and feel your feet", "you came back to the ground",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.presence.r.listen", "Listen to someone fully", "you really heard them",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.presence.r.senses", "Name five things you can sense", "the senses were counted",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.presence.r.tea", "Drink a tea or coffee slowly", "the cup got your full attention",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.presence.r.threshold", "Pause at one doorway today", "you crossed it awake",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.presence.r.commute", "Travel one stretch without your phone", "the journey was simply lived",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.presence.r.sky", "Look up at the sky for a minute", "you let the sky hold you a moment",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.presence.r.bell", "Treat one sound as a reminder", "the sound called you back",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.presence.r.weekly", "Set an intention for presence each week", "the week had a quiet aim",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("meditation.presence.o.day", "Spend a day mostly off screens", "a whole day, mostly unplugged",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.presence.o.slow", "Do one thing slowly on purpose", "you let one thing take its time",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.presence.o.nature", "Spend an hour in nature, just noticing", "an hour of simply being outside",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.presence.o.singletask", "Single-task a whole morning", "a morning with one thing at a time",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.presence.o.silence", "Spend a morning in silence", "the morning passed without words",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.presence.o.fast", "Go a day without notifications", "the day held no buzzing interruptions",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.presence.o.cook", "Cook a whole meal with full attention", "the meal was made with all of you",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.presence.o.dishes", "Wash the dishes mindfully start to finish", "even the chore became practice",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.presence.o.eatretreat", "Eat a meal in full silence", "the meal passed in pure quiet",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.presence.o.weekend", "Keep a low-screen weekend", "two days lived mostly unplugged",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.presence.o.art", "Spend an hour fully absorbed in making", "you lost yourself in the work",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.presence.o.dawnwalk", "Take a dawn walk noticing everything", "the dawn was met awake",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "meditation.calm",
            title = "Steady your nervous system",
            fragment = "you can find your own calm now",
            repeating = listOf(
                CatalogMinor("meditation.calm.r.scan", "Do a body scan", "the body was scanned head to toe",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.calm.r.relax", "Relax tense shoulders", "the shoulders dropped",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.calm.r.unwind", "Take ten minutes to unwind", "the wind-down happened",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.calm.r.rest", "Lie down and do nothing", "you let yourself simply rest",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.calm.r.name", "Name a feeling as it arises", "the feeling was named, not fought",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.calm.r.ground", "Ground yourself when stirred up", "you came back down to earth",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 2),
                CatalogMinor("meditation.calm.r.jaw", "Soften the jaw and face", "the held tension let go",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.calm.r.exhale", "Lengthen the out-breath to settle", "the long breath calmed the system",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.calm.r.walkcalm", "Walk slowly to discharge stress", "the walk took the edge off",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.calm.r.screensoff", "Wind down without screens before bed", "the night ended soft and dim",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.calm.r.warmth", "Use warmth to settle the body", "the warmth eased you down",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.calm.r.checkbody", "Check the body for held stress each week", "you caught the tension early",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("meditation.calm.o.yoganidra", "Do a full yoga-nidra session", "you went all the way under and came back",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.calm.o.toolkit", "Build a calming toolkit", "you have ways to settle yourself now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.calm.o.hard", "Sit with a hard feeling without fleeing", "you stayed with it and it passed",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.calm.o.spa", "Take a slow, restful afternoon", "an afternoon given over to rest",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.calm.o.trigger", "Stay steady through a known trigger", "the trigger came and you held",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.calm.o.coldcalm", "Stay calm in a cold shower", "you breathed through the cold",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.calm.o.massage", "Take a slow restorative session of care", "the body was given real rest",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.calm.o.float", "Try a deeply still sensory rest", "you sank into complete quiet",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.calm.o.conflict", "Stay grounded through a hard conversation", "you held steady while it was tense",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.calm.o.breathmap", "Map what tips you into stress", "you know your own triggers now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.calm.o.calmnight", "Settle yourself through a sleepless night", "you met the long night calmly",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.calm.o.restday", "Give a whole day to rest and quiet", "the day was wholly restful",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "meditation.kindness",
            title = "Practise loving-kindness",
            fragment = "your goodwill reaches wider than it did",
            repeating = listOf(
                CatalogMinor("meditation.kindness.r.self", "Wish yourself well", "you were kind to yourself today",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.kindness.r.loved", "Hold a loved one in mind", "someone dear was held in warmth",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.kindness.r.stranger", "Wish a stranger well", "your goodwill reached a stranger",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.kindness.r.difficult", "Soften toward someone difficult", "the hard heart loosened a little",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 2),
                CatalogMinor("meditation.kindness.r.phrase", "Repeat a kindness phrase", "the phrases were spoken inwardly",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("meditation.kindness.r.gratitude", "Bring one person to mind with thanks", "one person was thanked in silence",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.kindness.r.neutral", "Send goodwill to someone you barely know", "your warmth reached a near-stranger",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.kindness.r.body", "Send kindness to your own body", "the body was met with warmth",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 1),
                CatalogMinor("meditation.kindness.r.commute", "Wish strangers well as you pass them", "the goodwill spilled into the street",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.kindness.r.world", "Widen the wish to all beings", "the goodwill went out wide",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.kindness.r.mistake", "Be kind to yourself over a small slip", "you forgave the small mistake",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.kindness.r.monthly", "Hold a hard relationship in goodwill", "the difficult bond softened a little",
                    CADENCE_MONTHLY, cadenceCount = 2, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("meditation.kindness.o.long", "Do a full loving-kindness session", "the whole practice was carried through",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.kindness.o.forgive", "Sit with forgiving someone", "you set down a weight you'd carried",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.kindness.o.act", "Turn the practice into a kind act", "the goodwill became a real deed",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.kindness.o.letter", "Write a warm letter to someone", "the warm letter is written",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.kindness.o.self", "Sit with self-compassion when you fail", "you met your own failing gently",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.kindness.o.retreatkind", "Spend a half-day on kindness practice", "half a day given to goodwill",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.kindness.o.reconcile", "Reach out warmly to someone estranged", "you offered the first warm word",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.kindness.o.volunteer", "Give your time to people who need it", "the goodwill became real help",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.kindness.o.thankyou", "Thank someone who shaped you", "the old gratitude was finally spoken",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.kindness.o.enemy", "Sit with goodwill for someone who hurt you", "you wished them well despite it",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.kindness.o.anonymous", "Do a kind thing with no credit", "the quiet kindness left no name",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.kindness.o.daily", "Keep a kindness practice daily for a week", "a week of goodwill, unbroken",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "meditation.deepen",
            title = "Deepen your practice",
            fragment = "the cushion has taught you something lasting",
            repeating = listOf(
                CatalogMinor("meditation.deepen.r.longer", "Sit for twenty minutes", "the longer sit was kept",
                    CADENCE_WEEKLY, cadenceCount = 4, weight = 2),
                CatalogMinor("meditation.deepen.r.read", "Read a little on practice", "you read something steadying",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.deepen.r.silent", "Sit without guidance", "you sat with no voice to follow",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.deepen.r.walking", "Do walking meditation", "the walking sit is done",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.deepen.r.reflect", "Reflect on what you noticed", "the noticing was set down",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.deepen.r.openeyes", "Sit with your eyes open", "you stayed present with eyes open",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.deepen.r.notimer", "Sit without checking the time", "you let the sit find its own length",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.deepen.r.label", "Note thoughts as they pass", "the thoughts were named and let go",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("meditation.deepen.r.openawareness", "Rest in open awareness", "you let attention stay wide",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.deepen.r.journal", "Keep a short practice journal", "the practice was written down",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("meditation.deepen.r.dawnpractice", "Sit early before anyone is up", "you practised in the quiet hour",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 2),
                CatalogMinor("meditation.deepen.r.intention", "Set a practice intention each month", "the month had a clear aim",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("meditation.deepen.o.hour", "Sit for a full hour", "a whole hour held in stillness",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.deepen.o.retreat", "Attend a day-long retreat", "a full day given to practice",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.deepen.o.teacher", "Sit with a teacher or group", "you practised alongside a teacher",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.deepen.o.silentday", "Keep a half-day of silence", "half a day held in quiet",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.deepen.o.tradition", "Learn the roots of a tradition", "you came to understand where it comes from",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.deepen.o.dawnsit", "Sit through a sunrise", "you sat as the sun came up",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.deepen.o.weekend", "Keep a quiet weekend retreat at home", "two days given mostly to practice",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.deepen.o.newform", "Learn a meditation form new to you", "a new way of sitting is yours",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.deepen.o.mentor", "Ask a teacher a real question", "you got guidance you'd been missing",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("meditation.deepen.o.ninety", "Sit a single ninety-minute session", "an hour and a half held unbroken",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("meditation.deepen.o.share", "Share your practice with a friend", "you let someone in on it",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("meditation.deepen.o.year", "Mark a year of steady practice", "a whole year on the cushion",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
    )
}
