package com.grcarmenaty.lifegame.domain.catalog

import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_DAILY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_MONTHLY
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_ONE_OFF
import com.grcarmenaty.lifegame.data.entities.MinorQuest.Companion.CADENCE_WEEKLY

/**
 * Outdoors & nature. Six majors, each with six repeating minors
 * (sensible cadence) and six one-off minors (harder, higher weight).
 *
 * Fragments are lower-case completion clauses with no trailing period;
 * the daemon's archetype frame wraps them at completion time.
 */
internal object OutdoorsQuests {
    val majors = listOf(
        CatalogMajor(
            templateId = "outdoors.dailywalk",
            title = "Walk outside every day for a month",
            fragment = "a month of daily air is behind you",
            repeating = listOf(
                CatalogMinor("outdoors.dailywalk.r.walk", "Take a walk outdoors", "the day's walk is done",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.morning", "Get outside before noon", "the morning air was met",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.nophone", "Walk once without the phone", "the walk had no screen in it",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.green", "Walk through somewhere green", "the green stretch was walked",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.notice", "Notice one new thing on the route", "something new caught your eye",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.long", "Take a longer weekend walk", "the long walk is logged",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 2),
                CatalogMinor("outdoors.dailywalk.r.evening", "Take an after-dark stroll", "the night walk is behind you",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.pace", "Pick up the pace for ten minutes", "the brisk stretch is logged",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.stretch", "Stretch before stepping out", "the body was ready to move",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.barefoot", "Feel grass or earth underfoot", "the ground met your feet",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.companion", "Walk alongside someone", "the walk was shared",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.dailywalk.r.steps", "Hit your step goal for the day", "the step count was met",
                    CADENCE_DAILY, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("outdoors.dailywalk.o.streak30", "Walk outside 30 days running", "thirty days, every one outdoors",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.dailywalk.o.newroute", "Walk a route you've never taken", "the unknown street is yours now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.dailywalk.o.sunrise", "Walk out to catch a sunrise", "you met the day at its start",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.dailywalk.o.rain", "Walk happily in the rain", "the rain didn't keep you in",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.dailywalk.o.10k", "Walk ten kilometres in a day", "ten kilometres on foot",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.dailywalk.o.explore", "Walk a whole new neighbourhood", "a new quarter of the city is mapped",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.dailywalk.o.nightwalk", "Walk under a full moon", "the moonlit walk is yours",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.dailywalk.o.coast", "Walk a stretch of coastline", "the shoreline passed beneath you",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.dailywalk.o.hill", "Walk up the highest hill near you", "the high ground was reached on foot",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.dailywalk.o.dawnchorus", "Walk out to hear the dawn chorus", "the birds sang you into the day",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.dailywalk.o.marathon", "Walk a half-marathon distance", "twenty kilometres, all on foot",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.dailywalk.o.crosscity", "Walk clear across your city", "you crossed the whole city on foot",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "outdoors.hike",
            title = "Hike a real trail",
            fragment = "the trail is behind you and the view was earned",
            repeating = listOf(
                CatalogMinor("outdoors.hike.r.condition", "Build your legs with a brisk walk", "the legs got their training",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("outdoors.hike.r.stairs", "Climb some stairs or a hill", "the climbing legs woke up",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.hike.r.gearcheck", "Check and ready your kit", "the kit is sorted and ready",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.hike.r.route", "Scout a trail to try next", "the next trail is picked",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.hike.r.boots", "Break in the boots on a short walk", "the boots are wearing in",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.hike.r.pack", "Practise packing light", "the pack is lean again",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.hike.r.incline", "Walk a hilly route on purpose", "the hills got their hour",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.hike.r.hydrate", "Carry and drink proper water", "the water habit held",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.hike.r.weather", "Check the trail forecast", "the weather was read ahead",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.hike.r.snack", "Pack trail snacks for energy", "the fuel for the path is ready",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.hike.r.core", "Strengthen your core for the climb", "the core got its work",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.hike.r.descend", "Practise walking downhill steadily", "the descent felt surer",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("outdoors.hike.o.first", "Complete a short waymarked trail", "the first real trail is walked",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.hike.o.summit", "Reach a summit on foot", "you stood on top of it",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.hike.o.daylong", "Finish a full-day hike", "a whole day spent on the path",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.hike.o.map", "Navigate a route by map", "you found the way by map alone",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.hike.o.sunrisehike", "Hike up for a sunrise view", "the dawn from the ridge was yours",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.hike.o.overnight", "Do an overnight backpacking trip", "you slept out where you walked to",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.hike.o.peakbag", "Bag three named peaks in a season", "three summits stand to your name",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.hike.o.scramble", "Tackle a route with some scrambling", "the rough ground was handled",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.hike.o.distance", "Hike twenty kilometres in one go", "twenty kilometres on the trail",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.hike.o.guided", "Join a guided group hike", "you walked with people who know it",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.hike.o.winter", "Hike a trail in winter conditions", "the cold trail was walked anyway",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.hike.o.longtrail", "Walk a famous long-distance section", "a stretch of the great trail is yours",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "outdoors.sun",
            title = "Live in daylight again",
            fragment = "the sun is part of your days, not a stranger",
            repeating = listOf(
                CatalogMinor("outdoors.sun.r.morninglight", "Get morning light on your face", "the morning light reached you",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("outdoors.sun.r.lunch", "Step outside on a break", "the break was taken outdoors",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("outdoors.sun.r.window", "Work near an open window", "the day got in while you worked",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("outdoors.sun.r.outside", "Eat one meal outside", "a meal was eaten in the open",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.sun.r.evening", "Catch the evening light", "the day's last light was caught",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.sun.r.sit", "Sit outside doing nothing", "you sat in the sun and just were",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.sun.r.coffee", "Drink your morning coffee outdoors", "the first cup met the sun",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("outdoors.sun.r.balcony", "Spend a quiet hour on the balcony", "the open-air hour was kept",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.sun.r.read", "Read outside in the light", "the page was turned in daylight",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.sun.r.noon", "Step into midday sun for ten minutes", "the noon light reached you",
                    CADENCE_DAILY, weight = 1),
                CatalogMinor("outdoors.sun.r.skywatch", "Look up and watch the sky change", "the sky got your attention",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.sun.r.shoes", "Take your shoes off in the sun", "the warmth reached your feet",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("outdoors.sun.o.sunrise", "Watch a full sunrise outside", "the whole sunrise was witnessed",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.sun.o.sunset", "Watch a sunset somewhere worth it", "the sky put on its show for you",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.sun.o.outdoorday", "Spend a whole day mostly outdoors", "a day lived almost entirely outside",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.sun.o.workout", "Move your work outside for a day", "the laptop met the open air",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.sun.o.stars", "Stay out to watch the stars", "the night sky got its hour",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.sun.o.swim", "Swim outdoors somewhere wild", "you swam in open water",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.sun.o.weekoutside", "Spend most of a week's daylight outdoors", "a week lived largely in the light",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.sun.o.picnic", "Host a long lazy outdoor lunch", "the meal stretched out under the sky",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.sun.o.goldenhour", "Photograph the golden hour", "the warm light is caught for keeps",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.sun.o.meteor", "Stay out for a meteor shower", "the falling stars got their night",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.sun.o.viewpoint", "Climb somewhere for a wide view", "the long view opened before you",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.sun.o.dawnvigil", "Stay up through the night to dawn", "you watched the dark turn to light",
                    CADENCE_ONE_OFF, weight = 5),
            ),
        ),
        CatalogMajor(
            templateId = "outdoors.localnature",
            title = "Learn the nature on your doorstep",
            fragment = "the wild near home has names you know now",
            repeating = listOf(
                CatalogMinor("outdoors.localnature.r.birds", "Notice and name one bird", "a bird got its name",
                    CADENCE_WEEKLY, cadenceCount = 3, weight = 1),
                CatalogMinor("outdoors.localnature.r.tree", "Learn one tree or plant", "another plant is no stranger",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.localnature.r.season", "Note how the season is turning", "the season's turn was marked",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.localnature.r.listen", "Stop and listen to the outdoors", "the soundscape got your ear",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.localnature.r.photo", "Photograph one wild thing", "a wild thing is captured",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.localnature.r.log", "Add a sighting to a nature log", "the sighting went in the log",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.localnature.r.insect", "Watch an insect at work", "a small life held your gaze",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.localnature.r.sky", "Track the moon's phase tonight", "the moon's shape was noted",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.localnature.r.weather", "Notice the day's weather properly", "the sky's mood was read",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.localnature.r.track", "Spot an animal track or sign", "the trace of something wild is read",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.localnature.r.sketch", "Sketch one thing you find outdoors", "a wild thing is drawn",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.localnature.r.touch", "Touch bark, leaf, or stone closely", "the texture of the wild is felt",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("outdoors.localnature.o.app", "Set up an ID app or field guide", "you have a way to name things now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.localnature.o.ten", "Learn ten local species by name", "ten neighbours of the wild are known",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.localnature.o.dawn", "Go out at dawn to watch wildlife", "the dawn chorus was yours",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.localnature.o.reserve", "Visit a local nature reserve", "the reserve is no longer just a name",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.localnature.o.feeder", "Put up a bird feeder or bug hotel", "the small creatures have a stop now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.localnature.o.survey", "Join a local wildlife survey", "your count helped the bigger picture",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.localnature.o.twenty", "Learn twenty more species by name", "twenty more wild names are yours",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.localnature.o.foraging", "Identify a wild edible safely", "you know one safe wild food now",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.localnature.o.nightwalk", "Go out to find nocturnal wildlife", "the night creatures showed themselves",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.localnature.o.journal", "Keep a nature journal for a month", "a month of the wild is recorded",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.localnature.o.plant", "Plant something native for wildlife", "the wild has a little more room now",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.localnature.o.migration", "Witness a seasonal migration", "the great movement was seen",
                    CADENCE_ONE_OFF, weight = 4),
            ),
        ),
        CatalogMajor(
            templateId = "outdoors.water",
            title = "Get out on the water",
            fragment = "the water is somewhere you belong now",
            repeating = listOf(
                CatalogMinor("outdoors.water.r.shore", "Spend time by water", "the time by the water is kept",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.water.r.swimfit", "Swim to build your wind", "the swimming wind is growing",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.water.r.cold", "Get comfortable with cooler water", "the cold felt a touch less cold",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.water.r.watch", "Watch the water and weather", "you read the water a little better",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.water.r.safety", "Review one water-safety basic", "a safety habit is firmer",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.water.r.breath", "Practise calm breathing by the water", "the breath stayed calm and slow",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.water.r.float", "Practise floating and staying calm", "you trusted the water to hold you",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.water.r.tide", "Read the tide or current times", "the water's rhythm is clearer",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.water.r.stroke", "Drill one swimming stroke", "the stroke is a little smoother",
                    CADENCE_WEEKLY, cadenceCount = 2, weight = 1),
                CatalogMinor("outdoors.water.r.kit", "Check your water kit is ready", "the gear is sorted for the water",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.water.r.dip", "Take a quick dip to acclimatise", "the water and you said hello",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.water.r.shorewalk", "Walk the water's edge slowly", "the shoreline walk is kept",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("outdoors.water.o.openswim", "Take your first open-water swim", "you swam where there were no walls",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.water.o.paddle", "Try kayaking or paddleboarding", "you stayed up and moved on the water",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.water.o.river", "Walk the length of a river stretch", "the river was followed to its bend",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.water.o.coast", "Walk a coastal path for a day", "the coast path is a day older friend",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.water.o.coldplunge", "Take a proper cold-water dip", "the cold water didn't win",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.water.o.lesson", "Take a lesson in a water sport", "the basics were taught right",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.water.o.distanceswim", "Swim a full kilometre open water", "a kilometre of open water is behind you",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.water.o.sail", "Crew a boat for a day", "you helped sail her for a day",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.water.o.island", "Reach a small island by water", "you crossed water to reach land",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.water.o.snorkel", "Snorkel and watch the underwater life", "the world below the surface opened up",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.water.o.waterfall", "Hike to a wild waterfall and swim", "you swam where the water falls",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.water.o.dawnswim", "Take a swim at first light", "the water at dawn was all yours",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
        CatalogMajor(
            templateId = "outdoors.camp",
            title = "Sleep under the open sky",
            fragment = "you spent a night out where the stars are",
            repeating = listOf(
                CatalogMinor("outdoors.camp.r.gear", "Sort one piece of camp kit", "another piece of kit is ready",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.skill", "Practise a camp skill at home", "the camp skill is surer",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.outdoorscook", "Cook a meal outdoors", "a meal was made in the open",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.scout", "Scout possible camp spots", "a spot is on the shortlist",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.weather", "Read the weather like a camper", "the forecast makes sense to you",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.pack", "Refine the kit list", "the kit list is tighter",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.knots", "Practise a useful knot", "the knot is in your hands now",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.firelay", "Practise laying a fire", "the fire-lay is surer",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.map", "Study a map of where you'll camp", "the ground is known on paper",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.firstaid", "Review one first-aid basic", "the safety know-how is fresher",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.layers", "Plan your layers for the cold", "the warmth is planned for",
                    CADENCE_WEEKLY, cadenceCount = 1, weight = 1),
                CatalogMinor("outdoors.camp.r.water", "Practise treating drinking water", "clean water is one less worry",
                    CADENCE_MONTHLY, cadenceCount = 1, weight = 1),
            ),
            oneOff = listOf(
                CatalogMinor("outdoors.camp.o.tent", "Pitch a tent in the garden", "the tent went up at home first",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.camp.o.firstnight", "Spend a first night under canvas", "the first night out is behind you",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.camp.o.fire", "Build and tend a safe campfire", "the fire caught and held",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.camp.o.wild", "Camp somewhere genuinely remote", "you slept far from the road",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.camp.o.stargaze", "Stay up to watch the night sky", "the stars got their long look",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.camp.o.weekend", "Camp a full weekend outdoors", "two nights out, start to finish",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.camp.o.hammock", "Sleep a night in a hammock outdoors", "you slept slung between the trees",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.camp.o.cookfire", "Cook a full meal over the fire", "the whole meal came off the flames",
                    CADENCE_ONE_OFF, weight = 3),
                CatalogMinor("outdoors.camp.o.winter", "Camp out in cold-season conditions", "you slept out when it was cold",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.camp.o.solo", "Spend a night camping solo", "a night out, alone and fine",
                    CADENCE_ONE_OFF, weight = 5),
                CatalogMinor("outdoors.camp.o.hiketocamp", "Hike in to a backcountry camp", "you carried your bed to the wild",
                    CADENCE_ONE_OFF, weight = 4),
                CatalogMinor("outdoors.camp.o.sunrisecamp", "Wake at camp for the sunrise", "you greeted the dawn from your tent",
                    CADENCE_ONE_OFF, weight = 3),
            ),
        ),
    )
}
