package com.grcarmenaty.lifegame.domain

import androidx.annotation.DrawableRes
import com.grcarmenaty.lifegame.R

/**
 * Ethereal-abstract face icon per (archetype, theme) pair. Each pair has
 * three symmetric stroke-only VectorDrawable variants generated by
 * `tools/generate_faces.py` into `res/drawable/face_<preset>_<theme>_<n>.xml`
 * and indexed by the generated [DaemonFaceTable]. A theme of `null` (or a
 * theme with no art) falls back to the archetype's `_other` baseline.
 *
 * The variant is chosen deterministically from [seed] (pass a daemon's id so
 * a daemon keeps the same face; the summoning preview derives a stable seed
 * from the chosen pair). Compose tints the line-art via
 * [androidx.compose.material3.Icon].
 */
object DaemonFaceSuggestions {

    @DrawableRes
    fun faceFor(preset: VoicePreset, theme: LifeTheme? = null, seed: Long = 0L): Int {
        val presetToken = preset.name.lowercase()
        val themeToken = theme?.key?.lowercase() ?: "other"
        val variants = DaemonFaceTable.byKey["${presetToken}_$themeToken"]
            ?: DaemonFaceTable.byKey.getValue("${presetToken}_other")
        val index = (((seed % variants.size) + variants.size) % variants.size).toInt()
        return variants[index]
    }
}
