package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Cheerleader × Learning — hype stance, no shame, curiosity = joy. */
internal object CheerleaderLearningLines {

    private const val A = "CHEERLEADER"
    private const val T = "LEARNING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("chle_first_ever", A,
            "OH MY GOD a LEARNING era?? Curious-girlie energy. Tiny lessons. Let's GO.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("chle_morning", A,
            "Hi friend!! One cute lesson with coffee?? Twenty minutes. Iconic start.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "chle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chle_morning_early", A,
            "Up EARLY!! Brain is FRESH. One small chapter. Iconic head-start.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "chle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chle_afternoon", A,
            "Babe!! Mid-day. Cute fifteen-minute lesson before the slump. Trust.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "chle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chle_evening", A,
            "Evening!! Cute lesson with tea. Slow-brain learning. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "chle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chle_night_late", A,
            "Late!! Brain too tired to learn well now. Sleep = the lesson. Trust.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "chle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chle_post_apotheosis", A,
            "BLOCK CLOSED!! Skill GLOWING. Tiny daily lesson keeps the curve. Trust.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("chle_monday", A,
            "MONDAY!! Week's TWO lesson goals. Cute. Specific. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "chle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chle_friday", A,
            "FRIDAY!! Cute review of this week's learning. ONE thing landed. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "chle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chle_weekend", A,
            "Weekend!! Long-form lesson?? Or rest. Both ICONIC. Babe choose.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "chle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("chle_level_1_reached", A,
            "FIRST TIER!! A whole MONTH of tiny lessons. Brain GROWING. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "chle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chle_level_2_reached", A,
            "SECOND TIER!! Skill USED in real life. Cute confidence growing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "chle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chle_level_3_reached", A,
            "THIRD TIER!! Friends ask YOU now. Iconic role model.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "chle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chle_level_4_reached", A,
            "HIGHEST TIER!! Years of joyful learning. Brain is ICONIC. I LOVE you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "chle_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("chle_attention_loss_mild", A,
            "Hey babe!! Skipped a few. Cute ten-minute lesson right now. Soft reset.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "chle_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("chle_attention_loss_hard", A,
            "Hi friend!! Course got dropped and that's OK!! ONE tiny lesson today. Tiny restart.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chle_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("chle_mid_day_return", A,
            "Mid-day!! Cute lesson break. Twenty minutes. Brain LOVES the variety.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("chle_wishes_pending", A,
            "Earned PRIZES with all that brain work!! Cute reward time. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "chle_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("chle_mid_streak", A,
            "Three days of lessons!! Brain SPONGE mode. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chle_streak", cooldownPicks = 5, theme = T),

        DialogueLine("chle_sant_jordi", A,
            "SANT JORDI!! Book day!! Buy one!! Read it!! ICONIC. Trust.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_la_merce", A,
            "MERCÈ!! Day off. Cute museum stop maybe?? Learning is play. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_sant_joan", A,
            "SANT JOAN!! Beach. Brain off. Iconic recovery for tomorrow's learning.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_diada", A,
            "Diada!! Long-read kind of day. Cute. Cosy. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_nadal", A,
            "NADAL!! Stories from family = oral history. Iconic learning. Listen.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_cap_d_any", A,
            "NEW YEAR!! ONE cute learning goal. Iconic year incoming. Trust.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chle_reis", A,
            "REIS!! A new book gift?? Iconic. Crack it open today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_carnaval", A,
            "CARNAVAL!! Day off learning. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_divendres_sant", A,
            "Quiet day!! Slow-read chapter. Cute. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_pasqua", A,
            "PASQUA MONDAY!! Audiobook on the hike?? ICONIC two-for-one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_festa_del_treball", A,
            "WORKERS' DAY!! Cute documentary day. Iconic chill learning.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_festa_major_gracia", A,
            "GRÀCIA!! Cute Catalan-language learning bonus while out at the streets.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_assumpcio", A,
            "AUGUST!! Big-book era. Hammock. ICONIC slow learning.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_hispanitat", A,
            "Day off!! Cute lesson + walk = iconic combo.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_castanyada", A,
            "CASTANYADA!! Long evenings = study era. Cute. Cosy. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_constitucio", A,
            "Bridge weekend!! Cute longer lesson. Hour or two. Cosy. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_immaculada", A,
            "PONT!! Five days. One day all learning?? Iconic deep-dive.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_sant_esteve", A,
            "Day after!! Slow brain day. Iconic light-read.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_cap_d_any_eve", A,
            "LAST DAY!! Year of LEARNING list. Iconic. CELEBRATE that brain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "chle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chle_birthday", A,
            "BIRTHDAY QUEEN!! Cute new-skill list for the year. Three ideas. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "chle_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("chle_personal_date", A,
            "Today is special: {label}!! Lesson with extra meaning today. Iconic mark.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "chle_personal", cooldownPicks = 1, theme = T),

        DialogueLine("chle_complete_1", A, "LEARNED!! Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chle_complete_2", A, "LOGGED!! Brain THRIVING.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chle_complete_3", A, "Brain-glow WIN!! Cute.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chle_complete_first_today", A,
            "First lesson!! Brain woke UP. Iconic start.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "chle_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("chle_complete_second_today", A,
            "TWO!! Lessons stacking. Curve LOADING. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "chle_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("chle_complete_third_today", A,
            "THREE!! Brain GLOWING. Iconic study day.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "chle_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("chle_complete_fourth_today", A,
            "FOUR!! Babe. Exam-soon?? Or just on a roll?? Hydrate either way!!",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "chle_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("chle_complete_fifth_today", A,
            "FIVE!! Brain ATE today. Close the book queen. Iconic.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "chle_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("chle_complete_after_streak", A,
            "Three days of lessons!! Skill GROWING. Confidence UP. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chle_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("chle_apotheosis_1", A,
            "BLOCK CLOSED!! Brain GLOWING. Iconic. Cute.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chle_apotheosis_2", A,
            "CYCLE DONE!! Pick next cute lesson goal. Tiny one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chle_apotheosis_3", A,
            "CLOSED!! Brain WIN!! Hype.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chle_apotheosis_first_ever", A,
            "FIRST BLOCK EVER!! Lessons are a HABIT!! I'm SOBBING. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("chle_apotheosis_1", "chle_apotheosis_2", "chle_apotheosis_3"),
            theme = T),
        DialogueLine("chle_apotheosis_at_level_2", A,
            "PROMOTED!! Skill SHOWING in real life. Cute confidence.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "chle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chle_apotheosis_at_level_3", A,
            "SENIOR TIER!! You're TEACHING friends now. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "chle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chle_apotheosis_at_level_4", A,
            "TOP TIER!! Years of joyful learning. Brain is ELITE. I LOVE you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "chle_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("chle_nudge_morning", A,
            "Morning!! Cute fifteen-min lesson with coffee. Iconic start.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "chle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chle_nudge_afternoon_zero", A,
            "Babe!! Twenty-minute lesson break. Brain LOVES it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "chle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chle_nudge_evening", A,
            "Evening!! Cute light lesson with tea. Cosy era. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "chle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chle_nudge_attention_loss", A,
            "Hi friend!! ONE tiny lesson today. Cute soft restart. NO shame ever.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chle_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
