package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Cheerleader × Digital — hype stance, no shame, screen-balance era. */
internal object CheerleaderDigitalLines {

    private const val A = "CHEERLEADER"
    private const val T = "DIGITAL"

    val all: List<DialogueLine> = listOf(

        DialogueLine("chdi_first_ever", A,
            "OH MY GOD a SCREEN-BALANCE era?? Phone in pocket. Eyes UP. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("chdi_morning", A,
            "Hi friend!! Phone face-down first hour please!! Iconic morning move.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "chdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chdi_morning_early", A,
            "Up EARLY!! Don't doom-scroll the morning queen!! Cute slow coffee. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "chdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chdi_afternoon", A,
            "Babe!! Mid-day. Cute screen-time glance. Honest. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "chdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chdi_evening", A,
            "Evening!! Phone in another room at dinner!! Eyes UP. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "chdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chdi_night_late", A,
            "Late!! Phone OUT of bedroom queen!! Tomorrow-you is BEGGING. Trust.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "chdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chdi_post_apotheosis", A,
            "BLOCK CLOSED!! Screen balance ICONIC. Keep the daily caps. Trust.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("chdi_monday", A,
            "MONDAY!! Cute week's screen-time target. Lower it just a touch. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "chdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chdi_friday", A,
            "FRIDAY!! Phone-free dinner tonight!! Friends-first. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "chdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chdi_weekend", A,
            "Weekend!! Cute half-day phone-OFF. In another room. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "chdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("chdi_level_1_reached", A,
            "FIRST TIER!! A whole week of cute morning-no-scroll!! Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "chdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chdi_level_2_reached", A,
            "SECOND TIER!! Screen-time DOWN. Hour reclaimed. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "chdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chdi_level_3_reached", A,
            "THIRD TIER!! Friends NOTICE the eye contact. Iconic role.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "chdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chdi_level_4_reached", A,
            "HIGHEST TIER!! Years of cute screen-balance. Phone is a TOOL. I LOVE you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "chdi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("chdi_attention_loss_mild", A,
            "Hey babe!! Few scroll-heavy days. Phone OUT of bedroom tonight. Cute soft restart.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "chdi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("chdi_attention_loss_hard", A,
            "Hi friend!! Doom-scroll era happened, NO shame!! Uninstall ONE app today. Tiny restart.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chdi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("chdi_mid_day_return", A,
            "Mid-day!! Phone in drawer ONE hour right now. Iconic mood-shift!!",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("chdi_wishes_pending", A,
            "Earned PRIZES with that screen discipline!! Cute treat — not a new app. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "chdi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("chdi_mid_streak", A,
            "Three days of cute low-scroll!! Brain QUIETER. Mood UP. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chdi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("chdi_sant_jordi", A,
            "SANT JORDI!! Phone in pocket today. Eyes UP. ICONIC street day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_la_merce", A,
            "MERCÈ!! Don't film the WHOLE thing!! Watch it!! Iconic presence.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_sant_joan", A,
            "SANT JOAN!! Phone in bag. Be at the beach. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_diada", A,
            "Diada!! Cute day off the news cycle. Phone in drawer half the day. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_nadal", A,
            "NADAL!! Phone in bag at table. Family > scrolling. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_cap_d_any", A,
            "NEW YEAR!! Cute app-audit day. Delete TWO. Iconic year-of-clarity.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chdi_reis", A,
            "REIS!! Set the cute kid-screen rules. Iconic. For YOU first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_carnaval", A,
            "CARNAVAL!! Phone away. Watch the parade. Iconic eyes-up day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_divendres_sant", A,
            "Quiet day!! Cute phone-off two-hour block. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_pasqua", A,
            "PASQUA MONDAY!! Reset notifications. Cute three-apps-only rule. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_festa_del_treball", A,
            "WORKERS' DAY!! Work-phone OFF. Iconic. Don't peek.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_festa_major_gracia", A,
            "GRÀCIA!! Cute eyes-up nights. Streets are art. Don't lens it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_assumpcio", A,
            "AUGUST!! Cute notification-off week. Iconic city-quiet vibe.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_hispanitat", A,
            "Day off!! Cute screen-audit honestly. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_castanyada", A,
            "CASTANYADA!! Cute long evenings. Don't fill them all with scroll. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_constitucio", A,
            "Bridge weekend!! Cute phone-off full day. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_immaculada", A,
            "PONT!! Five days!! Cute two phone-light ones. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_sant_esteve", A,
            "Day after!! Phone in another room. Cute family chaos. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_cap_d_any_eve", A,
            "LAST DAY!! Twelve grapes — EYES UP. Phone away. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "chdi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chdi_birthday", A,
            "BIRTHDAY QUEEN!! Phone OFF tonight. The room is the gift. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "chdi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_personal_date", A,
            "Today is special: {label}!! Phone in pocket. Eyes on what's HERE. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "chdi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("chdi_complete_1", A, "PHONE DOWN!! Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chdi_complete_2", A, "Cute screen-discipline LOGGED!!",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chdi_complete_3", A, "Eyes-up WIN!! Hype.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chdi_complete_first_today", A,
            "First boundary held!! Hour reclaimed. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "chdi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("chdi_complete_second_today", A,
            "TWO!! Compound brain-glow. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "chdi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("chdi_complete_third_today", A,
            "THREE!! Cute. Hours reclaimed. Notice what you DID with them!!",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "chdi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("chdi_complete_fourth_today", A,
            "FOUR!! Babe sick day or hiding from phone?? Honest cute check.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "chdi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("chdi_complete_fifth_today", A,
            "FIVE!! Iconic boundary day. Now stop counting. Just exist.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "chdi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("chdi_complete_after_streak", A,
            "Three days low scroll!! Brain QUIETER. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chdi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("chdi_apotheosis_1", A,
            "BLOCK CLOSED!! Screen balance ICONIC. Hype.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chdi_apotheosis_2", A,
            "CYCLE DONE!! Pick next cute screen goal. Tiny one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chdi_apotheosis_3", A,
            "CLOSED!! Eyes-up WIN!! Iconic.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chdi_apotheosis_first_ever", A,
            "FIRST BLOCK EVER!! Phone-free hours are a HABIT!! I'm SOBBING. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("chdi_apotheosis_1", "chdi_apotheosis_2", "chdi_apotheosis_3"),
            theme = T),
        DialogueLine("chdi_apotheosis_at_level_2", A,
            "PROMOTED!! Phone is a TOOL now. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "chdi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chdi_apotheosis_at_level_3", A,
            "SENIOR TIER!! Friends NOTICE the presence. Iconic role.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "chdi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chdi_apotheosis_at_level_4", A,
            "TOP TIER!! Years of clear attention. Iconic. I LOVE you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "chdi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("chdi_nudge_morning", A,
            "Morning!! Phone face-down first hour. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "chdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chdi_nudge_afternoon_zero", A,
            "Babe!! Phone in drawer one hour. Iconic mood-shift.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "chdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chdi_nudge_evening", A,
            "Evening!! Phone in the kitchen. Bedroom stays clean. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "chdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chdi_nudge_attention_loss", A,
            "Hi friend!! Uninstall ONE app today. Cute soft restart. NO shame ever.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chdi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
