package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Cheerleader × Writing — hype stance, no shame, words = joy. */
internal object CheerleaderWritingLines {

    private const val A = "CHEERLEADER"
    private const val T = "WRITING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("chwr_first_ever", A,
            "OH MY GOD a WRITING era?? Notebook open. Cute pages. Let's GO.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("chwr_morning", A,
            "Hi friend!! Three cute pages or one tiny scene. Brain is FRESH. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "chwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chwr_morning_early", A,
            "Up EARLY!! Best writing brain of the day. Iconic head-start. Write!!",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "chwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chwr_afternoon", A,
            "Babe!! Mid-day. Cute thirty-minute writing sprint. Coffee + words. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "chwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chwr_evening", A,
            "Evening!! Soft journaling. Even ONE line counts. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "chwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chwr_night_late", A,
            "Late!! Brain too soft for real writing. ONE line — sleep on the rest. Trust.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "chwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chwr_post_apotheosis", A,
            "BLOCK CLOSED!! Voice is GROWING. Keep the daily ritual. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("chwr_monday", A,
            "MONDAY!! Word count goal for the week. Cute small. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "chwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chwr_friday", A,
            "FRIDAY!! Cute review of the week's pages. ONE good sentence?? Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "chwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chwr_weekend", A,
            "Weekend!! Long-write era?? Cosy café. Hours of words. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "chwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("chwr_level_1_reached", A,
            "FIRST TIER!! Daily writing for a MONTH. Voice is FORMING. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "chwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chwr_level_2_reached", A,
            "SECOND TIER!! You finish drafts now. Cute. Real-writer behaviour. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "chwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chwr_level_3_reached", A,
            "THIRD TIER!! People SHARE your work. Iconic. Role-model writer.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "chwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chwr_level_4_reached", A,
            "HIGHEST TIER!! Years of pages. The voice is YOURS. I LOVE you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "chwr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("chwr_attention_loss_mild", A,
            "Hey babe!! Few skipped days. ONE cute paragraph today. Soft restart. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "chwr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("chwr_attention_loss_hard", A,
            "Hi friend!! Pages got dropped and that's OK!! ONE line today. Tiny restart.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chwr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("chwr_mid_day_return", A,
            "Mid-day!! Twenty-minute writing sprint. Cute. Phone away. GO!!",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("chwr_wishes_pending", A,
            "Earned PRIZES with all those pages!! Cute writer-reward time, queen.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "chwr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("chwr_mid_streak", A,
            "Three days of pages!! Voice CLEARER. Hands easier. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chwr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("chwr_sant_jordi", A,
            "SANT JORDI!! BOOK DAY!! Write a tiny love letter to someone. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_la_merce", A,
            "MERCÈ!! Cute scene-write — capture the streets. ONE paragraph!! Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_sant_joan", A,
            "SANT JOAN!! Notes by the fire. Write tomorrow. Tonight = SHOW UP.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_diada", A,
            "Diada!! Slow morning, long write. Iconic café session.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_nadal", A,
            "NADAL!! Cute Christmas-card writing. Real handwritten ones. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_cap_d_any", A,
            "NEW YEAR!! Year-of-writing intention. Cute small word count. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chwr_reis", A,
            "REIS!! Cute thank-you notes for gifts. Real handwriting. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_carnaval", A,
            "CARNAVAL!! Cute character-sketch from the street. ICONIC writer-watch.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_divendres_sant", A,
            "Quiet day!! Cute long-form day. Iconic deep-write.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_pasqua", A,
            "PASQUA MONDAY!! Notes on the hike. Iconic field-writing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_festa_del_treball", A,
            "WORKERS' DAY!! Cute morning-pages session. Iconic free thinking.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_festa_major_gracia", A,
            "GRÀCIA!! Notes on the decorated streets. Iconic immersion.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_assumpcio", A,
            "AUGUST!! Slow city. Iconic writer-summer. Long mornings. Pages.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_hispanitat", A,
            "Day off!! Cute slow writing session. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_castanyada", A,
            "CASTANYADA!! Long evenings = page-flow era. Cute. Cosy. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_constitucio", A,
            "Bridge weekend!! Cute long-write. Two hours. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_immaculada", A,
            "PONT!! Five days. Finish a cute draft. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_sant_esteve", A,
            "Day after!! Cute journal entry — what mattered yesterday. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_cap_d_any_eve", A,
            "LAST DAY!! Year-in-review pages. Cute reflection. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "chwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chwr_birthday", A,
            "BIRTHDAY QUEEN!! Cute letter to future-you. One year ahead. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "chwr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_personal_date", A,
            "Today is special: {label}!! Write three lines about today. Iconic mark.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "chwr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("chwr_complete_1", A, "WROTE!! Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chwr_complete_2", A, "PAGES DOWN!! Hype.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chwr_complete_3", A, "Words WIN!! Obsessed.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chwr_complete_first_today", A,
            "First pages!! Voice loosening. Iconic warm-up.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "chwr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("chwr_complete_second_today", A,
            "TWO!! Compound writing!! Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "chwr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("chwr_complete_third_today", A,
            "THREE!! Brain in FLOW. Stay there. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "chwr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("chwr_complete_fourth_today", A,
            "FOUR!! Babe big draft day or running from something?? Hydrate. Eat.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "chwr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("chwr_complete_fifth_today", A,
            "FIVE!! Iconic. Close the file. Body and brain BOTH need a walk.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "chwr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("chwr_complete_after_streak", A,
            "Three days of pages!! Voice TIGHTENING. Hands easier. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chwr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("chwr_apotheosis_1", A,
            "BLOCK CLOSED!! Voice GROWING. Cute. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chwr_apotheosis_2", A,
            "CYCLE DONE!! Pick next cute writing goal. We GOT this.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chwr_apotheosis_3", A,
            "CLOSED!! Writing-glow WIN. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chwr_apotheosis_first_ever", A,
            "FIRST BLOCK EVER!! Daily writing is a HABIT!! I'm SOBBING. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("chwr_apotheosis_1", "chwr_apotheosis_2", "chwr_apotheosis_3"),
            theme = T),
        DialogueLine("chwr_apotheosis_at_level_2", A,
            "PROMOTED!! You finish drafts now. Cute writer-confidence. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "chwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chwr_apotheosis_at_level_3", A,
            "SENIOR TIER!! People SHARE your work. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "chwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chwr_apotheosis_at_level_4", A,
            "TOP TIER!! Years of pages. The voice is YOURS. I LOVE you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "chwr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("chwr_nudge_morning", A,
            "Morning!! Three cute pages. Brain is fresh. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "chwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chwr_nudge_afternoon_zero", A,
            "Babe!! Twenty-minute sprint. Phone away. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "chwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chwr_nudge_evening", A,
            "Evening!! ONE journal line. That's it. Cute. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "chwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chwr_nudge_attention_loss", A,
            "Hi friend!! ONE line today. Cute soft restart. NO shame ever.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chwr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
