package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Cheerleader × Boundaries — hype stance, no shame, cute "no" energy. */
internal object CheerleaderBoundariesLines {

    private const val A = "CHEERLEADER"
    private const val T = "BOUNDARIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("chbo_first_ever", A,
            "You summoned a whole daemon to help you say “no”?? That's self-respect in ACTION. Okay. Let's go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("chbo_morning", A,
            "There you are. Pick today's one “no” before the day picks it for you. Which one is it?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "chbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chbo_morning_early", A,
            "You're up before anyone can ask you for anything. Don't open email yet — this hour is all yours.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "chbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chbo_afternoon", A,
            "Hi babe. When the “just one more thing” request lands today, you already know the answer. Proud in advance.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "chbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chbo_evening", A,
            "Hey. Work is done — actually done. Flip the notifications off and let the evening be soft.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "chbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chbo_night_late", A,
            "Anyone messaging you at this hour can meet tomorrow-you. Tonight-you is officially off the clock.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "chbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chbo_post_apotheosis", A,
            "Still glowing over that closed block — every limit held. Before the next “yes”, pause first. You've earned pauses.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("chbo_monday", A,
            "Fresh week. Quick peek at the calendar — did anything sneak in over the weekend? Cut it now, while it's small.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "chbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chbo_friday", A,
            "We made it. Out-of-office goes on, and the weekend stays a work-free zone. Guard it like treasure.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "chbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chbo_weekend", A,
            "No alarms. Phone on silent for the family hours — that one's non-negotiable, and I love that about us.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "chbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("chbo_level_1_reached", A,
            "LEVEL ONE!! You said a real “no” and kept it — and look, the sky is exactly where you left it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "chbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chbo_level_2_reached", A,
            "Level two. Your limits hold without rehearsal now. Do you know how long some people practice that?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "chbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chbo_level_3_reached", A,
            "Level three. People have stopped asking the wrong way — you taught them without a single fight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "chbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chbo_level_4_reached", A,
            "MAX LEVEL. Years of clean limits, and a calendar that finally belongs to you. I'm so unbelievably proud.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "chbo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("chbo_attention_loss_mild", A,
            "Hey you. Been saying yes to everything lately? It happens. Refuse one small thing today and we're back.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "chbo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("chbo_attention_loss_hard", A,
            "I missed you. If the calendar collapsed on you, we rebuild small: reclaim one block today. Zero shame, ever.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chbo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("chbo_mid_day_return", A,
            "Hi again. Steal one hour back from this day and put your own name on it. Right now, while I'm watching.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("chbo_wishes_pending", A,
            "All those limits earned you actual prizes. Spend one on a real day off — the kind with no phone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "chbo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("chbo_mid_streak", A,
            "Three days of limits held. Notice how much quieter everything got? That's you, doing that.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chbo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("chbo_sant_jordi", A,
            "Sant Jordi! Out-of-office on, roses and books first. Work can admire you from a distance today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_la_merce", A,
            "It's La Mercè and you are OFF. Say it out loud once, mean it, phone away — the city will do the rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_sant_joan", A,
            "Sant Joan! Firecrackers till sunrise — so no, you're not taking that early call tomorrow. Decline it now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_diada", A,
            "The Diada is a day off, and it's yours. Anything that asks for it gets a warm, polite no.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_nadal", A,
            "It's Nadal. Family hours mean the phone lives in another room — the sweetest limit you'll hold all year.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_cap_d_any", A,
            "A whole new year!! Start it by cutting two commitments that were never really yours. Feel how light that is.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chbo_reis", A,
            "Gift morning! Today belongs to family and wrapping paper — any work ask can wait in line behind the Kings.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_carnaval", A,
            "Carnaval! Permission to skip one party so you can actually enjoy the next two. Pacing is a costume too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_divendres_sant", A,
            "The whole city went quiet today, and so can you. No work — even the streets agree with your boundary.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_pasqua", A,
            "Pasqua Monday. You do not owe anyone Friday's hours back — holidays aren't debts. Eat the mona.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_festa_del_treball", A,
            "A day off named after work — the original boundary. Honor the line between working and resting. Lie down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_festa_major_gracia", A,
            "Gràcia is calling every single night this week. Pick two, decline the rest, love the two twice as hard.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_assumpcio", A,
            "Mid-August. The whole city closes — copy its homework. Out-of-office on, and make it REAL this time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_hispanitat", A,
            "A free day landed in the calendar. Defend it like it's yours — because it is. Warm, polite refusals only.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_castanyada", A,
            "Chestnut season means year-end pressure is warming up. Refuse the scope-creep NOW, while it's still small.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_constitucio", A,
            "Bridge weekend — two whole days with no work in them. Say it out loud so your calendar hears you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_immaculada", A,
            "The pont is HERE. Five days of nothing — and the “quick favour” email doesn't get a single one of them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_sant_esteve", A,
            "Second day of family is the heavy one. Slip away for an hour — a gentle “no” said with your feet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_cap_d_any_eve", A,
            "Last day of the year!! Name three commitments you're not carrying into January. Drop them with the grapes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "chbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chbo_birthday", A,
            "IT'S YOUR DAY!!! Refuse one obligation tonight and call it a present to yourself. Best gift on the table.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "chbo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_personal_date", A,
            "{label} — it's today. Guard the hour it deserves and let the noise wait outside. I'm here with you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "chbo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("chbo_complete_1", A, "You said no! Beautifully. Cleanly. I'm beaming.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chbo_complete_2", A, "Limit HELD. I saw the whole thing and I'm still clapping.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chbo_complete_3", A, "That refusal? Graceful. Kind. Absolutely yours.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chbo_complete_first_today", A,
            "First “no” of the day — and look at that, the sky's still up there. Told you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "chbo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("chbo_complete_second_today", A,
            "Two! That's a pattern now. People are learning where the line is, and you barely raised your voice.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "chbo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("chbo_complete_third_today", A,
            "THREE?! And the day got quieter every single time. That's a properly defended day and I'm in awe.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "chbo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("chbo_complete_fourth_today", A,
            "Four! Heavy day for limits — or are we picking fights? Asking gently, with all the love.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "chbo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("chbo_complete_fifth_today", A,
            "FIVE?! Okay, breathe. Boundaries are a garden, not a war. Stop counting and go enjoy the quiet you made.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "chbo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("chbo_complete_after_streak", A,
            "Three days of clean limits in a row. Your calendar finally tells the truth. That's rare and it's yours.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chbo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("chbo_apotheosis_1", A,
            "You closed the whole block. Just remember: the next “yes” gets a pause first. You've earned pauses.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chbo_apotheosis_2", A,
            "A whole cycle, done! The limits held because YOU held them. Same grip on the next one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chbo_apotheosis_3", A,
            "CLOSED!! Confetti everywhere!! Tomorrow we hold the line exactly the same, just with glitter on it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chbo_apotheosis_first_ever", A,
            "Your first block EVER. Saying “no” is an actual habit now. I'm not crying, there's glitter in my eye.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("chbo_apotheosis_1", "chbo_apotheosis_2", "chbo_apotheosis_3"),
            theme = T),
        DialogueLine("chbo_apotheosis_at_level_2", A,
            "Look at this. The calendar answers to you now. Keep it that way — I'd defend it with you any day.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "chbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chbo_apotheosis_at_level_3", A,
            "Level three. People respect your limits before you even say them. That's reputation — and you built it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "chbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chbo_apotheosis_at_level_4", A,
            "Top level. Years of clean limits, and the calendar tells the whole story. I'd pick you every single time.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "chbo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("chbo_nudge_morning", A,
            "Psst. Name today's one “no” before breakfast — decisions are cheaper in the morning.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "chbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chbo_nudge_afternoon_zero", A,
            "Nothing reclaimed yet today? One hour, back in your name. The calendar won't fight you — promise.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "chbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chbo_nudge_evening", A,
            "Before the couch wins: notifications off. One tap, whole evening yours. I'll cheer quietly.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "chbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chbo_nudge_attention_loss", A,
            "Still here, still yours. Reclaim one small block today — soft restart, zero shame, endless cheering.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chbo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
