package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Cheerleader × Admin — hype stance, no shame, cute folder rituals. */
internal object CheerleaderAdminLines {

    private const val A = "CHEERLEADER"
    private const val T = "ADMIN"

    val all: List<DialogueLine> = listOf(

        DialogueLine("chad_first_ever", A,
            "OH MY GOD an ADMIN era?? Cute folder vibes. Iconic. Let's GO.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("chad_morning", A,
            "Hi friend!! ONE cute form before coffee. Iconic small win.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "chad_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chad_morning_early", A,
            "Up EARLY!! Beat the queue at nine. Iconic head-start.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "chad_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chad_afternoon", A,
            "Babe!! One bill, one email, one form. Three cute things. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "chad_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chad_evening", A,
            "Evening!! Cute five-minute admin sweep. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "chad_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chad_night_late", A,
            "Late!! No tax form now please!! Note it, sleep, morning-you slays it. Trust.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "chad_greet", cooldownPicks = 3, theme = T),
        DialogueLine("chad_post_apotheosis", A,
            "BLOCK CLOSED!! Stack cleared. Iconic. Tiny daily pile-prevention. Trust.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("chad_monday", A,
            "MONDAY!! Cute week's-bills queue. Iconic prep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "chad_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chad_friday", A,
            "FRIDAY!! Cute close-the-week sweep. Monday-you THANKS.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "chad_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("chad_weekend", A,
            "Weekend!! ONE cute admin hour. Then play. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "chad_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("chad_level_1_reached", A,
            "FIRST TIER!! A whole month no overdue!! Iconic glow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "chad_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chad_level_2_reached", A,
            "SECOND TIER!! Cute quarterly rhythm. Taxes filed early. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "chad_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chad_level_3_reached", A,
            "THIRD TIER!! Cute system runs ITSELF. Role model.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "chad_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("chad_level_4_reached", A,
            "HIGHEST TIER!! Years no admin-dread. Iconic glow. I LOVE you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "chad_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("chad_attention_loss_mild", A,
            "Hey babe!! Pile crept up!! Open ONE envelope right now. Cute soft reset.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "chad_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("chad_attention_loss_hard", A,
            "Hi friend!! Stack got scary and that's OK!! ONE form today. Auto-pay the rest. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chad_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("chad_mid_day_return", A,
            "Mid-day!! Cute ten-minute folder time. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("chad_wishes_pending", A,
            "Earned PRIZES with that paperwork glow!! Cute treat queen.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "chad_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("chad_mid_streak", A,
            "Three days at the folder!! Pile SHRINKING. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chad_streak", cooldownPicks = 5, theme = T),

        DialogueLine("chad_sant_jordi", A,
            "SANT JORDI!! Gestoria pickup, then STREETS. Iconic. Be quick.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_la_merce", A,
            "MERCÈ!! Closed. Cute. Queue for tomorrow. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_sant_joan", A,
            "SANT JOAN!! Closed. Iconic admin-free day. Trust.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_diada", A,
            "Diada!! Closed. Cute slow-form day. Iconic for the deep ones.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_nadal", A,
            "NADAL!! NO admin today!! Iconic. Folder waits.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_cap_d_any", A,
            "NEW YEAR!! Cute standing-order renewal sweep. Iconic year-start.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chad_reis", A,
            "REIS!! Note tomorrow's first task tonight. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_carnaval", A,
            "CARNAVAL weekend!! Cute slow Tuesday morning = tax envelope time. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_divendres_sant", A,
            "Quiet day!! Cute filing-weather. Twenty minutes. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_pasqua", A,
            "PASQUA MONDAY!! Closed. Tomorrow's queue ready. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_festa_del_treball", A,
            "WORKERS' DAY!! Cute digital folder sort. Iconic five-minutes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_festa_major_gracia", A,
            "GRÀCIA!! Slow office week. Cute queue-build. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_assumpcio", A,
            "AUGUST!! Cute renewal sweep — passport, ID. Iconic prep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_hispanitat", A,
            "Bridge day!! Online-only forms. File two cute ones. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_castanyada", A,
            "CASTANYADA!! Year-end approaches!! Cute receipt-sweep starts. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_constitucio", A,
            "Bridge weekend!! ONE cute hour at the folder. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_immaculada", A,
            "PONT!! Five days. ONE cute tax-folder morning. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_sant_esteve", A,
            "Day after!! No admin today. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_cap_d_any_eve", A,
            "LAST DAY!! Cute year-end statements sweep. Iconic close.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "chad_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("chad_birthday", A,
            "BIRTHDAY QUEEN!! No admin today!! Note ID renewal for later. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "chad_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("chad_personal_date", A,
            "Today is special: {label}!! Note it in admin calendar. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "chad_personal", cooldownPicks = 1, theme = T),

        DialogueLine("chad_complete_1", A, "FILED!! Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chad_complete_2", A, "DONE!! Cute pile-shrink.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chad_complete_3", A, "Form WIN!! Hype.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("chad_complete_first_today", A,
            "First form done!! Dread is GONE. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "chad_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("chad_complete_second_today", A,
            "TWO!! Pile compounding-down. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "chad_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("chad_complete_third_today", A,
            "THREE!! Admin queen behaviour!! Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "chad_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("chad_complete_fourth_today", A,
            "FOUR!! Babe big-sweep day or avoiding bigger stuff?? Honest cute check.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "chad_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("chad_complete_fifth_today", A,
            "FIVE!! Big backlog day. Iconic. Tomorrow the REAL work. Close folder.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "chad_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("chad_complete_after_streak", A,
            "Three days at folder!! System FORMING. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "chad_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("chad_apotheosis_1", A,
            "BLOCK CLOSED!! Stack DONE. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chad_apotheosis_2", A,
            "CYCLE DONE!! Cute auto-pay audit. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chad_apotheosis_3", A,
            "CLOSED!! Folder-glow WIN!! Hype.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("chad_apotheosis_first_ever", A,
            "FIRST BLOCK EVER!! Admin rhythm is a HABIT!! I'm SOBBING. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("chad_apotheosis_1", "chad_apotheosis_2", "chad_apotheosis_3"),
            theme = T),
        DialogueLine("chad_apotheosis_at_level_2", A,
            "PROMOTED!! Folder runs itself. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "chad_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chad_apotheosis_at_level_3", A,
            "SENIOR TIER!! Quarterly audits. Iconic role.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "chad_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("chad_apotheosis_at_level_4", A,
            "TOP TIER!! Years no dread. Iconic. I LOVE you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "chad_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("chad_nudge_morning", A,
            "Morning!! One cute form before email. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "chad_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chad_nudge_afternoon_zero", A,
            "Babe!! Ten cute minutes at folder. NOW.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "chad_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chad_nudge_evening", A,
            "Evening!! Cute one envelope opened. That counts. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "chad_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("chad_nudge_attention_loss", A,
            "Hi friend!! ONE form today. Auto-pay the rest. Soft restart. NO shame ever.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "chad_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
