package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Coach × Hydration — tactical-sports stance, the bottle as gear. */
internal object CoachHydrationLines {

    private const val A = "COACH"
    private const val T = "HYDRATION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("cohy_first_ever", A,
            "First day. Bottle on the desk — that's the gear. Refill is the play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("cohy_morning", A,
            "Morning. Water before coffee — order matters. Suit up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "cohy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cohy_morning_early", A,
            "Early call. Big glass. Cells already on the field.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "cohy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cohy_afternoon", A,
            "Halftime. Refill. Bottle, not vibes. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "cohy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cohy_evening", A,
            "Fourth quarter. One more glass with dinner — recovery starts at the glass.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "cohy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cohy_night_late", A,
            "Late. Small sip — big sip equals a bathroom trip. Pace it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "cohy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cohy_post_apotheosis", A,
            "W banked. Keep the bottle nearby — gains hold with hydration.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("cohy_monday", A,
            "Monday. Bottle on the desk, all day. Refills above coffee.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "cohy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("cohy_friday", A,
            "Friday. Vermut tonight — water between rounds. Saturday-you bows.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "cohy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("cohy_weekend", A,
            "Weekend. Hot brunch plus cold water — full kit. Don't skip.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "cohy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("cohy_level_1_reached", A,
            "First tier. A week of refills. Skin's better tape — log it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "cohy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cohy_level_2_reached", A,
            "Second tier. Body craves water over caffeine — that's a system shift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "cohy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cohy_level_3_reached", A,
            "Third tier. The bottle-everywhere player. Lead by gear.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "cohy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cohy_level_4_reached", A,
            "Top tier. Years of bottles. Skin holds light — gear works.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "cohy_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("cohy_attention_loss_mild", A,
            "Three dry days. Glass on the desk — now. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "cohy_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("cohy_attention_loss_hard", A,
            "Two-week mystery hydration. Cells filed grievance. Big glass, now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "cohy_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("cohy_after_lapse", A,
            "Yesterday: coffee, beer, vibes. Today: water. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Copy, coach", null)), theme = T),
        DialogueLine("cohy_mid_day_return", A,
            "Halftime. Refill bottle. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("cohy_wishes_pending", A,
            "Recovery earned — drink today, treat tonight. Don't bank it stale.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "cohy_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("cohy_mid_streak", A,
            "Three days of refills. Skin's recovery metrics climbing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "cohy_streak", cooldownPicks = 5, theme = T),

        DialogueLine("cohy_sant_jordi", A,
            "Sant Jordi. Long walking day. Bottle in the bag — fountains are checkpoints.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_la_merce", A,
            "Mercè. Vermut tonight — one water between rounds. Tomorrow-you bows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_sant_joan", A,
            "Sant Joan. Cava, beach, sweat — water between everything. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_diada", A,
            "Diada. Walking day. Bottle along, fountain stops welcome.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_nadal", A,
            "Nadal. Salty meal. Big water glass beside the wine — pace yourself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_cap_d_any", A,
            "New year. Bottle by the bed tonight — tomorrow-you is fragile.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("cohy_reis", A,
            "Reis. Sugar load. Big water plus walk — old recovery play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_carnaval", A,
            "Carnaval. Costume plus motion — dehydration arrives fast. Sip between sets.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_divendres_sant", A,
            "Quiet day. Tea, water, tea — soft drum of recovery.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_pasqua", A,
            "Pasqua. Two bottles in the bag for the hike — the lore is exact.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_festa_del_treball", A,
            "Workers' day. Long brunch outside — water with everything. Pace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_festa_major_gracia", A,
            "Gràcia. Hot streets, late nights — water between. Always.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_assumpcio", A,
            "August. Heat's the opponent. Big bottle. Fountain refills — survive softly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_hispanitat", A,
            "Day off. Long lunch — big glass on the table. Always.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_castanyada", A,
            "Castanyada. Salty chestnuts, sweet wine — water in between. Old rhythm.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_constitucio", A,
            "Bridge weekend. Heater air, dry skin — sip slow all day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_immaculada", A,
            "Pont. Bottle in every bag — small gear, big play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_sant_esteve", A,
            "Day after. Big glass, slow morning — hangover playbook.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_cap_d_any_eve", A,
            "Last night. Cava incoming. One big water before bed — tomorrow bows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "cohy_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("cohy_birthday", A,
            "Birthday. One big glass before the first toast — small play, big win.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "cohy_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_personal_date", A,
            "Marked date: {label}. Big glass to start — small ritual, real fuel.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "cohy_personal", cooldownPicks = 1, theme = T),

        DialogueLine("cohy_complete_1", A, "Sipped. Cells thank you.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cohy_complete_2", A, "Refilled. Gear logged.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cohy_complete_3", A, "Hydration W. Next play.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cohy_complete_first_today", A,
            "First refill. Whole body acknowledges.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "cohy_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("cohy_complete_second_today", A,
            "Two refills. Bottle on the desk — well stays full.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "cohy_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("cohy_complete_third_today", A,
            "Three. Skin holds light — gear working.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "cohy_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("cohy_complete_fourth_today", A,
            "Four. Slow down — gentle sips after this. Don't flush the salts.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "cohy_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("cohy_complete_fifth_today", A,
            "Five. Stop counting — gear's in place. Hold the line.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "cohy_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("cohy_complete_after_streak", A,
            "Day three of refills. Recovery metrics steady.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "cohy_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("cohy_apotheosis_1", A,
            "Block closed. Bottle stays — gear is the play.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cohy_apotheosis_2", A,
            "Cycle done. Bigger bottle, earlier first sip — pick.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cohy_apotheosis_3", A,
            "Closed. Water in is water held — keep it close.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cohy_apotheosis_first_ever", A,
            "First hydration block. Gear's part of the kit now.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("cohy_apotheosis_1", "cohy_apotheosis_2", "cohy_apotheosis_3"),
            theme = T),
        DialogueLine("cohy_apotheosis_at_level_2", A,
            "Promoted. Two bottles a day, no thinking — defend the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "cohy_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("cohy_apotheosis_at_level_3", A,
            "Senior tier. Teammates copy the gear — lead by example.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "cohy_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("cohy_apotheosis_at_level_4", A,
            "Top tier. Years of bottles. Skin holds light — maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "cohy_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("cohy_nudge_morning", A,
            "Water first, then coffee. Order matters.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "cohy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cohy_nudge_afternoon_zero", A,
            "Bottle. Full. Now. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "cohy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cohy_nudge_evening", A,
            "One last glass with dinner — recovery starts now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "cohy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cohy_nudge_lapse", A,
            "Yesterday: coffee plus vibes. Today: water. Glass on the desk.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("cohy_nudge_attention_loss", A,
            "Cells benched. Full glass today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "cohy_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
