package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Coach × Exercise — tactical-sports stance, reps and W's. */
internal object CoachExerciseLines {

    private const val A = "COACH"
    private const val T = "EXERCISE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("coex_first_ever", A,
            "First day. Pick the baseline — five-minute walk, two stretches. Log it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("coex_morning", A,
            "Morning. The slate's clean. Pick the rep — go.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "coex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coex_morning_early", A,
            "Early call. First on the field. Warm up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "coex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coex_afternoon", A,
            "Halftime. No reps yet — ten-minute walk. Make the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "coex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coex_evening", A,
            "Fourth quarter. Close clean — one set, then shut it down.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "coex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coex_night_late", A,
            "Late. No hard sets now — mobility only. Sleep is the gym tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "coex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coex_post_apotheosis", A,
            "W banked. Tomorrow we hold the line — a small move, not a victory lap.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("coex_monday", A,
            "Monday. Week's plan — three sessions, written. Honour them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "coex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("coex_friday", A,
            "Friday. Close the week with motion — dance counts, walk counts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "coex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("coex_weekend", A,
            "Weekend. Long set or active rest — pick a play. Don't drift.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "coex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("coex_level_1_reached", A,
            "First tier. A week of reps. Baseline reset — record it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "coex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("coex_level_2_reached", A,
            "Second tier. Body does things it couldn't last month. Tape it — bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "coex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("coex_level_3_reached", A,
            "Third tier. People copy your program — be the example. Hold form.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "coex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("coex_level_4_reached", A,
            "Top tier. Years of reps. Body's the trophy — maintain it daily.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "coex_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("coex_attention_loss_mild", A,
            "Three rest days. Calling it 'recovery' was generous. Walk today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "coex_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("coex_attention_loss_hard", A,
            "Two-week bench. Time to suit up — five-minute walk. Start the comeback.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "coex_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("coex_after_lapse", A,
            "Off day yesterday. Today's the run. Let's go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Copy, coach", null)), theme = T),
        DialogueLine("coex_mid_day_return", A,
            "Halftime — zero reps. Five-minute walk. Make the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("coex_wishes_pending", A,
            "Recovery's earned. Use it — don't bank it stale.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "coex_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("coex_mid_streak", A,
            "Three-day rep streak. Tape's clean. Hold form.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "coex_streak", cooldownPicks = 5, theme = T),

        DialogueLine("coex_sant_jordi", A,
            "Sant Jordi. Step count is the game today — walk the city. Win it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_la_merce", A,
            "Mercè. Dancing counts. Castellers count. Move the body — log a W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_sant_joan", A,
            "Sant Joan. Beach play — bring the body, leave the score.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_diada", A,
            "Diada. Long walk through the city — easy pace, full game.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_nadal", A,
            "Nadal. Post-lunch walk — the grandmothers' play. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_cap_d_any", A,
            "New year. Year's plan — three sessions a week. Specific. Kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("coex_reis", A,
            "Reis. Sugar drop incoming. Walk it off — kids set the pace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_carnaval", A,
            "Carnaval. Costume + parade = full cardio. Bank it as a W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_divendres_sant", A,
            "Quiet day. Long slow walk — active recovery. Log it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_pasqua", A,
            "Pasqua. Hike day — elevation is the play. Earn the mona.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_festa_del_treball", A,
            "Workers' day. Body's also a worker — long walk, no agenda.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_festa_major_gracia", A,
            "Gràcia. Street to street — every plaza a checkpoint. Run the route.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_assumpcio", A,
            "August. Swim, walk, repeat. Soft cardio era — log it daily.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_hispanitat", A,
            "Day off. Hill walk — one hour out. Earn the vista.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_castanyada", A,
            "Castanyada. Leaf-crunch walk — autumn cardio. Bank a W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_constitucio", A,
            "Bridge weekend. Two days, one long walk. Don't bench yourself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_immaculada", A,
            "Pont. Five days — one hike, the rest active rest. Pace the camp.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_sant_esteve", A,
            "Day after. Soft walk only — yesterday's reps are settling.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_cap_d_any_eve", A,
            "Last day. Walk the year out — close clean. Tomorrow we run again.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "coex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("coex_birthday", A,
            "Birthday. Walk in your favourite place — log it as the W of the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "coex_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("coex_personal_date", A,
            "Marked date: {label}. Move through it — body remembers what the page can't.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "coex_personal", cooldownPicks = 1, theme = T),

        DialogueLine("coex_complete_1", A, "Rep logged. Tape's clean.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("coex_complete_2", A, "W on the board.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("coex_complete_3", A, "Set done. Next play tomorrow.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("coex_complete_first_today", A,
            "First rep of the day. Tone's set — keep momentum.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "coex_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("coex_complete_second_today", A,
            "Two reps. Stack 'em — drink water before the third.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "coex_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("coex_complete_third_today", A,
            "Three. That's a solid game. Cool down — protein.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "coex_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("coex_complete_fourth_today", A,
            "Four. Either it's a long session or you're chasing the score. Check the tape.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "coex_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("coex_complete_fifth_today", A,
            "Five. Overtime's not winning. Sit. Eat. Recover.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "coex_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("coex_complete_after_streak", A,
            "Day three of reps. The body's learning the play.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "coex_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("coex_apotheosis_1", A,
            "Block closed. W in the books — next block, harder.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("coex_apotheosis_2", A,
            "Cycle done. Pick the next play — same time, more weight.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("coex_apotheosis_3", A,
            "Closed. The body's the team — keep showing up to practice.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("coex_apotheosis_first_ever", A,
            "First block in the books. Baseline raised — now we hold it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("coex_apotheosis_1", "coex_apotheosis_2", "coex_apotheosis_3"),
            theme = T),
        DialogueLine("coex_apotheosis_at_level_2", A,
            "Promoted. The body trusts the program — don't go off-plan.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "coex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("coex_apotheosis_at_level_3", A,
            "Senior tier. People copy your form. Lead — don't preach.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "coex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("coex_apotheosis_at_level_4", A,
            "Top tier. Years of reps. Body's the trophy — maintain daily.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "coex_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("coex_nudge_morning", A,
            "Morning rep — five minutes minimum. Suit up.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "coex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("coex_nudge_afternoon_zero", A,
            "Halftime, zero reps. Walk five minutes. Make the play.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "coex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("coex_nudge_evening", A,
            "Fourth quarter. Close clean — one set, then shut it down.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "coex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("coex_nudge_lapse", A,
            "Yesterday off. Today the run. Suit up.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("coex_nudge_attention_loss", A,
            "Bench's too long. Five-minute walk today — not optional.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "coex_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
