package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Coach × Recovery — tactical-sports stance, off-day discipline. */
internal object CoachRecoveryLines {

    private const val A = "COACH"
    private const val T = "RECOVERY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("core_first_ever", A,
            "Welcome to the program. Recovery's a play too, not garbage time — pick a rest block and log it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("core_morning", A,
            "Slow start today — coffee, stretch, breath. Pre-game doesn't need to be loud to count.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "core_greet", cooldownPicks = 3, theme = T),
        DialogueLine("core_morning_early", A,
            "First one up again. Don't sprint into it — the body needs its warm-up same as anyone else's.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "core_greet", cooldownPicks = 3, theme = T),
        DialogueLine("core_afternoon", A,
            "Plenty of clock left today. Twenty minutes feet-up now buys you the fourth quarter.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "core_greet", cooldownPicks = 3, theme = T),
        DialogueLine("core_evening", A,
            "This is the wind-down quarter — bath, book, low light. Close it out slow on purpose.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "core_greet", cooldownPicks = 3, theme = T),
        DialogueLine("core_night_late", A,
            "Late again. Lights low, screens off — the body's already calling for the bench. Listen to it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "core_greet", cooldownPicks = 3, theme = T),
        DialogueLine("core_post_apotheosis", A,
            "W banked. Hold the rest — recovery is a rep, not a luxury.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("core_monday", A,
            "Game week opens. Pick this week's rest blocks now and book them — that sets the tone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "core_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("core_friday", A,
            "One practice left before the break. Read the load tape — what's the body actually asking for.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "core_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("core_weekend", A,
            "Off-days aren't zero-days, but they're not grind days either. Take one full slow day, no admin.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "core_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("core_level_1_reached", A,
            "You're on the roster now — a weekly recovery block held long enough to be wired in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "core_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("core_level_2_reached", A,
            "Starter minutes. You're stopping before the injury now instead of after — that's the real W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "core_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("core_level_3_reached", A,
            "Captain's armband. Sleep, food, rest are non-negotiable at this level — hold the standard.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "core_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("core_level_4_reached", A,
            "Hall of Fame pacing. Years of knowing when to sit — and the body's still in the game for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "core_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("core_attention_loss_mild", A,
            "Few skipped rest days. Twenty minutes feet-up now — small reset.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "core_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("core_attention_loss_hard", A,
            "Two weeks of grinding. Suit up — full rest day this week. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "core_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("core_after_lapse", A,
            "Yesterday the grind won the rep. Fine — today's rest block is the only one that's live. Take it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Copy, coach", null)), theme = T),
        DialogueLine("core_mid_day_return", A,
            "Halftime nap — door closed, alarm set, twenty minutes on the clock. That's the whole play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("core_wishes_pending", A,
            "Recovery earned — massage, day off, real vacation. Bring it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "core_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("core_mid_streak", A,
            "Three days of pacing. Body's repaying — hold form.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "core_streak", cooldownPicks = 5, theme = T),

        DialogueLine("core_sant_jordi", A,
            "Sant Jordi's a walking day, book in hand, no race to it. Let today's rep be that slow lap.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_la_merce", A,
            "Mercè has the city running all weekend. Sit one show out, feet up, water in hand — recovery counts too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_sant_joan", A,
            "Sant Joan's bonfires run long tonight, so plan tomorrow's lie-in now — sleep is the recovery play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_diada", A,
            "Diada's an earned slow day. Don't let admin sneak in and fill up the bench time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_nadal", A,
            "Nadal's long table calls for slow plates — pace the meal and let the recovery build itself in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_cap_d_any", A,
            "New season opens. Pick one rest vow — sleep, breathing room, an actual nap — and suit up for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("core_reis", A,
            "Reis morning runs long and loud around you. Let the kids run — take the slow sip, old play kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_carnaval", A,
            "Carnaval brings the noise; the recovery play after it is a long, unhurried sleep. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_divendres_sant", A,
            "City's gone quiet today. Match it with a whole-day recovery — bath, book, bed. That's the session.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_pasqua", A,
            "Pasqua's hike earns its reward — long lunch, longer nap after. Bank the W properly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_festa_del_treball", A,
            "Today's literally about rest earned by work, and the body's the one that put in the shift. Rest it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_festa_major_gracia", A,
            "Gràcia's streets are dressed up all week. Find a bench, watch it go by, hydrate — that's today's rep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_assumpcio", A,
            "Empty city, half the squad at the beach — August runs on naps. The bench is wide open, take it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_hispanitat", A,
            "Day off, opinions everywhere else. Our lane stays simple — sleep in, long brunch, slow body.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_castanyada", A,
            "Castanyada calls for the couch, a blanket, warm food. Old play, still the right one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_constitucio", A,
            "Bridge weekend opening up. Book a long rest block now — non-negotiable — and bank the W early.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_immaculada", A,
            "Five open days ahead — long sleep, slow days. The body's earned that kind of buffer.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_sant_esteve", A,
            "Day-after protocol: the whole day on the bench, earned fair and square. Run it slow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("core_cap_d_any_eve", A,
            "Last session of the season tonight. Pace it — bath before, water during — bank the W at midnight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "core_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("core_birthday", A,
            "Your day, so the plan flexes. Sleep in, eat slow — the body's the whole team today. Hold the play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "core_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("core_personal_date", A,
            "Today's {label}. You told me it matters, so today's play is simple — one rest block, and slow down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "core_personal", cooldownPicks = 1, theme = T),

        DialogueLine("core_complete_1", A, "Rested. Tape's clean.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("core_complete_2", A, "Off the field. W banked.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("core_complete_3", A, "Body refilled. Good rep.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("core_complete_first_today", A,
            "First rest block. Tomorrow's sharper for it — momentum's on.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "core_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("core_complete_second_today", A,
            "Two rest blocks. Battery climbing — stay with it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "core_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("core_complete_third_today", A,
            "Three. Solid recovery day — hold form.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "core_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("core_complete_fourth_today", A,
            "Four. Sick day, or hiding behind it? Check the tape.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "core_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("core_complete_fifth_today", A,
            "Five. Move a little — body needs blood-flow too. Game on.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "core_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("core_complete_after_streak", A,
            "Day three of pacing. Body's repaying — hand is fluent.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "core_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("core_apotheosis_1", A,
            "Block closed. Recovery's wired — next block sharper.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("core_apotheosis_2", A,
            "Cycle done. Pick next rest play — sleep, food, slow.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("core_apotheosis_3", A,
            "Closed. Bench is wider now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("core_apotheosis_first_ever", A,
            "First rest-block. Recovery is canon — body's a teammate now.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("core_apotheosis_1", "core_apotheosis_2", "core_apotheosis_3"),
            theme = T),
        DialogueLine("core_apotheosis_at_level_2", A,
            "Promoted. You stop before injury — keep the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "core_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("core_apotheosis_at_level_3", A,
            "Senior tier. Sleep, food, rest — non-negotiable. Hold form.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "core_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("core_apotheosis_at_level_4", A,
            "Top tier. Years of pacing. Body's still in the game — steady.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "core_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("core_nudge_morning", A,
            "Slow start. Coffee, stretch, breath. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "core_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("core_nudge_afternoon_zero", A,
            "Twenty-minute nap. Door closed. Bench is empty.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "core_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("core_nudge_evening", A,
            "Wind-down play. Bath, book, low light.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "core_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("core_nudge_lapse", A,
            "Yesterday the grind won that round. It's on tape, not live — today's rest block is the one that counts.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("core_nudge_attention_loss", A,
            "Recovery benched. Full rest day this week. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "core_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
