package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Coach × Love — tactical-sports stance, partner-team plays. */
internal object CoachLoveLines {

    private const val A = "COACH"
    private const val T = "LOVE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("colo_first_ever", A,
            "First day. Pick one small play — text, ask, listen. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("colo_morning", A,
            "Morning. Real good-morning — eye contact, not phone. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "colo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("colo_morning_early", A,
            "Early call. Coffee for two — small offering. Tape's clean.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "colo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("colo_afternoon", A,
            "Halftime. One-line check-in — how's the day? Run the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "colo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("colo_evening", A,
            "Fourth quarter. Dinner together — phones away. Score the meal.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "colo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("colo_night_late", A,
            "Late. Hand on shoulder, soft word — count it. Then sleep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "colo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("colo_post_apotheosis", A,
            "W banked. Hold the small plays — relationship's built on reps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("colo_monday", A,
            "Monday. Quick how's-your-week check — sets the tone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "colo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("colo_friday", A,
            "Friday. Plan something for the two of you — book it. Mark it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "colo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("colo_weekend", A,
            "Weekend. Long block of time together — phones off. Bench earned.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "colo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("colo_level_1_reached", A,
            "First tier. Daily small acts for a month — wired in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "colo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("colo_level_2_reached", A,
            "Second tier. Repair plays come fast now — that's the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "colo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("colo_level_3_reached", A,
            "Third tier. You see the team before yourself. Maintain — hold form.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "colo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("colo_level_4_reached", A,
            "Top tier. Years of small offerings. Partnership is built.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "colo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("colo_attention_loss_mild", A,
            "Few skipped days. Send one warm text now — small reset.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "colo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("colo_attention_loss_hard", A,
            "Two weeks of distance. Suit up — call them today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "colo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("colo_after_lapse", A,
            "Yesterday: distance 1, you 0. Today: one warm message. No appeal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Copy, coach", null)), theme = T),
        DialogueLine("colo_mid_day_return", A,
            "Halftime. Send one specific text — what you saw, thought of them. Run it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("colo_wishes_pending", A,
            "Recovery earned — small date, small gift, small letter. Bring it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "colo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("colo_mid_streak", A,
            "Three days of showing up. Connection tightens — hold form.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "colo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("colo_sant_jordi", A,
            "Sant Jordi. Book and rose — classic play. Hand-delivered. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_la_merce", A,
            "Mercè. Take them — crowd-coded romance. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_sant_joan", A,
            "Sant Joan. Beach, fire, slow night with them. Phones away.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_diada", A,
            "Diada. Long lunch with them — old play, kept. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_nadal", A,
            "Nadal. Small thought-out gift — show you noticed. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_cap_d_any", A,
            "New year. Kiss at midnight is canon. Don't fumble.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("colo_reis", A,
            "Reis. Wrapped small thing — note in the box. Old play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_carnaval", A,
            "Carnaval. Costume-team — go together. Photos count.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_divendres_sant", A,
            "Quiet day. Slow morning together — read in the same room. Counts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_pasqua", A,
            "Pasqua. Easter walk — small hike, holding hands. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_festa_del_treball", A,
            "Workers' day. Slow morning, late breakfast — together. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_festa_major_gracia", A,
            "Gràcia. Take them to see the streets — neighbours' love-letter to home.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_assumpcio", A,
            "August. Empty city — long days together. Wide-open bench.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_hispanitat", A,
            "Day off. Long lunch, slow afternoon — phones away.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_castanyada", A,
            "Castanyada. Warm food, candles — at home together. Old play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_constitucio", A,
            "Bridge weekend. Small trip — somewhere new, two of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_immaculada", A,
            "Pont. Block out the day for them — no admin allowed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_sant_esteve", A,
            "Day after. Slow morning, quiet talk — what mattered yesterday?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_cap_d_any_eve", A,
            "Last day. Long honest talk together — what built the year. Hold the play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "colo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("colo_birthday", A,
            "Birthday. Hold the partnership in mind — small gift, real one. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "colo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("colo_personal_date", A,
            "Marked date: {label}. Hold them in mind today — one small play marks it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "colo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("colo_complete_1", A, "Showed up. Tape's clean.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("colo_complete_2", A, "Small play kept. W banked.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("colo_complete_3", A, "Connection held. Good rep.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("colo_complete_first_today", A,
            "First play. Day's warmer for it — momentum's on.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "colo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("colo_complete_second_today", A,
            "Two. They notice — stay with it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "colo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("colo_complete_third_today", A,
            "Three. Solid day for the team — hold form.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "colo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("colo_complete_fourth_today", A,
            "Four. Big love-day, or covering for something? Check the tape.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "colo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("colo_complete_fifth_today", A,
            "Five. Be with them now — drop the checklist. Game on.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "colo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("colo_complete_after_streak", A,
            "Day three of small plays. They feel held — hand is fluent.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "colo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("colo_apotheosis_1", A,
            "Block closed. Team's tighter — next block warmer.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("colo_apotheosis_2", A,
            "Cycle done. Pick next small play — date, repair, ritual.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("colo_apotheosis_3", A,
            "Closed. Floor between you is wider.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("colo_apotheosis_first_ever", A,
            "First love-block. Showing up is canon — relationship's a system now.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("colo_apotheosis_1", "colo_apotheosis_2", "colo_apotheosis_3"),
            theme = T),
        DialogueLine("colo_apotheosis_at_level_2", A,
            "Promoted. Repair plays come fast — keep the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "colo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("colo_apotheosis_at_level_3", A,
            "Senior tier. You see team before self. Hold form.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "colo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("colo_apotheosis_at_level_4", A,
            "Top tier. Years of small offerings. Partnership is built — steady.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "colo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("colo_nudge_morning", A,
            "Real good-morning. Eye contact. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "colo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("colo_nudge_afternoon_zero", A,
            "One specific text. What you saw, thought of them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "colo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("colo_nudge_evening", A,
            "Dinner — phones away. Score the meal.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "colo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("colo_nudge_lapse", A,
            "Yesterday: distance won. Today: one warm message. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("colo_nudge_attention_loss", A,
            "They've been benched. Call them today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "colo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
