package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Coach × Digital — tactical-sports stance, screen-discipline plays. */
internal object CoachDigitalLines {

    private const val A = "COACH"
    private const val T = "DIGITAL"

    val all: List<DialogueLine> = listOf(

        DialogueLine("codi_first_ever", A,
            "First day. Pick one window — phone in drawer, twenty minutes. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("codi_morning", A,
            "Morning. No phone before coffee — clear scoreboard. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "codi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("codi_morning_early", A,
            "Early call. Phone in another room until breakfast — tape's clean.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "codi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("codi_afternoon", A,
            "Halftime. Twenty-minute focus block — notifications off. Run it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "codi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("codi_evening", A,
            "Fourth quarter. Phone down at dinner — non-negotiable.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "codi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("codi_night_late", A,
            "Late. Screens off ninety minutes before bed. No appeal. Then sleep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "codi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("codi_post_apotheosis", A,
            "W banked. Hold the boundary — focus stays sharp with reps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("codi_monday", A,
            "Monday. Pick three offline blocks this week — book them. Sets the tone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "codi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("codi_friday", A,
            "Friday. Read week's screen-time tape — what crowded the slate?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "codi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("codi_weekend", A,
            "Weekend. Half-day offline — phone in drawer. Bench earned.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "codi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("codi_level_1_reached", A,
            "First tier. Daily phone-down hours for a month — wired in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "codi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("codi_level_2_reached", A,
            "Second tier. You catch the reach-for-phone before it lands — that's the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "codi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("codi_level_3_reached", A,
            "Third tier. Long focus blocks come easy. Maintain — hold form.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "codi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("codi_level_4_reached", A,
            "Top tier. Years of phone-down. Attention is yours again.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "codi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("codi_attention_loss_mild", A,
            "Few skipped days. Phone in drawer one hour — small reset.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "codi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("codi_attention_loss_hard", A,
            "Two weeks of doomscroll. Suit up — half-day offline today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "codi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("codi_after_lapse", A,
            "Yesterday: scroll 1, you 0. Today: one offline hour. No appeal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Copy, coach", null)), theme = T),
        DialogueLine("codi_mid_day_return", A,
            "Halftime. Phone in another room — twenty-minute focus block. Run it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("codi_wishes_pending", A,
            "Recovery earned — paper book, dumb phone, walk without device. Bring it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "codi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("codi_mid_streak", A,
            "Three days of phone-down. Brain's quieter — hold form.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "codi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("codi_sant_jordi", A,
            "Sant Jordi. Phone in pocket, eyes up — city's the feed. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_la_merce", A,
            "Mercè. One photo per show — eyes on the stage, not the screen.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_sant_joan", A,
            "Sant Joan. Phone away at the beach. Fire's the screen tonight. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_diada", A,
            "Diada. Half-day offline — slow play. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_nadal", A,
            "Nadal. Phone in drawer through the meal — non-negotiable. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_cap_d_any", A,
            "New year. Pick the screen-time vow — kept beats large. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("codi_reis", A,
            "Reis. Phone away while kids unwrap — eyes on faces. Old play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_carnaval", A,
            "Carnaval. Costume's not for the phone — eyes up. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_divendres_sant", A,
            "Quiet day. Long offline block — the city's already pausing. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_pasqua", A,
            "Pasqua. Trail day — phone airplane-mode. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_festa_del_treball", A,
            "Workers' day. Off the laptop. Off the phone. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_festa_major_gracia", A,
            "Gràcia. Look at the streets, not the feed about the streets.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_assumpcio", A,
            "August. Empty city — perfect offline conditions. Bench is wide open.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_hispanitat", A,
            "Day off. Half-day phone-in-drawer. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_castanyada", A,
            "Castanyada. Candles, warm food, no screens — old play, kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_constitucio", A,
            "Bridge weekend. Phone in airplane mode — trip's the screen.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_immaculada", A,
            "Pont. Half-day offline — slow days allow it. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_sant_esteve", A,
            "Day after. Slow morning, phone in drawer — long-form recovery.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_cap_d_any_eve", A,
            "Last day. Phone off through the night — eyes on the room. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "codi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("codi_birthday", A,
            "Birthday. Phone-free dinner — people there in person count. Hold the play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "codi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("codi_personal_date", A,
            "Marked date: {label}. One offline hour today — hold the date off-screen.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "codi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("codi_complete_1", A, "Phone down. Tape's clean.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("codi_complete_2", A, "Block held. W banked.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("codi_complete_3", A, "Focus kept. Good rep.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("codi_complete_first_today", A,
            "First block. Brain's coming back online — momentum's on.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "codi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("codi_complete_second_today", A,
            "Two blocks. Attention's stitched — stay with it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "codi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("codi_complete_third_today", A,
            "Three. Solid focus day — hold form.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "codi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("codi_complete_fourth_today", A,
            "Four. Big offline day, or hiding from a message? Check the tape.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "codi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("codi_complete_fifth_today", A,
            "Five. Reply to the people who matter — phone has uses too. Game on.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "codi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("codi_complete_after_streak", A,
            "Day three of phone-down. Brain runs longer — hand is fluent.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "codi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("codi_apotheosis_1", A,
            "Block closed. Attention's wider — next block sharper.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("codi_apotheosis_2", A,
            "Cycle done. Pick next limit — app, hour, room.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("codi_apotheosis_3", A,
            "Closed. Slate's clean.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("codi_apotheosis_first_ever", A,
            "First focus-block. Phone-down hour is canon — attention's yours.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("codi_apotheosis_1", "codi_apotheosis_2", "codi_apotheosis_3"),
            theme = T),
        DialogueLine("codi_apotheosis_at_level_2", A,
            "Promoted. You catch the reach-for-phone — keep the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "codi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("codi_apotheosis_at_level_3", A,
            "Senior tier. Long focus blocks come easy — hold form.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "codi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("codi_apotheosis_at_level_4", A,
            "Top tier. Years phone-down. Attention is yours — steady.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "codi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("codi_nudge_morning", A,
            "No phone before coffee. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "codi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("codi_nudge_afternoon_zero", A,
            "Phone in another room. Twenty-minute focus block.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "codi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("codi_nudge_evening", A,
            "Phone down at dinner. Non-negotiable.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "codi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("codi_nudge_lapse", A,
            "Yesterday: scroll won. Today: one offline hour. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("codi_nudge_attention_loss", A,
            "Focus benched. Half-day offline today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "codi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
