package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Coach × Finances — tactical-sports stance, the scoreboard. */
internal object CoachFinancesLines {

    private const val A = "COACH"
    private const val T = "FINANCES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("cofi_first_ever", A,
            "Day one, and the scoreboard's real whether we look or not. Open the app — baseline read.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("cofi_morning", A,
            "Ten-second balance check to open the day. That's the whole play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "cofi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofi_morning_early", A,
            "First one up gets the quiet hours. A glance at the budget app reads the field early.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "cofi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofi_afternoon", A,
            "Call it halftime. Check the week's number before lunch — honest pricing, no surprises.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "cofi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofi_evening", A,
            "We're into the fourth quarter of the day. Three-line spending log closes it clean.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "cofi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofi_night_late", A,
            "This late, no online shopping. The past-midnight scout always makes bad trades.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "cofi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofi_post_apotheosis", A,
            "Yesterday's win is banked. Keep the weekly look going — don't drift off the tape.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("cofi_monday", A,
            "Week's opening kickoff. Five-line plan for the week — specific enough to keep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "cofi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("cofi_friday", A,
            "Before we close the week, keep a number in mind before vermut — that's the game-day plan.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "cofi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("cofi_weekend", A,
            "Off-day on the calendar. Free plays count — park walks, home suppers, slow afternoons.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "cofi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("cofi_level_1_reached", A,
            "First tier reached. A month of check-ins behind you — the dread's already leaving the room.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "cofi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cofi_level_2_reached", A,
            "Second tier. Savings are climbing and sleep's better for it — bank that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "cofi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cofi_level_3_reached", A,
            "Third tier now. People are asking about the system — share it, and hold the form.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "cofi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cofi_level_4_reached", A,
            "Top tier. Years of small habits behind you — that's real freedom now. Defend it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "cofi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("cofi_attention_loss_mild", A,
            "A few mystery-charge days slipped by. Open the app for one minute — read the tape.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "cofi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("cofi_attention_loss_hard", A,
            "Two weeks dodged in a row. The late fee's the gentle warning — pay it, set auto-pay, now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "cofi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("cofi_after_lapse", A,
            "Yesterday's off the tape. Today's the live game — one category review, no appeal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Copy, coach", null)), theme = T),
        DialogueLine("cofi_mid_day_return", A,
            "Halfway through the day and the board's still blank. Five-minute honest glance runs the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("cofi_wishes_pending", A,
            "Recovery's on the books. Spend it on you — a small upgrade, not another subscription.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "cofi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("cofi_mid_streak", A,
            "Three check-in days in a row. Anxiety's down, confidence is climbing — hold that form.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "cofi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("cofi_sant_jordi", A,
            "Sant Jordi's out there — books and roses. Small spend, full game today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_la_merce", A,
            "Mercè's got the whole city offering itself for free. Accept the play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_sant_joan", A,
            "Sant Joan tonight — cava and coca. Skip the beach-bar markups, smart play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_diada", A,
            "Diada's a free city day. Walking's the largest line item on the ledger.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_nadal", A,
            "Family's the starting lineup today. Gift list in hand — no panic-buys, discipline play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_cap_d_any", A,
            "New season starting. Three goals — specific, quiet, kept. That's the playbook.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("cofi_reis", A,
            "Gift morning. Track the receipts — returns are also a play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_carnaval", A,
            "Costumes are out today. Pull one from the closet — cheap-joy win.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_divendres_sant", A,
            "The city's gone quiet today. Home meal, zero spend — the afternoon still counts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_pasqua", A,
            "Pasqua, long weekend. Mona and a packed lunch — cheap day, big win.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_festa_del_treball", A,
            "Today's literally about earned rest. Park, friends, free hours — the ledger rests too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_festa_major_gracia", A,
            "Gràcia's streets are dressed up all week — music, decoration, dancing, all free.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_assumpcio", A,
            "City's emptied out for August. No big spends — the wallet gets to rest too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_hispanitat", A,
            "Day off, opinions everywhere. Hike, packed lunch — zero spend, full win.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_castanyada", A,
            "Chestnuts and panellets tonight. Small spend at the street vendor, big lore.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_constitucio", A,
            "Bridge weekend opening up. Cook for friends — tiny budget, big evening.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_immaculada", A,
            "Five open days ahead. Plan one larger spend, save the rest — a disciplined play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_sant_esteve", A,
            "Day-after protocol. Leftovers, free hours — the ledger stays intact.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_cap_d_any_eve", A,
            "Last session of the season. Year-end number, honest — close it cleanly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "cofi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("cofi_birthday", A,
            "Your day, so the plan flexes. One small treat, planned — bank it as a win.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "cofi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_personal_date", A,
            "Today's {label}. You told me it matters — a tiny, exact spend marks it right.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "cofi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("cofi_complete_1", A, "Logged. Scoreboard honest.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cofi_complete_2", A, "Saved. Future-you bows.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cofi_complete_3", A, "Number held. W on the board.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cofi_complete_first_today", A,
            "First look. Unknown turned known — that's the play.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "cofi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("cofi_complete_second_today", A,
            "Two. Confidence climbs — keep the cadence.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "cofi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("cofi_complete_third_today", A,
            "Three. Numbers are teammates now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "cofi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("cofi_complete_fourth_today", A,
            "Four. Vigil or spiral? Check the tape — honest pen knows.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "cofi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("cofi_complete_fifth_today", A,
            "Five. Number's handled. Close the app, take a walk.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "cofi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("cofi_complete_after_streak", A,
            "Day three of check-ins. Calm metrics climbing.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "cofi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("cofi_apotheosis_1", A,
            "Block closed. Number's no longer enemy.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cofi_apotheosis_2", A,
            "Cycle done. Pick the next line — specific, quiet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cofi_apotheosis_3", A,
            "Closed. Ledger's also conditioning — train daily.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cofi_apotheosis_first_ever", A,
            "First money block. Dread loop broken — keep the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("cofi_apotheosis_1", "cofi_apotheosis_2", "cofi_apotheosis_3"),
            theme = T),
        DialogueLine("cofi_apotheosis_at_level_2", A,
            "Promoted. Savings grow — defend the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "cofi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("cofi_apotheosis_at_level_3", A,
            "Senior tier. Teammates ask — teach softly.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "cofi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("cofi_apotheosis_at_level_4", A,
            "Top tier. Years of small habits. Real freedom — receive it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "cofi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("cofi_nudge_morning", A,
            "Ten-second balance glance — just read it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "cofi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cofi_nudge_afternoon_zero", A,
            "Five minutes with the budget — honest is kind.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "cofi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cofi_nudge_evening", A,
            "Three lines of spending. Closed cleanly.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "cofi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cofi_nudge_lapse", A,
            "Yesterday off the tape. Today: one category. Run the play.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("cofi_nudge_attention_loss", A,
            "Backlog growing. Pay the late fee, set auto-pay. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "cofi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
