package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Coach × Family — tactical-sports stance, household-team plays. */
internal object CoachFamilyLines {

    private const val A = "COACH"
    private const val T = "FAMILY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("cofa_first_ever", A,
            "First day. Pick one — call mom, text sibling, write parent. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("cofa_morning", A,
            "Morning. Quick check-in voice note — sets the tone. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "cofa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofa_morning_early", A,
            "Early call. They're up too — quick hello. Tape's clean.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "cofa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofa_afternoon", A,
            "Halftime. Five-minute call between meetings — that's a play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "cofa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofa_evening", A,
            "Fourth quarter. Real call — phone in hand, eyes off screen.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "cofa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofa_night_late", A,
            "Late. Voice note now — they'll wake to it. Run it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "cofa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("cofa_post_apotheosis", A,
            "W banked. Hold the rhythm — family stays close with reps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("cofa_monday", A,
            "Monday. Quick Sunday-debrief text — what'd you do? Sets the tone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "cofa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("cofa_friday", A,
            "Friday. Plan weekend call — book the time. Mark it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "cofa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("cofa_weekend", A,
            "Weekend. Long Sunday call — old play, kept. Bench earned.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "cofa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("cofa_level_1_reached", A,
            "First tier. Weekly call held for a month — habit's wired.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "cofa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cofa_level_2_reached", A,
            "Second tier. They feel held — that's the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "cofa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cofa_level_3_reached", A,
            "Third tier. Hard conversations land softer. Maintain — hold form.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "cofa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("cofa_level_4_reached", A,
            "Top tier. Years of presence. The team's strong.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "cofa_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("cofa_attention_loss_mild", A,
            "Few skipped days. Quick voice note now — small reset.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "cofa_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("cofa_attention_loss_hard", A,
            "Two weeks of silence. Suit up — call today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "cofa_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("cofa_after_lapse", A,
            "Yesterday: silence 1, you 0. Today: one call. No appeal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Copy, coach", null)), theme = T),
        DialogueLine("cofa_mid_day_return", A,
            "Halftime. Five-minute call — between meetings is fine. Run it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("cofa_wishes_pending", A,
            "Recovery earned — visit, gift, long letter. Bring it home.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "cofa_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("cofa_mid_streak", A,
            "Three days of contact. Family feels seen — hold form.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "cofa_streak", cooldownPicks = 5, theme = T),

        DialogueLine("cofa_sant_jordi", A,
            "Sant Jordi. Drop a book at parents' — small offering. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_la_merce", A,
            "Mercè. Take family along — kids love it. Run the play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_sant_joan", A,
            "Sant Joan. Beach with the whole team — late night, kept. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_diada", A,
            "Diada. Family lunch — old play, kept. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_nadal", A,
            "Nadal. Whole family at the table. Phones down, presence up. Suit up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_cap_d_any", A,
            "New year. Call the older folks first — old play, hold it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("cofa_reis", A,
            "Reis. Family gift day. Show up — be the one who gives the thoughtful one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_carnaval", A,
            "Carnaval. Costumes with the kids — team play. Photos count.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_divendres_sant", A,
            "Quiet day. Long call with parents — slow, full. Counts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_pasqua", A,
            "Pasqua. Family hike, family lunch — both. Bank the W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_festa_del_treball", A,
            "Workers' day. Long family lunch — slow, full. Run it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_festa_major_gracia", A,
            "Gràcia. Bring the kids — neighbourhood-team welcomes them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_assumpcio", A,
            "August. Quiet city. Family trip, family table — bench is wide open.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_hispanitat", A,
            "Day off. Drop in on a relative — small visit, big W.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_castanyada", A,
            "Castanyada. Chestnuts, kids, candles — at home together. Old play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_constitucio", A,
            "Bridge weekend. Visit family town — old play, kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_immaculada", A,
            "Pont. Family-time block — no admin allowed. Phone down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_sant_esteve", A,
            "Day after. Slow family breakfast — quiet talk. Counts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_cap_d_any_eve", A,
            "Last day. Hold the older folks in mind — call. Hold the play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "cofa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("cofa_birthday", A,
            "Birthday. Call the people who knew you small — old play, kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "cofa_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_personal_date", A,
            "Marked date: {label}. Hold family in mind today — one call marks it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "cofa_personal", cooldownPicks = 1, theme = T),

        DialogueLine("cofa_complete_1", A, "Called. Tape's clean.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cofa_complete_2", A, "Reached out. W banked.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cofa_complete_3", A, "Voice note sent. Good rep.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("cofa_complete_first_today", A,
            "First call. They'll hold it all day — momentum's on.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "cofa_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("cofa_complete_second_today", A,
            "Two reach-outs. Family feels seen — stay with it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "cofa_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("cofa_complete_third_today", A,
            "Three. Solid day for the team — hold form.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "cofa_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("cofa_complete_fourth_today", A,
            "Four. Big family day, or covering for something? Check the tape.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "cofa_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("cofa_complete_fifth_today", A,
            "Five. Put the phone down — be where you are. Game on.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "cofa_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("cofa_complete_after_streak", A,
            "Day three of contact. Family feels close — hand is fluent.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "cofa_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("cofa_apotheosis_1", A,
            "Block closed. Team's tighter — next block warmer.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cofa_apotheosis_2", A,
            "Cycle done. Pick next small play — visit, call, photo.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cofa_apotheosis_3", A,
            "Closed. Family floor is wider now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("cofa_apotheosis_first_ever", A,
            "First family-block. Showing up is canon — relationship's a system.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("cofa_apotheosis_1", "cofa_apotheosis_2", "cofa_apotheosis_3"),
            theme = T),
        DialogueLine("cofa_apotheosis_at_level_2", A,
            "Promoted. They feel held — keep the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "cofa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("cofa_apotheosis_at_level_3", A,
            "Senior tier. Hard talks land softer — hold form.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "cofa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("cofa_apotheosis_at_level_4", A,
            "Top tier. Years of presence. Team's strong — steady.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "cofa_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("cofa_nudge_morning", A,
            "Voice note. Quick. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "cofa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cofa_nudge_afternoon_zero", A,
            "Five-minute call. Between meetings. Bench is empty.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "cofa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cofa_nudge_evening", A,
            "Real call. Phone in hand, eyes off screen.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "cofa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("cofa_nudge_lapse", A,
            "Yesterday: silence won. Today: one call. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("cofa_nudge_attention_loss", A,
            "Family benched. Call today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "cofa_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
