package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Coach × Career — tactical-sports stance, the franchise. */
internal object CoachCareerLines {

    private const val A = "COACH"
    private const val T = "CAREER"

    val all: List<DialogueLine> = listOf(

        DialogueLine("coca_first_ever", A,
            "First day in the franchise. Set three priorities — specific. Game on.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("coca_morning", A,
            "Morning. One deep block before lunch — that's the play. Phone away.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "coca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coca_morning_early", A,
            "Early call. First on the field — own the silence before the meetings.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "coca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coca_afternoon", A,
            "Halftime. One meaningful task — the hard one. Shortens by being faced.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "coca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coca_evening", A,
            "Fourth quarter. Tomorrow's three priorities — written. Close the laptop.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "coca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coca_night_late", A,
            "Late. Not tonight — brain wants the whole game tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "coca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("coca_post_apotheosis", A,
            "W banked. Keep the deep-work cadence — don't drift into reply-as-work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("coca_monday", A,
            "Monday. Three priorities — specific. Vague ones drift.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "coca_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("coca_friday", A,
            "Friday. Week-tape review — one honest line. What landed?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "coca_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("coca_weekend", A,
            "Weekend. Skill-nibble or rest — both train the franchise. Pick.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "coca_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("coca_level_1_reached", A,
            "First tier. Week of deep-work. People notice the steady tape.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "coca_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("coca_level_2_reached", A,
            "Second tier. Recognition incoming. Receive it — don't apologise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "coca_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("coca_level_3_reached", A,
            "Third tier. You're the go-to. Iconic role — defend the deep block.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "coca_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("coca_level_4_reached", A,
            "Top tier. Years of focused work. Skill's the trophy — maintain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "coca_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("coca_attention_loss_mild", A,
            "Three scattered days. Inbox-as-work is a bench play. One deep block today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "coca_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("coca_attention_loss_hard", A,
            "Two weeks of meetings-as-work. Suit up — one real task today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "coca_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("coca_after_lapse", A,
            "Yesterday: meetings-as-work. Today: one meaningful task. No appeal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Copy, coach", null)), theme = T),
        DialogueLine("coca_mid_day_return", A,
            "Halftime. Phone in drawer. One hour deep — run the play.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("coca_wishes_pending", A,
            "Recovery earned — real reward, not 'one more meeting'. Spend it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "coca_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("coca_mid_streak", A,
            "Three days of focus. Skill compounds — hold form.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "coca_streak", cooldownPicks = 5, theme = T),

        DialogueLine("coca_sant_jordi", A,
            "Sant Jordi. Half-day. Get one thing done by noon — then streets.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_la_merce", A,
            "Mercè. Day off. Inbox is benched today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_sant_joan", A,
            "Sant Joan. Closed. Rest is investment — the fire teaches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_diada", A,
            "Diada. Career rests. The line keeps without you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_nadal", A,
            "Nadal. No work tonight. Family's the game.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_cap_d_any", A,
            "New year. Three career goals — specific. Set the playbook.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("coca_reis", A,
            "Reis. Closed. Plot's kids-only today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_carnaval", A,
            "Carnaval. Long weekend. Mute Slack — it's still on. Mute it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_divendres_sant", A,
            "Quiet day. Map next quarter slowly — pen does the strategy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_pasqua", A,
            "Pasqua. Closed. Body and brain rest as one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_festa_del_treball", A,
            "Workers' day. Not working is also work — honour it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_festa_major_gracia", A,
            "Gràcia week. Busy nights. Small work mornings — fair bargain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_assumpcio", A,
            "August. Slow career month. Strategic-thinking weather — use it slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_hispanitat", A,
            "Day off. Work rests. The line keeps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_castanyada", A,
            "Castanyada. Q4 hum. Three priorities — specific. Set them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_constitucio", A,
            "Bridge weekend. One strategy hour — then rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_immaculada", A,
            "Pont. Year-end roadmap in small chunks. Body sleeps between.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_sant_esteve", A,
            "Day after. No work. Family chaos outranks the inbox.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_cap_d_any_eve", A,
            "Last day. Year-of-wins list — specific. Don't be modest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "coca_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("coca_birthday", A,
            "Birthday. Career goals tomorrow. Today: be the protagonist of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "coca_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("coca_personal_date", A,
            "Marked date: {label}. Work rests. The page receives the pause.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "coca_personal", cooldownPicks = 1, theme = T),

        DialogueLine("coca_complete_1", A, "Shipped. W on the board.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("coca_complete_2", A, "Done. Skill more itself.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("coca_complete_3", A, "Deep-work landed. Banked.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("coca_complete_first_today", A,
            "First block done. Exposition's over.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "coca_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("coca_complete_second_today", A,
            "Two. Line lengthens — skill compounds.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "coca_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("coca_complete_third_today", A,
            "Three. Work mood lifts — game's clean.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "coca_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("coca_complete_fourth_today", A,
            "Four. Closing-day flow, or anxiety in disguise? Check the tape.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "coca_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("coca_complete_fifth_today", A,
            "Five. Close the laptop. Game's enough today.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "coca_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("coca_complete_after_streak", A,
            "Day three of deep-work. Skill compounds — hold form.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "coca_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("coca_apotheosis_1", A,
            "Block closed. Don't drift into reply-as-work.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("coca_apotheosis_2", A,
            "Cycle done. Pick the next true line — specific, quiet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("coca_apotheosis_3", A,
            "Closed. Skill stacks itself when you're not looking.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("coca_apotheosis_first_ever", A,
            "First career block. Deep work is canon — hold it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("coca_apotheosis_1", "coca_apotheosis_2", "coca_apotheosis_3"),
            theme = T),
        DialogueLine("coca_apotheosis_at_level_2", A,
            "Promoted. Skill grows — keep the deep block sacred.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "coca_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("coca_apotheosis_at_level_3", A,
            "Senior tier. Others copy your habits — be the steady one.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "coca_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("coca_apotheosis_at_level_4", A,
            "Top tier. Years of focused work. Skill's the trophy — maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "coca_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("coca_nudge_morning", A,
            "Deep-work block. Phone away. Run the play.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "coca_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("coca_nudge_afternoon_zero", A,
            "Phone in drawer. One focused hour. Now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "coca_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("coca_nudge_evening", A,
            "Write tomorrow's three. Close the laptop.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "coca_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("coca_nudge_lapse", A,
            "Yesterday: meetings-as-work. Today: one real task. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("coca_nudge_attention_loss", A,
            "Plot stalled. One real task — today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "coca_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
