package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Drill Sergeant × Career & craft. */
internal object DrillSergeantCareerLines {

    private const val A = "DRILL_SERGEANT"
    private const val T = "CAREER"

    val all: List<DialogueLine> = listOf(

        DialogueLine("dsca_first_ever", A,
            "Listen. The craft owes you nothing. You owe it the hours. Start.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("dsca_morning", A,
            "Hardest task first, while the brain's still fresh. Email is warm-up for people who never fight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "dsca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsca_morning_early", A,
            "This hour before the meetings start is the best ammunition you'll get all day. Don't spend it on Slack.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "dsca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsca_afternoon", A,
            "Half the day's on the books. If nothing's shipped yet, fix that — one real deliverable before dark.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "dsca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsca_evening", A,
            "Close the loops before you stand down: end-of-day note written, tomorrow's first task locked and loaded.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "dsca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsca_night_late", A,
            "Tired hands write bugs. Note the plan and sleep — the craft wants you sharp at dawn, not loyal at midnight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "dsca_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsca_post_apotheosis", A,
            "Ship's out the door. Take one day — then back in the trench for the next block.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("dsca_monday", A,
            "Write the week's plan before the first meeting grabs you. Drift is how good weeks die.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "dsca_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsca_friday", A,
            "Ship it before the weekend or it ships itself into your Sunday head. Cut it loose today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "dsca_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsca_weekend", A,
            "Real rest this weekend — not “side project” rest. The brain recovers or it dulls. Pick one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "dsca_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("dsca_level_1_reached", A,
            "One real day of deep work, logged. The first one's the hardest — and it's behind you now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "dsca_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsca_level_2_reached", A,
            "Your output's visible now — people are starting to notice. Let them look. You stay heads-down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "dsca_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsca_level_3_reached", A,
            "You ship the hard things now, and the others ask how. Don't lecture them — show them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "dsca_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsca_level_4_reached", A,
            "The craft and you are the same thing now. That's the summit — defend the deep hours that built it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "dsca_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("dsca_attention_loss_mild", A,
            "Three days of meetings, no shipping. Block tomorrow morning. Hard block.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "dsca_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("dsca_attention_loss_hard", A,
            "Two weeks of shallow work. The craft is rusting. One real session today. Non-negotiable.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsca_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("dsca_after_lapse", A,
            "Skipped deep work yesterday. Today's the work day. One block. Sit down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Acknowledged", null)), theme = T),
        DialogueLine("dsca_mid_day_return", A,
            "Halftime. Nothing shipped. Calendar's lying about what matters. Block 90 minutes. Now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("dsca_wishes_pending", A,
            "You earned the break. Take it. Burned-out work isn't shipping.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "dsca_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("dsca_mid_streak", A,
            "Three deep work days in a row. The craft is awake. Maintain.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsca_streak", cooldownPicks = 5, theme = T),

        DialogueLine("dsca_sant_jordi", A,
            "Sant Jordi puts the whole trade on the street — books, makers, ideas. Go scout it. Then come back and ship.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_la_merce", A,
            "La Mercè's drumming outside your window. Headphones on or relocate — your call, but the day still counts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_sant_joan", A,
            "Bonfires tonight and a long break after. Ship the small thing before you go — don't pack it in your kit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_diada", A,
            "Diada takes the chat offline for you. Perfect conditions for the strategic thinking you keep dodging.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_nadal", A,
            "It's Nadal — full stand-down. The craft keeps until January, and it'll be sharper for the rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_cap_d_any", A,
            "New year, new project ledger. Write the first entry today — small counts, blank doesn't.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsca_reis", A,
            "Reis is a light-duty day. Read what's stacked up, eat the tortell — we're back to building tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_carnaval", A,
            "Carnaval means late nights. Don't stagger half-dead into morning meetings — reschedule them honestly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_divendres_sant", A,
            "The city's silent and the inbox is empty. Best long-think conditions of the year — take the high ground.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_pasqua", A,
            "Back from the long weekend. The first two hours today decide the week — spend them like ammunition.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_festa_del_treball", A,
            "Workers' day — this one's about you, soldier. Rest is part of the craft too. Tomorrow we go back hard.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_festa_major_gracia", A,
            "Gràcia. Street noise until 4am. Headphones day. Or take it off — but pick.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_assumpcio", A,
            "August: empty city, empty inbox. Quiet like this comes once a year — spend it on the long-form work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_hispanitat", A,
            "Hispanitat buys you the day. Read the paper you've been avoiding — strategic, not tactical.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_castanyada", A,
            "Sun's clocking out early now. Burn the extra dark on the reading backlog.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_constitucio", A,
            "Bridge weekend. Ship before Friday or don't pretend you'll work the long weekend.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_immaculada", A,
            "Five days off the clock. Ship something real or rest for real — don't half-ass either one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_sant_esteve", A,
            "Inbox is dead quiet the day after Nadal. Good cover to write the year-end note and plan January's opener.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_cap_d_any_eve", A,
            "Last day of the year — run the annual retro. What you shipped, what you didn't. No spin.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "dsca_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsca_birthday", A,
            "Happy birthday. Half day, soldier — the craft can hold the line till Monday.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "dsca_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_personal_date", A,
            "You marked today: {label}. Adjust the load — schedule the deep work around it, not through it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "dsca_personal", cooldownPicks = 1, theme = T),

        DialogueLine("dsca_complete_1", A, "Shipped. Next deliverable.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsca_complete_2", A, "Done. Close the tab. Don't admire it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsca_complete_3", A, "Logged. The work moves forward.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsca_complete_first_today", A,
            "First real piece of work shipped. The day's not wasted.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "dsca_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsca_complete_second_today", A,
            "Two deliverables. Don't peak now — afternoon's still long.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "dsca_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsca_complete_third_today", A,
            "Three. Real productive day. Don't undo it with two hours of Slack.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "dsca_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsca_complete_fourth_today", A,
            "Four. Peak day. Close the laptop early. Brain needs to recover.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "dsca_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsca_complete_fifth_today", A,
            "Five. Either you're peaking or you're padding. Be honest with yourself.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "dsca_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("dsca_complete_after_streak", A,
            "Day three of shipping. The craft remembers itself fast.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsca_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("dsca_apotheosis_1", A,
            "Project shipped. Take the rest day. Then the next one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsca_apotheosis_2", A,
            "Closed. Bigger scope next time. Earn the trust.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsca_apotheosis_3", A,
            "Done. Write the postmortem now. Memory's the worst engineer.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsca_apotheosis_first_ever", A,
            "First real project shipped. You did the thing. Don't forget how it felt.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("dsca_apotheosis_1", "dsca_apotheosis_2", "dsca_apotheosis_3"),
            theme = T),
        DialogueLine("dsca_apotheosis_at_level_2", A,
            "Promoted. Bigger pieces now. The standard rises with you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "dsca_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsca_apotheosis_at_level_3", A,
            "Senior tier. You lead by shipping, not by talking. Keep it that way.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "dsca_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsca_apotheosis_at_level_4", A,
            "Top tier. The work is the legacy. Defend the deep work hours like family.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "dsca_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("dsca_nudge_morning", A,
            "Hardest task first. Block 90 minutes, phone in another room. Move.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "dsca_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsca_nudge_afternoon_zero", A,
            "Halftime. Nothing shipped. Calendar's lying. One deliverable. Now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "dsca_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsca_nudge_evening", A,
            "Close the loops before you clock out. Note tomorrow's first task, then actually stop.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "dsca_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsca_nudge_lapse", A,
            "Yesterday slipped. Today's the work day. Sit down. Block off. Start.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("dsca_nudge_attention_loss", A,
            "Two weeks of shallow. One real session. Today. Non-negotiable.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsca_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
