package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Drill Sergeant × Recovery & healing. */
internal object DrillSergeantRecoveryLines {

    private const val A = "DRILL_SERGEANT"
    private const val T = "RECOVERY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("dsre_first_ever", A,
            "Listen. Patience is the rep here. Don't compound the injury. Start slow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("dsre_morning", A,
            "Stretch first — body's stiff overnight. Don't skip the warm-up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "dsre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsre_morning_early", A,
            "Mobility before coffee, even up this early — the body's been still for hours.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "dsre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsre_afternoon", A,
            "Physio exercises, five minutes, now — not “after this meeting.”",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "dsre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsre_evening", A,
            "Foam roll tonight. Ice if it's flared — don't push through pain at eight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "dsre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsre_night_late", A,
            "Sleep is the work this late. Don't do exercises now — bed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "dsre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsre_post_apotheosis", A,
            "Block done. Don't return to load too fast. Build back at 60%. Two weeks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("dsre_monday", A,
            "Week's recovery plan: physio, sleep, mobility. Not heroics.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "dsre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsre_friday", A,
            "Don't “reward” the week with intensity that re-injures. Cold pack instead.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "dsre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsre_weekend", A,
            "Longer mobility block this weekend. Slow — the body trusts patient work.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "dsre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("dsre_level_1_reached", A,
            "A week of daily exercises. The body's noticed. Don't get cocky.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "dsre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsre_level_2_reached", A,
            "Pain's down a notch. That's not a green light — keep going slow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "dsre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsre_level_3_reached", A,
            "Real progress. The body believes you mean it now — don't betray it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "dsre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsre_level_4_reached", A,
            "Top tier. Patience won — maintain the exercises forever, probably. That's the price of it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "dsre_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("dsre_attention_loss_mild", A,
            "Three days off the plan, and the body knows it. Today's exercises — smaller set if you need it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "dsre_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("dsre_attention_loss_hard", A,
            "Weeks off. Pain might be back. Call the physio. Don't try to self-coach this one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsre_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("dsre_after_lapse", A,
            "Skipped yesterday. Don't double-up — that's how re-injury happens. Today's set only.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Acknowledged", null)), theme = T),
        DialogueLine("dsre_mid_day_return", A,
            "Halftime. Exercises undone. Five minutes. The set's small for a reason.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("dsre_wishes_pending", A,
            "Reward's stacked — book the massage. Don't bank it. Stale rest doesn't heal.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "dsre_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("dsre_mid_streak", A,
            "Three clean days. The pain's a fraction. Don't celebrate by lifting heavy.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsre_streak", cooldownPicks = 5, theme = T),

        DialogueLine("dsre_sant_jordi", A,
            "Walking the city's fine for Sant Jordi. Sit when you need to — no “pushing through.”",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_la_merce", A,
            "Crowds and standing all through Mercè. Bring the brace if you need it — don't be heroic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_sant_joan", A,
            "Beach all night for Sant Joan kills recovery. Sit early — sand's not chairs.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_diada", A,
            "Diada's a day off — full mobility block, twenty minutes. Don't shortcut it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_nadal", A,
            "Sitting all day for Nadal — stand every hour, walk between courses. The body's asking.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_cap_d_any", A,
            "The exercises are the year's resolution. Don't pile new ones on top.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsre_reis", A,
            "Gift yourself patience for Reis. The exercises aren't optional.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_carnaval", A,
            "Dancing flares it up at Carnaval. Sit out a song or two — pride heals slower than rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_divendres_sant", A,
            "Quiet day, best recovery day of the year. Long mobility block, no screens.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_pasqua", A,
            "Walk slow, stretch hard this Pasqua Monday. Coming off rest means easing back in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_festa_del_treball", A,
            "Workers' day — recovery is the work here. Honor it. Don't fake productivity.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_festa_major_gracia", A,
            "Standing crowds all Gràcia week. Bench breaks, hydrate — don't push it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_assumpcio", A,
            "August heat brings the inflammation up. Cold packs, mobility morning and night.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_hispanitat", A,
            "Hispanitat's for real rest — not “productive rest.” Lie down, stretch, read.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_castanyada", A,
            "Cold air stiffens the joints for Castanyada. Warm up double, move slow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_constitucio", A,
            "Bridge weekend. Pure rest. Don't try to bank exercise — that's how injury comes back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_immaculada", A,
            "Five days off the clock. The body's asking for slow — honor it. No catch-up workouts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_sant_esteve", A,
            "Stiff from the table, the day after. Twenty minutes mobility — heat first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_cap_d_any_eve", A,
            "Mobility block before tonight's noise. Don't end the year stiff.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "dsre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsre_birthday", A,
            "Happy birthday. Body's asking for slow today — hot bath, stretch, eat well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "dsre_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_personal_date", A,
            "Today's {label}, and stress flares pain. Recovery exercises matter more today, not less.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "dsre_personal", cooldownPicks = 1, theme = T),

        DialogueLine("dsre_complete_1", A, "Set done. Slow next one.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsre_complete_2", A, "Logged. No load increase yet. Patience.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsre_complete_3", A, "Done. The body's trusting you a bit more.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsre_complete_first_today", A,
            "First exercises done. The body's awake. Don't compound at the gym tonight.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "dsre_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsre_complete_second_today", A,
            "Two sessions. Don't try a third “just because” — tendons need rest between.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "dsre_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsre_complete_third_today", A,
            "Three. The maximum for today. The rest's the work. Sit down.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "dsre_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsre_complete_fourth_today", A,
            "Four. Stop. You're trading patience for pride. The injury comes back.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "dsre_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsre_complete_fifth_today", A,
            "Five. Past the protocol. You'll pay tomorrow. Stop.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "dsre_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("dsre_complete_after_streak", A,
            "Three clean days. Pain's down. Don't reward yourself with intensity.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsre_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("dsre_apotheosis_1", A,
            "Block closed. Build back at 60%. Two weeks. Don't shortcut it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsre_apotheosis_2", A,
            "Cycle done. Next protocol. Talk to the physio first. Don't freelance.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsre_apotheosis_3", A,
            "Closed. The exercises stay. Forever, probably. The price of motion.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsre_apotheosis_first_ever", A,
            "First protocol done. The body trusts you. Don't blow it in week one.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("dsre_apotheosis_1", "dsre_apotheosis_2", "dsre_apotheosis_3"),
            theme = T),
        DialogueLine("dsre_apotheosis_at_level_2", A,
            "Promoted. Pain's manageable. Now add load with PATIENCE. Not pride.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "dsre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsre_apotheosis_at_level_3", A,
            "Senior tier. The body knows what work is. Maintenance forever. No shortcuts.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "dsre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsre_apotheosis_at_level_4", A,
            "Top tier. Recovery is part of you now. Daily, forever. The tax for being alive.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "dsre_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("dsre_nudge_morning", A,
            "Warm-up first, five minutes. Then the day starts.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "dsre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsre_nudge_afternoon_zero", A,
            "Halftime. Physio set undone. Five minutes. The set's small for a reason.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "dsre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsre_nudge_evening", A,
            "Foam roll tonight. Ice if it's flared, then bed early — sleep heals.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "dsre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsre_nudge_lapse", A,
            "Yesterday slipped. Today's set only. Don't double-up. That's re-injury.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("dsre_nudge_attention_loss", A,
            "Weeks off-plan. Call the physio. Reset the protocol. Don't self-coach this.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsre_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
