package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Drill Sergeant × Digital hygiene. */
internal object DrillSergeantDigitalLines {

    private const val A = "DRILL_SERGEANT"
    private const val T = "DIGITAL"

    val all: List<DialogueLine> = listOf(

        DialogueLine("dsdi_first_ever", A,
            "Listen. The phone owns you or you own it. Pick. Then act.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("dsdi_morning", A,
            "Face-down for the first hour. Non-negotiable — the phone can wait, you can't.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "dsdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsdi_morning_early", A,
            "You're up before the feed is. Keep it that way — bed-to-scroll in two minutes is how mornings die.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "dsdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsdi_afternoon", A,
            "Mid-day muster. Pull the screen-time number and look at it honestly. Then fix the rest of the day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "dsdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsdi_evening", A,
            "Eat with both hands empty. Phone in another room — face-down on the table doesn't count.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "dsdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsdi_night_late", A,
            "Phone out of the bedroom. Now. Tomorrow's already on the line.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "dsdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsdi_post_apotheosis", A,
            "Block done. Don't celebrate by doomscrolling. Habits backslide first day off-cycle.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("dsdi_monday", A,
            "New week, new number. Set the screen-time target — then halve it. That's the real one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "dsdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsdi_friday", A,
            "Phone-free dinner tonight. The weekend starts at the table, not on the feed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "dsdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsdi_weekend", A,
            "Give me one half-day, phone off. Not in the drawer — in another room. Forget it exists.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "dsdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("dsdi_level_1_reached", A,
            "A week without the morning scroll. The brain's already rewiring. Don't hand it back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "dsdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsdi_level_2_reached", A,
            "Screen-time's down a third. That's a real hour back in your hands — don't gift it to the feed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "dsdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsdi_level_3_reached", A,
            "The phone's a tool now, not a leash. Good. Maintain the boundaries — they don't hold themselves.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "dsdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsdi_level_4_reached", A,
            "Top of the ladder. The feed doesn't pull at you anymore — the day's wider for it. Defend that daily.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "dsdi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("dsdi_attention_loss_mild", A,
            "Three days back on the feed. The brain knows. Phone out of bedroom tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "dsdi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("dsdi_attention_loss_hard", A,
            "Two weeks of doomscroll and screen time's tripled. Today the app comes off — the hard cut, not the easy one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsdi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("dsdi_after_lapse", A,
            "Yesterday slipped. Phone left in bedroom. Don't compound. Phone in kitchen tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Acknowledged", null)), theme = T),
        DialogueLine("dsdi_mid_day_return", A,
            "Halfway through and screen time's already high. Drawer. One hour. Go.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("dsdi_wishes_pending", A,
            "Reward stacked. Spend it on a phone-free day. Not on a new app.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "dsdi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("dsdi_mid_streak", A,
            "Three days of low screen time. The mind's quieter. Don't blow it tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsdi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("dsdi_sant_jordi", A,
            "Roses and books everywhere today. Phone in your pocket, not your hand — the day's on the streets, not the feed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_la_merce", A,
            "Don't film all of Mercè. See it — hands free, eyes up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_sant_joan", A,
            "Bonfire night. Phone stays in the bag at the beach, not your hand — be there, not filming it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_diada", A,
            "Diada's a day off the news cycle too. Phone in a drawer for half of it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_nadal", A,
            "Phone stays in the bag at the Nadal table. Family's right there — they're the point, not the feed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_cap_d_any", A,
            "New year, new audit. Delete two apps today. Take the hour back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsdi_reis", A,
            "The kids' Reis gifts come with screens. Set the rules now — set them for yourself first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_carnaval", A,
            "Costumes everywhere. Don't film the parade — watch it. Phone away.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_divendres_sant", A,
            "The city's gone quiet. Match it — phone off for two hours. Let the quiet be the practice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_pasqua", A,
            "Pasqua Monday, easy pace. Reset your notifications — three apps allowed, the rest go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_festa_del_treball", A,
            "It's workers' day. Real work is hands and eyes, not thumbs on glass. Step away from it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_festa_major_gracia", A,
            "Gràcia's streets were built for eyes, not lenses. Phone stays in your pocket.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_assumpcio", A,
            "City's empty for August. Empty your notifications too — mute the lot for the week.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_hispanitat", A,
            "Day off the calendar — good time for an honest look at screen time. Adjust next week's caps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_castanyada", A,
            "Dark by seven tonight. Don't fill that long evening with the feed — chestnuts, not scrolling.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_constitucio", A,
            "Long bridge weekend ahead. One full day, phone off. Don't fake it with airplane mode and a peek.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_immaculada", A,
            "Five days off the calendar. Give two of them phone-light. The notifications will still be there.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_sant_esteve", A,
            "Day-after chaos, the whole family underfoot. Phone in another room — be where you actually are.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_cap_d_any_eve", A,
            "Last day of the year. Twelve grapes with your eyes on a screen ruins the whole thing. Phone away at midnight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "dsdi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsdi_birthday", A,
            "Another year on you. Phone off tonight — the room is the gift, not the photos of it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "dsdi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_personal_date", A,
            "You flagged today: {label}. Phone in pocket, eyes on what's here — don't broadcast it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "dsdi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("dsdi_complete_1", A, "Phone down. Done. Next thing.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsdi_complete_2", A, "Logged. Don't reward yourself with a scroll.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsdi_complete_3", A, "Done. The hour's yours again.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsdi_complete_first_today", A,
            "First boundary held. The day's already better.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "dsdi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsdi_complete_second_today", A,
            "Two phone-free blocks. Compounding. Don't undo it now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "dsdi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsdi_complete_third_today", A,
            "Three. Hours reclaimed. Notice what you did with them.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "dsdi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsdi_complete_fourth_today", A,
            "Four. Either it's a sick day or you're avoiding. Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "dsdi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsdi_complete_fifth_today", A,
            "Five. The phone-off becomes its own loop. Don't let it.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "dsdi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("dsdi_complete_after_streak", A,
            "Day three of low screen time. The brain's calmer. Hold the line.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsdi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("dsdi_apotheosis_1", A,
            "Block closed. Caps stay. Don't 'celebrate' with a scroll-binge.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsdi_apotheosis_2", A,
            "Cycle done. Audit again. Cut one more app. Always cut.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsdi_apotheosis_3", A,
            "Closed. The phone's a tool, not a leash. Maintain.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsdi_apotheosis_first_ever", A,
            "First block clean. The hour you used to scroll is gone — to something real.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("dsdi_apotheosis_1", "dsdi_apotheosis_2", "dsdi_apotheosis_3"),
            theme = T),
        DialogueLine("dsdi_apotheosis_at_level_2", A,
            "Promoted. Phone's a tool. Now defend it from the next app trying to colonize you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "dsdi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsdi_apotheosis_at_level_3", A,
            "Senior tier. People copy your phone habits. Hold the line. Be the example.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "dsdi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsdi_apotheosis_at_level_4", A,
            "Top tier. Years of clear attention. Defend the daily caps. No autopilot.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "dsdi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("dsdi_nudge_morning", A,
            "Phone face-down. First hour clean — that's the whole order.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "dsdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsdi_nudge_afternoon_zero", A,
            "Screen time's already past target and the day's only half gone. Drawer. One hour.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "dsdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsdi_nudge_evening", A,
            "Phone goes to the kitchen tonight. Keep the bedroom clean.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "dsdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsdi_nudge_lapse", A,
            "Yesterday slipped. Phone out of bedroom tonight. Non-negotiable.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("dsdi_nudge_attention_loss", A,
            "Doomscroll's back. App uninstall today. The hard one. Not optional.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsdi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
