package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/**
 * Drill Sergeant × Body & exercise. 60 themed lines mirroring the
 * base DrillSergeant corpus with reps/sets/training vocabulary.
 *
 * All lines carry `theme = T` so they only fire for daemons whose
 * `Daemon.theme == "EXERCISE"`. The base archetype lines stay in the
 * pool too; the engine's themed-first tiebreaker prefers these.
 */
internal object DrillSergeantExerciseLines {

    private const val A = "DRILL_SERGEANT"
    private const val T = "EXERCISE"

    val all: List<DialogueLine> = listOf(

        // -------- OPENER · time of day --------

        DialogueLine("dsex_first_ever", A,
            "Listen up. Body's the only one you get. Training starts now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("dsex_morning", A,
            "Warm up. Move. That's the whole conversation this early.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "dsex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsex_morning_early", A,
            "Pre-dawn rep. Quiet city. Hardest minute is the first one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "dsex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsex_afternoon", A,
            "Midday roll call. Trained already? Breathe. Haven't yet? Get up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "dsex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsex_evening", A,
            "Form over speed tonight. Don't injure yourself trying to catch up on the day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "dsex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsex_night_late", A,
            "No PRs at midnight, soldier. Mobility or sleep — pick one, then commit.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "dsex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsex_post_apotheosis", A,
            "Block closed. Deload one day, then we build the next one harder.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        // -------- OPENER · day of week --------

        DialogueLine("dsex_monday", A,
            "Set the week's intensity on the first rep. That's what Monday's for.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "dsex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsex_friday", A,
            "Heavy day or recovery day — be honest with yourself about which one you needed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "dsex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsex_weekend", A,
            "No alarm today. Long, slow, outside — the kind of work no one sees or claps for.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "dsex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        // -------- OPENER · per-level transitions --------

        DialogueLine("dsex_level_1_reached", A,
            "Newbie strength — every rep's still teaching you something. Pay attention.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "dsex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsex_level_2_reached", A,
            "The plateau starts around here. Bigger lifts cost more sleep than you'd like.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "dsex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsex_level_3_reached", A,
            "Form's locked in now. The body's asking you to be smart about recovery instead.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "dsex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsex_level_4_reached", A,
            "Top rank. The only opponent left is yesterday's lift. Hold the line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "dsex_level_xform", cooldownPicks = 999, theme = T),

        // -------- OPENER · attention loss --------

        DialogueLine("dsex_attention_loss_mild", A,
            "Strength leaks fast. Take it back with one easy set. Then add weight tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "dsex_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("dsex_attention_loss_hard", A,
            "You detrained. We start at 60% and build. Two weeks gets you back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsex_atten_loss", cooldownPicks = 2, theme = T),

        // -------- OPENER · lapse / mid-day / wishes / streak --------

        DialogueLine("dsex_after_lapse", A,
            "Missed yesterday's session. Don't double up. Today's the run.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Acknowledged", null)), theme = T),
        DialogueLine("dsex_mid_day_return", A,
            "Half the day gone. Body's already cold. Warm up properly or skip honestly.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("dsex_wishes_pending", A,
            "You earned recovery. Take it. Stale rest days don't compound.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "dsex_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("dsex_mid_streak", A,
            "Streak's holding. Don't admire it. Just keep showing up to training.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsex_streak", cooldownPicks = 5, theme = T),

        // -------- OPENER · holidays (loaded six) --------

        DialogueLine("dsex_sant_jordi", A,
            "Sant Jordi. Walk the city, buy the book, then earn the evening with a set.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_la_merce", A,
            "Mercè. City's loud, sleep'll be short. Light technique session, then go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_sant_joan", A,
            "Sant Joan. You'll be up til 4 on the beach. Train early. Sleep next day, don't drink through it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_diada", A,
            "Diada's an off day. Walk an hour at least — recovery is training too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_nadal", A,
            "Nadal. You'll eat heavy. Move twice today — once before, once after. Doesn't have to be hard.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_cap_d_any", A,
            "First training day of the year. Set the standard. Doesn't have to be a PR — just clean.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),

        // -------- OPENER · cultural calendar (lesser 13) --------

        DialogueLine("dsex_reis", A,
            "Gift day for the kids. Eat the candy, then move your legs — the body's been still all morning.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_carnaval", A,
            "Costume night. Don't injure yourself dancing — mobility before bed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_divendres_sant", A,
            "The city's quiet today. Long walk, easy stretch — the body remembers easy work too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_pasqua", A,
            "Pasqua Monday. Active recovery — no max effort. Mona later, run first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_festa_del_treball", A,
            "It's workers' day. The body works too — honor it with a clean session.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_festa_major_gracia", A,
            "Gràcia week. Wandering counts as zone-2 cardio. Take the long way home.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_assumpcio", A,
            "August heat. Train at 7am or 9pm. Hydrate twice as much as you think.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_hispanitat", A,
            "Day off the calendar. Empty gym, full park — pick one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_castanyada", A,
            "Chestnut smoke and early dark tonight. Move before dinner or you won't move at all.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_constitucio", A,
            "Bridge weekend opens. Build a four-day microcycle. Or rest hard — your call.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_immaculada", A,
            "Five days off the calendar starting now. Pick three session days — don't let it become five rest days.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_sant_esteve", A,
            "Day after Nadal. Body's stiff from the table. Twenty minutes, easy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_cap_d_any_eve", A,
            "Last day of the year. Light session before the grapes — don't carry soreness into the new one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "dsex_holiday", cooldownPicks = 1, theme = T),

        // -------- OPENER · birthday + personal date --------

        DialogueLine("dsex_birthday", A,
            "Another year on you. Light session — cake's coming. Real training resumes tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "dsex_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_personal_date", A,
            "You flagged today: {label}. Load adjusted. Take what the day needs.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "dsex_personal", cooldownPicks = 1, theme = T),

        // -------- COMPLETION · escalating count --------

        DialogueLine("dsex_complete_1", A,
            "Set logged. Reset. Next.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsex_complete_2", A,
            "Clean rep. Don't get sloppy on the next one.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsex_complete_3", A,
            "Done. Now make it look easier.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsex_complete_first_today", A,
            "First session of the day. Hardest part's behind. Move.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "dsex_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsex_complete_second_today", A,
            "Two sessions in. Body's warm. Stop chasing the third.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "dsex_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsex_complete_third_today", A,
            "Three. That's a real training day. Eat properly tonight.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "dsex_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsex_complete_fourth_today", A,
            "Four. Past anyone's recovery window. Sleep early or you'll pay tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "dsex_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsex_complete_fifth_today", A,
            "Five in a day. Either you're peaking or you're stupid. Be honest about which.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "dsex_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("dsex_complete_after_streak", A,
            "Day three of training. Your tendons are catching up to your ambition.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsex_streak_complete", cooldownPicks = 4, theme = T),

        // -------- APOTHEOSIS · per-level --------

        DialogueLine("dsex_apotheosis_1", A,
            "Block closed. Eat. Sleep. We deload tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsex_apotheosis_2", A,
            "Phase done. Bigger lifts coming. Don't get cute.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsex_apotheosis_3", A,
            "Closed. Plan the next mesocycle while it's fresh.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsex_apotheosis_first_ever", A,
            "First training block in the books. Don't forget how this felt.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("dsex_apotheosis_1", "dsex_apotheosis_2", "dsex_apotheosis_3"),
            theme = T),
        DialogueLine("dsex_apotheosis_at_level_2", A,
            "Promoted. Time to add load — but only to lifts your form has earned.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "dsex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsex_apotheosis_at_level_3", A,
            "Senior lifter. Other people watch how you warm up now. Make it count.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "dsex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsex_apotheosis_at_level_4", A,
            "Top tier. Volume gives, recovery takes. Pick your battles.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "dsex_apotheosis_levelband", cooldownPicks = 3, theme = T),

        // -------- NUDGE --------

        DialogueLine("dsex_nudge_morning", A,
            "Body's stiff this early. Five minutes of mobility, then the real session.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "dsex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsex_nudge_afternoon_zero", A,
            "Day's half gone and nothing's trained yet. Twenty minutes is still twenty minutes.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "dsex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsex_nudge_evening", A,
            "Light session beats no session. Don't end the day cold.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "dsex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsex_nudge_lapse", A,
            "Rest day yesterday. Today's the run. Move.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("dsex_nudge_attention_loss", A,
            "Detrained. Comeback set: light, clean, today. That's the whole job.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsex_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
