package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Drill Sergeant × Money & finances. */
internal object DrillSergeantFinancesLines {

    private const val A = "DRILL_SERGEANT"
    private const val T = "FINANCES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("dsfi_first_ever", A,
            "Listen. The numbers don't lie. We track them. Discipline scales.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("dsfi_morning", A,
            "Open the ledger. Balance is what it is — no flinching.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "dsfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsfi_morning_early", A,
            "You're up before the day starts spending. Five-minute money check — faster than coffee, just as bracing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "dsfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsfi_afternoon", A,
            "Receipts logged yet? If not, do it now — memory's not your ledger.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "dsfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsfi_evening", A,
            "Get the day's spending in. Don't go to bed wondering what you spent.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "dsfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsfi_night_late", A,
            "Don't online-shop tired, soldier. Browser closed. Bed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "dsfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsfi_post_apotheosis", A,
            "Cycle closed. Numbers up. Don't celebrate by undoing them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("dsfi_monday", A,
            "Weekly review time — income, outflow, runway. Five minutes, no skipping.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "dsfi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsfi_friday", A,
            "Weekend's coming. Set the cash limit now — don't card-swipe your way through Saturday.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "dsfi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsfi_weekend", A,
            "Spending happens on weekends. Track each one — two seconds per receipt, no excuses.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "dsfi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("dsfi_level_1_reached", A,
            "You know your numbers now. Most people never do. Don't get cocky about it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "dsfi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsfi_level_2_reached", A,
            "A month tracked straight. The pattern's visible now — time to act on it, not just watch it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "dsfi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsfi_level_3_reached", A,
            "The savings rate is real now. The number's growing — keep the system that got you here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "dsfi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsfi_level_4_reached", A,
            "Money's a tool now, not a worry. Maintain the discipline that made it one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "dsfi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("dsfi_attention_loss_mild", A,
            "Three days unlogged. Catch up now. Receipts pile up fast.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "dsfi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("dsfi_attention_loss_hard", A,
            "Ledger's two weeks stale. Don't try to fix it all today. One week. Now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsfi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("dsfi_after_lapse", A,
            "Yesterday's spending unlogged. Pull the receipts. Five minutes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Acknowledged", null)), theme = T),
        DialogueLine("dsfi_mid_day_return", A,
            "Half the day gone, nothing tracked. The receipts are right there in your pocket. Out. Logged.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("dsfi_wishes_pending", A,
            "Reward stacked. Spend it deliberately — not on impulse.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "dsfi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("dsfi_mid_streak", A,
            "Three clean days of tracking. Compounding starts here.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsfi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("dsfi_sant_jordi", A,
            "Books and roses today, and both cost money. Cash budget for Sant Jordi — not the card.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_la_merce", A,
            "The Mercè bars take cash. Set a number before you leave. Stop at it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_sant_joan", A,
            "Cava and fireworks tonight, and they add up fast. Cash in pocket, card at home.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_diada", A,
            "Diada's a day off. Use it for the quarterly review — numbers don't review themselves.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_nadal", A,
            "Nadal gift spending peaks right about now. Set the number tonight and hold to it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_cap_d_any", A,
            "First day of the year. New budget. New savings target. Write them down now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsfi_reis", A,
            "Last gift round of Reis today — and the card statement's about to land. Brace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_carnaval", A,
            "The Carnaval costume's a sunk cost. Don't compound it with bar rounds.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_divendres_sant", A,
            "The city's quiet today. Open the accounts and look at where it actually went last month.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_pasqua", A,
            "Pasqua Monday. Trip costs landed last week. Reconcile now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_festa_del_treball", A,
            "It's workers' day. Your money is your hours — honor it, account for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_festa_major_gracia", A,
            "Festival food in Gràcia adds up fast. Cash, not card — and set the limit before you go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_assumpcio", A,
            "August burns budgets fast. Pull the year-to-date now, while you still can.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_hispanitat", A,
            "Day off the calendar. Quarterly check — net worth up or down? Be honest about it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_castanyada", A,
            "Chestnut season means the heating bill's coming. Front-load the savings now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_constitucio", A,
            "Long bridge weekend, travel costs likely. Cap it Friday — don't blow December's budget early.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_immaculada", A,
            "Christmas spending starts with this bridge weekend. Make the list — stick to it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_sant_esteve", A,
            "Day after Nadal. Tally the gift spending. Don't pretend it didn't happen.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_cap_d_any_eve", A,
            "Last day of the year. Annual close — total spent, total saved, honest numbers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "dsfi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsfi_birthday", A,
            "Another year on you. Dinner's on you tonight, fine — log it after.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "dsfi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_personal_date", A,
            "You flagged today: {label}. Plan the cost first — don't let the day pick your number.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "dsfi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("dsfi_complete_1", A, "Logged. Next entry.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsfi_complete_2", A, "Entered. Reconciled. Move.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsfi_complete_3", A, "Done. Number's where it should be.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsfi_complete_first_today", A,
            "First entry of the day. The ledger is real again.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "dsfi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsfi_complete_second_today", A,
            "Two in. Don't drift now. Receipts on the desk go in.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "dsfi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsfi_complete_third_today", A,
            "Three. Day's accounted for. Sleep without the financial fog.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "dsfi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsfi_complete_fourth_today", A,
            "Four. Either it was payday or you spent a lot. Be honest about it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "dsfi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsfi_complete_fifth_today", A,
            "Five. Big day. Tomorrow's a quiet one. Don't make this the new normal.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "dsfi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("dsfi_complete_after_streak", A,
            "Day three of tracking. Every euro accounted for. That's discipline.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsfi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("dsfi_apotheosis_1", A,
            "Cycle closed. Numbers up. Set the next target tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsfi_apotheosis_2", A,
            "Done. The savings rate held. Now don't blow it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsfi_apotheosis_3", A,
            "Closed. Compound interest is real. Patience is the trade.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsfi_apotheosis_first_ever", A,
            "First budget cycle in the book. You see the numbers now. Don't look away again.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("dsfi_apotheosis_1", "dsfi_apotheosis_2", "dsfi_apotheosis_3"),
            theme = T),
        DialogueLine("dsfi_apotheosis_at_level_2", A,
            "Promoted. The ledger runs itself. Time to plan, not just track.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "dsfi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsfi_apotheosis_at_level_3", A,
            "Senior tier. Money serves your goals now. Don't let lifestyle creep eat the gains.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "dsfi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsfi_apotheosis_at_level_4", A,
            "Top tier. The numbers compound on their own. Maintain the discipline.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "dsfi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("dsfi_nudge_morning", A,
            "Balance check, two minutes. Don't enter the day blind.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "dsfi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsfi_nudge_afternoon_zero", A,
            "Day's half gone, nothing logged. Receipts are in your pocket — out, and log them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "dsfi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsfi_nudge_evening", A,
            "Get the day's spending in before bed. Five minutes.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "dsfi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsfi_nudge_lapse", A,
            "Yesterday's ledger unfilled. Pull the receipts. Now.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("dsfi_nudge_attention_loss", A,
            "Ledger's stale. One week at a time. Don't try to fix it all today.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsfi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
