package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Drill Sergeant × Hobbies & play. */
internal object DrillSergeantHobbiesLines {

    private const val A = "DRILL_SERGEANT"
    private const val T = "HOBBIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("dsho_first_ever", A,
            "Listen. Joy is rationed. Take the dose. Don't apologize for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("dsho_morning", A,
            "Morning. Twenty minutes on the thing you love. Before the day grabs them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "dsho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsho_morning_early", A,
            "Up early. Stolen hour. Use it on the hobby — not on email.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "dsho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsho_afternoon", A,
            "Mid-day. Fifteen minutes of play between meetings. Don't pretend you don't have it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "dsho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsho_evening", A,
            "Evening. The hobby table. The instrument. The garden. Whatever it is — sit at it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "dsho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsho_night_late", A,
            "Late. Don't start a project now. Five minutes of the easy thing. Then bed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "dsho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("dsho_post_apotheosis", A,
            "Block done. The hobby stays — don't put it down. It's not a phase.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("dsho_monday", A,
            "Monday. Plan the hobby block this week. Same as you'd plan a meeting.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "dsho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsho_friday", A,
            "Friday. End the week with one good session. Not productive — pleasurable.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "dsho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("dsho_weekend", A,
            "Weekend. Long block. Two hours minimum. Don't let chores eat them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "dsho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("dsho_level_1_reached", A,
            "Level one. A week of real play. You're a person again. Don't quit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "dsho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsho_level_2_reached", A,
            "Level two. The hobby's getting good. Don't monetize it — that's the trap.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "dsho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsho_level_3_reached", A,
            "Level three. Real skill now. Real joy. Defend the time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "dsho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("dsho_level_4_reached", A,
            "Top tier. The hobby is part of you. Defend it like work. More than work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "dsho_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("dsho_attention_loss_mild", A,
            "Three days of pure work, no play. The body knows. Tonight: the hobby.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "dsho_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("dsho_attention_loss_hard", A,
            "Weeks of pure productivity. You're a person, not a function. Pick it up tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsho_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("dsho_after_lapse", A,
            "Skipped play yesterday. Today's the day. Twenty minutes. No guilt.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Acknowledged", null)), theme = T),
        DialogueLine("dsho_mid_day_return", A,
            "Halftime. Nothing playful yet. Fifteen minutes. Not a luxury — a need.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("dsho_wishes_pending", A,
            "Reward stacked. Buy the new tool, the new book, the new strings. Stale wins rot.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "dsho_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("dsho_mid_streak", A,
            "Three days of real play. The brain's softer. Don't undo it tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsho_streak", cooldownPicks = 5, theme = T),

        DialogueLine("dsho_sant_jordi", A,
            "Sant Jordi. Browse the makers' stalls. Inspiration's free. Take some.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_la_merce", A,
            "Mercè. The arts festival's part of it. Find the one tucked-away thing. Watch.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_sant_joan", A,
            "Sant Joan. No hobby tonight. Beach. Fire. Real off. Tomorrow back to it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_diada", A,
            "Diada. Day off. Long hobby block. Three hours. Don't fill it with errands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_nadal", A,
            "Nadal. Family today. The hobby waits til the 26th. Don't sneak away.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_cap_d_any", A,
            "New year. Pick the new skill within the hobby. Specific. Schedulable.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsho_reis", A,
            "Reis. Use the gift. If it's a tool, hold it. If it's an idea, try it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_carnaval", A,
            "Carnaval. Make the costume. With your hands. That's the hobby.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_divendres_sant", A,
            "Quiet day. Best hobby day of the year. Hours uninterrupted.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_pasqua", A,
            "Pasqua Monday. Don't waste the day off catching up. The hobby's the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_festa_del_treball", A,
            "Workers' day. The play is rest. Honor it. No productivity in disguise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_festa_major_gracia", A,
            "Gràcia. The decorations are someone's hobby. See them. Take notes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_assumpcio", A,
            "August. Empty city. Workshop hours possible. Take them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_hispanitat", A,
            "Day off. Workshop day. Don't fill it with errands you've been avoiding.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_castanyada", A,
            "Castanyada. Dark by 7. Hobby season opens. Long evenings at the bench.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_constitucio", A,
            "Bridge weekend. Pure play. Don't dress productivity up as the hobby.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_immaculada", A,
            "Pont. Five days. Hobby intensive. Or full rest. Don't trickle through both.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_sant_esteve", A,
            "Day after Nadal. Quiet workshop time. Build the small thing in your head.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_cap_d_any_eve", A,
            "Last day. List the year's hobby wins. Even small. Honest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "dsho_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("dsho_birthday", A,
            "Birthday. Treat yourself to a tool or material. Don't browse — buy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "dsho_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_personal_date", A,
            "Today: {label}. The hobby's a refuge. Use it. Don't apologize.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "dsho_personal", cooldownPicks = 1, theme = T),

        DialogueLine("dsho_complete_1", A, "Session in. Next.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsho_complete_2", A, "Done. Tools back where they belong. Maintain.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsho_complete_3", A, "Logged. No guilt for spending the time on it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("dsho_complete_first_today", A,
            "First play. The day's not all work now. Good.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "dsho_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsho_complete_second_today", A,
            "Two sessions. Don't burn out — savor it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "dsho_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsho_complete_third_today", A,
            "Three. Real hobby day. The skill's denser than this morning.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "dsho_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsho_complete_fourth_today", A,
            "Four. Stop forcing it. Hobbies don't have quotas.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "dsho_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("dsho_complete_fifth_today", A,
            "Five. Past play. You're escaping. Be honest with yourself.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "dsho_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("dsho_complete_after_streak", A,
            "Day three of real play. The mind's wider. Notice the colors.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "dsho_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("dsho_apotheosis_1", A,
            "Project done. Display it. The hobby earned its space.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsho_apotheosis_2", A,
            "Closed. The skill's bigger. Don't monetize it. Just enjoy.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsho_apotheosis_3", A,
            "Done. Plan the next piece. Forward motion, low stakes.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("dsho_apotheosis_first_ever", A,
            "First finished project. You're not just dabbling — you make things now.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("dsho_apotheosis_1", "dsho_apotheosis_2", "dsho_apotheosis_3"),
            theme = T),
        DialogueLine("dsho_apotheosis_at_level_2", A,
            "Promoted. The skill's real. Don't add pressure — the joy is the metric.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "dsho_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsho_apotheosis_at_level_3", A,
            "Senior tier. People ask. Be modest. Be specific. Keep playing.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "dsho_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("dsho_apotheosis_at_level_4", A,
            "Top tier. The hobby's part of who you are. Defend the bench, the time, the joy.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "dsho_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("dsho_nudge_morning", A,
            "Morning. Twenty minutes of play. Before the day eats them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "dsho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsho_nudge_afternoon_zero", A,
            "Halftime. Nothing playful. Fifteen minutes. Not optional.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "dsho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsho_nudge_evening", A,
            "Evening. The bench. The instrument. The garden. Sit down.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "dsho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("dsho_nudge_lapse", A,
            "Skipped play yesterday. Today's the play day. Twenty minutes. Now.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("dsho_nudge_attention_loss", A,
            "Weeks of all-work. Pick it up tonight. Even ten minutes. The body needs it.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "dsho_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
