package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Money & finances. */
internal object GentleMentorFinancesLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "FINANCES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmfi_first_ever", A,
            "Money isn't shame. It's information. We'll learn to look — gently. Welcome.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmfi_morning", A,
            "Morning. Open the account — just look. Notice what's there. No judgment.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfi_morning_early", A,
            "Up early. Five-minute money check — kinder than coffee. Almost.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfi_afternoon", A,
            "Mid-day. Receipts in the pocket — log them now, before memory drifts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfi_evening", A,
            "Evening. Day's spending logged. Soft close — no anxiety about it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfi_night_late", A,
            "It's late. Don't browse the bank tired. Tomorrow, with fresh eyes.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmfi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfi_post_apotheosis", A,
            "A real stretch of tracking. The numbers are friends now, not strangers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmfi_monday", A,
            "Monday. Weekly look — five minutes. Income, outflow, kindness.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmfi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmfi_friday", A,
            "Friday. Weekend ahead — set a soft cash limit. Not a rule, a guide.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmfi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmfi_weekend", A,
            "Weekend. Spending happens. Log each one — two seconds. Then enjoy.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmfi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmfi_level_1_reached", A,
            "First level. You know your numbers now. The fog is lifting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmfi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmfi_level_2_reached", A,
            "Second level. A month logged. The patterns are visible. Be kind about them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmfi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmfi_level_3_reached", A,
            "Third level. Savings rate is real. The numbers grow quietly. Notice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmfi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmfi_level_4_reached", A,
            "Top level. Money's a tool. Hold it lightly — not tightly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmfi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmfi_attention_loss_mild", A,
            "A few days unlogged. Catch up gently — fifteen minutes today. No shame.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmfi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmfi_attention_loss_hard", A,
            "Weeks of avoidance — that's okay, the numbers don't bite. Just this week. Today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmfi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("gmfi_mid_day_return", A,
            "Mid-day. Receipts in pockets. Take them out gently — log them now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmfi_wishes_pending", A,
            "You've earned a treat. Spend it on something true to you — not on impulse.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmfi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmfi_mid_streak", A,
            "Three days of tracking. The ledger's calm. Notice — that's quiet wisdom.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmfi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmfi_sant_jordi", A,
            "Sant Jordi. Books and roses. Set a soft cash budget — then enjoy fully.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_la_merce", A,
            "Mercè. Cash in pocket, card at home. The limit's a friend tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_sant_joan", A,
            "Sant Joan. Cava and fire cost something. Set the number — then let the night be.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_diada", A,
            "Diada. Day off. Quarterly look — soft, with tea. Don't rush.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_nadal", A,
            "Nadal. Gifts peak. Set a kind number — and keep it. Future-you sleeps better.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_cap_d_any", A,
            "First day. New budget, gently. No grand promises — just a soft target.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmfi_reis", A,
            "Reis. The card statement's about to land. Open it without dread.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_carnaval", A,
            "Carnaval. The costume is what it is — log it, then enjoy the night.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_divendres_sant", A,
            "Quiet day. Open the accounts — kindly. Look at last month without judgment.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_pasqua", A,
            "Pasqua Monday. Reconcile the trip costs — softly. Then close the book.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_festa_del_treball", A,
            "Workers' day. Your money is your hours — honor it by tending it kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_festa_major_gracia", A,
            "Gràcia. Festival food adds up — cash, not card. A soft cap on the night.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_assumpcio", A,
            "August. Summer spending burns budgets. Look at year-to-date — gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_hispanitat", A,
            "Day off. Quarterly check — net worth up or down. Be honest, then be kind.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_castanyada", A,
            "Castanyada. Heating bill's coming. Set aside a little now — quietly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_constitucio", A,
            "Bridge weekend. Trip costs. Cap softly on Friday. Then enjoy without ledger.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_immaculada", A,
            "Pont. December spending begins. The list helps — make it kind, not strict.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_sant_esteve", A,
            "Day after Nadal. Tally the gift spending. No judgment — it's done.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_cap_d_any_eve", A,
            "Last day. Annual close. Honest numbers — followed by kindness about them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmfi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmfi_birthday", A,
            "Happy birthday. Dinner's on you tonight — don't log it. Enjoy it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmfi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_personal_date", A,
            "Today: {label}. Plan the cost gently — don't let the day choose the number.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmfi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmfi_complete_1", A, "Logged. The book holds it now.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmfi_complete_2", A, "Well done. Soft pace. Move on.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmfi_complete_3", A, "Good. The number's where it should be.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmfi_complete_first_today", A,
            "First entry. The ledger's awake. The mental load lightens already.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmfi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmfi_complete_second_today", A,
            "Two entries. Don't rush — there are no points for speed.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmfi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmfi_complete_third_today", A,
            "Three. The day's accounted for. Sleep without the fog.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmfi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmfi_complete_fourth_today", A,
            "Four. The day was lively, clearly. Notice without judgment.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmfi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmfi_complete_fifth_today", A,
            "Five. Big day. Tomorrow can be quieter — that's a choice you can make.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmfi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmfi_complete_after_streak", A,
            "Day three of tracking. Every euro accounted for. Quiet wisdom.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmfi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmfi_apotheosis_1", A,
            "A budget cycle, complete. Set a kind next target — not a stretch one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmfi_apotheosis_2", A,
            "Closed. The savings held. Don't add new ambitions yet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmfi_apotheosis_3", A,
            "Done. Compound interest works in silence. Patience is the trade.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmfi_apotheosis_first_ever", A,
            "First budget cycle, done. The numbers are visible. Don't look away again.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmfi_apotheosis_1", "gmfi_apotheosis_2", "gmfi_apotheosis_3"),
            theme = T),
        DialogueLine("gmfi_apotheosis_at_level_2", A,
            "Two cycles. The ledger runs itself. Time to plan, not just track.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmfi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmfi_apotheosis_at_level_3", A,
            "Senior tier. Money serves your life now — keep it that way.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmfi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmfi_apotheosis_at_level_4", A,
            "Top tier. The numbers compound on their own. Hold the practice lightly.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmfi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmfi_nudge_morning", A,
            "Morning. A soft balance check — two minutes. No catastrophe.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmfi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmfi_nudge_afternoon_zero", A,
            "Halftime. Receipts in pockets. Out — log them gently.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmfi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmfi_nudge_evening", A,
            "Evening. Day's spending in before bed. Soft close.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmfi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmfi_nudge_attention_loss", A,
            "The ledger's stale. One week at a time — kindly. No catch-up sprint.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmfi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
