package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Recovery & healing. */
internal object GentleMentorRecoveryLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "RECOVERY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmre_first_ever", A,
            "The body heals on its own schedule, and patience is the whole practice — welcome, I'm glad you found your way here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmre_morning", A,
            "Good morning — the body's stiff from the night, so a stretch first would serve you well. Don't skip the warm-up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmre_morning_early", A,
            "You're up early, and the body's been still for hours — a little mobility before the coffee would help.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmre_afternoon", A,
            "It's the middle of the day — five minutes of physio exercises now, not 'after this meeting', would do you good.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmre_evening", A,
            "Evening's here — a little foam rolling, ice if things have flared, and please don't push through pain this late.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmre_night_late", A,
            "It's late now, and sleep is the real work tonight — no exercises, just bed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmre_post_apotheosis", A,
            "That block is done, and there's no need to rush back to full load — build back at around 60% over two weeks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmre_monday", A,
            "The week is opening — physio, sleep, a little mobility, that's the whole plan. No heroics needed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmre_friday", A,
            "The week is closing, and there's no need to 'reward' it with intensity that could re-injure you — a cold pack instead.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmre_weekend", A,
            "It's the weekend, so take a longer mobility block, slowly — the body trusts patient work more than anything.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmre_level_1_reached", A,
            "A whole week of daily exercises now — the body's noticed, truly, so be soft with yourself about it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmre_level_2_reached", A,
            "The pain's down a notch now, and that's real progress — though it's not a green light, so let's keep going slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmre_level_3_reached", A,
            "This is real progress — the body has started believing you mean it, and I'd hate to see that trust betrayed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmre_level_4_reached", A,
            "Patience won, in the end — the exercises stay part of your life now, probably forever, but kindly, always kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmre_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmre_attention_loss_mild", A,
            "A few days slipped off the plan, and that's alright — today's exercises, even a smaller set if that's what you need.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmre_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmre_attention_loss_hard", A,
            "It's been weeks now, and the pain may well be back — this one's worth calling the physio for, not self-coaching alone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmre_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("gmre_mid_day_return", A,
            "We're halfway through the day and the exercises are still waiting — just five minutes, the set's small on purpose.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmre_wishes_pending", A,
            "There's a reward waiting for you — book the massage rather than banking it, since rest left too long doesn't heal the same.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmre_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmre_mid_streak", A,
            "Three clean days now, and the pain's down to a fraction — let's not celebrate by lifting heavy, though.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmre_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmre_sant_jordi", A,
            "It's Sant Jordi, and walking the city is fine — just sit when you need to, no 'pushing through' today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_la_merce", A,
            "Mercè brings crowds and a lot of standing — bring the brace along if you need it, gently, no shame in it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_sant_joan", A,
            "Sant Joan tempts a whole night on the beach, but that would cost your recovery — sit down early, sand's no chair.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_diada", A,
            "Diada gives you the day off — a full mobility block, twenty minutes, done kindly, would be a lovely use of it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_nadal", A,
            "Nadal means sitting at the table most of the day — stand every hour if you can, walk between courses, the body asks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_cap_d_any", A,
            "The new year's here, and the exercises can be resolution enough — no need to pile new ones on top.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmre_reis", A,
            "It's Reis — the gift worth giving yourself today is patience, since the exercises still aren't optional.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_carnaval", A,
            "Carnaval and its dancing can flare things up — sit out a song or two if you need to, pride heals slower than rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_divendres_sant", A,
            "It's a quiet day, the whole city gone still — maybe the best recovery day of the year, so long mobility, no screens.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_pasqua", A,
            "Pasqua Monday — walk slowly, stretch well, and ease back in gently after all this rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_festa_del_treball", A,
            "It's Workers' Day, and recovery is the real work today — honor it, no need to fake productivity.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_festa_major_gracia", A,
            "Gràcia means standing crowds all week — take the bench breaks, keep drinking water, and don't push past what feels right.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_assumpcio", A,
            "The August heat brings inflammation up with it — cold packs help, and a little mobility morning and night.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_hispanitat", A,
            "It's a day off — real rest, not the productive kind. Lie down, stretch a little, read something gentle.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_castanyada", A,
            "Castanyada brings the cold air, and it stiffens the joints — warm up twice as long today, and move slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_constitucio", A,
            "This bridge weekend calls for real rest — don't bank the exercises for later, that's usually how injury creeps back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_immaculada", A,
            "Five days off ahead of you — the body's asking for slow, so honor that, and skip the catch-up workouts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_sant_esteve", A,
            "The day after, and you're stiff from all that table time — twenty minutes of mobility, heat first, would help.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_cap_d_any_eve", A,
            "The last day of the year — a mobility block before tonight's festivities, so you don't end it stiff.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmre_birthday", A,
            "Happy birthday — the body's asking for slow today, so a hot bath, a stretch, and eating well would be a lovely gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmre_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_personal_date", A,
            "Today is {label}, and stress has a way of flaring old pain — the recovery exercises matter more than ever.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmre_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmre_complete_1", A, "Set done. Slow next one.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmre_complete_2", A, "Logged. No load increase yet — patience.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmre_complete_3", A, "Good. The body's trusting you a bit more.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmre_complete_first_today", A,
            "First exercises done. The body's awake — don't compound at the gym tonight.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmre_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmre_complete_second_today", A,
            "Two sessions. Don't add a third 'just because' — tendons need rest between.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmre_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmre_complete_third_today", A,
            "Three. The maximum for today — the rest is the work. Sit down.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmre_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmre_complete_fourth_today", A,
            "Four. Stop — you're trading patience for pride. The injury returns.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmre_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmre_complete_fifth_today", A,
            "Five. Past the protocol — you'll pay tomorrow. Stop, kindly.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmre_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmre_complete_after_streak", A,
            "Three clean days. Pain's down — don't reward yourself with intensity.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmre_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmre_apotheosis_1", A,
            "Block closed. Build back at 60% — two weeks. Don't shortcut.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmre_apotheosis_2", A,
            "Cycle done. Next protocol — talk to the physio first. Don't freelance.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmre_apotheosis_3", A,
            "Closed. The exercises stay — forever, probably. The price of motion.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmre_apotheosis_first_ever", A,
            "First protocol done. The body trusts you — don't blow it in week one.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmre_apotheosis_1", "gmre_apotheosis_2", "gmre_apotheosis_3"),
            theme = T),
        DialogueLine("gmre_apotheosis_at_level_2", A,
            "Promoted. Pain's manageable — now add load with patience, not pride.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmre_apotheosis_at_level_3", A,
            "Senior tier. The body knows what work is — maintenance forever. No shortcuts.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmre_apotheosis_at_level_4", A,
            "Top tier. Recovery is part of you now — daily, forever. The tax for being alive.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmre_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmre_nudge_morning", A,
            "Morning. Warm-up first — five minutes. Then the day starts.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmre_nudge_afternoon_zero", A,
            "Halftime. Physio set undone. Five minutes — the set's small for a reason.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmre_nudge_evening", A,
            "Evening. Foam roll. Ice if flared — then bed early, sleep heals.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmre_nudge_attention_loss", A,
            "Weeks off-plan. Call the physio — reset the protocol. Don't self-coach.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmre_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
