package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Relationships & love. */
internal object GentleMentorLoveLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "LOVE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmlo_first_ever", A,
            "Love is just attention, given small and often — we'll learn to show up for it together, gently, no rush.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmlo_morning", A,
            "Before you leave this morning, maybe leave them one real sentence — not just 'have a good day', something yours.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmlo_morning_early", A,
            "You're up early — if they're stirring too, pour a second coffee. It's the small daily acts that build something lasting.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmlo_afternoon", A,
            "Somewhere in the middle of your day, send them one real sentence — not a meme forwarded without a thought behind it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmlo_evening", A,
            "When you sit down to eat tonight, maybe leave the phone in another room — just look at each other for a while.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmlo_night_late", A,
            "It's late, and it's easy to drift apart on separate screens without meaning to — reach over instead, even just a hand.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmlo_post_apotheosis", A,
            "That stretch is closed now, and it's alright to rest in it a moment — though the relationship still asks its small daily due.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmlo_monday", A,
            "The week is opening up — maybe plan one real thing together before it fills with everything else and drifts away.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmlo_friday", A,
            "The weekend ahead is for being together, not just beside each other on the couch with two different screens.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmlo_weekend", A,
            "There's room today for one real conversation — slow, unhurried, nothing about logistics at all.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmlo_level_1_reached", A,
            "That was your first real check-in with them, and something softened because of it — don't let the wall creep back up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmlo_level_2_reached", A,
            "They notice the care you've been putting in, even when you don't say so — let's keep it warm, not let it cool.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmlo_level_3_reached", A,
            "The relationship has become its own living thing now, doesn't it — something to tend gently, like a garden.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmlo_level_4_reached", A,
            "This is real partnership now, and it deserves your daily attention — nothing this alive can run on autopilot.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmlo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmlo_attention_loss_mild", A,
            "A few days of just 'fine' back and forth — that's usually the quiet warning. One real question tonight, asked gently.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmlo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmlo_attention_loss_hard", A,
            "It's been weeks of drifting now, I think — sit down together tonight, no screens, no agenda, and just talk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmlo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("gmlo_mid_day_return", A,
            "The day's half gone and you haven't reached out yet — a real sentence now would mean more than you'd think.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmlo_wishes_pending", A,
            "There's a little reward waiting — maybe let it become a slow date together, rather than sitting and going cold.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmlo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmlo_mid_streak", A,
            "Three days now of showing up for them, quietly — they feel it, even unsaid, so let's keep the thread going.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmlo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmlo_sant_jordi", A,
            "There are roses and books everywhere today — bring one with intention, something you noticed they'd actually love.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_la_merce", A,
            "The city will be all crowds and noise tonight for Mercè — hold their hand, and don't lose each other in the crush.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_sant_joan", A,
            "Tonight is for beach fires and staying close — end it together, not drifted onto separate couches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_diada", A,
            "You've got the day off together for Diada — let it stay that way, rather than filling it with separate errands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_nadal", A,
            "Family will take most of today, and that's lovely — but steal ten quiet minutes alone together too, you'll both need it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_cap_d_any", A,
            "The year is brand new — let the first real conversation of it be an honest one, this soft moment doesn't come twice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmlo_reis", A,
            "Today is gift day — choose something specific rather than something last-minute, the paying attention is the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_carnaval", A,
            "Pick something silly to wear together today and laugh about it — that lightness together is its own kind of practice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_divendres_sant", A,
            "The city's gone quiet today — a long, slow talk over coffee, the kind only a day like this allows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_pasqua", A,
            "The long weekend is still unspooling — plan one small thing together, a meal, a walk, anything kind.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_festa_del_treball", A,
            "Today honors work, and the relationship is its own kind of work too — but honor the rest as well, and just show up softly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_festa_major_gracia", A,
            "Gràcia's streets are dressed in paper and light — walk them together, eat at one tiny stall, and stay close.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_assumpcio", A,
            "August has slowed everything to a warm hush — a long lunch together, and let the errands wait for another day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_hispanitat", A,
            "You've got the day free — a trip out of the city, even just an hour away, would be lovely together.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_castanyada", A,
            "Roast chestnuts and the first real chill of autumn — walk together, stand close, let the cold be your excuse.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_constitucio", A,
            "The long weekend is opening up — plan one small trip, it doesn't need to be far, just the two of you together.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_immaculada", A,
            "Five soft days ahead — rest together or travel together, whichever you choose, give it your whole attention.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_sant_esteve", A,
            "Yesterday's family chaos is still settling — steal a quiet moment alone with them today, just the two of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_cap_d_any_eve", A,
            "As the year closes out, talk together about it honestly — the good and the hard both, held with kindness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmlo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmlo_birthday", A,
            "Happy birthday — let yourself simply receive whatever they've planned today, no critiquing, just being present in it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmlo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_personal_date", A,
            "Today is {label}, and they know it matters to you — let them in on it, rather than carrying it alone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmlo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmlo_complete_1", A, "You showed up for them, and that's lovely, truly.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmlo_complete_2", A, "That's done now, and they felt it — you don't need to go fishing for proof of that.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmlo_complete_3", A, "Good — when you sit with them next, let the phone stay tucked away.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmlo_complete_first_today", A,
            "That first real check-in already shifted something — the day feels different between you now, doesn't it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmlo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmlo_complete_second_today", A,
            "Two reaches out today, and that's plenty warmth for now — no need to smother, just let it breathe a little.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmlo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmlo_complete_third_today", A,
            "Three now, and the day's been full of them — this is what real partnership actually looks like, quietly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmlo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmlo_complete_fourth_today", A,
            "Four already — either it's been a big day for you both, or you're hovering a little. Be honest, gently.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmlo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmlo_complete_fifth_today", A,
            "Five today — and maybe give them a little space now, connection was never meant to feel like being watched.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmlo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmlo_complete_after_streak", A,
            "Three days now of quietly showing up for them — they feel it, I promise, you don't need to ask if they do.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmlo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmlo_apotheosis_1", A,
            "That stretch is closed now, and well — keep showing up the same kind way tomorrow, nothing needs to change.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmlo_apotheosis_2", A,
            "A whole cycle finished, and the relationship is stronger for it — just don't coast too long on the credit.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmlo_apotheosis_3", A,
            "It's closed now — perhaps plan the next small thing together, gentle forward motion, nothing more.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmlo_apotheosis_first_ever", A,
            "Your first real chapter together, and you showed up fully for it — hold onto how that felt, it matters.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmlo_apotheosis_1", "gmlo_apotheosis_2", "gmlo_apotheosis_3"),
            theme = T),
        DialogueLine("gmlo_apotheosis_at_level_2", A,
            "Something has really taken root here — you're a true partner to them now, and that's worth protecting gently.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmlo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmlo_apotheosis_at_level_3", A,
            "People notice how you treat them, you know, even the ones who never say so — stay consistent with it, kindly.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmlo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmlo_apotheosis_at_level_4", A,
            "You're deep in this now — hold the relationship as carefully as anything else that matters to you, softly, always awake to it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmlo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmlo_nudge_morning", A,
            "Before you head out this morning, maybe leave them one specific thing — more than just 'love you, bye'.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmlo_nudge_afternoon_zero", A,
            "The day's half over and there's been no word yet — a real sentence now would go a long way.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmlo_nudge_evening", A,
            "As you sit down to eat this evening, let the phone rest elsewhere and just look at them a while.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmlo_nudge_attention_loss", A,
            "It's been weeks of drifting, I think — sit down together tonight, no screens, and just talk softly.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmlo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
