package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Meditation & stillness. */
internal object GentleMentorMeditationLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "MEDITATION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmme_first_ever", A,
            "Stillness is a practice, soft and daily, with no goal to chase — we'll simply sit together, and I'm glad you're here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmme_morning", A,
            "Whenever you're ready this morning, there's a cushion waiting — ten minutes, gently, nothing more required.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmme_morning_early", A,
            "The mind is still quiet in this pre-dawn hush — sit now, before the day gets its hooks in fully.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmme_afternoon", A,
            "Right where you are at your desk, three slow breaths would do — just a small reset, no ceremony needed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmme_evening", A,
            "Before the screens come out tonight, a short sit would help — the mind can't settle to sleep with all that static on.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmme_night_late", A,
            "It's late now, and three slow breaths right there in bed is plenty of practice for tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmme_post_apotheosis", A,
            "That was a real stretch of sitting, and I hope you feel it — the daily practice just continues, kindly, no graduating from this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmme_monday", A,
            "The week is opening — the same quiet time each day, met with kindness rather than force, the cushion already knows you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmme_friday", A,
            "The weekend is close now — don't let the looseness of it talk you out of sitting, it counts for even more on days like that.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmme_weekend", A,
            "There's room today for a longer sit, if you'd like — twenty minutes, starting slow, no need to rush into stillness.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmme_level_1_reached", A,
            "A whole week of sitting now, and it's been quietly boring on purpose — that repetition is exactly the point.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmme_level_2_reached", A,
            "The breath comes back to you faster now, doesn't it, and you notice the noise sooner too — that's real progress, quietly made.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmme_level_3_reached", A,
            "The stillness has started showing up off the cushion too, in the middle of ordinary moments — hold it lightly, it doesn't need gripping.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmme_level_4_reached", A,
            "This is a daily practice forever now, and there's no graduating from it — just kindness, held as the whole discipline.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmme_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmme_attention_loss_mild", A,
            "A few days away from the cushion, and that's alright — today, just five minutes would be the whole task, nothing more.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmme_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmme_attention_loss_hard", A,
            "It's been weeks away, I know — don't try to restart at thirty minutes, just five today, and five again tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmme_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("gmme_mid_day_return", A,
            "The day's half gone and you haven't sat yet — five minutes right at your desk, eyes closed, would be enough.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmme_wishes_pending", A,
            "There's a little reward waiting for you — a longer sit, or a slow walk instead, either one is still the practice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmme_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmme_mid_streak", A,
            "Three days in a row now — the cushion's grown familiar, and that's lovely, though it needn't become something sacred or heavy.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmme_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmme_sant_jordi", A,
            "Sit early today, before the roses and the crowds — the rest of Sant Jordi will be loud enough on its own.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_la_merce", A,
            "The city will be loud tonight for Mercè — sit for a while before you go, the noise lands easier after a still room.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_sant_joan", A,
            "Tonight will run until dawn for Sant Joan — sit quietly before you go, a little stillness before all that fire.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_diada", A,
            "You've got the day free for Diada — a longer sit is possible, twenty minutes, taken slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_nadal", A,
            "Sit for a little while before the table today — gratitude tends to land differently after some stillness first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_cap_d_any", A,
            "This is the first sit of the whole new year — it sets the rhythm for what follows, gently, without any pressure.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmme_reis", A,
            "The morning is quiet before the gifts come out — sit for a moment first, kindness tends to land differently that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_carnaval", A,
            "The costume-energy out there today is loud — sit early, so you're not walking into the noise already wired.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_divendres_sant", A,
            "The whole city pauses today — this may be the best sit of the whole year, if you'll let yourself take it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_pasqua", A,
            "Let today gently reset the practice — same quiet time tomorrow, just as it was before the long weekend.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_festa_del_treball", A,
            "Today honors work, and here the work is simply the breath — no holiday off from that, just kindness, daily.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_festa_major_gracia", A,
            "The streets of Gràcia will be loud all week — sitting twice a day might help, you'll likely need the quiet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_assumpcio", A,
            "The city's emptied out and the days have slowed for August — perhaps the best month all year for longer sits.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_hispanitat", A,
            "You've got the day free — a longer sit is possible, half an hour, kindly, rather than filling it all with errands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_castanyada", A,
            "An evening sit feels different in this first real chill of autumn, Castanyada's chestnuts and all — take it slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_constitucio", A,
            "The bridge weekend is here, and it's tempting to skip — but daily stays daily, kindly, even on loose days like this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_immaculada", A,
            "Five soft days stretch ahead — pack the cushion if you're traveling, the daily sit keeps you anchored wherever you land.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_sant_esteve", A,
            "The family chaos is still going strong today — five minutes between rounds might be the most practical practice there is.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_cap_d_any_eve", A,
            "As the year winds down, sit before the noise of tonight begins — it tends to end quieter that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmme_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmme_birthday", A,
            "Happy birthday — a longer sit is allowed today, twenty minutes if you'd like, and then the whole day is yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmme_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_personal_date", A,
            "Today is {label} — sit longer if the day feels heavy, shorter if it's light, but let yourself sit either way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmme_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmme_complete_1", A, "You sat, and that's lovely — the mind softens a little more each time.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmme_complete_2", A, "That's done now — stand slowly, and carry the breath with you into whatever comes next.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmme_complete_3", A, "Good — the mind returns to the breath so much faster these days, have you noticed?",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmme_complete_first_today", A,
            "That first sit sets the whole day on grounded footing — it would be a shame to lose it straight to the phone.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmme_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmme_complete_second_today", A,
            "Two sits now, and the reset feels real — carry that breath forward into what's left of the day.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmme_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmme_complete_third_today", A,
            "Three sits — this has become a real practice day, and it would be a shame to lose it now to a screen-coma.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmme_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmme_complete_fourth_today", A,
            "Four sits today — either it's been a rough one, or you're using the cushion to hide a little. Be honest, softly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmme_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmme_complete_fifth_today", A,
            "Five now — and the cushion was never meant as escape. Stand up when you're ready, and go live the day.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmme_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmme_complete_after_streak", A,
            "Three days now, and the mind sits quieter for it — notice that if you like, no need to make anything of it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmme_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmme_apotheosis_1", A,
            "A whole block of sitting, finished — and the daily practice just continues on, there's no graduating from this.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmme_apotheosis_2", A,
            "A cycle is done now — no need to lengthen the sit just to look serious about it, same quiet time tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmme_apotheosis_3", A,
            "It's closed now — the practice stays the practice, quietly boring on purpose, and that's exactly as it should be.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmme_apotheosis_first_ever", A,
            "Your first real block of regular sitting, finished — you've built something here that most people never quite get to.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmme_apotheosis_1", "gmme_apotheosis_2", "gmme_apotheosis_3"),
            theme = T),
        DialogueLine("gmme_apotheosis_at_level_2", A,
            "Two blocks in now, and the mind finds the breath so much faster — no need to go chasing after deeper states, though.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmme_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmme_apotheosis_at_level_3", A,
            "The stillness follows you off the cushion now, into ordinary moments — stay humble about it, kindly, as always.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmme_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmme_apotheosis_at_level_4", A,
            "You're deep into this now — the daily sit goes on forever, this discipline never really graduates, so hold it lightly.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmme_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmme_nudge_morning", A,
            "The cushion's waiting for you this morning — ten minutes, and maybe leave the phone in the kitchen for those few.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmme_nudge_afternoon_zero", A,
            "The day's half gone and there's been no sit yet — five minutes at the desk, eyes closed, would still count.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmme_nudge_evening", A,
            "Before bed tonight, a short sit would help — the mind can't really settle to sleep with all that static still on.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmme_nudge_attention_loss", A,
            "It's been weeks away — just five minutes today, building back slowly, with kindness rather than force.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmme_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
