package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Writing & creativity. */
internal object GentleMentorWritingLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "WRITING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmwr_first_ever", A,
            "The page is patient, and we'll fill it together — slowly, ugly first if it needs to be. Welcome.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmwr_morning", A,
            "This is often the best writing hour of the day — even fifty words would be a fine place to start.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmwr_morning_early", A,
            "You're up early and the mind's still quiet — two hundred words, gently, and then the day can properly start.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmwr_afternoon", A,
            "It's the middle of the day, and inspiration is mostly a story we tell ourselves — sit down and write, that's the only real trick.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmwr_evening", A,
            "As evening comes in, maybe two gentle passes over this morning's words — and then you can close the file for the night.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmwr_night_late", A,
            "It's late, and drafting tired rarely serves the words — just note the idea down, and sharpen it tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmwr_post_apotheosis", A,
            "The piece is done — publish it or shelve it, kindly, whenever feels right. Stale drafts have a way of growing heavy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmwr_monday", A,
            "The week is opening — set yourself a kind word count, and then halve it. Make it something you can actually reach.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmwr_friday", A,
            "The week is folding up — ship the draft before the weekend if it's ready, or shelve it kindly if it isn't.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmwr_weekend", A,
            "There's nothing pulling at you today — a long-form day, if you like, three unhurried hours of slow words, no editing yet.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmwr_level_1_reached", A,
            "Your first piece, finished — notice that, truly, because most people never leave the blank page at all.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmwr_level_2_reached", A,
            "The voice is showing up on the page now — trust it, and try not to edit it into silence.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmwr_level_3_reached", A,
            "This is real work now, at a real cadence — share it when you can, gently. Hiding it too long is usually just fear.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmwr_level_4_reached", A,
            "The voice is unmistakably yours now — defend the writing time for it, gently, day after day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmwr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmwr_attention_loss_mild", A,
            "A few days with the page blank, and that's allowed — one paragraph today, anything at all, would be enough.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmwr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmwr_attention_loss_hard", A,
            "I know it's been weeks of silence — write something rough today, whatever comes. The voice returns, with patience.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmwr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("gmwr_mid_day_return", A,
            "Half the day's gone and the page is still empty — twenty minutes, even rough words, they still count.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmwr_wishes_pending", A,
            "You've earned a retreat day — take it if you can, the words tend to come when they're not being chased.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmwr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmwr_mid_streak", A,
            "Three writing days now, and the voice is awake — there's no need to strain trying to hold onto it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmwr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmwr_sant_jordi", A,
            "It's the writers' day, roses and books on every table — buy one, then write a single slow paragraph of your own.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_la_merce", A,
            "The city's loud with the Mercè today — maybe a café in the morning instead, words tend to gather where there's tea.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_sant_joan", A,
            "No words needed tonight for Sant Joan — just watch the fire, and write about it tomorrow if it stays with you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_diada", A,
            "It's a long day for the Diada — a long writing block if you want one, three hours of slow words as a gift to yourself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_nadal", A,
            "The words can rest today for Nadal — just listen at the table, and maybe jot a few notes for January, gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_cap_d_any", A,
            "It's the first day of the year — the first three sentences somehow set the whole year's voice, so write them slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmwr_reis", A,
            "It's gift day — read the new book if you got one, and notice what works in it. Reading is writing practice too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_carnaval", A,
            "The streets are full of borrowed faces for Carnaval — watch the costumes, characters practically write themselves there.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_divendres_sant", A,
            "The city's gone quiet and slow today — the stillness writing needs. Two hours, no phone, if you can manage it kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_pasqua", A,
            "Coming off the long weekend now — just a gentle reset, one paragraph today, that would be plenty.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_festa_del_treball", A,
            "A day set aside to honor work, and for you the work is words — honor the rest today instead, and return to it tomorrow, gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_festa_major_gracia", A,
            "Gràcia's streets are dressed in paper and light again — carry a notebook, they have a way of writing themselves into you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_assumpcio", A,
            "The city empties out in August, and it's quietly the best writing month of the year — slow, slow words, if you feel it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_hispanitat", A,
            "With the day off, maybe read the thing you've been avoiding, and then write a kind response to it, whenever you're ready.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_castanyada", A,
            "It's dark by seven now with the Castanyada arriving — indoor evenings again, and long-form's proper season.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_constitucio", A,
            "It's a bridge weekend — either ship a piece properly, or rest fully. Half-drafting through it serves neither.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_immaculada", A,
            "Five days ahead of you — a real first draft is possible in that stretch, or a proper rest. Better than dabbling at either.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_sant_esteve", A,
            "The day after Nadal — a light edit if you feel like it, but no new work. Let the voice rest a little longer.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_cap_d_any_eve", A,
            "The year's last day — count the pages you wrote, honestly, and let next year's plans form softly, without pressure.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmwr_birthday", A,
            "Happy birthday — write yourself a kind letter today, if you feel like it, and read it back again next year.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmwr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_personal_date", A,
            "Today is {label} — the kind of day worth writing about, even just soft notes, even just one paragraph.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmwr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmwr_complete_1", A, "Lovely — the words are down, and that's really the whole of it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmwr_complete_2", A, "Logged — try not to reread it just yet, momentum is a precious, easily-startled thing.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmwr_complete_3", A, "Good — close the file now, if you can, and let the editing wait for tomorrow.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmwr_complete_first_today", A,
            "The first words are down, and with them the blank page is gone — the rest tends to come easier after that.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmwr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmwr_complete_second_today", A,
            "Two sessions now — no need to push further, the quality tends to drop once you're past ninety minutes anyway.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmwr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmwr_complete_third_today", A,
            "Three now — a real writing day, this — and the piece has gotten denser than it was this morning. Notice that.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmwr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmwr_complete_fourth_today", A,
            "Four already — time to stop, I think. Rest the voice tonight, and tomorrow it'll come back sharper.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmwr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmwr_complete_fifth_today", A,
            "Five today — past the point of lucid now, more typing than writing. Rest, kindly, the page will keep.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmwr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmwr_complete_after_streak", A,
            "Three days of writing now, and the voice is awake — keep the rhythm going, but softly, there's no need to force it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmwr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmwr_apotheosis_1", A,
            "The piece is done — publish it or shelve it within a couple of days, kindly. Don't let it sit and rot in a drawer.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmwr_apotheosis_2", A,
            "That's closed now — if you write the next piece's first sentence while you're still warm, it'll be easier to return to.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmwr_apotheosis_3", A,
            "Done — read it back tomorrow with fresh eyes, and edit it kindly when you do.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmwr_apotheosis_first_ever", A,
            "Your first piece, top to bottom, truly finished — most people never get there. Notice what that means.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmwr_apotheosis_1", "gmwr_apotheosis_2", "gmwr_apotheosis_3"),
            theme = T),
        DialogueLine("gmwr_apotheosis_at_level_2", A,
            "A second piece now, and the voice is holding steady — longer pieces feel possible from here, whenever you're ready.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmwr_apotheosis_at_level_3", A,
            "People are actually reading what you write now — that's not a reason to write less, but to write with more care.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmwr_apotheosis_at_level_4", A,
            "The voice is unmistakably yours by now — keep defending the time for it, softly, day after day.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmwr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmwr_nudge_morning", A,
            "Good morning — the page is open, whenever you are. Two hundred words, and try not to overthink them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmwr_nudge_afternoon_zero", A,
            "Just checking in — the page is still blank, and twenty minutes of anything at all would be a start.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmwr_nudge_evening", A,
            "Evening's here — a gentle edit pass, if you like, two reads through, and then you can close it for the night.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmwr_nudge_attention_loss", A,
            "It's been quiet for weeks now, and that's alright — a rough page today, anything at all, would bring the voice back gently.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmwr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
