package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Learning & study. */
internal object GentleMentorLearningLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "LEARNING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmle_first_ever", A,
            "Learning is slow joy. We open the book together — one page at a time. Welcome.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmle_morning", A,
            "Morning. One page, when you're ready. The mind's clearest now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmle_morning_early", A,
            "Up early. The pre-work hour is best for study. Don't fill it with news.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmle_afternoon", A,
            "Lunch break study. Fifteen minutes — you'll remember more than you'd expect.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmle_evening", A,
            "Evening. One chapter. Then close it — the brain consolidates overnight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmle_night_late", A,
            "Late. Don't cram tired. One paragraph and sleep — it'll stick better tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmle_post_apotheosis", A,
            "A subject closed. Notice it. The next one waits — gently, when you're ready.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmle_monday", A,
            "Monday. Week's study plan — small, schedulable. One page a day, perhaps.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmle_friday", A,
            "Friday. End of the week. What did you learn? Honest, no judgment.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmle_weekend", A,
            "Weekend. Longer block possible — but no pressure. Two hours of real study suffices.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmle_level_1_reached", A,
            "First level. First chapter, retained. Most quit at this point — you didn't.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmle_level_2_reached", A,
            "Second level. Concepts connect. The map is forming. Notice the new shapes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmle_level_3_reached", A,
            "Third level. You can explain it now. Teach someone — kindly, slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmle_level_4_reached", A,
            "Top level. The subject is yours. Find another — curiosity is the engine.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmle_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmle_attention_loss_mild", A,
            "A few days, book closed. That's fine. Open it — anywhere. The page waits.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmle_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmle_attention_loss_hard", A,
            "The book's been waiting. Don't start over — pick up where you left.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmle_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("gmle_mid_day_return", A,
            "Half the day. The book's unopened. Ten minutes is enough.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmle_wishes_pending", A,
            "Reward stacked. Buy the next book on your shelf-of-curiosity. No need to justify it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmle_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmle_mid_streak", A,
            "Three study days in a row. The subject's denser in your head now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmle_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmle_sant_jordi", A,
            "Sant Jordi. Buy the new book today. Read the first chapter tonight — slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_la_merce", A,
            "Mercè. Loud city. Library, headphones, or skip — pick gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_sant_joan", A,
            "Sant Joan. No study tonight. Real off. Tomorrow, gently, back to the page.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_diada", A,
            "Diada. Day off. Long-form reading. Three hours — no phone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_nadal", A,
            "Nadal. Family takes the day. Tomorrow, the page returns — kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_cap_d_any", A,
            "New year. New subject on the shelf, perhaps. Pick it today — open it when ready.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmle_reis", A,
            "Reis. A book as a gift. Read it slowly — don't shelve it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_carnaval", A,
            "Carnaval. Groggy mornings ahead. Study at lunch — not 7am, kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_divendres_sant", A,
            "Quiet day. Best study day of the year. Phone off. Two slow hours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_pasqua", A,
            "Pasqua Monday. Reset the study habit — one page. That's the whole day's goal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_festa_del_treball", A,
            "Workers' day. The book waits. Read tomorrow — kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_festa_major_gracia", A,
            "Gràcia. Distractions outside. Pick: library or festival. Either is okay.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_assumpcio", A,
            "August. Empty city. Best long-read month. Use it gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_hispanitat", A,
            "Day off. The textbook you've avoided. Open it — one tough chapter, slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_castanyada", A,
            "Castanyada. Dark by 7. Indoor reading season opens — lean in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_constitucio", A,
            "Bridge weekend. Pick a book. Finish it by Monday — gently, if it takes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_immaculada", A,
            "Pont. Five days. One real subject — or rest. Don't dabble.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_sant_esteve", A,
            "Day after. Light reading. The fiction book — earn the easy one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_cap_d_any_eve", A,
            "Last day. Books read this year — list them. Honest. Plan the next stack gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmle_birthday", A,
            "Happy birthday. Read the fun book — the hard one waits, kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmle_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_personal_date", A,
            "Today: {label}. Lighter reading — or none. The book understands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmle_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmle_complete_1", A, "Chapter done. Lovely.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmle_complete_2", A, "Logged. Note the key idea — before it drifts.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmle_complete_3", A, "Good. The brain's filing it overnight.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmle_complete_first_today", A,
            "First study block. The book remembers you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmle_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmle_complete_second_today", A,
            "Two blocks. Don't push past ninety minutes — comprehension drops there.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmle_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmle_complete_third_today", A,
            "Three. Real study day. The subject's clearer than this morning.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmle_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmle_complete_fourth_today", A,
            "Four. Stop. Sleep on it — tomorrow it'll be clearer than rereading.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmle_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmle_complete_fifth_today", A,
            "Five. Past comprehension. Words now, not knowledge. Rest, kindly.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmle_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmle_complete_after_streak", A,
            "Day three of study. The subject's alive in you now. Notice.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmle_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmle_apotheosis_1", A,
            "Subject closed. Find a way to use it — knowledge unused leaks.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmle_apotheosis_2", A,
            "Course done. Teach someone the core idea — kindly. That's the test.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmle_apotheosis_3", A,
            "Closed. Write the summary now — future-you will need it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmle_apotheosis_first_ever", A,
            "First subject, top to bottom. You're not a beginner anymore. Notice.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmle_apotheosis_1", "gmle_apotheosis_2", "gmle_apotheosis_3"),
            theme = T),
        DialogueLine("gmle_apotheosis_at_level_2", A,
            "A second subject. The map's wider — pick a harder one next, when curious.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmle_apotheosis_at_level_3", A,
            "Senior tier. You teach the basics now — keep learning the hard parts.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmle_apotheosis_at_level_4", A,
            "Top tier. You've earned the deep, narrow subject. Take it — slowly.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmle_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmle_nudge_morning", A,
            "Morning. One page. Even one paragraph. Now — before the day eats it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmle_nudge_afternoon_zero", A,
            "Halftime. Book unopened. Ten minutes — pick a paragraph.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmle_nudge_evening", A,
            "Evening. One chapter, then close it. The brain consolidates overnight.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmle_nudge_attention_loss", A,
            "The book's been waiting. Pick up where you left — don't restart from page one.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmle_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
