package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Body & exercise. */
internal object GentleMentorExerciseLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "EXERCISE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmex_first_ever", A,
            "We're going to move, together, at the pace your body asks for. Welcome.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmex_morning", A,
            "Good morning. A few easy reps, when you're ready. The body wakes slowly.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmex_morning_early", A,
            "You're up early. Gentle warm-up first — joints before muscles. We have time.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmex_afternoon", A,
            "Mid-day. If you trained, rest. If you didn't, even ten minutes counts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmex_evening", A,
            "Evening. A short session is enough. Form before intensity, always.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmex_night_late", A,
            "It's late. Some gentle stretching, perhaps. Bed soon — that's training too.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmex_post_apotheosis", A,
            "That block was real work. Rest a day or two. The body asks for it now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmex_monday", A,
            "A new week. Let's set a kind pace — easier than last week if you need it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmex_friday", A,
            "Friday. Honest check: is today a session day, or a rest day? Both are okay.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmex_weekend", A,
            "Weekend. Long walks count. Outdoor movement counts. Joy counts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmex_level_1_reached", A,
            "First level. You've shown up. That's the hardest part — most don't.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmex_level_2_reached", A,
            "Second level. Notice how the body's already different. Be kind to it now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmex_level_3_reached", A,
            "Third level. Form is locked. Now we listen — the body tells us what it needs.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmex_level_4_reached", A,
            "Top level. The practice is yours now. Hold it lightly. Don't make it a religion.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmex_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmex_attention_loss_mild", A,
            "A few days off. That's allowed. One easy session today brings it back. No catch-up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmex_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmex_attention_loss_hard", A,
            "A long pause. Welcome back, with no apology. We start at half. The body remembers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmex_atten_loss", cooldownPicks = 2, theme = T),

                DialogueLine("gmex_mid_day_return", A,
            "The afternoon's here. If you can move a little before evening, that's plenty.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmex_wishes_pending", A,
            "You've earned rest. Take it without guilt. The body is asking.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmex_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmex_mid_streak", A,
            "Three days in a row. Lovely. Notice the rhythm — don't chase it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmex_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmex_sant_jordi", A,
            "Sant Jordi. Walking the city is movement enough today. Notice the roses.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_la_merce", A,
            "Mercè. A loud, full day ahead. Skip the gym — the festival is the cardio.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_sant_joan", A,
            "Sant Joan. Beach all night. Tomorrow be soft on yourself. Sleep counts as training.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_diada", A,
            "Diada. A slow walk somewhere green is more than enough today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_nadal", A,
            "Nadal. A light walk between meals helps. Don't aim for anything more.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_cap_d_any", A,
            "A new year. No grand resolutions — just the next easy session, when you're ready.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmex_reis", A,
            "Reis. A walk to clear the sugar from breakfast. Slow pace. No goal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_carnaval", A,
            "Carnaval. Dancing is the workout. Be gentle with the morning after.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_divendres_sant", A,
            "A quiet day. Long, slow movement — a walk, a stretch. The body unwinds.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_pasqua", A,
            "Pasqua Monday. Easy session — coming off a holiday means easing back in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_festa_del_treball", A,
            "A day for workers. The body works hard. Rest, gently, today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_festa_major_gracia", A,
            "Gràcia week. Walking the streets is the practice. Light shoes. Wander.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_assumpcio", A,
            "August heat. Move very early or after sunset. Water, shade. No heroics.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_hispanitat", A,
            "A day off. Pick something you'd enjoy — a hike, a swim. Movement as gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_castanyada", A,
            "Castanyada. Dark earlier now — move when the light's still here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_constitucio", A,
            "Bridge weekend opens. You can train every day or none — both are fine.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_immaculada", A,
            "Pont. Five days. Move on two, rest on three — or whatever shape feels right.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_sant_esteve", A,
            "Day after Nadal. Stiff from the table. A slow walk loosens everything.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_cap_d_any_eve", A,
            "Last day of the year. A short, kind session. Don't end the year sore.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmex_birthday", A,
            "Happy birthday. Move gently today, if you move at all. Tomorrow's its own day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmex_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_personal_date", A,
            "You marked today: {label}. Lower the load. The body knows when to rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmex_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmex_complete_1", A, "Lovely. Rest a moment.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmex_complete_2", A, "Well done. The body's quietly grateful.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmex_complete_3", A, "Good session. Hydrate. Stretch a little.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmex_complete_first_today", A,
            "First session of the day. The hardest one — the rest comes easier.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmex_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmex_complete_second_today", A,
            "Two sessions. That's plenty. Don't reach for a third — savor this one.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmex_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmex_complete_third_today", A,
            "Three. A real day of work. Eat well tonight — your body earned it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmex_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmex_complete_fourth_today", A,
            "Four sessions. That's a lot. Tomorrow may ask for rest — listen to it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmex_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmex_complete_fifth_today", A,
            "Five. The body is whispering — please rest now. Listen, kindly.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmex_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmex_complete_after_streak", A,
            "Day three in a row. The body's adapting. Notice the small shifts.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmex_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmex_apotheosis_1", A,
            "A block of training, complete. Rest, then we plan the next one — kindly.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmex_apotheosis_2", A,
            "Done. The next phase can wait until you've truly rested. No rush.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmex_apotheosis_3", A,
            "Closed. Write down what worked — your future self will thank you.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmex_apotheosis_first_ever", A,
            "Your first finished training block. Notice it. Most never reach this point.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmex_apotheosis_1", "gmex_apotheosis_2", "gmex_apotheosis_3"),
            theme = T),
        DialogueLine("gmex_apotheosis_at_level_2", A,
            "A second block. The body's adapting — add load only when it feels easy.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmex_apotheosis_at_level_3", A,
            "A real practice now. Others notice your form. Stay humble — keep listening.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmex_apotheosis_at_level_4", A,
            "The highest tier. Recovery becomes the work. Be patient with the new pace.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmex_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmex_nudge_morning", A,
            "A gentle morning session, if you can. Mobility first. The day softens after.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmex_nudge_afternoon_zero", A,
            "Half the day's gone. Even fifteen minutes of movement is enough.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmex_nudge_evening", A,
            "Evening. A small session beats no session — be soft with the form.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
                DialogueLine("gmex_nudge_attention_loss", A,
            "Welcome back. Start at half — the body remembers more than you think.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmex_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
