package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Boundaries & voice. */
internal object GentleMentorBoundariesLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "BOUNDARIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmbo_first_ever", A,
            "Come in — saying no is a kind act, to yourself and to them, and we'll learn it slowly, one small refusal at a time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmbo_morning", A,
            "When the first ask of the day arrives, you're allowed a breath before answering — the pause is yours to take.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmbo_morning_early", A,
            "You're up before anyone can ask anything of you — a lovely moment to set your own agenda before the inbox sets it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmbo_afternoon", A,
            "That favor you're about to say yes to — sit with it a moment, and ask gently whether it's really yours to carry.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmbo_evening", A,
            "The work day is allowed to end now — phone down, email closed, and nothing terrible will happen. I promise.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmbo_night_late", A,
            "It's late, and anything asked at this hour can be answered kindly in the morning — sleep is a boundary too.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmbo_post_apotheosis", A,
            "That chapter is closed — just be a little careful not to celebrate by saying yes to the next thing you don't want.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmbo_monday", A,
            "Before the week starts asking, perhaps write down what it may have — a cap on the hours, one meeting-free day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmbo_friday", A,
            "The week is closing — the auto-reply can hold the door all weekend, and you're allowed to let it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmbo_weekend", A,
            "These two days are simply yours, and being unavailable needs no apology — it never did.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmbo_level_1_reached", A,
            "You said your first real no, and the world went on turning — take a moment to notice how gently it did.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmbo_level_2_reached", A,
            "Have you noticed the asks slowing down? People are learning what you'll carry — your steadiness is teaching them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmbo_level_3_reached", A,
            "You ask for what you want in plain words now — it would be a pity to drift back into hinting, so let's keep the clarity.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmbo_level_4_reached", A,
            "You hold your line even when it's leaned on — that's a quiet power, and you carry it kindly. I've watched you do it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmbo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmbo_attention_loss_mild", A,
            "A few days of yes-to-everything happens to everyone — one small, specific no today would set you gently right again.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmbo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmbo_attention_loss_hard", A,
            "I know the calendar has stopped looking like yours — we can begin taking it back with one cancellation, just one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmbo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("gmbo_mid_day_return", A,
            "There you are — if the day has already taken three yeses from you, the next ask can wait while you catch your breath.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmbo_wishes_pending", A,
            "There's a kindness saved up with your name on it — that half-day you keep postponing, perhaps. The line will hold.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmbo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmbo_mid_streak", A,
            "Three days of gentle, honest nos, and look — the calendar is starting to look like yours again. Let yourself notice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmbo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmbo_sant_jordi", A,
            "It's Sant Jordi, and the streets are full of roses — whatever work asks for half your day, today you may decline it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_la_merce", A,
            "La Mercè is a holiday, truly — if work texts, the auto-reply was set for exactly this, and you may trust it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_sant_joan", A,
            "If the Sant Joan table gets loud tonight, you're allowed to step outside with the fireworks and keep your peace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_diada", A,
            "The Diada is a day off, whole and entire — if the office knocks, the door can stay gently closed. That's the practice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_nadal", A,
            "Before the Nadal table, decide your no for the pushy relative — then you can say it kindly once, and let it rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_cap_d_any", A,
            "A new year — a soft moment to remember the yeses that hurt last time around, and to promise yourself fewer of them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmbo_reis", A,
            "Reis carries loud expectations — deciding beforehand what you'll give, and what you won't, lets you hold it gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_carnaval", A,
            "If the Carnaval plans aren't yours, you can say so warmly — they'll go without you, and everyone will be all right.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_divendres_sant", A,
            "The whole city has gone quiet today — let the silence be real, and don't offer it to the inbox. It's yours to keep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_pasqua", A,
            "Pasqua Monday is still a resting day — there's no need to “catch up” at midnight. Tomorrow will hold everything.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_festa_del_treball", A,
            "A day for honoring work — and your time was always the first boundary, so today, let it be honored too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_festa_major_gracia", A,
            "Gràcia will sing until four every night this week — no need to argue with it. Earplugs, a closed window, your sleep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_assumpcio", A,
            "August is for being truly away — the out-of-office means what it says, and peeking would only unteach everyone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_hispanitat", A,
            "A day off, and if a favor comes asking anyway, you're allowed to say the day is already spoken for — by you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_castanyada", A,
            "If hosting the Castanyada isn't in you this year, saying so early is the kind version — then go enjoy the chestnuts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_constitucio", A,
            "A bridge weekend — and when “just one meeting” comes asking, the bridge is allowed to stay a bridge, whole.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_immaculada", A,
            "Five soft days ahead — the auto-reply is on, the team can carry it, and sneaking a look would only wake it all up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_sant_esteve", A,
            "If the family wants more of you today than you have to give, a slow walk is a lovely no — come back when you're ready.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_cap_d_any_eve", A,
            "The year's last night carries its own expectations — decide the evening you actually want, and let that be the plan.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmbo_birthday", A,
            "Happy birthday — the work call will survive being declined, and this day was always meant to be entirely yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmbo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_personal_date", A,
            "Today is {label}, and the day is already spoken for — every other ask can be gently told to wait its turn.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmbo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmbo_complete_1", A, "You said it, and you held it — quietly done, and quite enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmbo_complete_2", A, "It's said — and it doesn't need softening afterwards, or a second explanation. Once was whole.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmbo_complete_3", A, "That's done now, and no apology needs drafting — you can simply carry on with your day.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmbo_complete_first_today", A,
            "Your first clean no of the day — and just like that, the day belongs a little more to you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmbo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmbo_complete_second_today", A,
            "Two boundaries held, and both with a steady voice — calm and firm is exactly the register. Keep it warm.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmbo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmbo_complete_third_today", A,
            "Three held now — the day has walls and a garden inside them, and you're allowed to sit in it a while.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmbo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmbo_complete_fourth_today", A,
            "Four in a day — either the day truly asked that much of you, or something is bristling. Worth a gentle, honest look.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmbo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmbo_complete_fifth_today", A,
            "Five is enough for one day — boundaries are a garden fence, not a war. Let the evening be soft now.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmbo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmbo_complete_after_streak", A,
            "Three clean days, and the asks are already slowing — people learn quickly when you're kind and consistent about it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmbo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmbo_apotheosis_1", A,
            "The chapter closes, and the line holds — it will still ask for small daily decisions, and you're ready for them.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmbo_apotheosis_2", A,
            "The cycle is done and the calendar is yours again — be gentle about gifting it back to the next insistent ask.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmbo_apotheosis_3", A,
            "Closed, and your voice came out clearer for it — keep using it, gently and often, so it stays yours.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmbo_apotheosis_first_ever", A,
            "Your first real stretch of holding the line — people already treat you differently, and you did it without hardness.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmbo_apotheosis_1", "gmbo_apotheosis_2", "gmbo_apotheosis_3"),
            theme = T),
        DialogueLine("gmbo_apotheosis_at_level_2", A,
            "You can say no in five calm seconds now — that steadiness under pressure is worth tending like a small fire.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmbo_apotheosis_at_level_3", A,
            "People come to you now for advice on holding their own lines — give it the way you learned it, specific and honest.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmbo_apotheosis_at_level_4", A,
            "Your voice doesn't shake anymore — guard that gently, and never apologize for using it. It took years to grow.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmbo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmbo_nudge_morning", A,
            "Before the day's first ask gets its answer, you're allowed one unhurried breath — the pause is yours.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmbo_nudge_afternoon_zero", A,
            "Just a soft check-in — if today has already taken three yeses from you, the next ask can meet a gentle push back.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmbo_nudge_evening", A,
            "The work day can end now — email closed, phone quiet, and nothing tonight needs to be the exception.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmbo_nudge_attention_loss", A,
            "We can begin taking the calendar back today — one honest cancellation, no invented reasons needed.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmbo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
