package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Gentle Mentor × Family & kin. */
internal object GentleMentorFamilyLines {

    private const val A = "GENTLE_MENTOR"
    private const val T = "FAMILY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("gmfa_first_ever", A,
            "Family is slow weather — we call, we visit, we show up, kindly, over time. Come in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("gmfa_morning", A,
            "Maybe text your mother this morning — a real sentence, not just a heart emoji.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "gmfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfa_morning_early", A,
            "You're up before most — the old folks are awake too. A five-minute call, and they'll carry it all day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "gmfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfa_afternoon", A,
            "That cousin you've been meaning to text — maybe now's the moment, before it turns into an hour of drafting.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "gmfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfa_evening", A,
            "A call before bed tonight, even ten minutes — they'll sleep a little better with it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "gmfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfa_night_late", A,
            "It's late — maybe not the moment to call. Just note who, and reach out tomorrow, kindly.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "gmfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("gmfa_post_apotheosis", A,
            "That stretch is closed now — the weekly call can stay standing time, a soft, steady discipline.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("gmfa_monday", A,
            "The week is opening — maybe pencil in the weekly call, same time as always. Worth not skipping.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "gmfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmfa_friday", A,
            "They'll likely ask what you did this week — maybe have a real answer ready, not just 'work'.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "gmfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("gmfa_weekend", A,
            "Sunday lunch is its own quiet discipline — showing up matters more than you'd think. They notice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "gmfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("gmfa_level_1_reached", A,
            "That first real call in a while, and here's the first level — they'll probably mention it. Receive it kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "gmfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmfa_level_2_reached", A,
            "A second level, and the weekly call is a real thing now — they count on it, so try not to break the rhythm.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "gmfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmfa_level_3_reached", A,
            "A third level — the whole family knows you show up now. Keep earning that, one week at a time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "gmfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("gmfa_level_4_reached", A,
            "The top level — you're the one who shows up, now. Defend that quietly, it means more than it looks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "gmfa_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("gmfa_attention_loss_mild", A,
            "Three weeks of silence now, and they've noticed — maybe just call today, no apology needed, just showing up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "gmfa_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("gmfa_attention_loss_hard", A,
            "Months gone quiet now — skip the drafted explanation, just call. Today, if you can.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmfa_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("gmfa_mid_day_return", A,
            "Nobody's been reached today yet — the call won't make itself, but it could still happen, gently, now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("gmfa_wishes_pending", A,
            "A reward's been sitting there — maybe spend it driving over to visit. It won't happen on its own.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "gmfa_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("gmfa_mid_streak", A,
            "Three weeks of steady contact now — they feel it, even if it's never said out loud. Quiet maintenance, that's all this is.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmfa_streak", cooldownPicks = 5, theme = T),

        DialogueLine("gmfa_sant_jordi", A,
            "Sant Jordi might be the day to drop a book at your mother's, in person, not shipped.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_la_merce", A,
            "Family's likely at the Mercè parade — maybe stand with them in the crowd rather than catching up after.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_sant_joan", A,
            "A family beach gathering for Sant Joan — bring something to share, and stay through the fireworks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_diada", A,
            "A day off for Diada — maybe a long call this time, not the quick one. They have time today too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_nadal", A,
            "The table is the whole point of Nadal — be there for it, phone left in the bag.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_cap_d_any", A,
            "A new year opening — maybe the first call goes to the one you kept putting off in December.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmfa_reis", A,
            "The kids, and Reis — maybe show up with the gift yourself, in person, not delivered.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_carnaval", A,
            "Kids in costume for Carnaval — be the uncle or aunt who actually shows up to see it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_divendres_sant", A,
            "The whole city's gone quiet today — maybe a long call to the one who's hard to reach. Today might be the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_pasqua", A,
            "Family mona for Pasqua Monday — go, eat more than you meant to, hug the niece.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_festa_del_treball", A,
            "A day set aside for workers, and family lunch too — be at the table, and help clean up after.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_festa_major_gracia", A,
            "Gràcia this week — maybe take the niece along. The festival's really more for them than for you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_assumpcio", A,
            "Family's likely at the pueblo this August — even one day's visit counts for something with them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_hispanitat", A,
            "A day off today — maybe drive over instead of texting that you're busy. Just show up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_castanyada", A,
            "Maybe bring chestnuts to your mother for Castanyada, and sit with her an hour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_constitucio", A,
            "A bridge weekend ahead — if there's a family gathering, go. No need to fake a meeting to skip it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_immaculada", A,
            "Five days ahead with this pont — maybe two at the family place, real time, phone off.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_sant_esteve", A,
            "The day after Nadal, family's still gathered — maybe stay a while longer instead of slipping out early.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_cap_d_any_eve", A,
            "The year's last day — the twelve grapes go better with them, not alone on the couch.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "gmfa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("gmfa_birthday", A,
            "Happy birthday — maybe call your mother today. She brought you here, after all.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "gmfa_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_personal_date", A,
            "Today is {label} — family knows what this means. Maybe bring them into it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "gmfa_personal", cooldownPicks = 1, theme = T),

        DialogueLine("gmfa_complete_1", A, "Called, and lovely.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmfa_complete_2", A, "Done — they felt it, even if they don't say so. No need to ask.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmfa_complete_3", A, "Good. Phone away now — no need to broadcast it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("gmfa_complete_first_today", A,
            "That first call, and the day's already better than zero — no need to stop there, though.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "gmfa_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmfa_complete_second_today", A,
            "Two reaches now — no need to spam beyond that. Quality over frequency, always.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "gmfa_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmfa_complete_third_today", A,
            "Three now — either a big family day, or maybe a little overcompensating. Be honest with yourself, kindly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "gmfa_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmfa_complete_fourth_today", A,
            "Four already — let them breathe a little, they have lives of their own too.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "gmfa_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("gmfa_complete_fifth_today", A,
            "Five now, and that starts to feel like hovering — step back. Consistency matters more than quantity.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "gmfa_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("gmfa_complete_after_streak", A,
            "Three weeks of showing up now — they count on you for it, and that's a real thing to have built.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "gmfa_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("gmfa_apotheosis_1", A,
            "That stretch is closed — let the weekly call stay standing time. No need to go quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmfa_apotheosis_2", A,
            "Another cycle done — the reputation's built now, just keep tending it, weekly.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmfa_apotheosis_3", A,
            "Closed, and well. Maybe pencil the next visit somewhere real, on the calendar.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("gmfa_apotheosis_first_ever", A,
            "Your first real stretch of being present — they told someone about it, I'd bet, kindly.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("gmfa_apotheosis_1", "gmfa_apotheosis_2", "gmfa_apotheosis_3"),
            theme = T),
        DialogueLine("gmfa_apotheosis_at_level_2", A,
            "A second level, and the weekly call is something close to sacred now — worth protecting from a meeting.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "gmfa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmfa_apotheosis_at_level_3", A,
            "A senior tier now — you're the one who shows up. Defend that title, but gently.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "gmfa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("gmfa_apotheosis_at_level_4", A,
            "The top tier — the family lives differently because of you now. Just try not to slip.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "gmfa_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("gmfa_nudge_morning", A,
            "Maybe text your mother this morning, a real sentence, not just 'morning, love'.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "gmfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmfa_nudge_afternoon_zero", A,
            "Nobody's been reached yet today — even a five-minute call now would be enough.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "gmfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmfa_nudge_evening", A,
            "A short, real call before bed tonight — they'll sleep a little better with it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "gmfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("gmfa_nudge_attention_loss", A,
            "Months gone quiet now — maybe just call today. No draft needed, no explanation.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "gmfa_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
