package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Hermit × Family — quiet stance, the old kin-room. */
internal object HermitFamilyLines {

    private const val A = "HERMIT"
    private const val T = "FAMILY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("hefa_first_ever", A,
            "The old room. Family is its own quiet kind. One small reaching today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("hefa_morning", A,
            "A short voice-note to one of them, this early. Without performance.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "hefa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefa_morning_early", A,
            "They are up too, perhaps, at this hour. A small hello. Nothing more.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "hefa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefa_afternoon", A,
            "The day has turned. A quiet check-in to a parent, a sibling. Five minutes is enough.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "hefa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefa_evening", A,
            "Lamp lit. A real call, phone in hand — the world quieter for it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "hefa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefa_night_late", A,
            "Owl hours. A voice-note — they'll wake to it. A small kindness in the morning.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "hefa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefa_post_apotheosis", A,
            "A passage. The kin-room held it. Sit a while.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("hefa_monday", A,
            "New week, says the calendar. A small ask to a parent — how was Sunday. Small thread.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "hefa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hefa_friday", A,
            "The week loosens its grip about now. The week's call, perhaps. Or a weekend lunch.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "hefa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hefa_weekend", A,
            "No bells today. A long call, slowly. Or a short one. Both belong.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "hefa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("hefa_level_1_reached", A,
            "Quiet tending of the kin-room. They have noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "hefa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefa_level_2_reached", A,
            "The kin-room has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "hefa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefa_level_3_reached", A,
            "You return. Hard talks land softer. Old rooms remember.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "hefa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefa_level_4_reached", A,
            "Old company. Family is a long slow room you have learned to sit in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "hefa_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("hefa_attention_loss_mild", A,
            "A few quiet days from them. A short voice-note today. No more is asked.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "hefa_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("hefa_attention_loss_hard", A,
            "A long silence. The kin-room is patient. One call today, briefly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hefa_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("hefa_wishes_pending", A,
            "There is a kindness on the shelf. A visit, a long letter, a slow weekend with the old folks.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "hefa_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("hefa_mid_streak", A,
            "Three days of small contact. The kin-room is warmer.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hefa_streak", cooldownPicks = 5, theme = T),

        DialogueLine("hefa_sant_jordi", A,
            "Roses in the stalls today. Drop a book at the parents', without ceremony. Sit if they offer tea.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_la_merce", A,
            "Drums down the hill for La Mercè. Bring them along, if they want. Or send a photo.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_sant_joan", A,
            "Firecrackers tonight for Sant Joan. The old kitchen has coca, perhaps. A small visit, then the fire.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_diada", A,
            "Flags out for the Diada. A family lunch, slowly. The old food. The old talk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_nadal", A,
            "Nadal. The table, the people, the long meal. Sit through it. Don't hurry.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_cap_d_any", A,
            "The calendar turns to a new year. Call the older ones first. Old play, kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hefa_reis", A,
            "The kin-room loud with kids and paper — Reis morning. Sit in a corner, briefly. Watch.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_carnaval", A,
            "Costumes on the kids today, Carnaval. Send a small photo to the older ones, if there are any.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_divendres_sant", A,
            "A quiet day. A long call to a parent, perhaps. Slowly. Without summary.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_pasqua", A,
            "The mona out on the family table, Pasqua. Sit at it, briefly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_festa_del_treball", A,
            "A rest day. A slow lunch with them, if they're near. Otherwise a long call.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_festa_major_gracia", A,
            "Paper skies over Gràcia this week. Bring the kids; bring the old ones. The streets hold both.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_assumpcio", A,
            "August hush. Family's by the sea, or in the village. Call them slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_hispanitat", A,
            "A day off. A visit to a relative, brief and warm.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_castanyada", A,
            "Chestnut smoke outside, Castanyada. Sit at the family table. Eat slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_constitucio", A,
            "A pause. A visit to the family town, if it's near. Otherwise a slow call.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_immaculada", A,
            "The December pont, a whole quiet day open. With kin, or a long letter. Both belong.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_sant_esteve", A,
            "The day after. A slow second meal with them. Less talk than yesterday. That is fine.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_cap_d_any_eve", A,
            "The year closes. Call the old folks before the night begins. Old play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "hefa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hefa_birthday", A,
            "Your day. Call those who knew you small. They will hold it for you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "hefa_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_personal_date", A,
            "You marked today: {label}. Hold the kin-room in mind. One small reaching, in its honour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "hefa_personal", cooldownPicks = 1, theme = T),

        DialogueLine("hefa_complete_1", A, "Reached. The kin-room is gentler.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefa_complete_2", A, "A small call. Enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefa_complete_3", A, "Done. The line is quiet now.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefa_complete_first_today", A,
            "First reaching. They will hold it all day.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "hefa_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefa_complete_second_today", A,
            "Twice. The kin-room is being kept.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "hefa_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefa_complete_third_today", A,
            "Three small reachings. The day is held.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "hefa_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefa_complete_fourth_today", A,
            "A fourth. More than the day asked. Sit a while.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "hefa_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefa_complete_fifth_today", A,
            "Five. Put the phone down. Be in the room you're in.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "hefa_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("hefa_complete_after_streak", A,
            "Three days of small contact. The kin-room is warmer.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hefa_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("hefa_apotheosis_1", A,
            "A passage. The kin-room held it. Quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefa_apotheosis_2", A,
            "Closed. The next small contact will come when it comes.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefa_apotheosis_3", A,
            "Done. Sit a while.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefa_apotheosis_first_ever", A,
            "Your first. The kin-room and you have a small new history. I'll keep its quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("hefa_apotheosis_1", "hefa_apotheosis_2", "hefa_apotheosis_3"),
            theme = T),
        DialogueLine("hefa_apotheosis_at_level_2", A,
            "A second passage. The kin-room has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "hefa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hefa_apotheosis_at_level_3", A,
            "A third. Hard talks land softer now.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "hefa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hefa_apotheosis_at_level_4", A,
            "Old company. The kin-room is a long slow place you have learned to sit in.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "hefa_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("hefa_nudge_morning", A,
            "A short voice-note to one of them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "hefa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefa_nudge_afternoon_zero", A,
            "A quiet check-in. Five minutes is enough.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "hefa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefa_nudge_evening", A,
            "A real call. Phone in hand. World quieter for it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "hefa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefa_nudge_attention_loss", A,
            "The kin-room has waited. One call today, briefly.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hefa_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
