package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Hermit × Nutrition — quiet stance, food as small ritual. */
internal object HermitNutritionLines {

    private const val A = "HERMIT"
    private const val T = "NUTRITION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("henu_first_ever", A,
            "The kitchen, too, is a room. We tend it slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("henu_morning", A,
            "Morning. The first food of the day. Choose it with care.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "henu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("henu_morning_early", A,
            "Early. Something warm. The body wakes to it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "henu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("henu_afternoon", A,
            "Afternoon. A small meal. Sit while you eat it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "henu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("henu_evening", A,
            "Evening. A slow dinner. Lamp on, plate down, no rush.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "henu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("henu_night_late", A,
            "Late. Nothing heavy. A small piece of fruit, perhaps.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "henu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("henu_post_apotheosis", A,
            "A passage. The kitchen tended it. Quiet now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("henu_monday", A,
            "A week begins. A small plan for meals, no more.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "henu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("henu_friday", A,
            "Friday. The week's food has been the week's food. Notice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "henu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("henu_weekend", A,
            "Weekend. A long meal, or a small one. Both are welcome.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "henu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("henu_level_1_reached", A,
            "Quiet meals for a stretch. The kitchen has noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "henu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("henu_level_2_reached", A,
            "The plate has changed shape. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "henu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("henu_level_3_reached", A,
            "You return. The kitchen knows your hand.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "henu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("henu_level_4_reached", A,
            "Old company. Food is no longer a problem to solve.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "henu_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("henu_attention_loss_mild", A,
            "A few skipped meals. The kitchen is still here. Eat something small.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "henu_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("henu_attention_loss_hard", A,
            "A long disorder. Begin with the simplest thing. A piece of bread is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "henu_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("henu_wishes_pending", A,
            "There is a kindness on the shelf. A long market walk, a slow meal alone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "henu_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("henu_mid_streak", A,
            "Three meals tended in a row. The body is grateful, in its way.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "henu_streak", cooldownPicks = 5, theme = T),

        DialogueLine("henu_sant_jordi", A,
            "Sant Jordi. A book and a small lunch. The city moves outside.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_la_merce", A,
            "Mercè. Street food is offered. Choose one and sit somewhere quiet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_sant_joan", A,
            "Sant Joan. Coca and water. Old food for an old night.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_diada", A,
            "Diada. A slow lunch. The day is for tasting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_nadal", A,
            "Nadal. The meal is long. Eat slowly. Leave the second helping.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_cap_d_any", A,
            "New year. The first meal of the year. Small and warm.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("henu_reis", A,
            "Reis. The tortell is here. One slice, then put it away.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_carnaval", A,
            "Carnaval. The food is excess. Taste a little. The plate is yours to set down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_divendres_sant", A,
            "A quiet day. A simple meal. The city is also at table-rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_pasqua", A,
            "Pasqua. The mona is on the table. One piece. Then the walk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_festa_del_treball", A,
            "A rest day. A long slow meal fits. No hurry to the dishes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_festa_major_gracia", A,
            "Gràcia. Neighbours bring food to the street. Take a little, give a thanks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_assumpcio", A,
            "August. Fruit is heavy and ready. Eat it slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_hispanitat", A,
            "A day off. A slow breakfast. The afternoon will arrange itself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_castanyada", A,
            "Castanyada. Chestnuts, panellets, sweet potato. Warm food for a long dark.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_constitucio", A,
            "A pause. A slow meal. The day allows tasting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_immaculada", A,
            "Pont. Soup and bread, perhaps. The hours hold the meal gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_sant_esteve", A,
            "Day after. The cannelloni are warmed again. Small portion. Old play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_cap_d_any_eve", A,
            "The year closes. The grapes are on the table. Slowly, one by one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "henu_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("henu_birthday", A,
            "Your day. A meal you would have chosen for yourself. Sit while you eat it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "henu_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("henu_personal_date", A,
            "You marked today: {label}. A small meal in its honour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "henu_personal", cooldownPicks = 1, theme = T),

        DialogueLine("henu_complete_1", A, "Eaten. Slowly, I hope.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("henu_complete_2", A, "A small meal. Enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("henu_complete_3", A, "Done. The plate is quiet.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("henu_complete_first_today", A,
            "First food. The body softens.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "henu_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("henu_complete_second_today", A,
            "Twice. The body is being minded.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "henu_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("henu_complete_third_today", A,
            "Three meals. The day is held.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "henu_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("henu_complete_fourth_today", A,
            "A fourth. More than the room asked. Rest the plate.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "henu_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("henu_complete_fifth_today", A,
            "Five. The kitchen has done its work. Sit. Tea, perhaps.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "henu_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("henu_complete_after_streak", A,
            "Three days of small meals tended. The pattern has begun.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "henu_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("henu_apotheosis_1", A,
            "A passage. The kitchen tended it. Quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("henu_apotheosis_2", A,
            "Closed. The shelf still holds what it holds.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("henu_apotheosis_3", A,
            "Done. Sit while the dishes wait.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("henu_apotheosis_first_ever", A,
            "Your first. A small steady meal-week. I'll keep its quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("henu_apotheosis_1", "henu_apotheosis_2", "henu_apotheosis_3"),
            theme = T),
        DialogueLine("henu_apotheosis_at_level_2", A,
            "A second passage. The plate has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "henu_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("henu_apotheosis_at_level_3", A,
            "A third. Food is no longer asking for thought.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "henu_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("henu_apotheosis_at_level_4", A,
            "Old company. The kitchen and you are kin.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "henu_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("henu_nudge_morning", A,
            "Something warm to start the body. No more.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "henu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("henu_nudge_afternoon_zero", A,
            "A small meal. Sit while you eat it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "henu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("henu_nudge_evening", A,
            "A slow dinner. Lamp on, plate down.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "henu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("henu_nudge_attention_loss", A,
            "The kitchen has waited. A piece of bread. Begin there.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "henu_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
