package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Hermit × Outdoors — quiet stance, the door opens to a slow walk. */
internal object HermitOutdoorsLines {

    private const val A = "HERMIT"
    private const val T = "OUTDOORS"

    val all: List<DialogueLine> = listOf(

        DialogueLine("heou_first_ever", A,
            "The door opens. Ten minutes outside is enough today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("heou_morning", A,
            "Light on the sill. The first air of the day. Stand in it a moment.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "heou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("heou_morning_early", A,
            "Even the birds are still deciding. The light is slow. Walk the block before screens.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "heou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("heou_afternoon", A,
            "The sun has moved to the other window. A short walk. No phone, no plan.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "heou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("heou_evening", A,
            "The dusk walk calls now. Light low. Streets gentler.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "heou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("heou_night_late", A,
            "Owl hours. Five minutes on the balcony. The sky counts. Then sleep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "heou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("heou_post_apotheosis", A,
            "A passage. The path held it. Sit a while when you return.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("heou_monday", A,
            "New week, says the calendar. Pick one outdoor block. Defend it gently.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "heou_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("heou_friday", A,
            "The week loosens its grip about now. Plan a slow weekend trail. Or just a long walk.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "heou_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("heou_weekend", A,
            "No bells today. A long quiet walk. The day is patient.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "heou_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("heou_level_1_reached", A,
            "Quiet walks for a stretch. The path has noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "heou_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("heou_level_2_reached", A,
            "The body has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "heou_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("heou_level_3_reached", A,
            "You return. The outside is a room you keep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "heou_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("heou_level_4_reached", A,
            "Old company. The outside and the inside are no longer distinct.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "heou_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("heou_attention_loss_mild", A,
            "A few quiet days inside. The path is patient. A short walk today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "heou_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("heou_attention_loss_hard", A,
            "A long absence from outside. The body is patient. Ten minutes today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "heou_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("heou_wishes_pending", A,
            "There is a kindness on the shelf. A trail trip, new shoes, a slow mountain morning.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "heou_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("heou_mid_streak", A,
            "Three days outside. The body knows the route.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "heou_streak", cooldownPicks = 5, theme = T),

        DialogueLine("heou_sant_jordi", A,
            "Sant Jordi. Walk slowly through the stalls. Or around them. The city is full.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_la_merce", A,
            "Mercè. The streets are loud. A short loop through is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_sant_joan", A,
            "Sant Joan. The beach, or the balcony. Both meet the night.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_diada", A,
            "Diada. A slow walk in the park. The afternoon is wide.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_nadal", A,
            "Nadal. The post-meal walk. Old play, kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_cap_d_any", A,
            "New year. The first walk of the year. Small, kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("heou_reis", A,
            "Reis. A short cold walk after gifts. The air is itself a gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_carnaval", A,
            "Carnaval. Walk briefly through the costume-streets. Then home, quiet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_divendres_sant", A,
            "A quiet day. A long unhurried walk. The empty streets receive you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_pasqua", A,
            "Pasqua. A trail, or a long park loop. The body asks for both.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_festa_del_treball", A,
            "A rest day. A long park morning. The bench. The trees.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_festa_major_gracia", A,
            "Gràcia. Walk the decorated streets slowly. Eyes up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_assumpcio", A,
            "August. The empty city in the early morning. The streets are gentler.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_hispanitat", A,
            "A day off. A long park afternoon. Bench. Book. Sky.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_castanyada", A,
            "Castanyada. A crisp walk before dark. Gloves. Coat. Slow steps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_constitucio", A,
            "A pause. A slow walk somewhere new. Or somewhere familiar. Both work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_immaculada", A,
            "Pont. A long hike or a long park sit. The hours are patient.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_sant_esteve", A,
            "Day after. A slow walk to clear the meal. Old play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_cap_d_any_eve", A,
            "The year closes. A long quiet walk in the cold. The year falls away.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "heou_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("heou_birthday", A,
            "Your day. A long slow walk somewhere new. Or somewhere old. Both belong.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "heou_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("heou_personal_date", A,
            "You marked today: {label}. A walk somewhere meaningful, in its honour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "heou_personal", cooldownPicks = 1, theme = T),

        DialogueLine("heou_complete_1", A, "Walked. The room is gentler when you return.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("heou_complete_2", A, "A small loop. Enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("heou_complete_3", A, "Done. Sit a while.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("heou_complete_first_today", A,
            "First time outside. The lungs widen.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "heou_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("heou_complete_second_today", A,
            "Twice outside. The body softens.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "heou_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("heou_complete_third_today", A,
            "Three. The path has held its share.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "heou_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("heou_complete_fourth_today", A,
            "A fourth. More than asked. Sit. Tea.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "heou_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("heou_complete_fifth_today", A,
            "Five. Stay in for the rest of it. The room remembers you.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "heou_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("heou_complete_after_streak", A,
            "Three days outside. The body knows the route now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "heou_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("heou_apotheosis_1", A,
            "A passage. The path held it. Quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("heou_apotheosis_2", A,
            "Closed. The next walk will come when it comes.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("heou_apotheosis_3", A,
            "Done. Tea. Lamp.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("heou_apotheosis_first_ever", A,
            "Your first. The path and you have a small history now. I'll keep its quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("heou_apotheosis_1", "heou_apotheosis_2", "heou_apotheosis_3"),
            theme = T),
        DialogueLine("heou_apotheosis_at_level_2", A,
            "A second passage. The body has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "heou_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("heou_apotheosis_at_level_3", A,
            "A third. The outside is a room you keep.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "heou_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("heou_apotheosis_at_level_4", A,
            "Old company. The outside and the inside are no longer distinct.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "heou_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("heou_nudge_morning", A,
            "Stand in the first air a moment.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "heou_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("heou_nudge_afternoon_zero", A,
            "A short walk. No phone. No plan.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "heou_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("heou_nudge_evening", A,
            "The dusk walk. Light low. Streets gentler.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "heou_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("heou_nudge_attention_loss", A,
            "The path has waited. Ten minutes today.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "heou_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
