package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Hermit × Boundaries — quiet stance, the door has a latch. */
internal object HermitBoundariesLines {

    private const val A = "HERMIT"
    private const val T = "BOUNDARIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("hebo_first_ever", A,
            "The door has a latch. We use it gently. One quiet no today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("hebo_morning", A,
            "The day starts asking early. Decide quietly which yeses are real.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "hebo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hebo_morning_early", A,
            "The birds are still deciding. Don't promise yet — the morning hasn't seen the day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "hebo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hebo_afternoon", A,
            "The sun has moved along. One small no, slowly. The door has a latch.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "hebo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hebo_evening", A,
            "Lamp lit. One last no, to keep tomorrow yours. No ceremony in it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "hebo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hebo_night_late", A,
            "Owl hours. No new yeses now. The mind is bad at limits past ten.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "hebo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hebo_post_apotheosis", A,
            "A passage. The latch held it. Sit a while behind it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("hebo_monday", A,
            "The calendar clears its throat. Pick your nos before the week picks them for you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "hebo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hebo_friday", A,
            "The week loosens its grip. Notice where the line moved. No scoring.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "hebo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hebo_weekend", A,
            "No bells today. The bad-fit invitation can go unanswered. The room knows what to do with you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "hebo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("hebo_level_1_reached", A,
            "Quiet nos for a stretch. The latch has noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "hebo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hebo_level_2_reached", A,
            "The line is firmer. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "hebo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hebo_level_3_reached", A,
            "You return. The nos come without apology now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "hebo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hebo_level_4_reached", A,
            "Old company. The latch is part of the room now. People know.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "hebo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("hebo_attention_loss_mild", A,
            "A few drift-days. The latch is patient. One clean small no today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "hebo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("hebo_attention_loss_hard", A,
            "A long over-yes. The room has held the place. One clean no today, slowly. Without apology.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hebo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("hebo_wishes_pending", A,
            "There is a kindness on the shelf. A slow no to a chronic ask. A latch on a new door.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "hebo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("hebo_mid_streak", A,
            "Three days of small clean nos. The slate is lighter.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hebo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("hebo_sant_jordi", A,
            "Sant Jordi. Decline the work-event quietly. Walk the city instead.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_la_merce", A,
            "Mercè. Pick one show. Decline the rest. The lungs are finite.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_sant_joan", A,
            "Sant Joan. Pick one party. Decline the rest. The night will keep itself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_diada", A,
            "Diada. Decline the obligation lunch. Pick the people you actually want.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_nadal", A,
            "Nadal. If a kin-line is needed, keep it quiet and short. Winter carries the rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_cap_d_any", A,
            "A new year outside, they say. Name what you're done carrying. Set it down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hebo_reis", A,
            "Reis. Decline the gift-swap that doesn't fit. Opt out gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_carnaval", A,
            "Carnaval. No to the costume you don't want. Wear what feels true. Or stay in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_divendres_sant", A,
            "The city holds its breath today. Decline the noise, decline the plans. The day is yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_pasqua", A,
            "Pasqua. Decline the second-tier hike. One trail is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_festa_del_treball", A,
            "Tools down across the whole city. No work — a hard, quiet line. The body asked for this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_festa_major_gracia", A,
            "Gràcia. Decline the over-planned day. Walk slowly, leave when you wish.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_assumpcio", A,
            "August. Decline the work that creeps in. The slow city allows it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_hispanitat", A,
            "Flags arguing somewhere outside. No shop-talk, no screens in here. The day belongs to the room.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_castanyada", A,
            "Castanyada. Small circle. Decline the large gathering. Warm food, candles, the few.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_constitucio", A,
            "A civic pause, says the calendar. Decline the obligation trip. Go where you want, or stay.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_immaculada", A,
            "Pont. Decline the hidden admin. Slow days aren't for that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_sant_esteve", A,
            "Day after. Decline the second-round family. Rest. The kin-room understands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_cap_d_any_eve", A,
            "The year closes. Name three things you are leaving in it. Close them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "hebo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hebo_birthday", A,
            "Your day. Spend it your way. Decline the obligations, kindly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "hebo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_personal_date", A,
            "You marked today: {label}. One clean no in its honour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "hebo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("hebo_complete_1", A, "Held. The latch is gentler than you feared.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hebo_complete_2", A, "A small no. Enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hebo_complete_3", A, "Done. The door is shut. The room is yours.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hebo_complete_first_today", A,
            "First clean line. The day is lighter for it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "hebo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("hebo_complete_second_today", A,
            "Twice. The line is being kept.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "hebo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("hebo_complete_third_today", A,
            "Three small holdings. The slate is clearer.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "hebo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("hebo_complete_fourth_today", A,
            "A fourth. Notice if you're hiding behind the latch. Latches close both ways.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "hebo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("hebo_complete_fifth_today", A,
            "Five. Open the latch for the one yes that matters. The line exists to make yeses real.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "hebo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("hebo_complete_after_streak", A,
            "Three days of clean lines. The room is your own again.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hebo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("hebo_apotheosis_1", A,
            "A passage. The latch held it. Quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hebo_apotheosis_2", A,
            "Closed. The next small no will come when it comes.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hebo_apotheosis_3", A,
            "Done. Sit behind the latch.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hebo_apotheosis_first_ever", A,
            "Your first. The latch and you have a small history now. I'll keep its quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("hebo_apotheosis_1", "hebo_apotheosis_2", "hebo_apotheosis_3"),
            theme = T),
        DialogueLine("hebo_apotheosis_at_level_2", A,
            "A second passage. The line is firmer. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "hebo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hebo_apotheosis_at_level_3", A,
            "A third. The nos come without apology now.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "hebo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hebo_apotheosis_at_level_4", A,
            "Old company. The latch is part of the room. People know.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "hebo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("hebo_nudge_morning", A,
            "Notice what is being asked. Decide quietly which yeses are real.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "hebo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hebo_nudge_afternoon_zero", A,
            "One small no, slowly. The door has a latch.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "hebo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hebo_nudge_evening", A,
            "End-of-day no. Protect tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "hebo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hebo_nudge_attention_loss", A,
            "The latch has waited. One clean small no today. Without apology.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hebo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
