package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Hermit × Friendship — quiet stance, the far-room. */
internal object HermitFriendshipLines {

    private const val A = "HERMIT"
    private const val T = "FRIENDSHIP"

    val all: List<DialogueLine> = listOf(

        DialogueLine("hefr_first_ever", A,
            "Friends are far-rooms. We reach across slowly. One small reaching today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("hefr_morning", A,
            "Morning. One quiet voice-note to one friend. Without performance.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "hefr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefr_morning_early", A,
            "Early. They are up too, perhaps. A small hello to the one who rises with the dawn.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "hefr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefr_afternoon", A,
            "Afternoon. A small thought sent to one friend. Five lines, no more.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "hefr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefr_evening", A,
            "Evening. A real call to a far-friend. Slow, unrushed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "hefr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefr_night_late", A,
            "Late. A voice-note. They'll find it tomorrow. A small kindness in their morning.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "hefr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefr_post_apotheosis", A,
            "A passage. The far-room held it. Sit a while.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("hefr_monday", A,
            "A week begins. Pick one far-friend to reach across to this week.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "hefr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hefr_friday", A,
            "Friday. Notice who you have not spoken to. Without urgency. A small note will do.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "hefr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hefr_weekend", A,
            "Weekend. A long quiet hang with one friend. Or none. Both are tending.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "hefr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("hefr_level_1_reached", A,
            "Quiet reaching for a stretch. The far-rooms have noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "hefr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefr_level_2_reached", A,
            "The far-rooms have shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "hefr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefr_level_3_reached", A,
            "You return. People reach back without being asked now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "hefr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefr_level_4_reached", A,
            "Old company. The far-rooms are no longer far.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "hefr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("hefr_attention_loss_mild", A,
            "A few quiet days from the far-rooms. A small voice-note today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "hefr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("hefr_attention_loss_hard", A,
            "A long silence. The far-rooms are patient. One small message today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hefr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("hefr_wishes_pending", A,
            "There is a kindness on the shelf. A long letter, a slow dinner, a weekend for one good friend.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "hefr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("hefr_mid_streak", A,
            "Three days of small reachings. The far-rooms are warmer.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hefr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("hefr_sant_jordi", A,
            "Sant Jordi. Drop a book for a far-friend. Without ceremony.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_la_merce", A,
            "Mercè. Walk a quiet show with one friend. Then home.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_sant_joan", A,
            "Sant Joan. The fire is for the few. Stay with the one or two who matter most.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_diada", A,
            "Diada. A long slow lunch with one or two friends.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_nadal", A,
            "Nadal. A small message to the far-friend. Without performance.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_cap_d_any", A,
            "New year. One specific message to one specific friend. Old play, quiet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hefr_reis", A,
            "Reis. Send a small thing to a friend, without occasion-pressure. They will feel it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_carnaval", A,
            "Carnaval. Photos go quietly between friends today. Send one. Receive one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_divendres_sant", A,
            "A quiet day. A long unhurried call with the far-friend.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_pasqua", A,
            "Pasqua. A trail walk with one or two — the few who don't need conversation to be near.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_festa_del_treball", A,
            "A rest day. A slow brunch with one friend. Nothing planned after.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_festa_major_gracia", A,
            "Gràcia. A walk through the streets with one friend. Eyes up. Talk soft.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_assumpcio", A,
            "August. The far-rooms are scattered. A voice-note to each, slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_hispanitat", A,
            "A day off. Long brunch with one friend. Or none. Both are well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_castanyada", A,
            "Castanyada. A small fire-evening at home with one or two of them. Old play.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_constitucio", A,
            "A pause. A small trip with one or two friends, slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_immaculada", A,
            "Pont. A long unhurried dinner with the close few.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_sant_esteve", A,
            "Day after. A quiet coffee with one friend. Debrief gently. Or not.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_cap_d_any_eve", A,
            "The year closes. A long honest call with one close friend. The year between you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "hefr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hefr_birthday", A,
            "Your day. They will reach across. Receive it slowly. No need to perform.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "hefr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_personal_date", A,
            "You marked today: {label}. Reach across to one friend, in its honour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "hefr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("hefr_complete_1", A, "Reached. The far-room is gentler.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefr_complete_2", A, "A small note. Enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefr_complete_3", A, "Done. The line is quiet now.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefr_complete_first_today", A,
            "First reaching. They will hold it through the day.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "hefr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefr_complete_second_today", A,
            "Twice. The far-rooms are being kept.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "hefr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefr_complete_third_today", A,
            "Three small reachings. The day is held.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "hefr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefr_complete_fourth_today", A,
            "A fourth. More than the day asked. Notice if it's about avoidance.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "hefr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefr_complete_fifth_today", A,
            "Five. Put the phone down. Be in the room you're in.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "hefr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("hefr_complete_after_streak", A,
            "Three days of small reachings. The far-rooms are warmer.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hefr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("hefr_apotheosis_1", A,
            "A passage. The far-room held it. Quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefr_apotheosis_2", A,
            "Closed. The next small reaching will come when it comes.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefr_apotheosis_3", A,
            "Done. Sit a while.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefr_apotheosis_first_ever", A,
            "Your first. The far-rooms and you have a small new history. I'll keep its quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("hefr_apotheosis_1", "hefr_apotheosis_2", "hefr_apotheosis_3"),
            theme = T),
        DialogueLine("hefr_apotheosis_at_level_2", A,
            "A second passage. The far-rooms have shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "hefr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hefr_apotheosis_at_level_3", A,
            "A third. People reach back without being asked.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "hefr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hefr_apotheosis_at_level_4", A,
            "Old company. The far-rooms are no longer far.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "hefr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("hefr_nudge_morning", A,
            "One voice-note to one friend. Without performance.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "hefr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefr_nudge_afternoon_zero", A,
            "A small thought sent to one friend. Five lines, no more.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "hefr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefr_nudge_evening", A,
            "A real call to a far-friend. Slow, unrushed.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "hefr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefr_nudge_attention_loss", A,
            "The far-rooms have waited. One small message today.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hefr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
