package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Hermit × Sleep — quiet stance, the long dark as kin. */
internal object HermitSleepLines {

    private const val A = "HERMIT"
    private const val T = "SLEEP"

    val all: List<DialogueLine> = listOf(

        DialogueLine("hesl_first_ever", A,
            "The night, too, has rooms. We tend them slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("hesl_morning", A,
            "The night released you. Notice how, before you do anything.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "hesl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hesl_morning_early", A,
            "Even the birds are still deciding. The body has only just returned from sleep. Be gentle.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "hesl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hesl_afternoon", A,
            "The sun has moved to the other window. A short rest is also sleep, in its way.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "hesl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hesl_evening", A,
            "The lamps. The hour bending toward rest. Begin to soften.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "hesl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hesl_night_late", A,
            "Owl hours. The room is asking you to lie down.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "hesl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hesl_post_apotheosis", A,
            "A passage. The night will hold it for you. Sleep well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("hesl_monday", A,
            "New week, says the calendar. The first sleep sets the others. Tend to it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "hesl_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hesl_friday", A,
            "The week loosens its grip about now. It has used you. The night is patient.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "hesl_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hesl_weekend", A,
            "No bells today. Sleep when the body asks. The clock will keep itself.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "hesl_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("hesl_level_1_reached", A,
            "Quiet sleeps for a stretch. The body has noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "hesl_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hesl_level_2_reached", A,
            "The night has changed shape. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "hesl_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hesl_level_3_reached", A,
            "You return. The night has learned your hours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "hesl_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hesl_level_4_reached", A,
            "Old company. The night and the day are kin again.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "hesl_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("hesl_attention_loss_mild", A,
            "A few uneven nights. The bed will receive you again.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "hesl_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("hesl_attention_loss_hard", A,
            "A long disorder. The night is patient. Begin tonight, softly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hesl_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("hesl_wishes_pending", A,
            "There is a kindness on the shelf. A nap, a bath, a quieter blanket.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "hesl_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("hesl_mid_streak", A,
            "Three nights tended. The body feels it. Don't say it aloud.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hesl_streak", cooldownPicks = 5, theme = T),

        DialogueLine("hesl_sant_jordi", A,
            "Sant Jordi. The city is awake. The night will be later than usual. Honour it anyway.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_la_merce", A,
            "Mercè. The streets are loud. The bed remembers being still.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_sant_joan", A,
            "Sant Joan. Sleep when you can, not when the city does. Tomorrow allows the lie-in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_diada", A,
            "Diada. A slow morning, a longer rest. The day will keep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_nadal", A,
            "Nadal. The meal is long. Sleep will come heavy. Let it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_cap_d_any", A,
            "New year. The first night sets a small tone. Sleep when you can, softly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hesl_reis", A,
            "Reis. A long quiet evening. Sleep will arrive on its own.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_carnaval", A,
            "Carnaval. The streets are noise. The bed is still here, when you return.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_divendres_sant", A,
            "A quiet day. A long sleep fits. The city is also at rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_pasqua", A,
            "Pasqua. After the walk, the bed. Sleep heavy, sleep good.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_festa_del_treball", A,
            "A rest day. The body wanted it. Let it sleep in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_festa_major_gracia", A,
            "Gràcia. The neighbours are out late. The room will hold its quiet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_assumpcio", A,
            "August. The city half-asleep. Sleep is the season's only task.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_hispanitat", A,
            "A day off. The morning is yours. Stay in bed a while.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_castanyada", A,
            "Castanyada. The dark has lengthened. Sleep with it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_constitucio", A,
            "A pause. A long sleep, a slow morning. Both belong here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_immaculada", A,
            "Pont. Hours unhurried. Sleep finds itself when nothing pushes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_sant_esteve", A,
            "Day after. A late sleep. A slow waking. Both are the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_cap_d_any_eve", A,
            "The year closes. Tonight may be late. The first night of the next is yours to set.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "hesl_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hesl_birthday", A,
            "Your day. The night before holds the next year. Sleep softly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "hesl_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_personal_date", A,
            "You marked today: {label}. The night will carry it gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "hesl_personal", cooldownPicks = 1, theme = T),

        DialogueLine("hesl_complete_1", A, "Tended. Quiet now.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hesl_complete_2", A, "A small thing for the night. Enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hesl_complete_3", A, "Done. The lamps are lower.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hesl_complete_first_today", A,
            "First of the day. The night begins early, in a sense.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "hesl_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("hesl_complete_second_today", A,
            "Twice. The body knows you are minding it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "hesl_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("hesl_complete_third_today", A,
            "Three. The night will be calm. Likely.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "hesl_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("hesl_complete_fourth_today", A,
            "A fourth. More than the room asked. Rest, now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "hesl_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("hesl_complete_fifth_today", A,
            "Five. Lie down. There is no further task tonight.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "hesl_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("hesl_complete_after_streak", A,
            "Three nights in a row, tended. The bed knows you now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hesl_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("hesl_apotheosis_1", A,
            "A passage. The night has carried it. Quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hesl_apotheosis_2", A,
            "Closed. The bed waits.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hesl_apotheosis_3", A,
            "Done. Sleep on it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hesl_apotheosis_first_ever", A,
            "Your first. A small steady night. I'll keep its quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("hesl_apotheosis_1", "hesl_apotheosis_2", "hesl_apotheosis_3"),
            theme = T),
        DialogueLine("hesl_apotheosis_at_level_2", A,
            "A second passage. The night has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "hesl_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hesl_apotheosis_at_level_3", A,
            "A third. The hour you sleep is yours again.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "hesl_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hesl_apotheosis_at_level_4", A,
            "Old company. The night, the day, and you. Kin.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "hesl_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("hesl_nudge_morning", A,
            "Notice the night before doing. A breath, then the day.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "hesl_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hesl_nudge_afternoon_zero", A,
            "A short rest is also sleep. Close the door.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "hesl_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hesl_nudge_evening", A,
            "The lamps are lower. Begin softening.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "hesl_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hesl_nudge_attention_loss", A,
            "The bed has waited. Tonight, perhaps, you may answer.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hesl_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
