package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Hermit × Finances — quiet stance, money as another thing to be tended. */
internal object HermitFinancesLines {

    private const val A = "HERMIT"
    private const val T = "FINANCES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("hefi_first_ever", A,
            "Money is another thing to be tended. Begin small. The ledger waits.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("hefi_morning", A,
            "Morning. Open the ledger. Look gently. Close it again.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "hefi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefi_morning_early", A,
            "Early. The numbers are still asleep. Look briefly, then to other rooms.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "hefi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefi_afternoon", A,
            "Afternoon. One small reckoning. Then close the book.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "hefi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefi_evening", A,
            "Evening. The numbers settle. Note one, then put the lamp away.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "hefi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefi_night_late", A,
            "Late. The ledger is bad company at this hour. Close it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "hefi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hefi_post_apotheosis", A,
            "A passage. The ledger held it. Quiet now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("hefi_monday", A,
            "A week begins. One small note in the ledger. No more is asked today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "hefi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hefi_friday", A,
            "Friday. The week's small spending. Notice it, gently.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "hefi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hefi_weekend", A,
            "Weekend. A long slow reckoning, or none at all. Both belong.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "hefi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("hefi_level_1_reached", A,
            "Quiet tending of the ledger. The numbers have noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "hefi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefi_level_2_reached", A,
            "The ledger has changed shape. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "hefi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefi_level_3_reached", A,
            "You return. The numbers are no longer strangers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "hefi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hefi_level_4_reached", A,
            "Old company. Money is no longer something to be feared.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "hefi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("hefi_attention_loss_mild", A,
            "A few unchecked days. The ledger is patient. Open it gently.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "hefi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("hefi_attention_loss_hard", A,
            "A long avoidance. The numbers will be what they are. Look, slowly. Without judgement.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hefi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("hefi_wishes_pending", A,
            "There is a kindness on the shelf. A small gift to a future month.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "hefi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("hefi_mid_streak", A,
            "Three days the ledger has been opened. Less weight in the corner of the room.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hefi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("hefi_sant_jordi", A,
            "Sant Jordi. A book is a small spend. Note it, and let it be.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_la_merce", A,
            "Mercè. The city is free to walk. The ledger is light today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_sant_joan", A,
            "Sant Joan. Cava and bread are not large costs. Notice the small.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_diada", A,
            "Diada. The ledger can rest a day. So can you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_nadal", A,
            "Nadal. Gifts have been given. The ledger will be heavier. Be gentle reading it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_cap_d_any", A,
            "New year. One small intention with the ledger. No more.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hefi_reis", A,
            "Reis. The season's gifts are paid. The ledger will rest a little now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_carnaval", A,
            "Carnaval. Small spending on warmth and noise. Note it, and let it be.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_divendres_sant", A,
            "A quiet day. The ledger may be opened slowly, if at all.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_pasqua", A,
            "Pasqua. The trail costs nothing. Notice that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_festa_del_treball", A,
            "A rest day. The ledger rests too. Don't open it today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_festa_major_gracia", A,
            "Gràcia. Small drinks bought from neighbours. Cheap, well-spent.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_assumpcio", A,
            "August. The city is quiet, the spending is low. Notice the saving.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_hispanitat", A,
            "A day off. The ledger can wait. The day is for other rooms.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_castanyada", A,
            "Castanyada. Chestnuts and moscatel — small spendings, warm returns.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_constitucio", A,
            "A pause. A long slow look at the month's shape. Then close the book.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_immaculada", A,
            "Pont. Long hours for the quarterly numbers, if you wish. No hurry though.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_sant_esteve", A,
            "Day after. The ledger is patient. Tomorrow, perhaps. Not today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_cap_d_any_eve", A,
            "The year closes. A long slow read of the year's ledger, without flinching.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "hefi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hefi_birthday", A,
            "Your day. A small gift to the future you. Not large. Real.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "hefi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_personal_date", A,
            "You marked today: {label}. A small note in the ledger, in its honour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "hefi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("hefi_complete_1", A, "Noted. The ledger is still.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefi_complete_2", A, "A small tending. Enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefi_complete_3", A, "Done. Close the book.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hefi_complete_first_today", A,
            "First reckoning. The corner of the room is lighter.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "hefi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefi_complete_second_today", A,
            "Twice. The numbers know you are listening.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "hefi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefi_complete_third_today", A,
            "Three notes. The ledger rests easier.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "hefi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefi_complete_fourth_today", A,
            "A fourth. More than the day asked. Close the book now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "hefi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("hefi_complete_fifth_today", A,
            "Five. The ledger is sated. Sit. Tea. Anything but numbers.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "hefi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("hefi_complete_after_streak", A,
            "Three days the ledger has been opened gently. The pattern has begun.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hefi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("hefi_apotheosis_1", A,
            "A passage. The ledger held it. Quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefi_apotheosis_2", A,
            "Closed. The numbers can wait.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefi_apotheosis_3", A,
            "Done. The book is shut.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hefi_apotheosis_first_ever", A,
            "Your first. A small ledger-passage. I'll keep its quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("hefi_apotheosis_1", "hefi_apotheosis_2", "hefi_apotheosis_3"),
            theme = T),
        DialogueLine("hefi_apotheosis_at_level_2", A,
            "A second passage. The ledger has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "hefi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hefi_apotheosis_at_level_3", A,
            "A third. Numbers are not strangers anymore.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "hefi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hefi_apotheosis_at_level_4", A,
            "Old company. Money no longer asks for fear.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "hefi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("hefi_nudge_morning", A,
            "Open the ledger. Look gently. Close.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "hefi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefi_nudge_afternoon_zero", A,
            "One small reckoning. Then close the book.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "hefi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefi_nudge_evening", A,
            "Note one number. Then the lamp is for other things.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "hefi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hefi_nudge_attention_loss", A,
            "The ledger has waited. Open it slowly. Without judgement.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hefi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
