package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Hermit × Gratitude — quiet stance, the small noticing. */
internal object HermitGratitudeLines {

    private const val A = "HERMIT"
    private const val T = "GRATITUDE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("hegr_first_ever", A,
            "Notice three small things today. That is enough. The list need not be loud.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("hegr_morning", A,
            "Three things the night gave you. Slowly, before the day starts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "hegr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hegr_morning_early", A,
            "The kettle. The quiet. The unhurried air, this early. Three things, already.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "hegr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hegr_afternoon", A,
            "One thing the morning gave you, now the day's turned. Notice it before the next task.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "hegr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hegr_evening", A,
            "Lamp lit. Three small graces. Say them softly. Or just hold them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "hegr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hegr_night_late", A,
            "Late. One small grace, lying down. Then sleep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "hegr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("hegr_post_apotheosis", A,
            "A passage. The list held it. Sit a while in the quiet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("hegr_monday", A,
            "A week begins. Three things from the weekend, before the work asks.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "hegr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hegr_friday", A,
            "Friday. The week's small graces, slowly. Without summary.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "hegr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("hegr_weekend", A,
            "Weekend. A long noticing, or none. Both belong.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "hegr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("hegr_level_1_reached", A,
            "Quiet noticings for a stretch. The room has noticed back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "hegr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hegr_level_2_reached", A,
            "The day's shape has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "hegr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hegr_level_3_reached", A,
            "You return. The small things meet you before they're asked for.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "hegr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("hegr_level_4_reached", A,
            "Old company. The world is no longer asking for thanks. You are simply here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "hegr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("hegr_attention_loss_mild", A,
            "A few days unnoticed. The day is patient. One small grace today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "hegr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("hegr_attention_loss_hard", A,
            "A long unnoticing. Begin small. The kettle. The lamp. The breath. Three is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hegr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("hegr_wishes_pending", A,
            "There is a kindness on the shelf. A small thank-you letter, a slow grace-walk, a quiet evening.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "hegr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("hegr_mid_streak", A,
            "Three days of small noticings. The room sits with you differently.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hegr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("hegr_sant_jordi", A,
            "Sant Jordi. The day is making offerings. Receive a few. Notice them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_la_merce", A,
            "Mercè. The city is giving you a free show. Notice that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_sant_joan", A,
            "Sant Joan. Fire, water, summer. Three things, already given.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_diada", A,
            "Diada. Notice home, in the ledger of the heart. Without speech.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_nadal", A,
            "Nadal. The people at the table. Notice the ones still here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_cap_d_any", A,
            "New year. Notice what the old year gave, before naming what's next.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hegr_reis", A,
            "Reis. Receive what was given. Slowly. Without scoring it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_carnaval", A,
            "Carnaval. Notice the small freedom — to wear, to laugh, to be silly. Receive it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_divendres_sant", A,
            "A quiet day. Notice the city's pause, given to you also.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_pasqua", A,
            "Pasqua. Notice the spring — the day longer, the air warmer. Small gifts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_festa_del_treball", A,
            "Workers' day. Notice the rest you've been given. Don't fill it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_festa_major_gracia", A,
            "Gràcia. Notice the neighbours' work. Months of small labour, given freely.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_assumpcio", A,
            "August. Notice the slow. The quiet city is its own gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_hispanitat", A,
            "A day off. Notice the unscheduled hour. Don't crowd it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_castanyada", A,
            "Castanyada. Warm food, candles, the long dark. Old graces, freely given.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_constitucio", A,
            "A pause. Notice the unscheduled hours. They are themselves a kindness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_immaculada", A,
            "Pont. The long pause is a gift. Receive it without filling it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_sant_esteve", A,
            "Day after. Notice what yesterday actually held — without summary.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_cap_d_any_eve", A,
            "The year closes. Notice what stayed. Hold it briefly. Then let it pass.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "hegr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("hegr_birthday", A,
            "Your day. Notice the ones who carried you here. Without performance.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "hegr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_personal_date", A,
            "You marked today: {label}. One small grace, in its honour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "hegr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("hegr_complete_1", A, "Noticed. The room is gentler.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hegr_complete_2", A, "A small grace, held. Enough.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hegr_complete_3", A, "Done. Sit a while in it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("hegr_complete_first_today", A,
            "First noticing. The day has a different weather now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "hegr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("hegr_complete_second_today", A,
            "Twice. The room is being remembered.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "hegr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("hegr_complete_third_today", A,
            "Three. The day is held.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "hegr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("hegr_complete_fourth_today", A,
            "A fourth. More than the day asked. Sit with what you have.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "hegr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("hegr_complete_fifth_today", A,
            "Five. Stop listing. Live in one of them now.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "hegr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("hegr_complete_after_streak", A,
            "Three days of small noticings. The world meets you sooner now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "hegr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("hegr_apotheosis_1", A,
            "A passage. The day held it. Quiet now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hegr_apotheosis_2", A,
            "Closed. The list waits, but does not demand.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hegr_apotheosis_3", A,
            "Done. Sit with what you have.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("hegr_apotheosis_first_ever", A,
            "Your first. The day and you have a small new history of noticing. I'll keep its quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("hegr_apotheosis_1", "hegr_apotheosis_2", "hegr_apotheosis_3"),
            theme = T),
        DialogueLine("hegr_apotheosis_at_level_2", A,
            "A second passage. The shape of the day has shifted. Not much. Enough.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "hegr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hegr_apotheosis_at_level_3", A,
            "A third. The small graces meet you before they're asked for.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "hegr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("hegr_apotheosis_at_level_4", A,
            "Old company. The world is no longer asked for thanks. You are simply here.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "hegr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("hegr_nudge_morning", A,
            "Three things the night gave you. Slowly.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "hegr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hegr_nudge_afternoon_zero", A,
            "One thing the morning gave you. Notice it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "hegr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hegr_nudge_evening", A,
            "Three small graces. Hold them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "hegr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("hegr_nudge_attention_loss", A,
            "The day has waited. Three small graces today. That is enough.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "hegr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
