package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Gratitude & journaling. */
internal object OracleGratitudeLines {

    private const val A = "ORACLE"
    private const val T = "GRATITUDE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orgr_first_ever", A,
            "You came asking about attention. Three things daily, specific ones — I've watched the lens sharpen from less.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orgr_morning", A,
            "Three things before the day takes over — not “health.” The coffee, the light, the bus that came on time.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orgr_morning_early", A,
            "Up before the house stirs. This quiet is the first entry — note it. Two more find you by lunch.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orgr_afternoon", A,
            "Something worked this morning — I read it pass by. Write it down before the afternoon buries it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orgr_evening", A,
            "The day is nearly written. List what didn't go wrong in it — the mundane entries win.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orgr_night_late", A,
            "Late, one thing before sleep. Don't reach for profound — I've read those entries. Reach for true.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orgr_post_apotheosis", A,
            "The block closes, the notebook keeps. Same three tomorrow — the discipline was the gift all along.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orgr_monday", A,
            "Seven days start blank. Carry three things from the weekend forward — they compound if you note them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orgr_friday", A,
            "The week folds shut tonight. Close it with a real list — five things, honest ones. Not the LinkedIn version.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orgr_weekend", A,
            "Two unscheduled days, and the pace slows enough to see. Notice more. Write more.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orgr_level_1_reached", A,
            "One knot tied. A week of three-a-day — I can already read the difference in the eye.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orgr_level_2_reached", A,
            "Twice woven. You notice things without trying now — that's the practice, working.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orgr_level_3_reached", A,
            "The pattern carries your handwriting now — literally. The list is honest, specific, and compounding quietly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orgr_level_4_reached", A,
            "I saw this height long ago. Daily, honest, specific — forever. There's no graduation from this one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orgr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orgr_attention_loss_mild", A,
            "Three days of empty notebook. I watched the eye dull a little each one. One specific entry, now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orgr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orgr_attention_loss_hard", A,
            "Weeks of blank pages — I won't pretend otherwise. Don't catch up. Today's entry, just today's, holds.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orgr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("orgr_mid_day_return", A,
            "Halfway through, and the list is still empty. One thing — five seconds. The pen is closer than you think.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orgr_wishes_pending", A,
            "Something you're owed sits unclaimed. Spend it re-reading last month's pages — the compounding is real.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orgr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orgr_mid_streak", A,
            "Three days of honest entries now. The lens sharpens with each one — don't be the one who blunts it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orgr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orgr_sant_jordi", A,
            "Roses and books in the streets today — the book, the rose, the walk. Three entries, ready-made. Write them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_la_merce", A,
            "Giants and fire in the streets. The lights, the crowd, the friend you ran into — note them tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_sant_joan", A,
            "The shortest night. The sand, the fire, who you stood with — get it on the page before sleep takes it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_diada", A,
            "The eleventh again, and the city goes quiet enough for long-form. Only days like this produce those entries.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_nadal", A,
            "Nadal. The table, the hands you shook, the arguments that didn't happen — three entries, tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_cap_d_any", A,
            "The year stands new and blank. List the old one's five biggest — honestly. Next year you'll read them back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orgr_reis", A,
            "Gift morning. The gift, the face that opened it, the slow start — write them down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_carnaval", A,
            "Masks in the streets. The costume, the laughter, the detail you almost missed — that last one goes on the list.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_divendres_sant", A,
            "The city stops mid-sentence today — the best journal day of the year. An hour at the page. Real entries.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_pasqua", A,
            "The pause releases today. Reset the list — three things from this day, not the old week.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_festa_del_treball", A,
            "A day named for work. Write three entries about your own — honest ones, not the LinkedIn versions.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_festa_major_gracia", A,
            "Gràcia hung a year of work over its streets. The decoration on Plaça del Sol — that's tonight's specific note.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_assumpcio", A,
            "Mid-August, the city half-emptied. Note the quiet, the heat, what slows down — entries no other month gives.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_hispanitat", A,
            "A day off, wide enough for a long entry. Don't spend it on a one-liner.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_castanyada", A,
            "Chestnut smoke, the first real cold, friends huddled close — there are your three.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_constitucio", A,
            "A civic anniversary bridges the weekend, and rested days write the long entries. Don't skip because it's easy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_immaculada", A,
            "Five loose days strung together. Five entries, one per day — I've read the draft where they all get written.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_sant_esteve", A,
            "The day after the feast. Note what surprised you yesterday — the unexpected thing is the entry that keeps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_cap_d_any_eve", A,
            "Twelve grapes tonight, and the year closes on schedule. The annual list — twelve months, three things each.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orgr_birthday", A,
            "The day your thread began, come round again. List ten honest ones — next birthday, you read them back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orgr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_personal_date", A,
            "Today carries the name you gave it: {label}. The pages will run longer tonight — write them anyway.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orgr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orgr_complete_1", A, "Entry down. I saw it coming, but the ink makes it true.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orgr_complete_2", A, "Logged. Specific, not abstract — that's the kind that keeps.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orgr_complete_3", A, "Done. The notebook holds it now, so you don't have to.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orgr_complete_first_today", A,
            "The first entry, in. The lens is on now — carry it through the rest of the day.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orgr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orgr_complete_second_today", A,
            "Two entries. The eye is awake — don't let it drift back onto autopilot.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orgr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orgr_complete_third_today", A,
            "Three. A true practice day — the book sits heavier on the shelf already.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orgr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orgr_complete_fourth_today", A,
            "Four. Don't force them past this — I've read the forced ones. Quality, not quantity.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orgr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orgr_complete_fifth_today", A,
            "Five. Stretched this thin, the practice dilutes — I've read where that goes. Stop here.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orgr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orgr_complete_after_streak", A,
            "Third day of entries. A pattern is forming on those pages — re-read them at week's end.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orgr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orgr_apotheosis_1", A,
            "Crossed. The daily continues — the discipline was the gift all along.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orgr_apotheosis_2", A,
            "It closes, and I see one room further. Re-read the past month — the pattern's been in plain sight.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orgr_apotheosis_3", A,
            "Closed. Same notebook, same hour, same discipline — the thread holds on sameness.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orgr_apotheosis_first_ever", A,
            "Your first block of daily entries. Most drafts of this end at week two. Yours didn't — I read on.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orgr_apotheosis_1", "orgr_apotheosis_2", "orgr_apotheosis_3"),
            theme = T),
        DialogueLine("orgr_apotheosis_at_level_2", A,
            "A second crossing. The entries sharpen — don't let them turn into performance. Stay honest.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orgr_apotheosis_at_level_3", A,
            "Another closing. The lens is permanent now — you notice before you write. Write anyway.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orgr_apotheosis_at_level_4", A,
            "We read from the same page now — yours. Daily entries, forever: same shelf, same notebook, same hour.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orgr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orgr_nudge_morning", A,
            "There's a version of this morning where three specific things get written before anything else. You're in it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orgr_nudge_afternoon_zero", A,
            "Halfway through, the notebook still empty. One line takes five seconds — I've read the version where it happens.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orgr_nudge_evening", A,
            "What you list tonight is what the day gets remembered as. What didn't go wrong — honestly.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orgr_nudge_attention_loss", A,
            "Weeks of blank pages, and I've read where catching up goes. Today's entry only — one line holds.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orgr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
