package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Writing & creativity. */
internal object OracleWritingLines {

    private const val A = "ORACLE"
    private const val T = "WRITING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orwr_first_ever", A,
            "You came to ask of the page. The page is patient — words down, ugly first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orwr_morning", A,
            "The best writing hour of the day is usually this one. Don't hand it to the inbox instead.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orwr_morning_early", A,
            "The mind is quiet before dawn in a way it won't be again. Two hundred words, before the world starts talking.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orwr_afternoon", A,
            "Inspiration is a story people tell after the fact. Sit down and write anything — that's the actual method.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orwr_evening", A,
            "Edit what got written this morning — two passes, then stop before the edits start eating the thing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orwr_night_late", A,
            "Not a draft, not this tired — just note the idea. Sharpen it tomorrow with a clearer head.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orwr_post_apotheosis", A,
            "The piece closes. Publish it or shelve it deliberately — stale drafts just grow heavier the longer they sit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orwr_monday", A,
            "Set the week's word count today — then halve it. The smaller number is the one that actually gets hit.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orwr_friday", A,
            "Ship the draft before the weekend starts. Carrying it across that line rarely goes anywhere good.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orwr_weekend", A,
            "A long-form day today — three hours, no edits allowed. Just words going down.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orwr_level_1_reached", A,
            "A first piece, finished. Most people never leave the blank page — you're already past it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orwr_level_2_reached", A,
            "The voice is arriving now. Trust it on the page — don't edit it silent before it's said anything.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orwr_level_3_reached", A,
            "Real work now, on a regular cadence. Share it — hiding it at this point is just fear in a nicer coat.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orwr_level_4_reached", A,
            "The voice is yours now, unmistakably. Defend the writing time the way you'd defend a real deadline.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orwr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orwr_attention_loss_mild", A,
            "Three days without a word, and the blank page is winning. One paragraph today — anything, just to break it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orwr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orwr_attention_loss_hard", A,
            "Weeks of silence. Do not write the masterpiece — write garbage. The voice returns.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orwr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("orwr_mid_day_return", A,
            "Half the day, page blank. Twenty minutes — does not have to be good. Has to exist.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orwr_wishes_pending", A,
            "Something earned is sitting unspent. Take the writing retreat day — a win left unclaimed stops feeling like one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orwr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orwr_mid_streak", A,
            "Three writing days. Voice awake — do not break the rhythm.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orwr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orwr_sant_jordi", A,
            "The city's whole trade today is roses and books. Buy the book, then write one paragraph of your own.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_la_merce", A,
            "The city is loud all week for Mercè. Write at a café in the morning, before the noise claims the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_sant_joan", A,
            "No words tonight — the beach and the fireworks get this one. Write tomorrow about what you actually saw.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_diada", A,
            "A long day off, made for a long block. Three hours, uninterrupted, if you can find them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_nadal", A,
            "Words rest today. Listen at the table instead — the notes for January are being made right now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_cap_d_any", A,
            "The first three sentences of the year set its voice more than people expect. Write them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orwr_reis", A,
            "Read the new book today — note what works on the page. That's writing practice too, quietly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_carnaval", A,
            "Watch the costumes pass. Characters write themselves out there today — just take notes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_divendres_sant", A,
            "A quiet day, the city pauses. The kind of stillness writing actually needs — two hours, no phone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_pasqua", A,
            "Coming off a break resets the instinct more than people admit. One paragraph today gets it moving again.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_festa_del_treball", A,
            "A day off in the name of work. The work here is words, and words get to rest too — write tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_festa_major_gracia", A,
            "Carry a notebook through Gràcia this week. The streets write themselves into you if you let them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_assumpcio", A,
            "The city empties out in August — usually the best writing month of the year. Don't let it slide by unused.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_hispanitat", A,
            "A day off the calendar hands you. Read the thing you've been avoiding, then write a response — real writing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_castanyada", A,
            "Dark by seven now — long-form season starts. Indoor evenings make room for longer pages.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_constitucio", A,
            "A bridge weekend. Ship a piece, or actually rest — don't spend all four days half-drafting something.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_immaculada", A,
            "Five loose days ahead — enough for a real first draft, or enough to properly rest. Don't just dabble at either.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_sant_esteve", A,
            "A light edit on yesterday's notes suits today better than chasing new work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_cap_d_any_eve", A,
            "Count the pages written this year, honestly. Then plan next year's volume before the noise starts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orwr_birthday", A,
            "The day marked for you alone. Write yourself a letter, an honest one — read it again next year.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orwr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_personal_date", A,
            "You marked this day: {label}. The kind of day to write about — notes, one paragraph.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orwr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orwr_complete_1", A, "Words down. The next paragraph is already waiting its turn.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orwr_complete_2", A, "Logged. Do not reread now — keep going.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orwr_complete_3", A, "Done. Close the file. Edit tomorrow.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orwr_complete_first_today", A,
            "First lines down. The blank page is dead — move.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orwr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orwr_complete_second_today", A,
            "Two sessions. Do not burn out — quality drops past 90 minutes.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orwr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orwr_complete_third_today", A,
            "Three. Real writing day — the piece is denser than morning.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orwr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orwr_complete_fourth_today", A,
            "Four. Stop — rest the voice. Tomorrow sharper.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orwr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orwr_complete_fifth_today", A,
            "Five. Past lucid — typing, not writing. Stop.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orwr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orwr_complete_after_streak", A,
            "Day three of writing. Voice awake — keep the rhythm.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orwr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orwr_apotheosis_1", A,
            "The piece closes. Publish it or shelve it within 48 hours — don't let it rot in between.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orwr_apotheosis_2", A,
            "It closes. Write the next piece's first sentence now, while the voice is still warm.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orwr_apotheosis_3", A,
            "It's done. Read it tomorrow with fresh eyes, and edit it ruthlessly then.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orwr_apotheosis_first_ever", A,
            "First piece, top to bottom. You are a writer who finishes — most aren't.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orwr_apotheosis_1", "orwr_apotheosis_2", "orwr_apotheosis_3"),
            theme = T),
        DialogueLine("orwr_apotheosis_at_level_2", A,
            "The voice has gotten consistent. Longer pieces are possible from here.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orwr_apotheosis_at_level_3", A,
            "People read what you write now. That's not a reason to write less — it's a reason to write harder.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orwr_apotheosis_at_level_4", A,
            "The voice is unmistakable now, yours alone. Defend the writing time — always, not just when it's convenient.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orwr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orwr_nudge_morning", A,
            "Page open, two hundred words — don't think first, just write.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orwr_nudge_afternoon_zero", A,
            "The page is still blank. Twenty minutes of anything — just type.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orwr_nudge_evening", A,
            "An edit pass now — two reads through, then close the file.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orwr_nudge_attention_loss", A,
            "Weeks of silence. Write garbage today — type. The voice returns with patience.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orwr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
