package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Body & exercise. */
internal object OracleExerciseLines {

    private const val A = "ORACLE"
    private const val T = "EXERCISE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orex_first_ever", A,
            "You came to ask of the body. The body has been waiting. Begin.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orex_morning", A,
            "Morning. The sinews tighten in sleep — loosen them, slowly. Then move.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orex_morning_early", A,
            "Pre-dawn. The first rep is always the gate. Pass through.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orex_afternoon", A,
            "Mid-day. The body asks for movement. Listen — or the question grows louder.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orex_evening", A,
            "Evening. Form before intensity — always. The body remembers what the mind forgets.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orex_night_late", A,
            "Late. No truths arrive at midnight reps. Sleep. The next door opens tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orex_post_apotheosis", A,
            "A block has closed. Rest. The body's gift is given in sleep, not sweat.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orex_monday", A,
            "Monday. A new arc opens. Set the intensity here — the week answers it later.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orex_friday", A,
            "Friday. Heavy or recover — be honest about which the body asked for.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orex_weekend", A,
            "Weekend. Long, slow, outside — the kind of work no one sees but the body knows.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orex_level_1_reached", A,
            "First threshold. Newbie strength is its own teacher — listen.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orex_level_2_reached", A,
            "Second threshold. The plateau begins — sleep is the new lift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orex_level_3_reached", A,
            "Third threshold. Form is set. The body now asks for recovery, not heroics.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orex_level_4_reached", A,
            "The high tier. The only opponent left is yesterday — hold the line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orex_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orex_attention_loss_mild", A,
            "Strength is a candle — it dims fast. One easy set returns the flame.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orex_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orex_attention_loss_hard", A,
            "The detraining is real. Begin again at 60% — the body forgives the patient.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orex_atten_loss", cooldownPicks = 2, theme = T),

                DialogueLine("orex_mid_day_return", A,
            "Half the day has passed. The body is cold — warm it slowly, or rest. Choose.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orex_wishes_pending", A,
            "You have earned rest — the gift accumulates. Take it before it weighs.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orex_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orex_mid_streak", A,
            "The thread holds — three days. Walk it, do not admire it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orex_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orex_sant_jordi", A,
            "Sant Jordi. The city walks today — count the streets as your set. Earn the evening.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_la_merce", A,
            "Mercè. The festival is loud, sleep will be short — light technique, then go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_sant_joan", A,
            "Sant Joan. Train early — by midnight the fire holds you. Sleep tomorrow, do not fight it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_diada", A,
            "Diada. Walk an hour at least — the body learns recovery as its own training.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_nadal", A,
            "Nadal. The table is heavy — move twice today. Once before, once after. Light.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_cap_d_any", A,
            "The first session of the year sets the line — clean, not heavy. Mark it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orex_reis", A,
            "Reis. The sugar has settled in the body — move the legs. The hour will pass quickly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_carnaval", A,
            "Carnaval. The costume conceals — the body underneath still asks. Mobility before bed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_divendres_sant", A,
            "Divendres Sant. The city stills — walk slow, stretch slow. The body remembers stillness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_pasqua", A,
            "Pasqua Monday. Active recovery — the mona waits, the run first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_festa_del_treball", A,
            "Workers' day. The body works too — honor it with one clean session.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_festa_major_gracia", A,
            "Gràcia week. Wandering is zone-two cardio — take the long way home.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_assumpcio", A,
            "Heat. Train at the edges of the day — water double, salt at the meal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_hispanitat", A,
            "A day with no claim. Empty gym, full park — pick the one that calls.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_castanyada", A,
            "Castanyada. Dark earlier now — move before dinner, or the chair holds you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_constitucio", A,
            "Bridge opens. Four-day microcycle, or four-day rest — but pick. The middle is dust.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_immaculada", A,
            "Pont. Five days. Three sessions named — the rest is silence and food.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_sant_esteve", A,
            "Day after the long table. Stiff bones — twenty minutes, easy. The body asks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_cap_d_any_eve", A,
            "Last day. A light session before the grapes — the year ends loose, not sore.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orex_birthday", A,
            "Your day. Light session — the cake is the rep this evening.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orex_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orex_personal_date", A,
            "You marked this day: {label}. The body knows — take what it needs.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orex_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orex_complete_1", A, "The set is closed. Begin the next breath.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orex_complete_2", A, "Clean rep. The next one waits — do not rush.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orex_complete_3", A, "Done. Now make it look easier — that is the work.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orex_complete_first_today", A,
            "First session of the day — the hardest gate. The rest is corridor.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orex_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orex_complete_second_today", A,
            "Two sessions in. The body is warm — stop reaching for the third.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orex_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orex_complete_third_today", A,
            "Three. A true day's work — eat well tonight, the body asks.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orex_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orex_complete_fourth_today", A,
            "Four. Past the recovery window — sleep early, or the next day collects the debt.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orex_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orex_complete_fifth_today", A,
            "Five. Either you peak or you ruin — be honest which the day is.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orex_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orex_complete_after_streak", A,
            "Day three of training. Your tendons catch up to your ambition — be patient.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orex_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orex_apotheosis_1", A,
            "A block closed. Eat. Sleep. The next mesocycle waits in shadow.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orex_apotheosis_2", A,
            "Phase done. The bigger lifts are coming — do not be clever, be steady.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orex_apotheosis_3", A,
            "Closed. Plan the next arc while it is warm — the memory cools fast.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orex_apotheosis_first_ever", A,
            "Your first training block in the book — do not forget how the body felt.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orex_apotheosis_1", "orex_apotheosis_2", "orex_apotheosis_3"),
            theme = T),
        DialogueLine("orex_apotheosis_at_level_2", A,
            "Promoted. Add load only to lifts your form has earned. The body keeps the ledger.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orex_apotheosis_at_level_3", A,
            "Senior lifter. Others watch how you warm up — make it the standard.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orex_apotheosis_at_level_4", A,
            "The high tier. Volume gives, recovery takes — choose the battles carefully.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orex_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orex_nudge_morning", A,
            "Morning. The body is stiff — five minutes of mobility, then the real work.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orex_nudge_afternoon_zero", A,
            "Half the day, no movement. Twenty minutes is twenty minutes — the rest is story.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orex_nudge_evening", A,
            "Evening. Light session beats no session — do not end the day cold.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
                DialogueLine("orex_nudge_attention_loss", A,
            "Detrained. The comeback set: light, clean, today — that is the whole work.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orex_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
