package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Hobbies & play. */
internal object OracleHobbiesLines {

    private const val A = "ORACLE"
    private const val T = "HOBBIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orho_first_ever", A,
            "You came asking about play. Joy gets rationed in every draft I've read — take the dose. No apology.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orho_morning", A,
            "Twenty minutes on the thing you love, before the day notices they exist. I've read what happens when it does.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orho_morning_early", A,
            "Up before the house stirs — a stolen hour. Spend it at the hobby, not the inbox. The good drafts all start there.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orho_afternoon", A,
            "There are fifteen minutes of play hidden between your meetings. I've seen them — don't pretend you haven't.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orho_evening", A,
            "The evening opens. The bench, the instrument, the garden — whatever yours is, it's waiting. Sit at it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orho_night_late", A,
            "Late — not the hour to start a project. I've read those drafts; they end abandoned. Five easy minutes, then bed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orho_post_apotheosis", A,
            "The block closes, but the hobby stays. I've watched people set it down here and call it a phase. Not this draft.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orho_monday", A,
            "Seven days start blank. Put the hobby block in the calendar the way you'd book a meeting — it holds better.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orho_friday", A,
            "The week folds shut tonight. Close it with one good session — not a productive one. A pleasurable one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orho_weekend", A,
            "Two unscheduled days. The long block lives here — two hours minimum. I've watched chores eat it before.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orho_level_1_reached", A,
            "One knot tied. A week of real play, and you read as a person again — don't set it down now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orho_level_2_reached", A,
            "Twice woven, and the hobby's getting good. I've read the draft where it becomes a side hustle. It's the trap.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orho_level_3_reached", A,
            "The pattern holds. Real skill now, and real joy with it — the time that made both needs defending.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orho_level_4_reached", A,
            "I saw this height long ago. The hobby is part of you now — defend it like work. More than work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orho_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orho_attention_loss_mild", A,
            "Three days of pure work, no play. I watched the thread pull taut. Tonight belongs to the hobby.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orho_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orho_attention_loss_hard", A,
            "Weeks of pure productivity — I've read where that version ends. You're a person, not a function. Tonight, pick it up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orho_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("orho_mid_day_return", A,
            "Halfway through, and nothing playful in it yet. Fifteen minutes isn't a luxury — I've read the days without it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orho_wishes_pending", A,
            "Something you're owed sits unclaimed. The new tool, the book, the strings — take it before it goes stale.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orho_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orho_mid_streak", A,
            "Three days of real play now. The mind has gone softer at the edges — don't hand tomorrow back to the grind.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orho_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orho_sant_jordi", A,
            "Roses and books in the streets, and makers at every stall. Inspiration walks free today — take some home.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_la_merce", A,
            "Giants and fire in the streets, and an arts festival threaded through it. Find the tucked-away thing. Watch it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_sant_joan", A,
            "The shortest night — no bench tonight. Beach, fire, really off. The hobby reads better tomorrow for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_diada", A,
            "The eleventh again, a day off. Three uninterrupted hours at the hobby — I've read the version where errands win. Skip it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_nadal", A,
            "Nadal. Family fills today — the bench keeps until the 26th. No sneaking away between courses.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_cap_d_any", A,
            "The year zeroes itself tonight. Pick the new skill inside the hobby — specific enough to put on a calendar.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orho_reis", A,
            "Gift morning. Whatever came wrapped — if it's a tool, hold it today. If it's an idea, try it today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_carnaval", A,
            "Masks in the streets soon. Make the costume with your own hands — that's the hobby, wearing a disguise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_divendres_sant", A,
            "The city stops mid-sentence today — the best bench day of the year. Hours, uninterrupted. Take all of them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_pasqua", A,
            "The pause releases today. Don't spend it catching up on work — the hobby is what the day was for.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_festa_del_treball", A,
            "A day named for work, spent not working. Play is the rest — no productivity wearing its clothes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_festa_major_gracia", A,
            "Gràcia's paper sky is somebody's hobby, hung out for a week. Walk under it. Take notes for yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_assumpcio", A,
            "Mid-August, the city half-emptied. Workshop hours are lying around unclaimed — take them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_hispanitat", A,
            "A day off, wide open. Workshop day — I've read the version where avoided errands swallow it. Not this one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_castanyada", A,
            "Chestnut smoke, and dark by seven — hobby season opens tonight. The long evenings belong to the bench now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_constitucio", A,
            "A civic anniversary bridges the weekend. Pure play in it — don't dress productivity up as the hobby.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_immaculada", A,
            "Five loose days strung together. Hobby intensive, or full rest — I've read the trickled-through version. It's grey.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_sant_esteve", A,
            "The day made from Nadal's leftovers, quiet at last. That small thing you've been building in your head — build it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_cap_d_any_eve", A,
            "Twelve grapes tonight. List the year's hobby wins first — even the small ones count in this ledger.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orho_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orho_birthday", A,
            "The day your thread began, come round again. The tool you keep browsing — today you buy it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orho_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orho_personal_date", A,
            "Today carries the name you gave it: {label}. The hobby is a refuge on days like this — use it. No apology.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orho_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orho_complete_1", A, "Session in. I saw this hour coming — it was one of the good ones.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orho_complete_2", A, "Done. Tools back where they belong — future-you thanks you.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orho_complete_3", A, "Logged. No guilt for the hour — it was never owed elsewhere.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orho_complete_first_today", A,
            "The first play of the day. The all-work version quietly folds away.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orho_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orho_complete_second_today", A,
            "Two sessions. Don't burn through it — this is the kind of thing you savor.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orho_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orho_complete_third_today", A,
            "Three. A real hobby day — the skill sits denser in your hands than it did this morning.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orho_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orho_complete_fourth_today", A,
            "Four. Ease off — hobbies don't carry quotas, and forcing one in reads wrong.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orho_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orho_complete_fifth_today", A,
            "Five. I've read where this many in a day points — past play, into escape. Read yourself honestly.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orho_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orho_complete_after_streak", A,
            "Third day of real play. The mind runs wider — notice the colors on your way home.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orho_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orho_apotheosis_1", A,
            "Crossed. Put it on display — the hobby earned its shelf space.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orho_apotheosis_2", A,
            "It closes, and the skill is bigger than it was. I've read the monetized draft — don't. Just enjoy it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orho_apotheosis_3", A,
            "Done. Plan the next piece while the hands are warm — forward motion, low stakes.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orho_apotheosis_first_ever", A,
            "Your first finished project. I had seen it coming — you're not dabbling anymore. You make things.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orho_apotheosis_1", "orho_apotheosis_2", "orho_apotheosis_3"),
            theme = T),
        DialogueLine("orho_apotheosis_at_level_2", A,
            "A second crossing. The skill is real now — don't load pressure onto it. Joy stays the only metric.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orho_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orho_apotheosis_at_level_3", A,
            "Another closing. People ask about it now — be modest, be specific, and keep playing.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orho_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orho_apotheosis_at_level_4", A,
            "We read from the same page now, you and the craft of play. Defend the bench, the time, the joy.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orho_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orho_nudge_morning", A,
            "There's a version of this morning with twenty minutes of play in it, before the day eats them. You're still inside it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orho_nudge_afternoon_zero", A,
            "Halfway through, nothing playful yet. Fifteen minutes — I've read the days without them. They end thinner.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orho_nudge_evening", A,
            "The bench, the instrument, the garden — one of them is in tonight's good draft. Sit down at it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orho_nudge_attention_loss", A,
            "Weeks of all-work, and the thread's gone thin. Ten minutes tonight — the version where you pick it up holds.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orho_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
