package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Meditation & stillness. */
internal object OracleMeditationLines {

    private const val A = "ORACLE"
    private const val T = "MEDITATION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orme_first_ever", A,
            "You came asking about stillness. The cushion asks the same thing every day — five minutes. Begin.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orme_morning", A,
            "Sit before the day starts — ten minutes. I've read the mornings that argue with the cushion. They lose.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orme_morning_early", A,
            "Before the house stirs, the mind is still warm from sleep. Sit now — this quiet doesn't come twice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orme_afternoon", A,
            "By midday the mind runs loud. Three breaths at the desk — not a ceremony, just a reset.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orme_evening", A,
            "Sit before the screens tonight — I've read the nights after. The brain can't sleep with the static still on.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orme_night_late", A,
            "Late — three breaths in bed is enough. I've read the version that promises a full session now. It doesn't happen.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orme_post_apotheosis", A,
            "The block closes. Don't skip tomorrow — daily is the whole discipline. There's no graduating from this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orme_monday", A,
            "Seven days start blank. Fix the sit to one time, every day — I've read the floating version. It evaporates.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orme_friday", A,
            "The week folds shut tonight. Don't let the sit go with it — the discipline counts double on loose days.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orme_weekend", A,
            "Two unscheduled days. A longer sit fits here — twenty minutes. Don't skip it just because the day is loose.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orme_level_1_reached", A,
            "One knot tied. A week of sitting — boring on purpose. That boredom was always the point.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orme_level_2_reached", A,
            "Twice woven. The breath comes back faster now — you catch the noise sooner than you used to.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orme_level_3_reached", A,
            "The pattern carries your handwriting now. The stillness shows up off the cushion too — don't get smug about it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orme_level_4_reached", A,
            "I saw this height long ago. The maintenance is the work — daily, forever. No graduation here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orme_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orme_attention_loss_mild", A,
            "Three days off the cushion, and I watched the thread slip. Sit today — five minutes. Not enlightenment. Five.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orme_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orme_attention_loss_hard", A,
            "Weeks off the cushion — I won't pretend otherwise. Don't restart at thirty. Five today, five tomorrow. Build back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orme_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("orme_mid_day_return", A,
            "Halfway through, no sit yet. Five minutes at the desk, eyes closed — I've read the version where that's enough.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orme_wishes_pending", A,
            "Something you're owed sits unclaimed. Spend it on a longer sit, or a quiet walk — either one keeps.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orme_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orme_mid_streak", A,
            "Three days running. The cushion's an old friend now — don't get sentimental, just keep sitting.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orme_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orme_sant_jordi", A,
            "Roses and books fill the streets today, and the crowds with them. Sit early — the rest of the day runs loud.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_la_merce", A,
            "Giants and fire in the streets tonight. Sit before you go out — the noise lands better from a still room first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_sant_joan", A,
            "The shortest night, and you'll be up till dawn. Sit before you go — quiet before the fire.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_diada", A,
            "The eleventh again, a day off. A long sit fits — twenty minutes. Don't let errands crowd it out.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_nadal", A,
            "Nadal. Sit before the table today — I've read how differently gratitude lands after stillness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_cap_d_any", A,
            "The year stands new and blank. The first sit of it sets the rhythm the rest follows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orme_reis", A,
            "Gift morning, and a quiet one before it starts. Sit before the parcels — the kindness lands differently that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_carnaval", A,
            "Masks and loud energy in the streets tonight. Sit early — I've read what entering the noise already wired does.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_divendres_sant", A,
            "The city stops mid-sentence today. The whole of it goes quiet — the best sit of the year. Take it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_pasqua", A,
            "The pause releases today. Coming off the rest, reset the practice — same time as before, no drift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_festa_del_treball", A,
            "A day named for work, spent not working. But the work here is the breath — it takes no holiday.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_festa_major_gracia", A,
            "Gràcia's paper sky is up, and the streets stay loud all week beneath it. Sit twice a day — you need it more now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_assumpcio", A,
            "Mid-August, the heat sitting still over an empty city — the best month of the year for long sits. Use it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_hispanitat", A,
            "A day off, wide open. A half-hour sit fits inside it — don't let errands fill the space instead.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_castanyada", A,
            "Chestnut smoke, and dark by seven now. The evening sit lands differently in autumn — take it while it does.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_constitucio", A,
            "A civic anniversary bridges the weekend. Don't let the break swallow the practice — daily means daily.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_immaculada", A,
            "Five loose days strung together. Pack the cushion — I've read the trips without it. The daily sit is your anchor.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_sant_esteve", A,
            "The day made from yesterday's leftovers, the house still loud. Five minutes between rounds — call it survival.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_cap_d_any_eve", A,
            "Twelve grapes tonight. Sit before the noise starts — I've read the years that end quieter for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orme_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orme_birthday", A,
            "The day your thread began, come round again. A long sit first — twenty minutes. Then the day is yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orme_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orme_personal_date", A,
            "Today carries the name you gave it: {label}. Sit longer if it's heavy, shorter if light — but sit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orme_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orme_complete_1", A, "Sat. I saw that one coming.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orme_complete_2", A, "Logged. Stand slowly — carry the breath into the next thing.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orme_complete_3", A, "Done. The mind comes back fast now — I've watched it learn the way.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orme_complete_first_today", A,
            "The first sit, done. The day starts grounded — don't hand that straight to the phone.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orme_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orme_complete_second_today", A,
            "Two sits. The reset is real — carry the breath into whatever comes next.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orme_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orme_complete_third_today", A,
            "Three. A real practice day — don't undo it in a screen-coma tonight.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orme_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orme_complete_fourth_today", A,
            "Four sits. Either the day was rough or you're hiding on the cushion. Read yourself honestly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orme_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orme_complete_fifth_today", A,
            "Five. This isn't the work anymore — the cushion was never an escape hatch. Stand up. Live the day.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orme_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orme_complete_after_streak", A,
            "Third day of practice running. The mind's quieter — notice it, without turning it into a story.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orme_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orme_apotheosis_1", A,
            "Crossed. The daily continues — there's no graduating from this one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orme_apotheosis_2", A,
            "It closes, and I see one room further. Don't lengthen the sit to look serious — same time tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orme_apotheosis_3", A,
            "Closed. The practice is only ever the practice — boring on purpose, and that's the whole trick.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orme_apotheosis_first_ever", A,
            "Your first block of regular sitting. I had seen it — you've built something most people never do.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orme_apotheosis_1", "orme_apotheosis_2", "orme_apotheosis_3"),
            theme = T),
        DialogueLine("orme_apotheosis_at_level_2", A,
            "A second crossing. The mind finds the breath faster now — don't go chasing deeper states.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orme_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orme_apotheosis_at_level_3", A,
            "Another closing. The stillness shows up off the cushion now too — hold onto the humility.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orme_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orme_apotheosis_at_level_4", A,
            "We read from the same page now. Daily sit, forever — this discipline never graduates.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orme_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orme_nudge_morning", A,
            "There's a version of this morning with ten minutes on the cushion, phone in the kitchen. You're still in it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orme_nudge_afternoon_zero", A,
            "Halfway through, no sit yet. Five at the desk, eyes closed — I've read the version where you take them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orme_nudge_evening", A,
            "What you do before bed is what the night inherits. Sit — the brain can't sleep with the static on.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orme_nudge_attention_loss", A,
            "Weeks off, and I've read where restarting at thirty leads — right back to zero. Five today. Build back slowly.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orme_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
