package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Learning & study. */
internal object OracleLearningLines {

    private const val A = "ORACLE"
    private const val T = "LEARNING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orle_first_ever", A,
            "You came to ask of the page. The book on the shelf does not read itself — open it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orle_morning", A,
            "Morning. One page before anything else — the mind is clearest now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orle_morning_early", A,
            "Pre-work hour. Best study time — do not squander it on news.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orle_afternoon", A,
            "Mid-day. Lunch break study — fifteen minutes. Do not sleep on it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orle_evening", A,
            "Evening. One chapter — then close it. The brain consolidates overnight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orle_night_late", A,
            "Late. Do not cram tired — one paragraph, sleep. It will stick tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orle_post_apotheosis", A,
            "Course done. Do not put the book away — pick the next subject before forgetting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orle_monday", A,
            "Monday. Week's study plan — specific, schedulable. Or it does not happen.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orle_friday", A,
            "Friday. Review what you actually learned — honest answer.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orle_weekend", A,
            "Weekend. Longer block possible — two hours real study beats five of skimming.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orle_level_1_reached", A,
            "First threshold. First chapter retained — the hardest one. Most quit here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orle_level_2_reached", A,
            "Second threshold. Concepts connect — the map is forming. Keep adding.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orle_level_3_reached", A,
            "Third threshold. You can explain it — teach someone. That is the test.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orle_level_4_reached", A,
            "High tier. The subject is yours — do not quit. Pick a new one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orle_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orle_attention_loss_mild", A,
            "Three days no study — the page knows. Open the book, today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orle_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orle_attention_loss_hard", A,
            "Book gathering dust. Do not restart at chapter one — pick up where you left.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orle_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("orle_mid_day_return", A,
            "Half the day. Book unopened — ten minutes. Not optional.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orle_wishes_pending", A,
            "Reward accumulates. Buy the next book on the list.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orle_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orle_mid_streak", A,
            "Three study days. The subject is alive — do not waste the momentum.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orle_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orle_sant_jordi", A,
            "Sant Jordi. New book bought, surely — read the first chapter tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_la_merce", A,
            "Mercè. Loud city — headphones, library, or skip. Pick.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_sant_joan", A,
            "Sant Joan. No study tonight — real off. Tomorrow back to the page.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_diada", A,
            "Diada. Long-form reading day — three hours, no phone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_nadal", A,
            "Nadal. Family takes the day — study tomorrow, not faked tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_cap_d_any", A,
            "New year. New subject on the shelf — pick today, open tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orle_reis", A,
            "Reis. A book as a gift, probably — read it. Do not shelve it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_carnaval", A,
            "Carnaval. Late nights mean groggy mornings — study at lunch, not 7am.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_divendres_sant", A,
            "Quiet day. Best study day of the year — phone off, two hours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_pasqua", A,
            "Pasqua Monday. Reset the study habit — one page. The whole day's goal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_festa_del_treball", A,
            "Workers' day. The book is work too — honor the rest. Read tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_festa_major_gracia", A,
            "Gràcia. Library or festival — pick. Either commits.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_assumpcio", A,
            "August. Empty city — best long-read month. Use it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_hispanitat", A,
            "Day off. Pick up the textbook you avoided — one tough chapter.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_castanyada", A,
            "Castanyada. Dark by 7 — indoor reading season opens. Lean in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_constitucio", A,
            "Bridge weekend. Pick a book — finish before Monday. The real test.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_immaculada", A,
            "Pont. Five days. Close a real subject — or rest. Do not dabble.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_sant_esteve", A,
            "Day after. Light reading — the fiction book that waited. Earn it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_cap_d_any_eve", A,
            "Last day. Books read this year — count them honestly. Plan next year's stack.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orle_birthday", A,
            "Your day. Light study — pick the fun book. The hard one waits.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orle_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orle_personal_date", A,
            "You marked this day: {label}. Reading load adjusted — take what the day allows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orle_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orle_complete_1", A, "Chapter done. Walk on.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orle_complete_2", A, "Logged. Note the key idea before it drifts.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orle_complete_3", A, "Done. The brain files it overnight.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orle_complete_first_today", A,
            "First study block. The book remembers you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orle_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orle_complete_second_today", A,
            "Two blocks. Do not burn out — comprehension drops past 90 minutes.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orle_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orle_complete_third_today", A,
            "Three. Real study day — the subject is denser than morning.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orle_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orle_complete_fourth_today", A,
            "Four. Stop — sleep on it. Tomorrow it will be clearer than rereading.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orle_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orle_complete_fifth_today", A,
            "Five. Past comprehension — you store words, not knowledge. Stop.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orle_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orle_complete_after_streak", A,
            "Day three of study. The subject comes alive — keep showing up.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orle_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orle_apotheosis_1", A,
            "Subject closed. Find a way to use it — knowledge unused leaks.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orle_apotheosis_2", A,
            "Course done. Teach someone the core idea — that is the test.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orle_apotheosis_3", A,
            "Closed. Write the summary now — future-you will need it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orle_apotheosis_first_ever", A,
            "First subject, top to bottom. You are no longer a beginner — notice.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orle_apotheosis_1", "orle_apotheosis_2", "orle_apotheosis_3"),
            theme = T),
        DialogueLine("orle_apotheosis_at_level_2", A,
            "Promoted. The map is wider — pick a harder subject next.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orle_apotheosis_at_level_3", A,
            "Senior tier. You teach the basics — keep learning the hard parts.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orle_apotheosis_at_level_4", A,
            "High tier. You have earned the right to specialize — the deep, narrow thing.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orle_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orle_nudge_morning", A,
            "Morning. One page — before the day eats you.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orle_nudge_afternoon_zero", A,
            "Halftime. Book unopened. Ten minutes — pick a paragraph.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orle_nudge_evening", A,
            "Evening. One chapter — then close it. The brain consolidates overnight.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orle_nudge_attention_loss", A,
            "Book dusty. Do not restart from page one — pick up where you left.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orle_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
