package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Digital hygiene. */
internal object OracleDigitalLines {

    private const val A = "ORACLE"
    private const val T = "DIGITAL"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ordi_first_ever", A,
            "You came asking about attention. I've read both endings — one where the phone owns you, one where you own it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ordi_morning", A,
            "I've read the mornings that start face-up. They end scattered. Phone down, the first hour — no exceptions.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ordi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ordi_morning_early", A,
            "Up before the house stirs. I've watched bed-to-feed happen in under two minutes. Not this draft.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ordi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ordi_afternoon", A,
            "Midday. Look at the honest number on the screen-time page. The rest of the day still bends around it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ordi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ordi_evening", A,
            "Evening table. Face-down beside the plate still pulls at you — I've read it. Put it in another room.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ordi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ordi_night_late", A,
            "Late, and the phone's still on the nightstand. I've read what that does to tomorrow. Out of the room, now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ordi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ordi_post_apotheosis", A,
            "The block closes. I've watched the first day after become a scroll of celebration — not this one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ordi_monday", A,
            "Seven days start blank. I've read the draft where the week's screen-time target gets written — and halved.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ordi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ordi_friday", A,
            "The week folds shut tonight. The weekend doesn't open on the feed — a phone-free dinner starts it instead.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ordi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ordi_weekend", A,
            "Two unscheduled days. Give one half of one to a phone in another room. I've read what you do with the quiet.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ordi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ordi_level_1_reached", A,
            "One knot tied. A week without the morning scroll — I can already read the difference in you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ordi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ordi_level_2_reached", A,
            "Twice woven. Screen time down a third — that hour is yours now. Don't hand it back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ordi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ordi_level_3_reached", A,
            "The pattern holds. The phone reads as a tool now, not a leash. The boundaries are what changed the reading.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ordi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ordi_level_4_reached", A,
            "I saw this height long ago and doubted it. The feed doesn't pull you now — the day's gone wide. Defend it daily.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ordi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ordi_attention_loss_mild", A,
            "Three days back on the feed. I watched the thread slip toward it. Phone out of the bedroom, tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "ordi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ordi_attention_loss_hard", A,
            "Two weeks of doomscroll, screen time tripled — I won't soften that. But the version where you uninstall today holds.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "ordi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ordi_mid_day_return", A,
            "Halfway through, and the number's already loud. Phone in a drawer for the next hour — I've read it working.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ordi_wishes_pending", A,
            "Something you're owed sits unclaimed. Spend it on a phone-free day, not another app — that reading holds better.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ordi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ordi_mid_streak", A,
            "Three days of low screen time now. The mind's gone quieter — don't hand tonight back to the feed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ordi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ordi_sant_jordi", A,
            "Roses and books change hands in the street today. Phone in your pocket, not your hand — the day's out there.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_la_merce", A,
            "Giants walk and fire runs the streets. Don't film the whole thing — see it. Hands free, eyes up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_sant_joan", A,
            "The shortest night, fires on the sand. Phone stays in the bag — be there, not behind the lens.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_diada", A,
            "The eleventh again. Take it off the news cycle — phone in a drawer for half the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_nadal", A,
            "Nadal. Phone in the bag at the table — the faces across from you are the whole reading today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_cap_d_any", A,
            "The year zeroes itself tonight. Audit the apps — delete two. That hour comes back to you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ordi_reis", A,
            "Gift morning, and some of the parcels are screens. Set the rules for those — starting with your own.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_carnaval", A,
            "Masks in the streets today. Don't film the parade — watch it. Phone away.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_divendres_sant", A,
            "The city stops mid-sentence today. Phone off for two hours — the quiet itself is the practice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_pasqua", A,
            "The pause releases today. Reset the notifications — three apps only, the rest go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_festa_del_treball", A,
            "A day named for work, spent not working. Hands and eyes get the rest — the phone doesn't. Step away.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_festa_major_gracia", A,
            "Gràcia built a year of paper sky for this week. It's for the eyes, not the lens — phone in your pocket.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_assumpcio", A,
            "Mid-August, the city half-emptied. Mute everything this week — let the notifications empty out too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_hispanitat", A,
            "A date that pulls in different directions. Take an honest look at the screen-time number — adjust from it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_castanyada", A,
            "Chestnut smoke, and the dark comes earlier now. Don't let the feed fill the long evening it leaves behind.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_constitucio", A,
            "A civic anniversary bridges the weekend. Phone off for one full day of it — no faking the reading.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_immaculada", A,
            "Five loose days strung together. Keep two phone-light — the notifications will still be there after.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_sant_esteve", A,
            "The day made from yesterday's leftovers, the house still full. Phone in another room — be where you are.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_cap_d_any_eve", A,
            "Twelve grapes tonight. Eyes on a screen instead of the room ruins the reading — phone away for this one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ordi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ordi_birthday", A,
            "The day your thread began, come round again. Phone off tonight — the room in front of you is the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ordi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_personal_date", A,
            "Today carries the name you gave it: {label}. Phone in your pocket — this one isn't for broadcasting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ordi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ordi_complete_1", A, "Phone down. Done. I saw this one coming.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ordi_complete_2", A, "Logged. The reward isn't a scroll — I've read where that leads.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ordi_complete_3", A, "Done. The thread pulls tight — that hour is yours again.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ordi_complete_first_today", A,
            "The first boundary held. The day's other, scattered versions quietly fold away.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ordi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ordi_complete_second_today", A,
            "Two phone-free blocks now. It compounds — don't undo it in the third hour.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ordi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ordi_complete_third_today", A,
            "Three. Hours reclaimed — I've read what you did with them. Notice it yourself too.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ordi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ordi_complete_fourth_today", A,
            "Four. This many resets in one day is either recovery or avoidance. Read yourself honestly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ordi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ordi_complete_fifth_today", A,
            "Five. Even phone-off becomes its own loop if you let it. I've read where that one goes too.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ordi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ordi_complete_after_streak", A,
            "Third day running of low screen time. The mind's calmer for it — hold the line.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ordi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ordi_apotheosis_1", A,
            "Crossed. The caps stay — I've watched “closing” turn into an excuse to scroll. Skip that draft.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ordi_apotheosis_2", A,
            "The cycle closes, and I see one room further than I did. Audit again — cut one more app. Always cut.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ordi_apotheosis_3", A,
            "Closed. The phone reads as a tool now, not a leash. Keep it that way.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ordi_apotheosis_first_ever", A,
            "Your first clean block. The scroll-hour went somewhere real instead. I had seen it — the arriving is better.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ordi_apotheosis_1", "ordi_apotheosis_2", "ordi_apotheosis_3"),
            theme = T),
        DialogueLine("ordi_apotheosis_at_level_2", A,
            "A second crossing. The phone stays a tool — defend it from whatever app comes to colonize it next.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ordi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ordi_apotheosis_at_level_3", A,
            "Another closing, and the pattern's visible from outside now — people copy your habits. Hold the line.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ordi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ordi_apotheosis_at_level_4", A,
            "We read from the same page now, you and the phone. Years of clear attention — defend the caps. No autopilot.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ordi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ordi_nudge_morning", A,
            "There's a version of this morning with the phone face-down and the first hour clean. You're still inside it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ordi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ordi_nudge_afternoon_zero", A,
            "The number's past target already. I've read the version where the phone goes in a drawer for an hour.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ordi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ordi_nudge_evening", A,
            "What you do with the phone this hour is what the bedroom inherits tonight. Leave it in the kitchen.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ordi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ordi_nudge_attention_loss", A,
            "The doomscroll's back, and I've read where it goes uncut. The uninstall today isn't optional.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "ordi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
