package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Friendship & community. */
internal object OracleFriendshipLines {

    private const val A = "ORACLE"
    private const val T = "FRIENDSHIP"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orfr_first_ever", A,
            "You came asking about friendship. It dies quiet — I've read that pattern too often. Send the text.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orfr_morning", A,
            "I've read the mornings when that one friend stays unheard from all week. Reach out before lunch.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orfr_morning_early", A,
            "Up before the house stirs — the friend in another timezone is awake too. A voice note, two minutes.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orfr_afternoon", A,
            "Midday. I've read the version where lunch happens alone at the desk. Not that one — find someone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orfr_evening", A,
            "That text you've been drafting all evening doesn't need perfecting. I've read both versions — send it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orfr_night_late", A,
            "Late — not the hour for the deep text. Note who it's for; tomorrow morning reads better.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orfr_post_apotheosis", A,
            "The stretch closes. I've watched the quiet creep in right after — a name's already on your mind.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orfr_monday", A,
            "Seven days start blank. I've read the draft where you plan the meetup instead of waiting to be invited.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orfr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orfr_friday", A,
            "The week folds shut tonight. End it face-to-face — drinks, a walk, anything that isn't a screen.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orfr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orfr_weekend", A,
            "Two unscheduled days. I've read the version that dissolves into the couch alone — brunch counts too.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orfr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orfr_level_1_reached", A,
            "One knot tied. The first real reach in a while — I watched them waiting on the other end.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orfr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orfr_level_2_reached", A,
            "Twice woven. You're the friend who shows up now — earned, not given. Don't slack on it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orfr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orfr_level_3_reached", A,
            "The pattern carries your handwriting now. People text you when things go wrong — a privilege. Honor it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orfr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orfr_level_4_reached", A,
            "I saw this height long ago. You build the community around you now, weekly — defend that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orfr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orfr_attention_loss_mild", A,
            "Three weeks gone quiet. I watched them notice. One real text today undoes most of it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orfr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orfr_attention_loss_hard", A,
            "Months of silence — I won't pretend otherwise. Skip the apology draft; invite them to coffee. Today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orfr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("orfr_mid_day_return", A,
            "Halfway through, and nobody's been reached. I've read the version where the text sends itself — it doesn't.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orfr_wishes_pending", A,
            "Something you're owed sits unclaimed. Pay for the drinks tonight — it doesn't spend itself sitting there.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orfr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orfr_mid_streak", A,
            "Three weeks of steady reach now. I can read the group holding tighter for it. Keep weaving.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orfr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orfr_sant_jordi", A,
            "Roses and books change hands in the street today. Walk it with a friend — buy them the one they wouldn't.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_la_merce", A,
            "Giants walk the streets, and the group's meeting somewhere in it. Find them — the noise isn't a reason to bail.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_sant_joan", A,
            "The shortest night, and the crew's on the sand. Bring something. Stay past the first fireworks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_diada", A,
            "The eleventh again. Give it to a long lunch with old friends — the errands can wait.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_nadal", A,
            "Nadal. Family fills most tables today — text the friend whose doesn't. They need it more.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_cap_d_any", A,
            "The year zeroes itself tonight. Send the wishes — real ones, one per friend, not a single group blast.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orfr_reis", A,
            "Gift morning. Drop the small one in person — five minutes at the door beats a shipping label.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_carnaval", A,
            "Masks in the streets, and the group's got costume plans. Be in it — “tired” isn't the text to send.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_divendres_sant", A,
            "The city stops mid-sentence today. A long walk with one friend — the kind where things get said.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_pasqua", A,
            "The pause releases today. Coffee with whoever's still in the city — don't waste the day off alone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_festa_del_treball", A,
            "A day named for work, spent not working. Barbecue or friends' lunch — pick one, show up fully.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_festa_major_gracia", A,
            "Gràcia built a year of paper sky for this week. Sit with friends under it. Stay past the first song.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_assumpcio", A,
            "Mid-August, and everyone's scattered. Send the voice notes — I've read what distance friendships need.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_hispanitat", A,
            "A date that pulls in different directions. Brunch with someone you've missed — don't reschedule this one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_castanyada", A,
            "Chestnut smoke, and friends huddled around panellets. Be in that circle.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_constitucio", A,
            "A civic anniversary bridges the weekend. A trip with friends, even a short one — time is the whole gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_immaculada", A,
            "Five loose days strung together. Give one to friends — phone off, real talk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_sant_esteve", A,
            "The day made from yesterday's leftovers. Drinks with whoever isn't at a family lunch — they're out there.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_cap_d_any_eve", A,
            "Twelve grapes tonight, and the year closes on schedule. Send the year-end note personal — not a blast.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orfr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orfr_birthday", A,
            "The day your thread began, come round again. Tonight's theirs to plan — receive it, don't direct it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orfr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_personal_date", A,
            "Today carries the name you gave it: {label}. The friend who reads what this means — call them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orfr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orfr_complete_1", A, "Reached. I saw that one coming.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orfr_complete_2", A, "Done. They felt it — the thread doesn't need you to check.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orfr_complete_3", A, "Logged. Phone away now — this one wasn't for broadcasting.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orfr_complete_first_today", A,
            "The first reach, made. The day's other, silent versions quietly fold away.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orfr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orfr_complete_second_today", A,
            "Two now. Pace it — the thread holds better on rhythm than volume.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orfr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orfr_complete_third_today", A,
            "Three. A real social day — I've read what avoidance does to tomorrow if you don't watch it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orfr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orfr_complete_fourth_today", A,
            "Four. Stop here — real friendship never needed the volume.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orfr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orfr_complete_fifth_today", A,
            "Five. I've read where this many in one day tips into overcompensating. Quality over count.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orfr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orfr_complete_after_streak", A,
            "Third day running. The group remembers your name for it — that's the whole game.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orfr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orfr_apotheosis_1", A,
            "Crossed. I've watched the quiet creep in right after — a name's already on your mind. Reach it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orfr_apotheosis_2", A,
            "It closes, and I see one room further than I did. Set the next group thing — don't wait on someone else.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orfr_apotheosis_3", A,
            "Closed. Maintain the rhythm — I've read how quiet the ones that die actually are. Yours won't be.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orfr_apotheosis_first_ever", A,
            "Your first real stretch of showing up. I had seen it coming — the group reads different because of you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orfr_apotheosis_1", "orfr_apotheosis_2", "orfr_apotheosis_3"),
            theme = T),
        DialogueLine("orfr_apotheosis_at_level_2", A,
            "A second crossing. People text you first now — that's earned, not given.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orfr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orfr_apotheosis_at_level_3", A,
            "Another closing. You're the connector now — keep introducing people. The network compounds on its own.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orfr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orfr_apotheosis_at_level_4", A,
            "We read from the same page now, you and this community. Defend it weekly. No autopilot.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orfr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orfr_nudge_morning", A,
            "There's a version of this morning with a real sentence to one friend. You're still inside it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orfr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orfr_nudge_afternoon_zero", A,
            "Halfway through, nobody reached yet. I've read the version where the text sends itself now, not later.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orfr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orfr_nudge_evening", A,
            "What you set tonight is what the week inherits. Plan the meetup — don't wait for an invitation.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orfr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orfr_nudge_attention_loss", A,
            "Months of silence, and I've read where the apology-first draft goes. Invite instead. Action first.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orfr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
