package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Relationships & love. */
internal object OracleLoveLines {

    private const val A = "ORACLE"
    private const val T = "LOVE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orlo_first_ever", A,
            "You came asking about love. I've read enough of these — the other person only needs you present. Eyes up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orlo_morning", A,
            "Before you leave, tell them one specific thing — not “have a good day.” I've read which one they carry.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_morning_early", A,
            "Up before the house stirs. Coffee for two if they're awake — the small acts are the whole of it, daily.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_afternoon", A,
            "Send them something real at midday — not a meme. A sentence. I've read the difference it makes.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_evening", A,
            "At dinner, leave the phone in the other room and look at each other. I've read the meals where you don't.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_night_late", A,
            "Late, and you're drifting onto separate screens — I've read where that ends. Reach over instead.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_post_apotheosis", A,
            "The stretch closes. Don't coast now — I've read the ones that do. A relationship pays rent every day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orlo_monday", A,
            "Seven days start blank. Plan one real thing together in them — I've read the weeks where it drifts to none.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orlo_friday", A,
            "The week folds shut tonight. The weekend is together-time — not two people on the same couch, apart.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orlo_weekend", A,
            "Two unscheduled days. One real conversation in them — slow, not logistics. The rest sorts itself out.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orlo_level_1_reached", A,
            "One knot tied. The first real check-in, and a wall came down with it — don't be the one who rebuilds it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orlo_level_2_reached", A,
            "Twice woven. They notice the effort now — and this is exactly where most people slack. I've read it. Don't.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orlo_level_3_reached", A,
            "The pattern carries your handwriting now. The relationship is its own living thing — tend it like a garden.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orlo_level_4_reached", A,
            "I saw this height long ago. Real partnership — defend it daily. There's no autopilot for this one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orlo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orlo_attention_loss_mild", A,
            "Three days of “fine” between you — I've read where that word leads. Ask one real question tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orlo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orlo_attention_loss_hard", A,
            "Two weeks of drifting — I won't pretend otherwise. But the version where you sit down tonight, no screens, holds.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orlo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("orlo_mid_day_return", A,
            "Halfway through, and no word between you yet. Text them now — a real sentence. I've read the version where you do.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orlo_wishes_pending", A,
            "Something you're owed sits unclaimed. Plan a date with it — now, before it goes cold sitting there.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orlo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orlo_mid_streak", A,
            "Three days of showing up now. They feel it, even unsaid — don't drop the thread here.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orlo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orlo_sant_jordi", A,
            "Roses and books change hands in the street today. Book or rose, it doesn't matter — show up with intention.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_la_merce", A,
            "Giants and fire in the streets, and crowds thick between them. Hold their hand — don't lose each other in the crush.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_sant_joan", A,
            "The shortest night: beach, fireworks, the two of you. Don't let it end on different couches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_diada", A,
            "The eleventh again, a day off. Spend it together — I've read the version filled with separate errands. Skip it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_nadal", A,
            "Nadal. Family takes the whole day — steal ten minutes alone with them. You both need it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_cap_d_any", A,
            "The year zeroes itself tonight. Let the first real conversation of it be honest — don't waste the opening.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orlo_reis", A,
            "Gift morning. Give them something specific, something that proves you were paying attention — not a last-minute grab.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_carnaval", A,
            "Masks in the streets tonight. Pick something silly together — the laughing about it is the point, not the costume.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_divendres_sant", A,
            "The city stops mid-sentence today. A long talk over coffee — only days this quiet make room for one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_pasqua", A,
            "The pause releases today. Reset the week together — a meal, a walk, anything that's just the two of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_festa_del_treball", A,
            "A day named for work, spent not working. The relationship is work too — honor the rest by showing up for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_festa_major_gracia", A,
            "Gràcia's paper sky is up. Walk the streets together, stop at one tiny stall — and don't lose each other under it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_assumpcio", A,
            "Mid-August, the heat sitting still and slowing everything. A long lunch together — no errands threaded through it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_hispanitat", A,
            "A day off, wide open. A trip out of the city — even an hour away counts as real together-time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_castanyada", A,
            "Chestnut smoke, and the first real cold. Walk together, buy a paper cone of them, stand close.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_constitucio", A,
            "A civic anniversary bridges the weekend. Plan one trip — it needn't be far. Just the two of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_immaculada", A,
            "Five loose days strung together. Rest together, or travel together — I've read the half-and-half version. Pick one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_sant_esteve", A,
            "The day made from yesterday's leftovers, the house still full. Steal a quiet moment alone with them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_cap_d_any_eve", A,
            "Twelve grapes tonight, and the year closes on schedule. Talk it over together, honestly — the good and the hard.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orlo_birthday", A,
            "The day your thread began, come round again. Receive what they planned — don't critique it. Just be there.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orlo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_personal_date", A,
            "Today carries the name you gave it: {label}. They read that it matters — bring them into it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orlo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orlo_complete_1", A, "Showed up. I saw that one coming.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orlo_complete_2", A, "Done. They felt it — the thread doesn't need you to fish for proof.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orlo_complete_3", A, "Logged. Phone away next time you sit with them.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orlo_complete_first_today", A,
            "The first real check-in. The day already reads different between you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orlo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orlo_complete_second_today", A,
            "Two reaches. Pace yourself — the thread holds better with air in it than smothered.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orlo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orlo_complete_third_today", A,
            "Three. The day ran full of them — that's what real partnership reads like.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orlo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orlo_complete_fourth_today", A,
            "Four. This many is either a big day or hovering. Read yourself honestly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orlo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orlo_complete_fifth_today", A,
            "Five. Give them space now — I've read where this tips. Connection isn't surveillance.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orlo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_complete_after_streak", A,
            "Third day of showing up running. They feel it — the thread doesn't need you to ask.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orlo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orlo_apotheosis_1", A,
            "Crossed. Keep showing up tomorrow — the same small disciplines that got you here.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orlo_apotheosis_2", A,
            "It closes, and the relationship reads stronger for it — don't coast on that credit now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orlo_apotheosis_3", A,
            "Closed. Plan the next thing together while it's warm — forward motion keeps the thread taut.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orlo_apotheosis_first_ever", A,
            "Your first real chapter together, fully shown up for. I had seen it — don't forget how it felt.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orlo_apotheosis_1", "orlo_apotheosis_2", "orlo_apotheosis_3"),
            theme = T),
        DialogueLine("orlo_apotheosis_at_level_2", A,
            "A second crossing. You're a real partner now — and this is exactly where most people slack. Don't.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orlo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_apotheosis_at_level_3", A,
            "Another closing. People read how you treat them now — stay consistent, even unwatched.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orlo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_apotheosis_at_level_4", A,
            "We read from the same page now. Defend the relationship like a deadline — no autopilot, ever.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orlo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orlo_nudge_morning", A,
            "There's a version of this morning with one specific thing said before you leave — not “love you, bye.”",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orlo_nudge_afternoon_zero", A,
            "Halfway through, no word between you yet. Text them a real sentence — I've read the version where you do.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orlo_nudge_evening", A,
            "What you do at dinner is what tonight remembers. Phone elsewhere — look at them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orlo_nudge_attention_loss", A,
            "Weeks of drifting, and I've read where it ends unspoken. Sit down tonight, no screens. Talk.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orlo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
