package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Oracle × Relationships & love. */
internal object OracleLoveLines {

    private const val A = "ORACLE"
    private const val T = "LOVE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("orlo_first_ever", A,
            "You came to ask of love. The other person needs you to show up — phone down, eyes up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("orlo_morning", A,
            "Morning. Tell them something specific before you leave — not 'have a good day'.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_morning_early", A,
            "Up early. Coffee for two, if they are up — small acts, daily.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_afternoon", A,
            "Mid-day. Text them something real — not a meme. A sentence.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_evening", A,
            "Evening. Phone in the other room when you eat — look at each other.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_night_late", A,
            "Late. Do not drift apart on separate screens — reach over.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "orlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_post_apotheosis", A,
            "Stretch closed. Do not coast — relationships pay the rent every day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("orlo_monday", A,
            "Monday. Plan one real thing together this week — do not let it drift.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "orlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orlo_friday", A,
            "Friday. The weekend is together-time — not 'beside each other on the couch'-time.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "orlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("orlo_weekend", A,
            "Weekend. One real conversation — slow. Not logistics.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "orlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("orlo_level_1_reached", A,
            "First threshold. First real check-in. The wall came down — do not rebuild it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "orlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orlo_level_2_reached", A,
            "Second threshold. They notice the effort — do not slack. That is when most do.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "orlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orlo_level_3_reached", A,
            "Third threshold. The relationship is its own thing — tend it like a garden.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "orlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("orlo_level_4_reached", A,
            "High tier. Real partnership — defend it daily. There is no autopilot.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "orlo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("orlo_attention_loss_mild", A,
            "Three days of 'fine'. The danger zone — one real question tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "orlo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("orlo_attention_loss_hard", A,
            "Two weeks of drifting. Sit down tonight — no screens. Talk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orlo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("orlo_mid_day_return", A,
            "Halftime. No contact yet — text them now. Real sentence.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("orlo_wishes_pending", A,
            "Reward accumulates. Plan a date — now. Stale wins go cold.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "orlo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("orlo_mid_streak", A,
            "Three days of showing up. They feel it — do not drop now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orlo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("orlo_sant_jordi", A,
            "Sant Jordi. Book or rose, no matter — show up with intention.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_la_merce", A,
            "Mercè. Crowds together — hold their hand. Do not lose each other in the crush.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_sant_joan", A,
            "Sant Joan. Beach, fireworks, together — do not end the night on different couches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_diada", A,
            "Diada. Day off together — do not fill it with separate errands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_nadal", A,
            "Nadal. Family takes the day — steal ten minutes alone. You need it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_cap_d_any", A,
            "New year. First conversation of the year — honest. Do not waste the moment.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orlo_reis", A,
            "Reis. Gift them something specific — not last-minute. Pay attention.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_carnaval", A,
            "Carnaval. Costume night together — pick something silly. Laugh about it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_divendres_sant", A,
            "Quiet day. Long talk over coffee — only quiet days allow this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_pasqua", A,
            "Pasqua Monday. Reset the week together — meal, walk, anything.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_festa_del_treball", A,
            "Workers' day. The relationship is work too — honor the rest. Show up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_festa_major_gracia", A,
            "Gràcia. Walk the streets together — one tiny stall. Do not lose each other.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_assumpcio", A,
            "August. Heat slows things. Long lunch together — no errands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_hispanitat", A,
            "Day off. Trip out of the city — even an hour away counts as together-time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_castanyada", A,
            "Castanyada. Walk together. Roasted chestnuts. Stand close in the cold.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_constitucio", A,
            "Bridge weekend. Plan one trip — doesn't have to be far. Just the two of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_immaculada", A,
            "Pont. Five days. Rest together, or travel — pick one fully.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_sant_esteve", A,
            "Day after. Family chaos — steal a quiet moment alone with them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_cap_d_any_eve", A,
            "Last day. Talk about the year together — honest. The good and the hard.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "orlo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("orlo_birthday", A,
            "Your day. Receive what they planned — do not critique it. Be present.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "orlo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_personal_date", A,
            "You marked this day: {label}. They know it matters — bring them in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "orlo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("orlo_complete_1", A, "Showed up. Next moment.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orlo_complete_2", A, "Done. They felt it — do not fish for proof.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orlo_complete_3", A, "Logged. Phone away when you sit with them.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("orlo_complete_first_today", A,
            "First real check-in. The day is already different between you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "orlo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("orlo_complete_second_today", A,
            "Two reaches. Pace yourself — do not smother.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "orlo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("orlo_complete_third_today", A,
            "Three. The day was full of them — real partnership.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "orlo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("orlo_complete_fourth_today", A,
            "Four. Either a big day or you hover — be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "orlo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("orlo_complete_fifth_today", A,
            "Five. Give them space — connection is not surveillance.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "orlo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("orlo_complete_after_streak", A,
            "Day three of showing up. They feel it — do not ask if they do.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "orlo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("orlo_apotheosis_1", A,
            "Stretch closed. Keep showing up tomorrow — same disciplines.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orlo_apotheosis_2", A,
            "Cycle done. The relationship is stronger — do not coast on the credit.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orlo_apotheosis_3", A,
            "Closed. Plan the next thing together — forward motion.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("orlo_apotheosis_first_ever", A,
            "First real chapter together, fully shown up for. Do not forget how it felt.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("orlo_apotheosis_1", "orlo_apotheosis_2", "orlo_apotheosis_3"),
            theme = T),
        DialogueLine("orlo_apotheosis_at_level_2", A,
            "Promoted. You are a real partner now — do not slack. That is when most do.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "orlo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_apotheosis_at_level_3", A,
            "Senior tier. People notice how you treat them — stay consistent.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "orlo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("orlo_apotheosis_at_level_4", A,
            "High tier. Defend the relationship like a deadline — no autopilot. Ever.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "orlo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("orlo_nudge_morning", A,
            "Morning. One specific thing before you leave — not 'love you, bye'.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "orlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orlo_nudge_afternoon_zero", A,
            "Halftime. No contact yet — text them. Real sentence. Now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "orlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orlo_nudge_evening", A,
            "Evening. Phone elsewhere when you eat — look at them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "orlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("orlo_nudge_attention_loss", A,
            "Weeks of drifting. Sit down tonight — no screens. Talk.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "orlo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
