package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Hobbies — lyrical, the joy-line. */
internal object PoetHobbiesLines {

    private const val A = "POET"
    private const val T = "HOBBIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptho_first_ever", A,
            "The hobby is the joy-line. Begin one small thing — just for itself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptho_morning", A,
            "A little hobby-time now, before the day eats it — the hands already know the way.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptho_morning_early", A,
            "A quiet session at first light, before anyone's asking anything of you. The day inherits the line.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptho_afternoon", A,
            "The light's gone slanting. Twenty minutes on the hobby, nothing else running — just the line.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptho_evening", A,
            "Twilight, and the hobby beats the television tonight — thirty minutes is plenty.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptho_night_late", A,
            "It's late — a soft hobby only, no new projects at this hour. Let the hands wind down.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptho_post_apotheosis", A,
            "The hands are fluent. Keep the daily slot — the line wants the practice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptho_monday", A,
            "The week opens like a fresh page. Schedule the hobby slots into it — then defend them like small chapels.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptho_friday", A,
            "The week is nearly a fair copy. A long hobby slot tonight — the hands have been waiting for it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptho_weekend", A,
            "The weekend is unscheduled margin — hours of play in it. The page rests; the hands do the talking.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptho_level_1_reached", A,
            "A monthly rhythm now, and holding. The hands are learning their own voice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptho_level_2_reached", A,
            "You finish projects now — an underrated miracle. The hands have started trusting the line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptho_level_3_reached", A,
            "Friends are asking about the work now. Keep the answers brief — the hands tell it better.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptho_level_4_reached", A,
            "Years of joyful play sit behind this. The hands have become the long poem themselves.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptho_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptho_attention_loss_mild", A,
            "A few skipped days on the hobby. Fifteen minutes now would do — the hands re-remember quickly.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptho_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptho_attention_loss_hard", A,
            "The hobby's gone quiet a while now. One small session today would bring it softly back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptho_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptho_mid_day_return", A,
            "A twenty-minute hobby reset would suit this hour — the mood tends to lift with the hands.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptho_wishes_pending", A,
            "There's a gift still waiting — a hobby supply, a small tool. Bring it to the table and open it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptho_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptho_mid_streak", A,
            "Three days of play running now. The hands are learning it by heart.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptho_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptho_sant_jordi", A,
            "Roses and books on every corner today. Buy the craft book you've been circling — the page opens from there.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_la_merce", A,
            "Fireworks over the rooftops tonight — a whole city of hobby-fuel. Bring a notebook with you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_sant_joan", A,
            "Bonfires on the beach tonight — the hobby can wait for tomorrow. Let the hands rest by the fire.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_diada", A,
            "Flags on the balconies today, and a long free stretch of it. A long hobby slot — let the hands fill the page.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_nadal", A,
            "The table's set long tonight. Show the family what you've made this year — the line travels that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_cap_d_any", A,
            "A new-notebook smell to the year. One hobby goal for it, named precisely — the hands like precision.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptho_reis", A,
            "Wrapping paper on the floor this morning — and maybe a new tool in it. Crack it open; the hands wake fast.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_carnaval", A,
            "Masks in the street today — costume-craft is a hobby too. Let the hands invent something.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_divendres_sant", A,
            "The city's gone quiet, shutters down. A long hobby session would fit the hush — the room receives it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_pasqua", A,
            "Everything closed, the light gone soft. Outdoor sketching weather — the trail sits for its own portrait.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_festa_del_treball", A,
            "All the city's tools are down today — except yours, if you want them. A slow hobby morning; the hands do the talking.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_festa_major_gracia", A,
            "Gràcia's streets are strung with paper stars again — photo-walk weather. The neighbourhood is the page tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_assumpcio", A,
            "Mid-August, the city half-emptied. Hours of play there for the taking — the long light helps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_hispanitat", A,
            "A day off on the calendar. A long hobby session would suit it — let the hands stretch out.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_castanyada", A,
            "Chestnut smoke on the corner, evenings running long. Good hobby hours now — the lamp is company enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_constitucio", A,
            "A bridge weekend ahead — deep-hobby hours in it, if you claim them. The page accepts whatever you bring.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_immaculada", A,
            "A pont of empty days ahead. Finish a project in them — the hands love a long unbroken write.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_sant_esteve", A,
            "The day after the feast, leftovers still warm. A slow hobby hour — the hands rest best while moving a little.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_cap_d_any_eve", A,
            "The year's last page. A year-of-hobby-wins list, if you like — small, specific, the kind that gets kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptho_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptho_birthday", A,
            "Your day — the poem of you gains a stanza. A hobby gift to yourself; the hands accept it softly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptho_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_personal_date", A,
            "Today carries its own mark — {label}. A hobby moment to honour it; hold the date in the shape you make.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptho_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptho_complete_1", A, "Played. The hands settle.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptho_complete_2", A, "Made — a small honest thing that wasn't here before.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptho_complete_3", A, "The hobby kept its slot today. Good.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptho_complete_first_today", A,
            "The first session of the day — the mood lifts at its own pace from here.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptho_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptho_complete_second_today", A,
            "Two now. The hands compound; the line's going somewhere.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptho_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptho_complete_third_today", A,
            "Three. The flow's holding — the hands have gone fluent.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptho_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptho_complete_fourth_today", A,
            "Four. Water, food — let the body interrupt the page for a minute.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptho_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptho_complete_fifth_today", A,
            "Five. A big play day. Stop now, rest — the line accepts a pause gladly.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptho_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptho_complete_after_streak", A,
            "Three days of play running now. The hands are learning it by heart.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptho_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptho_apotheosis_1", A,
            "A cycle of play closes. The hands settle better than they were.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptho_apotheosis_2", A,
            "Wrapped. The next small project is already waiting — specific, and quiet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptho_apotheosis_3", A,
            "Closed. The hobby is also a writing practice.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptho_apotheosis_first_ever", A,
            "The first real block, finished. The hobby is becoming habit — the hands have found home.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptho_apotheosis_1", "ptho_apotheosis_2", "ptho_apotheosis_3"),
            theme = T),
        DialogueLine("ptho_apotheosis_at_level_2", A,
            "You finish projects now. Keep the rhythm — the hands trust the line for it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptho_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptho_apotheosis_at_level_3", A,
            "Friends are asking about it now. Keep the answers brief — the hands tell more than words could.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptho_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptho_apotheosis_at_level_4", A,
            "Years of joyful play behind this. The hands have become the long poem itself.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptho_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptho_nudge_morning", A,
            "A little hobby time before the day gets going — the hands already know the way.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptho_nudge_afternoon_zero", A,
            "Twenty minutes on it now — the mood tends to lift with the hands.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptho_nudge_evening", A,
            "The hobby beats the television tonight — thirty minutes is plenty.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptho_nudge_attention_loss", A,
            "One small session today would bring it softly back — the hands re-remember quickly.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptho_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
