package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Boundaries — lyrical, the kept margin. */
internal object PoetBoundariesLines {

    private const val A = "POET"
    private const val T = "BOUNDARIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptbo_first_ever", A,
            "A poem is mostly margin — that's what lets the line breathe. One kept “no” today would begin yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptbo_morning", A,
            "Somewhere in today there's a “no” with your name on it. Found before the email opens, it holds better.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptbo_morning_early", A,
            "The inbox is still asleep — no need to wake it. This first hour reads better unshared.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptbo_afternoon", A,
            "The light is slanting, and here comes the “just one more”. That's the line the margin was drawn for.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptbo_evening", A,
            "The work has had its hours. With the notifications off, the evening becomes a room with the door shut — yours.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptbo_night_late", A,
            "Whoever is asking at this hour isn't reading your hours. The answer will keep till morning — answers do.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptbo_post_apotheosis", A,
            "The margin holds, white and quiet. The next “yes” will come knocking — worth a breath at the door first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptbo_monday", A,
            "The week arrives already annotated in other hands. Whatever was added without your consent can be struck through.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptbo_friday", A,
            "The weekend is close enough to touch. The late work-creep will test the fence — it doesn't have to get in.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptbo_weekend", A,
            "Family hours, the phone on silent in another room — some margins aren't up for negotiation, and this is one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptbo_level_1_reached", A,
            "One real “no” kept this week, and the world went on turning. Worth writing down somewhere you'll find it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptbo_level_2_reached", A,
            "The limits hold without rehearsal now, and others are learning them by heart. That's how margins teach.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptbo_level_3_reached", A,
            "People have stopped asking the wrong way. The boundary did the teaching — you only had to keep it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptbo_level_4_reached", A,
            "Years of clean limits, and the calendar reads like your own handwriting. The page is wider than it was.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptbo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptbo_attention_loss_mild", A,
            "Three days of yes-to-everything, and the margin is thinning. One soft refusal would ink it back.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptbo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptbo_attention_loss_hard", A,
            "Two weeks with the margin worn to nothing. One block reclaimed today — softly, the hard one — redraws the line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptbo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptbo_mid_day_return", A,
            "The calendar has filled with other people's handwriting. One hour blocked back would put yours on the page.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptbo_wishes_pending", A,
            "A gift waits — a real day off. Not another favour for someone else.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptbo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptbo_mid_streak", A,
            "Three days of held limits, and the days are quieter, clearer — the line settling into the paper.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptbo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptbo_sant_jordi", A,
            "Sant Jordi, roses on the corners. Out of office is the right answer today — the streets are the work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_la_merce", A,
            "La Mercè, and the whole city is off — you too. It sounds truer said out loud, with the phone gone dark.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_sant_joan", A,
            "Sant Joan — fires on the beach until late. Tomorrow's early call can go unanswered; tomorrow is yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_diada", A,
            "The Diada fills the balconies with flags, and the day is yours. Any asks can meet a polite, unhurried no.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_nadal", A,
            "Nadal — the table long, the phone in another room. That small distance is the whole boundary, kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_cap_d_any", A,
            "A new year, blank as fresh paper. Two commitments that were never yours could stay in the old one — named today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptbo_reis", A,
            "Reis — a day that belongs to family and small hands. One clear decline, and the rest of it stays whole.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_carnaval", A,
            "Carnaval fills the week with invitations. One party skipped keeps the next two alive — counts less, carries more.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_divendres_sant", A,
            "The city has lowered its shutters and its voice — a whole town keeping a limit. Today is good for copying it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_pasqua", A,
            "Pasqua Monday. Friday's missed work will ask to be made up — it can be told, gently, no.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_festa_del_treball", A,
            "Workers' day — the oldest boundary on the calendar, the one between labour and rest. It holds if you let it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_festa_major_gracia", A,
            "Gràcia strings its streets with stars for a week. Two nights chosen, the rest declined — no one can give every evening.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_assumpcio", A,
            "Mid-August, and the city itself is out of office. A real away message, no side doors — the town shows how.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_hispanitat", A,
            "A bridge day — a small island of unclaimed time. Politely defended, it stays yours all the way to evening.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_castanyada", A,
            "Chestnut smoke on the corners, and year-end pressure lighting its first fires. Scope-creep refused now stays small.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_constitucio", A,
            "A bridge weekend — two white days. They hold better once you've said, out loud, that no work is coming in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_immaculada", A,
            "The pont opens wide, and with it the “quick favour” email. Refused early, it sets the limit for the whole bridge.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_sant_esteve", A,
            "Sant Esteve, the long table again. An hour slipped away with your coat on counts as a “no” — a kind one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_cap_d_any_eve", A,
            "The year's last page. Somewhere on it are three commitments that were never yours — tonight is good for naming them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptbo_birthday", A,
            "Your day — one obligation refused tonight would be a gift in your own wrapping. The page accepts it gladly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptbo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_personal_date", A,
            "Today carries {label} in your own hand. The noise can wait outside — this hour reads better unshared.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptbo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptbo_complete_1", A, "A “no”, said — and the line steadies under it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptbo_complete_2", A, "The limit held, and the room got quieter.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptbo_complete_3", A, "An hour back in your own hands.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptbo_complete_first_today", A,
            "The first refusal of the day, and the sky still where it was. Worth remembering next time it threatens to fall.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptbo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptbo_complete_second_today", A,
            "Two limits held now — a pattern forming, and others quietly learning to read it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptbo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptbo_complete_third_today", A,
            "Three. The day is quieter — defended, not earned.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptbo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptbo_complete_fourth_today", A,
            "Four. A heavy day for limits — or the pen picking fights? Only you can read that line honestly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptbo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptbo_complete_fifth_today", A,
            "Five. A margin is for breathing, not for battle — past a point, the counting is the war.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptbo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptbo_complete_after_streak", A,
            "Three days of clear limits, and the calendar finally tells the truth. The line holds.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptbo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptbo_apotheosis_1", A,
            "A cycle closes. The next “yes” will arrive soon enough — it can wait on the doorstep while you breathe.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptbo_apotheosis_2", A,
            "Wrapped, and quietly. Limits don't graduate — the next one will want the same steady hand.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptbo_apotheosis_3", A,
            "Closed. The boundary is the practice itself — it keeps you the way a margin keeps a poem, daily.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptbo_apotheosis_first_ever", A,
            "First block. Limits are canon. The yes-to-everything loop is broken.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptbo_apotheosis_1", "ptbo_apotheosis_2", "ptbo_apotheosis_3"),
            theme = T),
        DialogueLine("ptbo_apotheosis_at_level_2", A,
            "Calendar is yours. Defend it from the new request that just arrived.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptbo_apotheosis_at_level_3", A,
            "Others learn the limits without asking. Be the steady one.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptbo_apotheosis_at_level_4", A,
            "Years of clean limits. The calendar tells your story.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptbo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptbo_nudge_morning", A,
            "Name one 'no' for today. Before email opens.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptbo_nudge_afternoon_zero", A,
            "Block one hour back. Now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptbo_nudge_evening", A,
            "Notifications off. Work is done.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptbo_nudge_attention_loss", A,
            "Reclaim one block today — softly. The hard one.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptbo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
