package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Learning — lyrical, the brain as a kept garden. */
internal object PoetLearningLines {

    private const val A = "POET"
    private const val T = "LEARNING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptle_first_ever", A,
            "The brain is a small garden, and today only asks for one line planted — tomorrow's job is watering it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptle_morning", A,
            "One lesson alongside the coffee, twenty minutes only — the brain is at its freshest right now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_morning_early", A,
            "The light's barely up, and already there's room for one small chapter — the day's first kept promise.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_afternoon", A,
            "The shadows have started to lean — fifteen minutes now, before the slump, gets ahead of the dim.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_evening", A,
            "The light's going soft now — a lesson with tea, the slow-brain kind, is the most underrated stanza of the day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_night_late", A,
            "It's late, and the brain isn't holding anything new tonight — sleep is the lesson now, so trust the dark.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_post_apotheosis", A,
            "The garden holds what was planted — keep the daily lesson going, since the curve forgets the moment you stop.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptle_monday", A,
            "Two lesson goals for the week, pencilled in small and specific — the kind that actually get kept.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptle_friday", A,
            "One thing landed this week worth naming — Friday's only real job is to honour it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptle_weekend", A,
            "Long-form study or actual rest — both teach something, so pick the one you honestly need.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptle_level_1_reached", A,
            "A month of small lessons, and the brain has grown its own light out of them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptle_level_2_reached", A,
            "The skill has stepped off the page and into real life now — the line travels.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptle_level_3_reached", A,
            "Friends have started asking you now — teach it softly, the line belongs to the world once it's shared.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptle_level_4_reached", A,
            "Years of joyful learning have folded in on themselves — the garden and the brain are the same thing now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptle_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptle_attention_loss_mild", A,
            "A few sessions skipped, nothing more — the course is patient, and ten minutes today would be plenty, gently.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptle_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptle_attention_loss_hard", A,
            "The course has gone quiet for a while now — one tiny lesson today, and the garden remembers everything.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptle_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptle_mid_day_return", A,
            "A twenty-minute lesson would suit right about now — the brain loves the variety. Begin again.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptle_wishes_pending", A,
            "A gift waits — a book, not another course. The garden likes depth.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptle_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptle_mid_streak", A,
            "Three days of lessons in a row now — the brain has gone soft and absorbent again, like a sponge.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptle_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptle_sant_jordi", A,
            "Roses on every corner, books changing hands — buy one, crack the spine, the day only asks for a chapter.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_la_merce", A,
            "Fireworks and giants fill the streets tonight — but a quiet museum drop-in counts too, learning in disguise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_sant_joan", A,
            "Bonfires on the beach tonight — let the brain switch off completely, tomorrow's lesson will thank you for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_diada", A,
            "Flags on every balcony today — it's a long-read kind of day, cosy and a little iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_nadal", A,
            "The table's set long tonight, and the stories family tells are oral history — listen closely, that counts too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_cap_d_any", A,
            "The year turns over fresh — pick one learning goal, small and specific, the garden likes precision.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptle_reis", A,
            "A book arrived among the gifts today — crack it open now, the old lore is specific about that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_carnaval", A,
            "Masks in the street, everyone rehearsing someone else — take the day off learning, let the brain ferment a while.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_divendres_sant", A,
            "The city's gone quiet and slow today — good weather for one unhurried chapter, hands steady on the line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_pasqua", A,
            "Spring's in the air for the hike today — bring an audiobook along, two for one, walking and learning at once.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_festa_del_treball", A,
            "Every tool in the city rests today — a documentary counts as chill learning, the brain resting sideways too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_festa_major_gracia", A,
            "Gràcia's streets are strung with paper stars, Catalan on every wall — learn five words today, and learn them well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_assumpcio", A,
            "The city's half-emptied in the August heat — a big book and a hammock, and the plot fully endorses it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_hispanitat", A,
            "A heavy name for a day off — pair a small lesson with a walk, a modest couplet of a day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_castanyada", A,
            "Chestnut smoke on the corner and the evenings running long — good weather for a cosy stanza of study.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_constitucio", A,
            "A bridge weekend opens up some room — a longer lesson, an hour or two, lets the brain properly stretch.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_immaculada", A,
            "A short bridge of free days ahead — pick one for a real deep dive, the rest can be naps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_sant_esteve", A,
            "The day after the feast, chairs still out of place — a light read suits it, the brain running on low power.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_cap_d_any_eve", A,
            "The year's last page tonight — list out everything learned this year, and celebrate the brain that held it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptle_birthday", A,
            "A year added overnight — plant three small skills in it, and pick the ones that are actually joy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptle_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_personal_date", A,
            "The day carries a private mark — {label} — and today's lesson lands with a little more weight for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptle_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptle_complete_1", A, "A line learned — the garden holds it now.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptle_complete_2", A, "Logged away — the brain has a little more sky in it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptle_complete_3", A, "Brain-glow, small and real.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptle_complete_first_today", A,
            "The first lesson of the day — the brain wakes, and the page resumes where it left off.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptle_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptle_complete_second_today", A,
            "Two now — the curve is loading, slow and right.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptle_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptle_complete_third_today", A,
            "Three in now — the brain glows a little, and the line holds.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptle_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptle_complete_fourth_today", A,
            "Four lessons in — an exam coming, or just a good run? Either way, drink some water.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptle_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptle_complete_fifth_today", A,
            "Five today — close the book now and walk, the brain consolidates best in motion.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptle_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_complete_after_streak", A,
            "Three days of lessons in a row now — the skill is growing quietly, under the surface.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptle_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptle_apotheosis_1", A,
            "A cycle of lessons closes today, and the garden is bigger than it was this morning.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptle_apotheosis_2", A,
            "Wrapped for now — the next tiny lesson is already waiting, specific and quiet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptle_apotheosis_3", A,
            "Closed now — and the page is wider than it was.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptle_apotheosis_first_ever", A,
            "The first block closes — lessons have become habit now, and the garden is real.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptle_apotheosis_1", "ptle_apotheosis_2", "ptle_apotheosis_3"),
            theme = T),
        DialogueLine("ptle_apotheosis_at_level_2", A,
            "The skill is showing in real life now, a quiet kind of confidence — keep planting.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_apotheosis_at_level_3", A,
            "You're teaching friends now — the line belongs to the world once it's shared like that.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_apotheosis_at_level_4", A,
            "Years of joyful learning add up to this — the brain itself has become the long poem.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptle_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptle_nudge_morning", A,
            "A fifteen-minute lesson alongside the coffee — the brain is at its freshest right now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptle_nudge_afternoon_zero", A,
            "A twenty-minute lesson break would suit the afternoon — the brain loves a change of pace.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptle_nudge_evening", A,
            "A light lesson alongside the tea — still the most underrated stanza of the day.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptle_nudge_attention_loss", A,
            "One tiny lesson today — the garden remembers.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptle_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
