package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Gratitude — lyrical, the small noticed line. */
internal object PoetGratitudeLines {

    private const val A = "POET"
    private const val T = "GRATITUDE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptgr_first_ever", A,
            "Gratitude is the small noticed line. Name one thing — even if it's only the light.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptgr_morning", A,
            "Three small things, right now — the day already brightens for having named them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptgr_morning_early", A,
            "The quiet at first light is worth noting. The day inherits whatever line you give it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptgr_afternoon", A,
            "The light's gone slanting. One thing that went right today — note it, no need to dramatize.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptgr_evening", A,
            "Twilight — a three-thing list before sleep, the credits rolling on the day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptgr_night_late", A,
            "It's late. One good thing from today — just one. Sleep with it close.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptgr_post_apotheosis", A,
            "The noticing holds. Keep the daily list — the page brightens with use.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptgr_monday", A,
            "The week opens like a fresh page. Three things to look forward to in it — specific, no gilding.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptgr_friday", A,
            "The week is nearly a fair copy. Three moments from it worth keeping — specific, and honestly kind.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptgr_weekend", A,
            "The weekend asks for slow noticing — small things, the kind that warm the eye given time.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptgr_level_1_reached", A,
            "A month of lists. The mood lifts at its own pace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptgr_level_2_reached", A,
            "You catch yourself smiling at small things. A grace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptgr_level_3_reached", A,
            "Others notice the warmth. They learn the small line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptgr_level_4_reached", A,
            "Years of noticing sit behind this. The glow is real, and quiet the way real things are.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptgr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptgr_attention_loss_mild", A,
            "A few flat days now. One thing today would do — even the coffee counts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptgr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptgr_attention_loss_hard", A,
            "A heavy stretch lately. One small thing today — even the window light counts. Softly, no pressure.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptgr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptgr_mid_day_return", A,
            "Look up for a moment — one thing visible right now. Note it, no need to dramatize.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptgr_wishes_pending", A,
            "There's a gift still waiting — a small kindness to yourself. Let yourself receive it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptgr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptgr_mid_streak", A,
            "Three days of lists. The mood is steadier than it was.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptgr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptgr_sant_jordi", A,
            "Roses and books on every corner today. Note the ones that came your way — hold them a moment.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_la_merce", A,
            "Fireworks over the rooftops tonight. Note one street-moment from it — hold it, the day fills up that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_sant_joan", A,
            "Bonfires on the beach tonight — sparks, sea, friends. Note one of them; the line keeps that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_diada", A,
            "Flags on the balconies today. One small thing in the long day of it — hold that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_nadal", A,
            "The table's set long tonight. One family moment worth noticing — hold it close.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_cap_d_any", A,
            "A new-notebook smell to the year. A year-of-wins list, if you want one — specific, and the page receives it gladly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptgr_reis", A,
            "Wrapping paper on the floor this morning. Note the gift, and send the thank-you — the line travels both ways.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_carnaval", A,
            "Masks in the street today. Note the belly-laughs when they come — those lines write themselves.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_divendres_sant", A,
            "The city's gone quiet, shutters down. The silence itself is worth noting today — it is the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_pasqua", A,
            "Everything closed, the light gone soft. Somewhere on the trail today there'll be a moment — note it, hold it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_festa_del_treball", A,
            "All the city's tools are down today. The day off itself is worth noting — it's also a gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_festa_major_gracia", A,
            "Gràcia's streets are strung with paper stars again. Note the neighbours' decorations — they worked all year for you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_assumpcio", A,
            "Mid-August, the city half-emptied and slow. Note one warm thing in it — hold it a moment.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_hispanitat", A,
            "A day off on the calendar. One small joy somewhere in it — note it, and hold it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_castanyada", A,
            "Chestnut smoke on the corner — autumn's oldest smell. Note it; the season itself is the line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_constitucio", A,
            "A bridge weekend ahead — two whole free days. Worth noting on their own; they are the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_immaculada", A,
            "A pont of empty days ahead. An appreciate-list to fill some of it — small, exact, kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_sant_esteve", A,
            "The day after the feast, leftovers still warm. There's a leftover moment worth noticing too — hold it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_cap_d_any_eve", A,
            "The year's last page. A year-of-small-moments list, if you like — the line closes warm that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptgr_birthday", A,
            "Your day — the poem of you gains a stanza. One good thing per year you've had, small and specific. Hold them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptgr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_personal_date", A,
            "Today carries its own mark — {label}. Note one thing from the original day, and hold it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptgr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptgr_complete_1", A, "Noted. The page warms.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptgr_complete_2", A, "Joy logged. Quiet.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptgr_complete_3", A, "Glow-noticing. Real.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptgr_complete_first_today", A,
            "First gratitude. The mood lifts at its own pace.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptgr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptgr_complete_second_today", A,
            "Two. The joys compound, small.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptgr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptgr_complete_third_today", A,
            "Three. The eye warms. Good.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptgr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptgr_complete_fourth_today", A,
            "Four. A big-glow day, or forcing the line? Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptgr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptgr_complete_fifth_today", A,
            "Five. Stop counting joy. Just be in it.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptgr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptgr_complete_after_streak", A,
            "Three days of lists. The mood is steadier than it was.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptgr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptgr_apotheosis_1", A,
            "A cycle of noticing closes. The eye warms.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptgr_apotheosis_2", A,
            "Wrapped. The next small list — specific. Quiet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptgr_apotheosis_3", A,
            "Closed. The glow is also a writing practice.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptgr_apotheosis_first_ever", A,
            "First block. Daily gratitude is habit. The page brightens with use.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptgr_apotheosis_1", "ptgr_apotheosis_2", "ptgr_apotheosis_3"),
            theme = T),
        DialogueLine("ptgr_apotheosis_at_level_2", A,
            "You catch small joys without thinking. A grace.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptgr_apotheosis_at_level_3", A,
            "Others notice the warmth. They learn the small line.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptgr_apotheosis_at_level_4", A,
            "Years of noticing. The glow is real and quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptgr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptgr_nudge_morning", A,
            "Three things. Quick. Don't dramatize.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptgr_nudge_afternoon_zero", A,
            "Look up. One thing right now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptgr_nudge_evening", A,
            "Three-thing list before sleep. The credits roll.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptgr_nudge_attention_loss", A,
            "One small good thing today — even the light.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptgr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
