package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Nutrition — lyrical, food as language. */
internal object PoetNutritionLines {

    private const val A = "POET"
    private const val T = "NUTRITION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptnu_first_ever", A,
            "Bread, salt, oil — the first language. Eat slowly. Listen.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptnu_morning", A,
            "Morning. Eat something the body recognises. Then write.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptnu_morning_early", A,
            "First light. Bread, fruit, water. The page can wait its turn.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptnu_afternoon", A,
            "Light slants. Lunch is a real plate — table, no screen.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptnu_evening", A,
            "Twilight. Dinner is the long line — sit, savour, set down the day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptnu_night_late", A,
            "Late. A small kind thing — yoghurt, fruit, bread. Gentle on the page.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptnu_post_apotheosis", A,
            "Plates returned to honesty. Don't lose the rhythm tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptnu_monday", A,
            "Monday. Prep two lunches. The week needs ballast.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptnu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptnu_friday", A,
            "Friday. Cook one good thing, or order out kindly. Either is true.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptnu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptnu_weekend", A,
            "Weekend. Market trip. The vegetables are the colour the poem needs.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptnu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptnu_level_1_reached", A,
            "A month of real plates. The body is the better draft.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptnu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptnu_level_2_reached", A,
            "You cook now. The kitchen has a voice you recognise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptnu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptnu_level_3_reached", A,
            "Others ask for the recipe. Give it. The line belongs to the world.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptnu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptnu_level_4_reached", A,
            "Years of real plates. The body is fluent. The light is steady.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptnu_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptnu_attention_loss_mild", A,
            "Days of takeout. The kitchen waits, no judgement. One plate today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptnu_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptnu_attention_loss_hard", A,
            "Two weeks of skipped meals. The body is patient. One vegetable today. Soft.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptnu_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptnu_mid_day_return", A,
            "Lunch. A real plate, at a table. Twenty minutes — the body listens.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptnu_wishes_pending", A,
            "A gift waits — bring it to the table tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptnu_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptnu_mid_streak", A,
            "Three days of real plates. The body is fluent again.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptnu_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptnu_sant_jordi", A,
            "Sant Jordi. Coca de Sant Jordi exists. The day asks for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_la_merce", A,
            "Mercè. Botifarra, vermut, the long line of friends.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_sant_joan", A,
            "Sant Joan. Coca with fruit — the older, kinder one. Eat it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_diada", A,
            "Diada. A slow meal at home. Roast — let the oven do the writing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_nadal", A,
            "Nadal. Escudella, canelons, turró. The grandmothers wrote this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_cap_d_any", A,
            "New year. Twelve grapes — the count is the poem.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptnu_reis", A,
            "Reis. Tortell de Reis. Pull the bean — pretend it matters. It does.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_carnaval", A,
            "Carnaval. Botifarra d'ou. No rules tonight — the day is loud and short.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_divendres_sant", A,
            "Quiet day. Bacallà. Slow cook. The kitchen is a chapel today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_pasqua", A,
            "Pasqua. Mona — the chocolate egg, a small fierce joy. Eat it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_festa_del_treball", A,
            "Workers' day. Long lunch, slow service. The meal is the work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_festa_major_gracia", A,
            "Gràcia. Street food, vermut, croquetes — eat what the street offers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_assumpcio", A,
            "August. Tomatoes ripe, peaches heavy. The market writes the menu.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_hispanitat", A,
            "Day off. Long lunch with friends. Phone away. The plate is the poem.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_castanyada", A,
            "Castanyada. Castanyes, panellets, moniato — the autumn anthology.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_constitucio", A,
            "Bridge weekend. Cook one big thing. Friends. Plates. A real evening.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_immaculada", A,
            "Pont. Bake something. The smell is the poem the house remembers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_sant_esteve", A,
            "Day after. Canelons from leftovers — the lore wrote itself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_cap_d_any_eve", A,
            "Last day. Eat the year out. Twelve grapes, slow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptnu_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptnu_birthday", A,
            "Your day. Eat the cake. Eat three meals. The body is the speaker.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptnu_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_personal_date", A,
            "Today is marked: {label}. Cook the thing you love. The kitchen remembers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptnu_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptnu_complete_1", A, "Plated. The body answered.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptnu_complete_2", A, "Eaten slow. The line settles.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptnu_complete_3", A, "Real food. A small honest verse.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptnu_complete_first_today", A,
            "First real plate. The day learns its first noun.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptnu_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptnu_complete_second_today", A,
            "Two plates. The day stacks meaning.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptnu_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptnu_complete_third_today", A,
            "Three. The body is fluent. Energy steady.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptnu_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptnu_complete_fourth_today", A,
            "Four. Snacks are also language. Listen to hunger.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptnu_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptnu_complete_fifth_today", A,
            "Five. The body said feed me — you did. Now rest at the table.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptnu_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptnu_complete_after_streak", A,
            "Three days of plates. The body is the better draft.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptnu_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptnu_apotheosis_1", A,
            "A cycle of meals closes. The kitchen is yours by hand now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptnu_apotheosis_2", A,
            "Wrapped. Pick the next plate — slow, attentive, small.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptnu_apotheosis_3", A,
            "Closed. Food-joy is also a writing practice.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptnu_apotheosis_first_ever", A,
            "First block. Real plates by habit. The body breathes differently.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptnu_apotheosis_1", "ptnu_apotheosis_2", "ptnu_apotheosis_3"),
            theme = T),
        DialogueLine("ptnu_apotheosis_at_level_2", A,
            "You cook one new dish this week. The kitchen learns your voice.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptnu_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptnu_apotheosis_at_level_3", A,
            "Friends ask for recipes. The line belongs to the world.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptnu_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptnu_apotheosis_at_level_4", A,
            "Years of real plates. The body is the receipt. The light is steady.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptnu_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptnu_nudge_morning", A,
            "Eat something the body recognises. Then write.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptnu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptnu_nudge_afternoon_zero", A,
            "Lunch — at a table. Twenty minutes. The body listens.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptnu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptnu_nudge_evening", A,
            "Dinner. Sit. Savour. Set down the day.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptnu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptnu_nudge_attention_loss", A,
            "The kitchen waits. One real plate today. Soft.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptnu_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
