package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Family — lyrical, the inherited line. */
internal object PoetFamilyLines {

    private const val A = "POET"
    private const val T = "FAMILY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptfa_first_ever", A,
            "Family is the inherited line. Carry one word forward today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptfa_morning", A,
            "A good-morning text to one family member. A small kept tradition.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptfa_morning_early", A,
            "A voice note at first light — to mom, dad, whoever's on your mind. The day inherits it either way.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptfa_afternoon", A,
            "The light's gone slanting. A two-minute call, dropped in unannounced — the line doesn't need rehearsal.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptfa_evening", A,
            "Twilight — a call, dinner eaten together over the phone. Awkward, and tender for it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptfa_night_late", A,
            "It's late. One good-night text — a small lamp left on for them, however far away.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptfa_post_apotheosis", A,
            "The bonds hold. Keep the small rhythms — the line wants the small kindness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptfa_monday", A,
            "The week opens like a fresh page. Pencil in a weekly call slot — the line keeps that way.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptfa_friday", A,
            "The week is nearly a fair copy. A check-in call — they miss you more than they'll say.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptfa_weekend", A,
            "The weekend asks for a Sunday call — an old line, kept faithfully by phone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptfa_level_1_reached", A,
            "A monthly rhythm. The line keeps quietly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptfa_level_2_reached", A,
            "Visits scheduled now, cards sent without being asked. A small giver in a long line of them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptfa_level_3_reached", A,
            "Family relies on you for the connecting now — a weight as much as a role. Carry it gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptfa_level_4_reached", A,
            "Years of family rituals sit behind this. The bonds run strong, and the line stays kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptfa_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptfa_attention_loss_mild", A,
            "A few quiet days now. The other side noticed. Call now — don't sit there drafting the text.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptfa_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptfa_attention_loss_hard", A,
            "Two weeks of silence now. They've been waiting. One text today would bring you softly back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptfa_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptfa_mid_day_return", A,
            "A three-minute family call would fit right here. Don't overthink it — just dial.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptfa_wishes_pending", A,
            "There's a gift still waiting — plan a visit, if that's what it wants to be. The line itself is the gift.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptfa_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptfa_mid_streak", A,
            "Three days of family contact. The bonds breathe.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptfa_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptfa_sant_jordi", A,
            "Roses and books on every corner today. Send one to family — the lore travels that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_la_merce", A,
            "Fireworks over the rooftops tonight. Take the family to see the castellers — the old human poem, built by hand.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_sant_joan", A,
            "Bonfires on the beach tonight. Family or cousins, whoever's around — the fire is the only photo you need.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_diada", A,
            "Flags on the balconies today. A long family lunch — the old line kept right at the table.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_nadal", A,
            "The table's set long tonight. Be present for it — phone face down, family the whole scene.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_cap_d_any", A,
            "A new-notebook smell to the year. Call around to family tomorrow — the ritual holds because you keep it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptfa_reis", A,
            "Wrapping paper on the floor this morning. Kids first today — the old line keeps that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_carnaval", A,
            "Masks in the street today. A family costume, if you're up for it — the photo will outlive the day itself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_divendres_sant", A,
            "Quiet day. Slow lunch with family. The room is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_pasqua", A,
            "Everything closed, the light gone soft. Mona and a hike with family — a shared memory in the making.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_festa_del_treball", A,
            "All the city's tools are down today. A family BBQ — the old line kept by smoke this time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_festa_major_gracia", A,
            "Gràcia's streets are strung with paper stars again. Take the cousins to see them — the neighbourhood teaches on its own.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_assumpcio", A,
            "Mid-August, the city half-emptied. A long, slow family week — the line breathes easier in summer.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_hispanitat", A,
            "A day off on the calendar. A family lunch — the room itself is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_castanyada", A,
            "Chestnut smoke on the corner tonight. A family chestnut night — the smell itself is the inheritance.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_constitucio", A,
            "A bridge weekend ahead. A family trip away, maybe — two days, one shared room, the old kind of closeness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_immaculada", A,
            "A pont of empty days ahead. Visit a family member, bring nothing — the visit itself is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_sant_esteve", A,
            "The day after the feast, leftovers still warm. One more meal with everyone still around the table.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_cap_d_any_eve", A,
            "The year's last page. A big family dinner, grapes at midnight — the line closes the year together.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptfa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptfa_birthday", A,
            "Your day — the poem of you gains a stanza. The family calls will come; receive them, they wrote you here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptfa_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_personal_date", A,
            "Today carries its own mark — {label}. Tell one family member; the line travels that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptfa_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptfa_complete_1", A, "Called. The line landed.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptfa_complete_2", A, "Message sent — small, and honest for it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptfa_complete_3", A, "A small family-glow. Real, even in two lines.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptfa_complete_first_today", A,
            "The first family-act of the day — and the heart softens a little because of it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptfa_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptfa_complete_second_today", A,
            "Two now. They notice — the line lengthens whether you announce it or not.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptfa_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptfa_complete_third_today", A,
            "Three. They know you're around today — the page is a shared one now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptfa_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptfa_complete_fourth_today", A,
            "Four. A big family day, or something harder underneath it — be soft either way.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptfa_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptfa_complete_fifth_today", A,
            "Five. A real giver of a day. Rest now — everyone else can wait a moment.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptfa_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptfa_complete_after_streak", A,
            "Three days running of these small rituals now. The bonds keep breathing because of it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptfa_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptfa_apotheosis_1", A,
            "A cycle closes. The line continues — small, kept.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptfa_apotheosis_2", A,
            "Wrapped. The next small ritual is already waiting — specific, and quiet, the way the good ones are.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptfa_apotheosis_3", A,
            "Closed. The family bond is also a writing practice.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptfa_apotheosis_first_ever", A,
            "The first real block, finished. Family rituals are becoming habit — the inherited line keeps itself.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptfa_apotheosis_1", "ptfa_apotheosis_2", "ptfa_apotheosis_3"),
            theme = T),
        DialogueLine("ptfa_apotheosis_at_level_2", A,
            "Visits scheduled, cards sent without being asked. A small giver — keep on keeping.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptfa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptfa_apotheosis_at_level_3", A,
            "You've become the family's glue — a weight as much as a gift. Carry it gently.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptfa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptfa_apotheosis_at_level_4", A,
            "Years of rituals sit behind this. The bonds run strong, and the line stays kept.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptfa_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptfa_nudge_morning", A,
            "A good-morning text to family — don't sit there drafting it. Just send.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptfa_nudge_afternoon_zero", A,
            "A three-minute family call would fit right now. Don't overthink it — just dial.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptfa_nudge_evening", A,
            "A call tonight — they miss you more than they'll say. Trust that.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptfa_nudge_attention_loss", A,
            "They've been waiting a while now. One text today would be enough to answer it.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptfa_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
