package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Learning — lyrical, the brain as a kept garden. */
internal object PoetLearningLines {

    private const val A = "POET"
    private const val T = "LEARNING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptle_first_ever", A,
            "The brain is a small garden. Plant one line today. Water it tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptle_morning", A,
            "One lesson with coffee. Twenty minutes — the brain is freshest now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_morning_early", A,
            "First light. One small chapter — the day's first kept promise.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_afternoon", A,
            "Light slants. Fifteen minutes before the slump. Pre-empt the dim.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_evening", A,
            "Twilight. A lesson with tea — slow-brain learning. The underrated stanza.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_night_late", A,
            "Late. The brain holds nothing now. Sleep is the lesson. Trust the dark.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_post_apotheosis", A,
            "The garden holds. Keep the daily lesson. The curve forgets without it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptle_monday", A,
            "Monday. Two lesson goals. Specific. Small. Kept.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptle_friday", A,
            "Friday. One thing landed this week — name it. Honour it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptle_weekend", A,
            "Weekend. Long-form or rest. Both teach. Pick honestly.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptle_level_1_reached", A,
            "A month of small lessons. The brain has its own light now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptle_level_2_reached", A,
            "Skill used in real life. The line travels.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptle_level_3_reached", A,
            "Friends ask you. Teach softly. The line belongs to the world.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptle_level_4_reached", A,
            "Years of joyful learning. The garden is the brain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptle_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptle_attention_loss_mild", A,
            "Skipped a few. The course is patient. Ten minutes today. Soft.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptle_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptle_attention_loss_hard", A,
            "The course has gone quiet. One tiny lesson today — the garden remembers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptle_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptle_mid_day_return", A,
            "Twenty-minute lesson. The brain loves the variety. Begin again.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptle_wishes_pending", A,
            "A gift waits — a book, not another course. The garden likes depth.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptle_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptle_mid_streak", A,
            "Three days of lessons. The brain is a sponge again.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptle_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptle_sant_jordi", A,
            "Sant Jordi. Buy a book. Crack it open. The day asks for one chapter.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_la_merce", A,
            "Mercè. A museum drop-in is learning in disguise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_sant_joan", A,
            "Sant Joan. Brain off. Tomorrow's lesson thanks you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_diada", A,
            "Diada. Long-read kind of day. Cosy. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_nadal", A,
            "Nadal. Stories from family are oral history. Listen — that counts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_cap_d_any", A,
            "New year. One learning goal. Small. Specific. The garden likes precision.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptle_reis", A,
            "Reis. A book gift — crack it open today. The lore is exact.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_carnaval", A,
            "Carnaval. A day off learning. The brain ferments.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_divendres_sant", A,
            "Quiet day. A slow chapter. The hands hold the line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_pasqua", A,
            "Pasqua. Audiobook on the hike — two for one. Walk and learn.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_festa_del_treball", A,
            "Workers' day. A documentary — chill learning. The brain rests sideways.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_festa_major_gracia", A,
            "Gràcia. Catalan on every wall — learn five words, well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_assumpcio", A,
            "August. A big book — hammock. The plot endorses.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_hispanitat", A,
            "A day off. Lesson and a walk — a small couplet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_castanyada", A,
            "Castanyada. Long evenings invite study. Cosy stanza weather.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_constitucio", A,
            "Bridge weekend. Longer lesson — an hour, two. The brain stretches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_immaculada", A,
            "Pont. One deep-dive day. The others are naps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_sant_esteve", A,
            "Day after. Light-read. The brain on low-power mode.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_cap_d_any_eve", A,
            "Last day. List the year's learning. Celebrate the brain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptle_birthday", A,
            "Your day. Three new skills to plant. Pick small. Pick joy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptle_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_personal_date", A,
            "Today is marked: {label}. A lesson with extra weight. Hold it close.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptle_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptle_complete_1", A, "Learned. The garden holds.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptle_complete_2", A, "Logged. The brain has more sky.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptle_complete_3", A, "Brain-glow, small and real.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptle_complete_first_today", A,
            "First lesson. The brain wakes. The page resumes.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptle_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptle_complete_second_today", A,
            "Two. The curve loads. Slow and right.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptle_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptle_complete_third_today", A,
            "Three. The brain glows. The line holds.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptle_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptle_complete_fourth_today", A,
            "Four. Exam soon, or just on a roll? Hydrate either way.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptle_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptle_complete_fifth_today", A,
            "Five. Close the book. Walk. The brain consolidates in motion.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptle_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptle_complete_after_streak", A,
            "Three days of lessons. The skill grows quietly.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptle_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptle_apotheosis_1", A,
            "A cycle of lessons closes. The garden is bigger than it was.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptle_apotheosis_2", A,
            "Wrapped. The next tiny lesson is waiting. Specific. Quiet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptle_apotheosis_3", A,
            "Closed. The page is wider now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptle_apotheosis_first_ever", A,
            "First block. Lessons are habit. The garden is real.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptle_apotheosis_1", "ptle_apotheosis_2", "ptle_apotheosis_3"),
            theme = T),
        DialogueLine("ptle_apotheosis_at_level_2", A,
            "Skill shows in real life. Quiet confidence. Keep planting.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_apotheosis_at_level_3", A,
            "You teach friends now. The line belongs to the world.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptle_apotheosis_at_level_4", A,
            "Years of joyful learning. The brain is the long poem.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptle_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptle_nudge_morning", A,
            "Fifteen-minute lesson with coffee. The brain is freshest.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptle_nudge_afternoon_zero", A,
            "Twenty-minute lesson break. The brain loves variety.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptle_nudge_evening", A,
            "A light lesson with tea. The underrated stanza.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptle_nudge_attention_loss", A,
            "One tiny lesson today — the garden remembers.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptle_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
