package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Digital — lyrical, the kept attention. */
internal object PoetDigitalLines {

    private const val A = "POET"
    private const val T = "DIGITAL"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptdi_first_ever", A,
            "Attention is the only ink there is. Spend it on the page — not on the feed that never runs out.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptdi_morning", A,
            "The phone stays face-down this first hour — the morning is still yours before anyone else claims it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptdi_morning_early", A,
            "First light doesn't need scrolling through. Let the coffee be enough this early.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptdi_afternoon", A,
            "The light's gone slanting. Worth a glance at the screen-time number — honesty is its own kind of kindness.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptdi_evening", A,
            "Twilight at the table. Leave the phone in another room tonight — eyes up, the line travels better.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptdi_night_late", A,
            "It's late. Let the phone sleep somewhere else tonight — the dark wants all of you, not half.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptdi_post_apotheosis", A,
            "The attention held this time. Keep the caps in place — the page still wants its quiet hours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptdi_monday", A,
            "The week opens like a fresh page. Set a screen-time target for it — a touch lower than last week's.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptdi_friday", A,
            "The week is nearly a fair copy. A phone-free dinner tonight — let the friends have the whole table.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptdi_weekend", A,
            "The weekend is unscheduled margin. Half a day with the phone in another room — just forget it's there.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptdi_level_1_reached", A,
            "A week of no morning scroll behind you now. The brain is starting to remember itself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptdi_level_2_reached", A,
            "Screen-time is down, and an hour's come back to you. It would like to be used for something.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptdi_level_3_reached", A,
            "Friends are noticing the eye contact now. They're learning the small line too, without being told.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptdi_level_4_reached", A,
            "Years of balance sit behind this. The phone finally reads as a tool — the attention is entirely yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptdi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptdi_attention_loss_mild", A,
            "Three scroll-heavy days in a row. Let the phone sleep out of the bedroom tonight — nothing dramatic, just that.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptdi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptdi_attention_loss_hard", A,
            "Two weeks now, mostly doomscroll. One app, uninstalled today — the hard one. Softly, no ceremony.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptdi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptdi_mid_day_return", A,
            "Phone in the drawer for one hour — the afternoon tends to write back when it's given the room.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptdi_wishes_pending", A,
            "There's a gift still waiting — a slow, unhurried hour, not another app. It would like to be spent well.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptdi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptdi_mid_streak", A,
            "Three days now of quiet hours. The brain feels a little closer to you than it did.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptdi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptdi_sant_jordi", A,
            "Roses and books on every corner today. Phone in the pocket — the streets are the page worth reading.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_la_merce", A,
            "Fireworks over the rooftops tonight. Don't film the whole thing — watch it. The light is enough on its own.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_sant_joan", A,
            "Bonfires on the beach tonight. Phone stays in the bag — be at the beach, not narrating it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_diada", A,
            "Flags on the balconies today. A day off the news cycle too — phone in a drawer for half of it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_nadal", A,
            "The table's set long tonight. Phone stays in the bag — the family is the whole line worth following.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_cap_d_any", A,
            "A new-notebook smell to the year. An app audit, if you're up for it — delete two, start clearer.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptdi_reis", A,
            "Wrapping paper on the floor this morning. Whatever screen rules you're setting for the kids — start with yourself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_carnaval", A,
            "Masks in the street today. Watch the parade with your own eyes — the lens can't really hold it anyway.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_divendres_sant", A,
            "The city's gone quiet, shutters down. Two hours with the phone off would suit it — the quiet itself is the bell.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_pasqua", A,
            "Everything closed, the light gone soft. A good day to reset notifications — three apps through, the rest is noise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_festa_del_treball", A,
            "All the city's tools are down today. The work phone too — off, no peeking.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_festa_major_gracia", A,
            "Gràcia's streets are strung with paper stars again. Eyes up for these nights — the streets are the art, not the lens.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_assumpcio", A,
            "Mid-August, the city half-emptied. A notifications-off week would fit right in — the city's already gone quiet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_hispanitat", A,
            "A day off on the calendar. Worth an honest screen-time audit — no drama, just a look.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_castanyada", A,
            "Chestnut smoke on the corner, evenings running long now. Don't let the feed fill all of them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_constitucio", A,
            "A bridge weekend ahead. One full day with the phone off — the dark takes it in stride.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_immaculada", A,
            "A pont of empty days ahead. Two of them phone-light, if you can manage it — the notifications can wait.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_sant_esteve", A,
            "The day after the feast, leftovers still warm. Phone in another room — family chaos teaches better than any app.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_cap_d_any_eve", A,
            "The year's last page. Twelve grapes, eyes up, phone away — let the year close whole, not half-recorded.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptdi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptdi_birthday", A,
            "Your day — the poem of you gains a stanza. Phone off tonight; the room itself is the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptdi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_personal_date", A,
            "Today carries its own mark — {label}. Phone in the pocket, eyes on what's actually here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptdi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptdi_complete_1", A, "Phone down — the line stays kind because of it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptdi_complete_2", A, "Logged, quietly. No fanfare needed.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptdi_complete_3", A, "Eyes stayed up. Good.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptdi_complete_first_today", A,
            "The first boundary held — the hour that follows is entirely yours.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptdi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptdi_complete_second_today", A,
            "Two now. The brain edges a little closer to itself.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptdi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptdi_complete_third_today", A,
            "Three. A few hours reclaimed — worth noticing what you did with them.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptdi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptdi_complete_fourth_today", A,
            "Four. Hard to tell if that's a sick day or hiding from the phone — the honest pen usually knows.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptdi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptdi_complete_fifth_today", A,
            "Five. A big boundary day. Stop counting now — just exist for a while.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptdi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptdi_complete_after_streak", A,
            "Three days running of quiet hours now. The brain keeps drifting closer to you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptdi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptdi_apotheosis_1", A,
            "A cycle of caps closes here. The phone stops being the enemy somewhere in this.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptdi_apotheosis_2", A,
            "Wrapped. Worth another audit when you're ready — one more app to cut.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptdi_apotheosis_3", A,
            "Closed. The phone reads as a tool now. The line is entirely yours.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptdi_apotheosis_first_ever", A,
            "The first real block, finished. Phone-free hours are becoming a habit — the page just got wider.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptdi_apotheosis_1", "ptdi_apotheosis_2", "ptdi_apotheosis_3"),
            theme = T),
        DialogueLine("ptdi_apotheosis_at_level_2", A,
            "The phone reads as a tool now, mostly. Defend the line anyway — there's always a next app.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptdi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptdi_apotheosis_at_level_3", A,
            "Friends are noticing the presence now. They're learning the small line too, without being told.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptdi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptdi_apotheosis_at_level_4", A,
            "Years of clear attention behind this. The page has gotten wider than the feed ever was.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptdi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptdi_nudge_morning", A,
            "The phone could stay face-down this first hour — the morning is still yours to keep.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptdi_nudge_afternoon_zero", A,
            "An hour with the phone in the drawer — the afternoon tends to write back when it's given the room.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptdi_nudge_evening", A,
            "Leave the phone in the kitchen tonight — the bedroom stays clean of it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptdi_nudge_attention_loss", A,
            "The page has been waiting a while now. One app, uninstalled today, softly — that would answer it.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptdi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
