package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Poet × Exercise — lyrical, breath and stride. */
internal object PoetExerciseLines {

    private const val A = "POET"
    private const val T = "EXERCISE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("ptex_first_ever", A,
            "The body is a poem you've been forgetting. Take it for a walk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("ptex_morning", A,
            "Morning. The body wakes before the mind. Let it move.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "ptex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptex_morning_early", A,
            "First light. The street is still a draft. Walk into it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "ptex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptex_afternoon", A,
            "Light slants. The body asks to be moved. A walk is enough.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "ptex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptex_evening", A,
            "Twilight. The streets soften. Move slowly. The day undresses.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "ptex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptex_night_late", A,
            "Late. Stretch the body like a long sentence. Then close it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "ptex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("ptex_post_apotheosis", A,
            "The body learned a new line. Keep walking it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("ptex_monday", A,
            "Monday opens like a notebook. The first stride is the first line.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "ptex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptex_friday", A,
            "Friday. The week's stride. End it on a step worth keeping.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "ptex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("ptex_weekend", A,
            "Weekend. A long walk where the line is the road and the road is the line.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "ptex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("ptex_level_1_reached", A,
            "A week of motion. The body remembers itself. The poem holds.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "ptex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptex_level_2_reached", A,
            "A month. The body does things its old draft could not.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "ptex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptex_level_3_reached", A,
            "The body has a voice now. Others hear it without you speaking.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "ptex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("ptex_level_4_reached", A,
            "Years of motion. The body is the long poem you've been writing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "ptex_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("ptex_attention_loss_mild", A,
            "Days without movement. The body waits, patient. A small walk today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "ptex_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("ptex_attention_loss_hard", A,
            "The body has gone quiet a long while. Begin again — five minutes. Soft.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptex_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("ptex_mid_day_return", A,
            "The middle of the page. Stand. Move. Five minutes — the line returns.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("ptex_wishes_pending", A,
            "A gift waits, earned by stride. Open it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "ptex_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("ptex_mid_streak", A,
            "Three days of motion. The body is learning by heart.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptex_streak", cooldownPicks = 5, theme = T),

        DialogueLine("ptex_sant_jordi", A,
            "Sant Jordi. The city is a long line of bodies. Walk it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_la_merce", A,
            "Mercè. Dance is also a poem. Move with it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_sant_joan", A,
            "Sant Joan. Salt, smoke, sand under feet. The body remembers the sea.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_diada", A,
            "Diada. A long walk through a city that holds its breath.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_nadal", A,
            "Nadal. The post-lunch walk. An old line, kept by grandmothers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_cap_d_any", A,
            "New year. The first step is a poem you haven't read.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptex_reis", A,
            "Reis. The kids run; you keep up. The line keeps moving.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_carnaval", A,
            "Carnaval. Costume and stride — both are language. Move.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_divendres_sant", A,
            "A quiet day. Walk by the water. Let the surface read you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_pasqua", A,
            "Pasqua. The trail is a poem with elevation. Climb it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_festa_del_treball", A,
            "Workers' day. The body is also labour. Let it move freely.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_festa_major_gracia", A,
            "Gràcia. Every street a stanza. Walk all of them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_assumpcio", A,
            "August. The empty city is a poem you have to yourself. Walk it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_hispanitat", A,
            "A day off. A hill walk. A vista. Three stanzas.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_castanyada", A,
            "Castanyada. Crunch of leaves underfoot. The path remembers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_constitucio", A,
            "Bridge weekend. Walk both days. The line lengthens.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_immaculada", A,
            "Pont. Pick one trail. The other days will keep their stillness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_sant_esteve", A,
            "Day after. A soft walk. Let yesterday settle.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_cap_d_any_eve", A,
            "Last day. Walk the year out. Close the stanza.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "ptex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("ptex_birthday", A,
            "Your day. A walk to a place you love. The route is the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "ptex_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_personal_date", A,
            "Today is marked: {label}. Move through it. The body remembers what the page can't.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "ptex_personal", cooldownPicks = 1, theme = T),

        DialogueLine("ptex_complete_1", A, "The stride landed.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptex_complete_2", A, "A line set down. Good.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptex_complete_3", A, "Steps held the page.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("ptex_complete_first_today", A,
            "First motion. The day opens its eyes.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "ptex_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptex_complete_second_today", A,
            "Two strides. The line is forming.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "ptex_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptex_complete_third_today", A,
            "Three. The body is fluent. Drink water.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "ptex_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptex_complete_fourth_today", A,
            "Four. The page is full. Eat, rest — the next draft tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "ptex_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("ptex_complete_fifth_today", A,
            "Five. The body has spoken enough. Sit. Be still.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "ptex_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("ptex_complete_after_streak", A,
            "Three days of motion. The poem is being learned by foot.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "ptex_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("ptex_apotheosis_1", A,
            "A chapter of strides closes. The body is the page now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptex_apotheosis_2", A,
            "The cycle holds. Begin the next — softer, longer.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptex_apotheosis_3", A,
            "Closed. The body is the long poem you've been writing.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("ptex_apotheosis_first_ever", A,
            "First block. The body has voice. Don't lose it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("ptex_apotheosis_1", "ptex_apotheosis_2", "ptex_apotheosis_3"),
            theme = T),
        DialogueLine("ptex_apotheosis_at_level_2", A,
            "The body trusts the page now. Walk on.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "ptex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptex_apotheosis_at_level_3", A,
            "Others read your stride. They learn from it. Walk on.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "ptex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("ptex_apotheosis_at_level_4", A,
            "Years of motion. The poem is the body. Maintain it daily.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "ptex_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("ptex_nudge_morning", A,
            "Morning. Five minutes of motion before the page opens.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "ptex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptex_nudge_afternoon_zero", A,
            "Stand. Walk. Five minutes. The line returns.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "ptex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptex_nudge_evening", A,
            "Twilight walk. Slow. The day undresses.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "ptex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("ptex_nudge_attention_loss", A,
            "The body waits. Five minutes of walking — softly back.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "ptex_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
