package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Hydration & body basics. */
internal object StoicHydrationLines {

    private const val A = "STOIC"
    private const val T = "HYDRATION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("sthy_first_ever", A,
            "Small acts compound in silence. Water, light, salt — begin the daily practice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("sthy_morning", A,
            "Water before coffee. The body has been dry for hours and says nothing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "sthy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("sthy_morning_early", A,
            "The body has been still for hours at this hour. Drink before anything else.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "sthy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("sthy_afternoon", A,
            "The bottle has not refilled itself all afternoon. It will not start now without you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "sthy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("sthy_evening", A,
            "The last large glass goes here, not at midnight. Otherwise the night breaks twice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "sthy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("sthy_night_late", A,
            "A small sip at this hour if you must, not the whole bottle. The bladder remembers.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "sthy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("sthy_post_apotheosis", A,
            "The block is done. The small acts continue daily anyway — arrival is not a thing here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("sthy_monday", A,
            "Bottle on the desk, visible, before the week starts. The whole trick is making it present.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "sthy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("sthy_friday", A,
            "Beer is not hydration, whatever tonight argues. Match each round with water. Tomorrow nods.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "sthy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("sthy_weekend", A,
            "Routines slip on days like this. Keep the bottle visible anyway. That is the whole trick.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "sthy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("sthy_level_1_reached", A,
            "A week of small care, boring on purpose. Boring was always the gate.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "sthy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("sthy_level_2_reached", A,
            "Skin better. Headaches fewer. You noticed, which is the practice working twice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "sthy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("sthy_level_3_reached", A,
            "It runs automatically now. Do not let one bad week convince you it never mattered.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "sthy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("sthy_level_4_reached", A,
            "Small care, daily, forever. The quietest practice there is, and the longest-paying.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "sthy_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("sthy_attention_loss_mild", A,
            "The bottle has sat empty two days. Refill it now, before this becomes a custom.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "sthy_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("sthy_attention_loss_hard", A,
            "Headache, dry mouth, fog. The body is asking plainly. Two glasses, slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "sthy_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("sthy_after_lapse", A,
            "Yesterday ran dry. The body is behind now — small sips through the day, not a flood.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("sthy_mid_day_return", A,
            "Half the day gone, dry as bone. The bottle, now. I will not ask twice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("sthy_wishes_pending", A,
            "Reward accumulates. Take it — tomorrow's rhythm holds.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "sthy_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("sthy_mid_streak", A,
            "Three clean days. The body trusts you a little now. Maintain that.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "sthy_streak", cooldownPicks = 5, theme = T),

        DialogueLine("sthy_sant_jordi", A,
            "The streets walked, the book bought. Refill at the fountain before heading home.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_la_merce", A,
            "Three vermuts will be drunk before Mercè is done with you. Match each with water. That is the contract.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_sant_joan", A,
            "Beach, fireworks, cava tonight. Three liters of water alongside. Not optional.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_diada", A,
            "A long day outside for Diada. Hat, water, sunscreen — the three quiet companions.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_nadal", A,
            "Heavy food tonight. Water between the courses. Vitamins can wait until tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_cap_d_any", A,
            "The first glass of water of the year. It sets the rhythm more than the resolutions do.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("sthy_reis", A,
            "The kids run on sugar today. You are not a child. Water.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_carnaval", A,
            "Dancing all night for Carnaval. Water between the drinks, salt with the food.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_divendres_sant", A,
            "The streets have gone still. An easy hydration day — use it to catch up if you are behind.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_pasqua", A,
            "Long walk weather, this slow Monday. Bottle, hat, vitamin C.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_festa_del_treball", A,
            "A day for labor. Small body care is honest work too. Maintain it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_festa_major_gracia", A,
            "Gràcia's streets are packed and the sun is sharp. Sunscreen, hat, water.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_assumpcio", A,
            "August heat, the real kind. Three liters today, salt at every meal. Not negotiable.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_hispanitat", A,
            "A day off. Catch up on the small things — vitamins, the sunscreen check you keep postponing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_castanyada", A,
            "The sun leaves earlier now. Vitamin D, then. Pills are not an embarrassment.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_constitucio", A,
            "A long weekend. Do not let the bottle quietly become a wineglass. Both, if you must.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_immaculada", A,
            "Five days off-routine with this bridge. The bottle goes on the table wherever you go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_sant_esteve", A,
            "The day after the feast, the body asks for water and quiet. Two glasses, slowly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_cap_d_any_eve", A,
            "The year has a few hours left. A glass of water with the grapes — tomorrow-you bows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "sthy_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("sthy_birthday", A,
            "Another year completed. Drinks tonight, one water for each. Tomorrow-you bows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "sthy_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_personal_date", A,
            "You named this day {label}. The small body care still applies — the body keeps its own line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "sthy_personal", cooldownPicks = 1, theme = T),

        DialogueLine("sthy_complete_1", A, "Glass down. Walk on.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("sthy_complete_2", A, "Logged. Sunscreen on the way out.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("sthy_complete_3", A, "Done. The body quietly thanks you.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("sthy_complete_first_today", A,
            "First glass. The rest happens by itself — the bottle is visible.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "sthy_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("sthy_complete_second_today", A,
            "Two small acts in. They compound — do not stop, and do not strain either.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "sthy_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("sthy_complete_third_today", A,
            "Three in. A full hydration day — keep the bottle topped and forget about it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "sthy_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("sthy_complete_fourth_today", A,
            "Four in. The body swims already — do not overdo it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "sthy_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("sthy_complete_fifth_today", A,
            "Five in. Past full now — stop. Salt with dinner evens it out.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "sthy_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("sthy_complete_after_streak", A,
            "Three clean days running. The compounding is real. Maintain it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "sthy_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("sthy_apotheosis_1", A,
            "The block is done. Small acts compound — do not forget which ones carried it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("sthy_apotheosis_2", A,
            "The cycle is closed. The same maintenance starts again tomorrow. Discipline as ritual.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("sthy_apotheosis_3", A,
            "Done. The boring stuff has the highest leverage — hold it lightly.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("sthy_apotheosis_first_ever", A,
            "First block of small care closed. You learned the system — do not put it down now.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("sthy_apotheosis_1", "sthy_apotheosis_2", "sthy_apotheosis_3"),
            theme = T),
        DialogueLine("sthy_apotheosis_at_level_2", A,
            "Two blocks of maintenance. People notice it before you do. Do not get vain about water.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "sthy_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("sthy_apotheosis_at_level_3", A,
            "Skin, eyes, guts — all telling the truth now, and the truth is good.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "sthy_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("sthy_apotheosis_at_level_4", A,
            "You age slower because you tended. That is the gift you gave, quietly, one glass at a time.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "sthy_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("sthy_nudge_morning", A,
            "Glass, pill, sunscreen if you're walking out. Three small acts before the day starts asking.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "sthy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("sthy_nudge_afternoon_zero", A,
            "Half the day gone, the bottle empty. Refill it. Forty seconds.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "sthy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("sthy_nudge_evening", A,
            "The last glass goes now, not at one in the morning.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "sthy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("sthy_nudge_lapse", A,
            "Yesterday slipped. Today the maintenance returns, starting with a glass.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("sthy_nudge_attention_loss", A,
            "The body is behind. Three glasses today, spaced out. Do not chug them.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "sthy_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
