package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Learning & study. */
internal object StoicLearningLines {

    private const val A = "STOIC"
    private const val T = "LEARNING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stle_first_ever", A,
            "The book on the shelf does not read itself. Open it — one page is the gate.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stle_morning", A,
            "Morning. One page before anything else — the mind is clearest now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stle_morning_early", A,
            "Pre-work hour. Best study time — do not squander it on news.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stle_afternoon", A,
            "Mid-day. Lunch break study — fifteen minutes. Do not sleep on it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stle_evening", A,
            "Evening. One chapter — then close it. The brain consolidates overnight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stle_night_late", A,
            "Late. Do not cram tired — one paragraph, sleep. It will stick tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stle_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stle_post_apotheosis", A,
            "Course done. Do not put the book away — pick the next subject before forgetting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stle_monday", A,
            "Monday. Week's study plan — specific, schedulable. Or it does not happen.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stle_friday", A,
            "Friday. Review what you actually learned — honest answer.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stle_weekend", A,
            "Weekend. Longer block possible — two hours real study beats five of skimming.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stle_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stle_level_1_reached", A,
            "First tier. First chapter retained — the hardest one. Most quit here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stle_level_2_reached", A,
            "Second tier. Concepts connect — the map is forming. Keep adding.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stle_level_3_reached", A,
            "Third tier. You can explain it — teach someone. That is the test.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stle_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stle_level_4_reached", A,
            "Highest tier. The subject is yours — do not quit. Pick another.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stle_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stle_attention_loss_mild", A,
            "Three days no study — the page knows. Open the book today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stle_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stle_attention_loss_hard", A,
            "Book gathering dust. Do not restart at chapter one — pick up where you left.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stle_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stle_after_lapse", A,
            "Yesterday's chapter unread. Today's is in your control — one paragraph.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stle_mid_day_return", A,
            "Half the day. Book unopened — ten minutes. Not optional.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stle_wishes_pending", A,
            "Reward accumulates. Buy the next book on the list.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stle_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stle_mid_streak", A,
            "Three study days. The subject is alive — do not waste the momentum.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stle_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stle_sant_jordi", A,
            "Sant Jordi. New book bought, surely — read the first chapter tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_la_merce", A,
            "Mercè. Loud city — headphones, library, or skip. Pick.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_sant_joan", A,
            "Sant Joan. No study tonight — real off. Tomorrow back to the page.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_diada", A,
            "Diada. Long-form reading day — three hours, no phone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_nadal", A,
            "Nadal. Family takes the day — study tomorrow, not faked tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_cap_d_any", A,
            "New year. New subject on the shelf — pick today, open tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stle_reis", A,
            "Reis. A book as a gift, probably — read it. Do not shelve it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_carnaval", A,
            "Carnaval. Late nights mean groggy mornings — study at lunch, not 7am.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_divendres_sant", A,
            "Quiet day. Best study day of the year — phone off. Two hours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_pasqua", A,
            "Pasqua Monday. Reset the study habit — one page. The whole day's goal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_festa_del_treball", A,
            "Workers' day. The book is work too — honor the rest. Read tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_festa_major_gracia", A,
            "Gràcia. Library or festival — pick. Either commits.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_assumpcio", A,
            "August. Empty city — best long-read month. Use it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_hispanitat", A,
            "Day off. Pick up the textbook you avoided — one tough chapter.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_castanyada", A,
            "Castanyada. Dark by 7 — indoor reading season opens. Lean in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_constitucio", A,
            "Bridge weekend. Pick a book — finish before Monday. The real test.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_immaculada", A,
            "Pont. Five days. Close a real subject — or rest. Do not dabble.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_sant_esteve", A,
            "Day after. Light reading — the fiction book that waited. Earn it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_cap_d_any_eve", A,
            "Last day. Books read this year — count them honestly. Plan next year's stack.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stle_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stle_birthday", A,
            "Your day. Light study — pick the fun book. The hard one waits.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stle_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stle_personal_date", A,
            "You marked this day: {label}. Reading load adjusted — take what the day allows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stle_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stle_complete_1", A, "Chapter done. Walk on.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stle_complete_2", A, "Logged. Note the key idea before it drifts.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stle_complete_3", A, "Done. The brain files it overnight.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stle_complete_first_today", A,
            "First study block. The book remembers you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stle_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stle_complete_second_today", A,
            "Two blocks. Do not burn out — comprehension drops past 90 minutes.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stle_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stle_complete_third_today", A,
            "Three. Real study day — the subject is denser than morning.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stle_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stle_complete_fourth_today", A,
            "Four. Stop — sleep on it. Tomorrow will be clearer than rereading.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stle_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stle_complete_fifth_today", A,
            "Five. Past comprehension — you store words, not knowledge. Stop.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stle_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stle_complete_after_streak", A,
            "Day three of study. The subject comes alive — keep showing up.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stle_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stle_apotheosis_1", A,
            "Subject closed. Find a way to use it — knowledge unused leaks.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stle_apotheosis_2", A,
            "Course done. Teach someone the core idea — that is the test.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stle_apotheosis_3", A,
            "Closed. Write the summary now — future-you will need it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stle_apotheosis_first_ever", A,
            "First subject, top to bottom. You are no longer a beginner — notice.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stle_apotheosis_1", "stle_apotheosis_2", "stle_apotheosis_3"),
            theme = T),
        DialogueLine("stle_apotheosis_at_level_2", A,
            "Promoted. The map is wider — pick a harder subject next.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stle_apotheosis_at_level_3", A,
            "Senior tier. You teach the basics — keep learning the hard parts.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stle_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stle_apotheosis_at_level_4", A,
            "Highest tier. You have earned the right to specialize — the deep, narrow thing.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stle_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stle_nudge_morning", A,
            "Morning. One page — before the day eats you.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stle_nudge_afternoon_zero", A,
            "Halftime. Book unopened — ten minutes. Pick a paragraph.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stle_nudge_evening", A,
            "Evening. One chapter — then close it. The brain consolidates overnight.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stle_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stle_nudge_lapse", A,
            "Yesterday's chapter unread. Today's one paragraph. Start.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stle_nudge_attention_loss", A,
            "Book dusty. Do not restart from page one — pick up where you left.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stle_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
