package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Friendship & community. */
internal object StoicFriendshipLines {

    private const val A = "STOIC"
    private const val T = "FRIENDSHIP"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stfr_first_ever", A,
            "Friendships die quiet. The reaching is in your control — send the text.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stfr_morning", A,
            "Morning. One friend not heard from this week — reach out before lunch.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfr_morning_early", A,
            "Up early. Voice note to the friend in another timezone — two minutes.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfr_afternoon", A,
            "Mid-day. Lunch with someone — not at the desk alone. Move.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfr_evening", A,
            "Evening. Send the text you have been drafting — do not perfect it. Send.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfr_night_late", A,
            "Late. Do not write the deep text now — note who. Tomorrow morning.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stfr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfr_post_apotheosis", A,
            "Stretch closed. Do not go quiet — the next friend's name is on your mind.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stfr_monday", A,
            "Monday. Plan the week's meetup — do not wait to be invited.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stfr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stfr_friday", A,
            "Friday. End the week with one — drinks, walk, anything face-to-face.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stfr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stfr_weekend", A,
            "Weekend. Do not waste it on the couch alone — brunch counts. Park counts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stfr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stfr_level_1_reached", A,
            "First tier. First real reach in a while — they were waiting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stfr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stfr_level_2_reached", A,
            "Second tier. You are the friend who shows up — earned. Do not slack.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stfr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stfr_level_3_reached", A,
            "Third tier. People text you when things go wrong — a privilege. Honor it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stfr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stfr_level_4_reached", A,
            "Highest tier. You build the community around you — weekly. Defend it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stfr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stfr_attention_loss_mild", A,
            "Three weeks gone quiet. They notice — one real text today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stfr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stfr_attention_loss_hard", A,
            "Months of silence. Do not draft an apology — invite them to coffee. Today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stfr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stfr_after_lapse", A,
            "Missed yesterday's reach. Make it up today — do not compound the silence.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stfr_mid_day_return", A,
            "Halftime. Nobody contacted. The text will not send itself.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stfr_wishes_pending", A,
            "Reward accumulates. Pay for the drinks tonight — stale wins do not buy rounds.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stfr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stfr_mid_streak", A,
            "Three weeks of consistent reach. The group is tighter — maintain.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stfr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stfr_sant_jordi", A,
            "Sant Jordi. Walk with a friend through the stalls — buy them the book they would not.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_la_merce", A,
            "Mercè. The group meets somewhere — find them. Do not bail because it is loud.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_sant_joan", A,
            "Sant Joan. Beach with the crew — bring something. Stay til the fireworks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_diada", A,
            "Diada. Long lunch with old friends — do not bail for errands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_nadal", A,
            "Nadal. Family today — text the friend who has none. They need it more.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_cap_d_any", A,
            "New year. Send the wishes — real ones, one per friend. Not the blast.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stfr_reis", A,
            "Reis. Drop the small gift — do not ship. Five minutes at the door.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_carnaval", A,
            "Carnaval. The group has costume plans — be in. Do not text 'tired'.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_divendres_sant", A,
            "Quiet day. Long walk with one friend — the kind where things get said.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_pasqua", A,
            "Pasqua Monday. Coffee with whoever is still in the city — do not waste the day off.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_festa_del_treball", A,
            "Workers' day. Family barbecue or friends' lunch — pick one. Show up fully.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_festa_major_gracia", A,
            "Gràcia. Streets are tables — sit with friends at one. Stay til the music ends.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_assumpcio", A,
            "August. Everyone scattered — send the voice notes. Distance friendships need them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_hispanitat", A,
            "Day off. Brunch with someone you have missed — do not reschedule.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_castanyada", A,
            "Castanyada. Friends huddled around chestnuts and panellets — be there.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_constitucio", A,
            "Bridge weekend. Trip with friends — even a short one. Time is the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_immaculada", A,
            "Pont. Five days — one with friends. Phone off. Real talk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_sant_esteve", A,
            "Day after. Drinks with whoever is not at family lunches — they are out there.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_cap_d_any_eve", A,
            "Last day. Send the year-end note — personal. Not the group blast.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stfr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stfr_birthday", A,
            "Your day. Tonight is theirs to plan — receive it. Do not direct.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stfr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_personal_date", A,
            "You marked this day: {label}. The friend who knows what this means — call them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stfr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stfr_complete_1", A, "Reached. Next name.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stfr_complete_2", A, "Done. They felt it — move on.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stfr_complete_3", A, "Logged. Phone away — do not broadcast.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stfr_complete_first_today", A,
            "First reach. The day is no longer empty between you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stfr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stfr_complete_second_today", A,
            "Two friends. Pace it — do not spam.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stfr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stfr_complete_third_today", A,
            "Three. Real social day — do not burn out tomorrow with avoidance.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stfr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stfr_complete_fourth_today", A,
            "Four. Stop — real friendship does not need volume.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stfr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stfr_complete_fifth_today", A,
            "Five. Overcompensating — quality over count. Be honest.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stfr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stfr_complete_after_streak", A,
            "Day three. The group remembers your name — that is the whole game.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stfr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stfr_apotheosis_1", A,
            "Stretch closed. The next friend's name is on your mind — reach.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stfr_apotheosis_2", A,
            "Cycle done. Set the next group thing — do not wait for someone else.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stfr_apotheosis_3", A,
            "Closed. Maintain the rhythm — friendships die quiet. Yours will not.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stfr_apotheosis_first_ever", A,
            "First real stretch of showing up. The group is different because of you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stfr_apotheosis_1", "stfr_apotheosis_2", "stfr_apotheosis_3"),
            theme = T),
        DialogueLine("stfr_apotheosis_at_level_2", A,
            "Promoted. People text you first now — that is earned.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stfr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stfr_apotheosis_at_level_3", A,
            "Senior tier. You are the connector — keep introducing people. Compound the network.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stfr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stfr_apotheosis_at_level_4", A,
            "Highest tier. The community is the work — defend it weekly. No autopilot.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stfr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stfr_nudge_morning", A,
            "Morning. One friend — real sentence. Send.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stfr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stfr_nudge_afternoon_zero", A,
            "Halftime. Nobody reached. The text will not send itself — now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stfr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stfr_nudge_evening", A,
            "Evening. Set a meetup for the week — do not wait for invitations.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stfr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stfr_nudge_lapse", A,
            "Missed yesterday. Send it today — no apology.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stfr_nudge_attention_loss", A,
            "Months of silence. Invite — do not apologize. Action first.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stfr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
