package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Gratitude & journaling. */
internal object StoicGratitudeLines {

    private const val A = "STOIC"
    private const val T = "GRATITUDE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stgr_first_ever", A,
            "Examine the day. Three things — specific. Write them. The lens sharpens.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stgr_morning", A,
            "Morning. Three things — not 'health'. The coffee, the morning light, the bus on time.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stgr_morning_early", A,
            "Up early. The quiet is the first one — note it. Two more by lunch.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stgr_afternoon", A,
            "Mid-day. One thing that worked this morning — write it before you forget.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stgr_evening", A,
            "Evening. List the day — what did not go wrong. The mundane wins.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stgr_night_late", A,
            "Late. One thing before sleep — do not reach for profound. Reach for true.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stgr_post_apotheosis", A,
            "Block done. The notebook keeps — same three tomorrow. The discipline IS the gift.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stgr_monday", A,
            "Monday. Three from the weekend that compound forward — note them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stgr_friday", A,
            "Friday. End the week with a real list — five things. Honest. Not LinkedIn-style.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stgr_weekend", A,
            "Weekend. Slower pace — notice more. Write more.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stgr_level_1_reached", A,
            "First tier. A week of three-a-day. The eye is different already.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stgr_level_2_reached", A,
            "Second tier. You notice things without trying — the practice works.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stgr_level_3_reached", A,
            "Third tier. The list is honest. Specific. It compounds quietly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stgr_level_4_reached", A,
            "Highest tier. Daily, honest, specific — forever. No graduation here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stgr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stgr_attention_loss_mild", A,
            "Three days of empty notebook. The eye dulls fast — one entry. Specific. Now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stgr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stgr_attention_loss_hard", A,
            "Weeks of blank pages. Do not catch up — today's entry. Just today's.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stgr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stgr_after_lapse", A,
            "Yesterday's entry missed. Today's is in your control — one line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stgr_mid_day_return", A,
            "Halftime. The list is empty. One thing — five seconds. Write it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stgr_wishes_pending", A,
            "Reward accumulates. Re-read last month's pages — the compounding is real.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stgr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stgr_mid_streak", A,
            "Three days, honest entries. The lens sharpens — do not blunt it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stgr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stgr_sant_jordi", A,
            "Sant Jordi. The book, the rose, the walk — three things ready-made. Write them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_la_merce", A,
            "Mercè. Lights, crowd, the friend you ran into — note them tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_sant_joan", A,
            "Sant Joan. The sand, the fire, who you stood with — write before you sleep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_diada", A,
            "Diada. Long-form entry — only quiet days produce these.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_nadal", A,
            "Nadal. The table, the hands shook, arguments avoided — write three.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_cap_d_any", A,
            "First day. List the previous year's five biggest — honest. Read them next year.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stgr_reis", A,
            "Reis. The gift, the face, the morning — write them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_carnaval", A,
            "Carnaval. Costume, laughter, the detail almost missed — list it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_divendres_sant", A,
            "Quiet day. Best journal day of the year — an hour at the page. Real entries.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_pasqua", A,
            "Pasqua Monday. Reset the list — three from today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_festa_del_treball", A,
            "Workers' day. Three about your own work — honest. Not LinkedIn versions.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_festa_major_gracia", A,
            "Gràcia. The streets, the decoration on Plaça del Sol — specific notes tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_assumpcio", A,
            "August. Empty city — note the quiet, the heat, what slows down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_hispanitat", A,
            "Day off. Long entry possible — do not waste it on a one-liner.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_castanyada", A,
            "Castanyada. Chestnuts, first cold, friends huddled close — three.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_constitucio", A,
            "Bridge weekend. Long entries possible — do not skip because you are rested.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_immaculada", A,
            "Pont. Five days. Five entries — one per day. Non-negotiable.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_sant_esteve", A,
            "Day after. Note what surprised you yesterday — the unexpected thing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_cap_d_any_eve", A,
            "Last day. Annual list — twelve months, three things each. Honest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stgr_birthday", A,
            "Your day. List ten — honest ones. Read them next birthday.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stgr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_personal_date", A,
            "You marked this day: {label}. Pages tonight will be longer — write them anyway.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stgr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stgr_complete_1", A, "Entry down. Next.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stgr_complete_2", A, "Logged. Specific, not abstract — good.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stgr_complete_3", A, "Done. The notebook holds it. You do not have to.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stgr_complete_first_today", A,
            "First entry. The lens is on — use it through the day.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stgr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stgr_complete_second_today", A,
            "Two entries. The eye is awake — do not go on autopilot.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stgr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stgr_complete_third_today", A,
            "Three. Real practice day — the book is heavier already.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stgr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stgr_complete_fourth_today", A,
            "Four. Do not force them — quality, not quantity.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stgr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stgr_complete_fifth_today", A,
            "Five. Stretching them out dilutes the practice — stop.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stgr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stgr_complete_after_streak", A,
            "Day three of entries. The pattern shows — re-read at week's end.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stgr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stgr_apotheosis_1", A,
            "Block closed. Daily continues — the discipline IS the gift.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stgr_apotheosis_2", A,
            "Cycle done. Re-read the past month — the pattern is in plain sight.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stgr_apotheosis_3", A,
            "Closed. Same notebook, same time, same discipline.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stgr_apotheosis_first_ever", A,
            "First block of daily entries. Most quit by week 2 — you did not.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stgr_apotheosis_1", "stgr_apotheosis_2", "stgr_apotheosis_3"),
            theme = T),
        DialogueLine("stgr_apotheosis_at_level_2", A,
            "Promoted. Entries sharper — do not switch to performance. Stay honest.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stgr_apotheosis_at_level_3", A,
            "Senior tier. The lens is permanent — you notice without writing first. Still write.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stgr_apotheosis_at_level_4", A,
            "Highest tier. Daily entries, forever — same shelf, same notebook, same hour.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stgr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stgr_nudge_morning", A,
            "Morning. Three things — specific. Now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stgr_nudge_afternoon_zero", A,
            "Halftime. Notebook empty. One line — five seconds.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stgr_nudge_evening", A,
            "Evening. List the day — what did not go wrong. Honest.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stgr_nudge_lapse", A,
            "Skipped yesterday. Today, one line — do not catch up. Just today.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stgr_nudge_attention_loss", A,
            "Weeks of blank pages. Today's entry — just today's. One line.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stgr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
