package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Family & kin. */
internal object StoicFamilyLines {

    private const val A = "STOIC"
    private const val T = "FAMILY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stfa_first_ever", A,
            "Family is given, not chosen. Show up — it is what virtue looks like here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stfa_morning", A,
            "Morning. Text your mother — not a heart emoji. A sentence.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfa_morning_early", A,
            "Up early. The old folks are awake — one call. Five minutes. Worth it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfa_afternoon", A,
            "Mid-day. The cousin you meant to text — now. Do not draft for an hour.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfa_evening", A,
            "Evening. Call before bed — ten minutes. They sleep with it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfa_night_late", A,
            "Late. Do not call now — note who. Tomorrow morning. Real call.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stfa_post_apotheosis", A,
            "Stretch closed. Do not go silent — weekly call. Standing time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stfa_monday", A,
            "Monday. Plan the weekly call — same time, every week. Do not skip.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stfa_friday", A,
            "Friday. They will ask what you did — have a real answer ready.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stfa_weekend", A,
            "Weekend. Sunday lunch is a discipline — show up. They notice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stfa_level_1_reached", A,
            "First tier. First real call in a while — they will mention it. Brush it off.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stfa_level_2_reached", A,
            "Second tier. The weekly call is a thing — they count on it. Do not break it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stfa_level_3_reached", A,
            "Third tier. The whole family knows you show up — earn it weekly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stfa_level_4_reached", A,
            "Highest tier. You are the one who shows up — defend the title.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stfa_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stfa_attention_loss_mild", A,
            "Three weeks of silence. They noticed — call today. No apology, just show up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stfa_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stfa_attention_loss_hard", A,
            "Months gone quiet. Do not draft an explanation — call. Today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stfa_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stfa_after_lapse", A,
            "Missed the call yesterday. Make it up today — do not apologize. Just do it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stfa_mid_day_return", A,
            "Halftime. Nobody contacted. The call will not make itself — now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stfa_wishes_pending", A,
            "Reward accumulates. Visit them — drive over. Stale wins do not visit on their own.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stfa_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stfa_mid_streak", A,
            "Three weeks of consistent contact — they feel it. Maintain.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stfa_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stfa_sant_jordi", A,
            "Sant Jordi. Drop a book at your mother's — do not text. Drop by.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_la_merce", A,
            "Mercè. Family is at the parade — show up. Stand with them in the crowd.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_sant_joan", A,
            "Sant Joan. Family beach gathering — bring food. Stay til the fireworks.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_diada", A,
            "Diada. Day off. Call them — the long call, not the quick one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_nadal", A,
            "Nadal. The table is the whole point — be there. Phone in the bag.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_cap_d_any", A,
            "New year. First call of the year — to the one you put off in December.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stfa_reis", A,
            "Reis. The kids — show up with the gift. In person. Not the late delivery.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_carnaval", A,
            "Carnaval. Kids in costume — be the uncle or aunt who shows up to see it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_divendres_sant", A,
            "Quiet day. Long call to the one who is hard to reach — today is the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_pasqua", A,
            "Pasqua Monday. Family mona — go. Eat too much. Hug the niece.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_festa_del_treball", A,
            "Workers' day. Family lunch — be at the table. Help clean up after.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_festa_major_gracia", A,
            "Gràcia. Take the niece — the festival is for them more than you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_assumpcio", A,
            "August. Family is at the pueblo — visit. Even for one day. They count it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_hispanitat", A,
            "Day off. Drive over — do not text 'busy'. Show up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_castanyada", A,
            "Castanyada. Bring chestnuts to your mother — sit with her an hour.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_constitucio", A,
            "Bridge weekend. Family gathering somewhere — go. Do not fake a meeting.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_immaculada", A,
            "Pont. Five days — two at the family place. Real time, phone off.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_sant_esteve", A,
            "Day after Nadal. Family is still gathered — stay. Do not bolt early.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_cap_d_any_eve", A,
            "Last day. Twelve grapes with them — not alone on the couch.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stfa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stfa_birthday", A,
            "Your day. Call your mother — she brought you here. One call.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stfa_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_personal_date", A,
            "You marked this day: {label}. Family knows what this means — bring them in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stfa_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stfa_complete_1", A, "Called. Next.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stfa_complete_2", A, "Done. They felt it — do not ask if they did.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stfa_complete_3", A, "Logged. Phone away — do not broadcast it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stfa_complete_first_today", A,
            "First call. The day is now better than zero — do not stop.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stfa_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stfa_complete_second_today", A,
            "Two reaches. Do not spam — quality, not frequency.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stfa_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stfa_complete_third_today", A,
            "Three. Either a big family day or you overcompensate — be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stfa_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stfa_complete_fourth_today", A,
            "Four. Stop — let them breathe. They have lives too.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stfa_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stfa_complete_fifth_today", A,
            "Five. Hovering. Step back — consistency over quantity.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stfa_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stfa_complete_after_streak", A,
            "Three weeks of showing up. They count on you — a real thing.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stfa_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stfa_apotheosis_1", A,
            "Stretch closed. Do not go quiet — weekly call. Standing time.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stfa_apotheosis_2", A,
            "Cycle done. The reputation is built — maintain it weekly.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stfa_apotheosis_3", A,
            "Closed. Plan the next visit — real. On the calendar.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stfa_apotheosis_first_ever", A,
            "First real stretch of being present. They noticed — they told someone.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stfa_apotheosis_1", "stfa_apotheosis_2", "stfa_apotheosis_3"),
            theme = T),
        DialogueLine("stfa_apotheosis_at_level_2", A,
            "Promoted. The weekly call is sacred — do not break it for a meeting.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stfa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stfa_apotheosis_at_level_3", A,
            "Senior tier. You are the one who shows up — defend the title.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stfa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stfa_apotheosis_at_level_4", A,
            "Highest tier. The family lives different because of you — do not slip.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stfa_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stfa_nudge_morning", A,
            "Morning. Text your mother — real sentence. Not 'morning, love'.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stfa_nudge_afternoon_zero", A,
            "Halftime. Nobody contacted. One call — five minutes. Move.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stfa_nudge_evening", A,
            "Evening. Call before bed — short and real. They sleep with it.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stfa_nudge_lapse", A,
            "Missed yesterday. Call today — no apology. Just do it.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stfa_nudge_attention_loss", A,
            "Months gone quiet. Call today — do not draft an explanation.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stfa_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
