package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Relationships & love. */
internal object StoicLoveLines {

    private const val A = "STOIC"
    private const val T = "LOVE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stlo_first_ever", A,
            "The other person is not in your control — your attention is. Give it. Begin.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stlo_morning", A,
            "Tell them something specific before you leave. Not “have a good day” — a real thing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stlo_morning_early", A,
            "Coffee for two, if they are up. Small acts, done daily, are the whole of it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stlo_afternoon", A,
            "Text them something real, not a meme. A sentence they can hold.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stlo_evening", A,
            "Phone in another room while you eat. Look at each other instead.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stlo_night_late", A,
            "Do not drift apart on separate screens at this hour. Reach over.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stlo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stlo_post_apotheosis", A,
            "The stretch closed. Do not coast now — a relationship pays the rent every single day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stlo_monday", A,
            "Plan one real thing together this week. Do not let it drift into next.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stlo_friday", A,
            "The weekend is together-time. Not beside-each-other-on-the-couch time. There is a difference.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stlo_weekend", A,
            "One real conversation today, slow. Not logistics — the other kind.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stlo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stlo_level_1_reached", A,
            "The first real check-in. The wall came down — do not quietly rebuild it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stlo_level_2_reached", A,
            "Second tier. They notice the effort — do not slack. That is when most do.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stlo_level_3_reached", A,
            "Third tier. The relationship is its own thing — tend it like a garden.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stlo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stlo_level_4_reached", A,
            "Highest tier. Real partnership — defend it daily. There is no autopilot.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stlo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stlo_attention_loss_mild", A,
            "Three days of 'fine'. The danger zone — one real question tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stlo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stlo_attention_loss_hard", A,
            "Two weeks of drifting. Sit down tonight — no screens. Talk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stlo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stlo_after_lapse", A,
            "Yesterday went quiet. Do not compound — one real sentence tonight. Specific.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stlo_mid_day_return", A,
            "Halftime. No contact yet — text them now. Real sentence.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stlo_wishes_pending", A,
            "Reward accumulates. Plan a date — now. Stale wins go cold.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stlo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stlo_mid_streak", A,
            "Three days of showing up. They feel it — do not drop now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stlo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stlo_sant_jordi", A,
            "Sant Jordi. Book or rose, no matter — show up with intention.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_la_merce", A,
            "Mercè. Crowds together — hold their hand. Do not lose each other.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_sant_joan", A,
            "Sant Joan. Beach, fire, together — do not end on different couches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_diada", A,
            "Diada. Day off together — do not fill it with separate errands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_nadal", A,
            "Nadal. Family takes the day — steal ten minutes alone. You need it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_cap_d_any", A,
            "New year. First conversation of the year — honest. Do not waste the moment.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stlo_reis", A,
            "Reis. Gift them something specific — not last-minute. Pay attention.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_carnaval", A,
            "Carnaval. Costume night together — pick silly. Laugh.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_divendres_sant", A,
            "Quiet day. Long talk over coffee — only quiet days allow this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_pasqua", A,
            "Pasqua Monday. Reset the week together — meal, walk, anything.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_festa_del_treball", A,
            "Workers' day. The relationship is work too — honor the rest. Show up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_festa_major_gracia", A,
            "Gràcia. Walk the streets together — one tiny stall. Do not lose each other.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_assumpcio", A,
            "August. Heat slows things — long lunch together. No errands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_hispanitat", A,
            "Day off. Trip out of the city — even an hour away counts as together-time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_castanyada", A,
            "Castanyada. Walk together. Roasted chestnuts. Stand close in the cold.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_constitucio", A,
            "Bridge weekend. Plan one trip — doesn't have to be far. Just the two of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_immaculada", A,
            "Pont. Five days. Rest together, or travel — pick one fully.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_sant_esteve", A,
            "Day after. Family chaos — steal a quiet moment alone with them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_cap_d_any_eve", A,
            "Last day. Talk about the year together — honest. Good and hard both.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stlo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stlo_birthday", A,
            "Your day. Receive what they planned — do not critique. Be present.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stlo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_personal_date", A,
            "You marked this day: {label}. They know it matters — bring them in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stlo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stlo_complete_1", A, "Showed up. Next moment.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stlo_complete_2", A, "Done. They felt it — do not fish for proof.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stlo_complete_3", A, "Logged. Phone away when you sit with them.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stlo_complete_first_today", A,
            "First real check-in. The day is already different between you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stlo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stlo_complete_second_today", A,
            "Two reaches. Pace yourself — do not smother.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stlo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stlo_complete_third_today", A,
            "Three. The day was full of them — real partnership.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stlo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stlo_complete_fourth_today", A,
            "Four. Either a big day or you hover — be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stlo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stlo_complete_fifth_today", A,
            "Five. Give them space — connection is not surveillance.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stlo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stlo_complete_after_streak", A,
            "Day three of showing up. They feel it — do not ask if they do.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stlo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stlo_apotheosis_1", A,
            "Stretch closed. Keep showing up tomorrow — same disciplines.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stlo_apotheosis_2", A,
            "Cycle done. The relationship is stronger — do not coast on the credit.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stlo_apotheosis_3", A,
            "Closed. Plan the next thing together — forward motion.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stlo_apotheosis_first_ever", A,
            "First real chapter together, fully shown up for. Do not forget how it felt.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stlo_apotheosis_1", "stlo_apotheosis_2", "stlo_apotheosis_3"),
            theme = T),
        DialogueLine("stlo_apotheosis_at_level_2", A,
            "Promoted. You are a real partner now — do not slack. That is when most do.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stlo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stlo_apotheosis_at_level_3", A,
            "Senior tier. People notice how you treat them — stay consistent.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stlo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stlo_apotheosis_at_level_4", A,
            "Highest tier. Defend the relationship like a deadline — no autopilot. Ever.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stlo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stlo_nudge_morning", A,
            "Morning. One specific thing before you leave — not 'love you, bye'.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stlo_nudge_afternoon_zero", A,
            "Halftime. No contact yet — text them. Real sentence. Now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stlo_nudge_evening", A,
            "Evening. Phone elsewhere when you eat — look at them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stlo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stlo_nudge_lapse", A,
            "Yesterday went quiet. Do not compound — one real sentence today.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stlo_nudge_attention_loss", A,
            "Weeks of drifting. Sit down tonight — no screens. Talk.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stlo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
