package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Writing & creativity. */
internal object StoicWritingLines {

    private const val A = "STOIC"
    private const val T = "WRITING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stwr_first_ever", A,
            "The page is patient. The hand is in your control — write the ugly first sentence.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stwr_morning", A,
            "Morning. Best writing hour — do not give it to the inbox.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stwr_morning_early", A,
            "Pre-dawn. Mind quiet — two hundred words before the world starts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stwr_afternoon", A,
            "Mid-day. Inspiration is a story — sit, write. Anything.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stwr_evening", A,
            "Evening. Edit what was written this morning — two passes. Then stop.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stwr_night_late", A,
            "Late. Do not draft tired — note the idea. Sharpen it tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stwr_post_apotheosis", A,
            "Piece done. Publish or shelve — stale drafts grow heavy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stwr_monday", A,
            "Monday. Set the week's word count — halve it. Make it possible.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stwr_friday", A,
            "Friday. Ship the draft before the weekend — do not carry it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stwr_weekend", A,
            "Weekend. Long-form day — three hours. No edits. Words down.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stwr_level_1_reached", A,
            "First tier. First piece finished — most never leave the blank page.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stwr_level_2_reached", A,
            "Second tier. The voice is arriving — trust it. Do not edit it silent.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stwr_level_3_reached", A,
            "Third tier. Real work, regular cadence — share it. Hiding is fear.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stwr_level_4_reached", A,
            "Highest tier. The voice is yours — defend the writing time like a deadline.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stwr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stwr_attention_loss_mild", A,
            "Three days no words. The blank page wins — one paragraph today. Anything.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stwr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stwr_attention_loss_hard", A,
            "Weeks of silence. Do not write the masterpiece — write garbage. The voice returns.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stwr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stwr_after_lapse", A,
            "Yesterday's words did not happen. Today's are in your control — fifty.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stwr_mid_day_return", A,
            "Half the day, page blank. Twenty minutes — does not have to be good. Has to exist.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stwr_wishes_pending", A,
            "Reward accumulates. Take the writing retreat day — stale wins are no wins.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stwr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stwr_mid_streak", A,
            "Three writing days. Voice awake — do not break the rhythm.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stwr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stwr_sant_jordi", A,
            "Sant Jordi. Writers' day — buy a book, then write one paragraph.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_la_merce", A,
            "Mercè. City loud — write at a café in the morning. Do not lose the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_sant_joan", A,
            "Sant Joan. No words tonight — beach, fireworks. Write tomorrow about what you saw.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_diada", A,
            "Diada. Long day, long block — three hours uninterrupted.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_nadal", A,
            "Nadal. Words rest. Listen at the table — notes for January.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_cap_d_any", A,
            "First day. The first three sentences set the year's voice — write them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stwr_reis", A,
            "Reis. Read the new book — note what works. That is writing practice too.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_carnaval", A,
            "Carnaval. Watch the costumes — characters write themselves. Take notes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_divendres_sant", A,
            "Quiet day. The kind of stillness writing needs — two hours, no phone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_pasqua", A,
            "Pasqua Monday. Coming off break — reset. One paragraph today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_festa_del_treball", A,
            "Workers' day. The work is words — honor the rest. Write tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_festa_major_gracia", A,
            "Gràcia. Carry a notebook — the streets write themselves into you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_assumpcio", A,
            "August. Empty city — best writing month. Do not waste it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_hispanitat", A,
            "Day off. Read the thing you avoided — write a response. Real writing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_castanyada", A,
            "Castanyada. Dark by 7 — long-form season. Indoor evenings, long pages.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_constitucio", A,
            "Bridge weekend. Ship a piece — or rest. Do not half-draft for four days.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_immaculada", A,
            "Pont. Five days. A real first draft is possible — or rest. Do not dabble.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_sant_esteve", A,
            "Day after. Light edit on yesterday's notes — do not aim for new work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_cap_d_any_eve", A,
            "Last day. Count the pages written this year — honest. Plan next year's volume.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stwr_birthday", A,
            "Your day. Write yourself a letter — honest. Read it next year.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stwr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_personal_date", A,
            "You marked this day: {label}. The kind of day to write about — notes, one paragraph.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stwr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stwr_complete_1", A, "Words down. Next paragraph.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stwr_complete_2", A, "Logged. Do not reread now — keep going.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stwr_complete_3", A, "Done. Close the file. Edit tomorrow.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stwr_complete_first_today", A,
            "First lines down. The blank page is dead — move.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stwr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stwr_complete_second_today", A,
            "Two sessions. Do not burn out — quality drops past 90 minutes.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stwr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stwr_complete_third_today", A,
            "Three. Real writing day — the piece is denser than morning.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stwr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stwr_complete_fourth_today", A,
            "Four. Stop — rest the voice. Tomorrow sharper.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stwr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stwr_complete_fifth_today", A,
            "Five. Past lucid — typing, not writing. Stop.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stwr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stwr_complete_after_streak", A,
            "Day three of writing. Voice awake — keep the rhythm.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stwr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stwr_apotheosis_1", A,
            "Piece done. Publish or shelve in 48 hours — do not let it rot.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stwr_apotheosis_2", A,
            "Closed. Next piece's first sentence — write it now, while warm.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stwr_apotheosis_3", A,
            "Done. Read it tomorrow with fresh eyes — edit ruthlessly.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stwr_apotheosis_first_ever", A,
            "First piece, top to bottom. You are a writer who finishes — most aren't.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stwr_apotheosis_1", "stwr_apotheosis_2", "stwr_apotheosis_3"),
            theme = T),
        DialogueLine("stwr_apotheosis_at_level_2", A,
            "Promoted. Voice consistent — longer pieces possible.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stwr_apotheosis_at_level_3", A,
            "Senior tier. People read what you write — do not write less, write harder.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stwr_apotheosis_at_level_4", A,
            "Highest tier. The voice is unmistakable — defend the writing time. Always.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stwr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stwr_nudge_morning", A,
            "Morning. Page open. Two hundred words — do not think, write.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stwr_nudge_afternoon_zero", A,
            "Halftime. Page blank. Twenty minutes — anything. Type.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stwr_nudge_evening", A,
            "Evening. Edit pass — two reads, then close.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stwr_nudge_lapse", A,
            "Yesterday's words did not happen. Today's fifty. Now.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stwr_nudge_attention_loss", A,
            "Weeks of silence. Write garbage today — type. The voice returns with patience.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stwr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
