package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Tidyness & home. */
internal object StoicTidynessLines {

    private const val A = "STOIC"
    private const val T = "TIDYNESS"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stti_first_ever", A,
            "The room holds what you let it hold. The choice is yours — begin.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stti_morning", A,
            "Bed made, counter clear, and the day begins more orderly.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stti_morning_early", A,
            "Five minutes on the kitchen before dawn — the rest of the day softens because of it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stti_afternoon", A,
            "One surface, wiped at mid-day — two minutes is all it costs.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stti_evening", A,
            "The closing rounds this evening — dishes in, trash out. The room resets itself for tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stti_night_late", A,
            "Do not begin the deep clean at this hour. One small thing — then sleep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stti_post_apotheosis", A,
            "Block closed. Do not let it slide — two minutes daily holds the room.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stti_monday", A,
            "Counter clear, calendar clear, head clear — that is the order for a Monday.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stti_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stti_friday", A,
            "Do not enter the weekend carrying three days of dishes. Knock them out first.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stti_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stti_weekend", A,
            "One full pass through the room this weekend — then sit in it as it is. That is the reward.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stti_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stti_level_1_reached", A,
            "The kitchen is usable again. A small kingdom, restored.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stti_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stti_level_2_reached", A,
            "Surfaces stay clear now without effort. The system works.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stti_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stti_level_3_reached", A,
            "You walk in and the room is already right. Maintain it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stti_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stti_level_4_reached", A,
            "The home runs itself now, not the reverse. Do not let it slip.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stti_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stti_attention_loss_mild", A,
            "Three days of pile-up. Twenty-minute reset — now, not tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stti_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stti_attention_loss_hard", A,
            "The room is buried. One room today — do not try the whole place.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stti_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stti_after_lapse", A,
            "Yesterday's mess is today's — do not add to it. Clear one surface first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stti_mid_day_return", A,
            "Half the day gone, and the room is as it was. Five minutes fixes it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stti_wishes_pending", A,
            "Reward accumulates. Spend it — do not hoard wins.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stti_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stti_mid_streak", A,
            "Three clean days. The room feels different — do not quit yet.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stti_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stti_sant_jordi", A,
            "Out today for the roses and the books — a five-minute reset before you go. The room waits, patiently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_la_merce", A,
            "People over later for Mercè. Clear the entry, the bathroom, the table. Done.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_sant_joan", A,
            "Sand will land tomorrow after tonight's fires. Pre-clear the entryway now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_diada", A,
            "Window open today, one room deep-cleaned. The air moves, and the mood moves with it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_nadal", A,
            "Family arrives today. Bathroom and entry are what matter — nobody inspects the closets.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_cap_d_any", A,
            "A tidied room on the first day sets the tone for the year that follows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stti_reis", A,
            "Wrapping paper everywhere this morning. Bag it now — do not let it sit a week.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_carnaval", A,
            "The costume will be in pieces by Wednesday. Decide now where it goes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_divendres_sant", A,
            "A quiet day, well spent on the cupboard you have avoided. Forty minutes. Done, forever.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_pasqua", A,
            "Spring is real by this Monday. One window, one corner — take it slow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_festa_del_treball", A,
            "Domestic work is work too, and today honors it. One solid hour is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_festa_major_gracia", A,
            "The confetti from Gràcia ends up everywhere. Keep the vacuum by the door this week.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_assumpcio", A,
            "The August heat argues against a deep clean. One light surface pass, then shutters down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_hispanitat", A,
            "A day off is the moment to tackle the one drawer that mocks you. Forty minutes, no more.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_castanyada", A,
            "Autumn arrives properly now. Swap the closet — summer out, winter in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_constitucio", A,
            "A tidy day or a rest day, across this bridge weekend. Pick one — do not drift through both.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_immaculada", A,
            "Pont. Five days. Pre-Christmas reset of the kitchen — future-you bows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_sant_esteve", A,
            "Day after. Leftovers organized — wrapping paper gone. Twenty minutes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_cap_d_any_eve", A,
            "Last day. Room clean before midnight — start the year unburied.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stti_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stti_birthday", A,
            "Your day. Room clean before guests — the bathroom counts double.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stti_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stti_personal_date", A,
            "You marked this day: {label}. Room matches the day — tidy, or honestly let slide.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stti_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stti_complete_1", A, "Surface clear. Walk on.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stti_complete_2", A, "Done. Notice the surface stays — that is the gift.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stti_complete_3", A, "Logged. Put the tool back where you took it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stti_complete_first_today", A,
            "First clean task. The room is in motion.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stti_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stti_complete_second_today", A,
            "Two areas done. Compounding — do not trash it now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stti_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stti_complete_third_today", A,
            "Three. The place feels yours — sit in it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stti_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stti_complete_fourth_today", A,
            "Four. Stop — you are not running a hotel.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stti_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stti_complete_fifth_today", A,
            "Five. Either the room was a wreck or you avoid something — be honest.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stti_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stti_complete_after_streak", A,
            "Three clean days. The place is on cruise — keep the daily two minutes.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stti_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stti_apotheosis_1", A,
            "Big clean done. Daily two-minute pass starts tomorrow — quietly.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stti_apotheosis_2", A,
            "Cycle closed. The next room is the one you avoided — but later.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stti_apotheosis_3", A,
            "Closed. Maintenance is the work — do not get cocky.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stti_apotheosis_first_ever", A,
            "First real clean of the place in years, probably. Hold it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stti_apotheosis_1", "stti_apotheosis_2", "stti_apotheosis_3"),
            theme = T),
        DialogueLine("stti_apotheosis_at_level_2", A,
            "Promoted. The room holds itself — maintenance, not heroics.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stti_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stti_apotheosis_at_level_3", A,
            "Senior tier. The place is calm — guests notice. Do not slip.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stti_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stti_apotheosis_at_level_4", A,
            "Highest tier. The home holds you — defend that.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stti_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stti_nudge_morning", A,
            "Morning. Bed made. Surface clear. One minute each — move.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stti_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stti_nudge_afternoon_zero", A,
            "Halftime. Nothing tidied. Pick a surface — five minutes. Done.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stti_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stti_nudge_evening", A,
            "Evening. Dishes, counter, bag — three things, then rest.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stti_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stti_nudge_lapse", A,
            "Yesterday's mess. Today's reset — do not compound.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stti_nudge_attention_loss", A,
            "Room buried. One room today — do not try the whole flat.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stti_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
