package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Recovery (rest, deload, injury, illness, burnout). */
internal object StoicRecoveryLines {

    private const val A = "STOIC"
    private const val T = "RECOVERY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stre_first_ever", A,
            "Rest is in your control or it is not. Choose the rest — the rest follows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stre_morning", A,
            "An honest check this morning — what does the body say? Listen first, plan second.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stre_morning_early", A,
            "Up early calls for a slow start, not optional. The body keeps the ledger.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stre_afternoon", A,
            "Mid-day asks for a pause — a twenty-minute lie-down, or a walk in shade. Pick one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stre_evening", A,
            "Wind down this evening. No new project tonight — that is not weakness, that is wisdom.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stre_night_late", A,
            "Pushing through at this hour is not the discipline — sleeping is. Down tools, quietly.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stre_post_apotheosis", A,
            "Recovery block done. Now actually take a day off. Not a soft one — a real one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stre_monday", A,
            "The week starts with the recovery from the weekend, not the calendar. Note the deficit.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stre_friday", A,
            "The week leaves a tax by Friday. Plan tonight to do nothing, well.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stre_weekend", A,
            "Give the weekend one half-day of nothing — phone off, no chores, no plans. That is real recovery.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stre_level_1_reached", A,
            "A week of honouring rest, and sleep is already deeper. Mark it quietly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stre_level_2_reached", A,
            "Deloads scheduled and kept — the body trusts you again. Keep the promise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stre_level_3_reached", A,
            "You read the body now before it has to shout. Rare. Maintain it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stre_level_4_reached", A,
            "Years of rest as discipline, and the burnout is gone. Defend it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stre_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stre_attention_loss_mild", A,
            "Three days running on caffeine. Body keeps the ledger — pay it back tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stre_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stre_attention_loss_hard", A,
            "Two weeks pushing. This is burnout, not weakness — a real day off. Today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stre_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stre_after_lapse", A,
            "Yesterday slipped — you skipped rest. Today is in your control — bed by ten.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stre_mid_day_return", A,
            "Halfway through the day and no rest taken yet. A twenty-minute lie-down, now — not later.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stre_wishes_pending", A,
            "Reward accumulated. Spend it on a slow day — not on another sprint.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stre_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stre_mid_streak", A,
            "Three days of real rest. Body returning — do not undo it tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stre_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stre_sant_jordi", A,
            "The day will move you, roses and books both. Pace it. Sit when you can.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_la_merce", A,
            "The crowds this week drain more than they give. Leave when the body says. No guilt in it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_sant_joan", A,
            "Tonight runs late by the fires. That is the price of it — tomorrow, rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_diada", A,
            "A day off, and it deserves to be treated as one — no make-up work, no list.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_nadal", A,
            "The family is loud today. Slip away for twenty minutes — the body needs it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_cap_d_any", A,
            "Let this be a year of rest as discipline, not as collapse. Plan the deloads now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stre_reis", A,
            "The sugar crash will come by afternoon. Flat water, and walk slowly through it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_carnaval", A,
            "The noise tonight is depleting, whatever the costume. Recover properly on Tuesday — no bravery required.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_divendres_sant", A,
            "The city has gone quiet today, resting in place. Copy it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_pasqua", A,
            "A slow walk, a slow lunch — that is the whole work of this Monday.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_festa_del_treball", A,
            "The body is also a worker, and today is its day too. Give it the rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_festa_major_gracia", A,
            "The late nights in Gràcia stack quickly. Plan an afternoon off this week, and actually take it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_assumpcio", A,
            "August teaches its own lesson — rest fully, or rest poorly. The choice is yours.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_hispanitat", A,
            "A day off, best treated like maintenance. Do nothing, well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_castanyada", A,
            "The dark comes earlier now. Sleep earlier too — match the season instead of fighting it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_constitucio", A,
            "Two slow days sit ahead in this bridge weekend. Defend them from being filled.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_immaculada", A,
            "Five days open up. Give two of them to real rest — bed early, no plans.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_sant_esteve", A,
            "Holidays are tiring too, however they look from outside. A slow start today, no obligations.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_cap_d_any_eve", A,
            "A long night lies ahead. Nap this afternoon — not optional, however it feels.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stre_birthday", A,
            "The kindest thing you can give yourself today is a long sleep. Plan it in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stre_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stre_personal_date", A,
            "You marked this day: {label}. Body will feel it — clear tomorrow morning.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stre_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stre_complete_1", A, "Rest taken. Done. Body thanks you.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stre_complete_2", A, "Deload logged. The week is wiser for it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stre_complete_3", A, "Done. The slow day is the work.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stre_complete_first_today", A,
            "First rest taken — without guilt. That is the practice.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stre_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stre_complete_second_today", A,
            "Two recovery blocks. The body is being heard — do not undo it now.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stre_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stre_complete_third_today", A,
            "Three. Today was for recovery — let it be that. No bonus work.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stre_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stre_complete_fourth_today", A,
            "Four. Either you are very sick or you are turning rest into a task — be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stre_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stre_complete_fifth_today", A,
            "Five. Rest is not a leaderboard — stop counting. Sit.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stre_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stre_complete_after_streak", A,
            "Day three honouring rest. The system catches up — hold the cadence.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stre_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stre_apotheosis_1", A,
            "Block done. The recovery is not graduation — schedule the next deload now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stre_apotheosis_2", A,
            "Cycle closed. The body trusts you again. Do not betray it next month.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stre_apotheosis_3", A,
            "Done. Rest is the work — there is no graduation. Maintain.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stre_apotheosis_first_ever", A,
            "First block honouring rest. The burnout loop is broken — keep the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stre_apotheosis_1", "stre_apotheosis_2", "stre_apotheosis_3"),
            theme = T),
        DialogueLine("stre_apotheosis_at_level_2", A,
            "Promoted. Recovery is policy now — defend it from the urgent that is not important.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stre_apotheosis_at_level_3", A,
            "Senior tier. People see you rest and learn — be the example. No bravado.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stre_apotheosis_at_level_4", A,
            "Highest tier. Years of rest as discipline — the body is the proof. Hold it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stre_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stre_nudge_morning", A,
            "Morning. Honest check — what does the body say?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stre_nudge_afternoon_zero", A,
            "Halftime. No rest taken. Twenty-minute lie-down — that is the deal.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stre_nudge_evening", A,
            "Evening. Wind down. No new project tonight.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stre_nudge_lapse", A,
            "Yesterday skipped. Bed by ten tonight — non-negotiable.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stre_nudge_attention_loss", A,
            "Burnout signal is loud. A real day off — today. Not optional.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stre_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
