package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Stoic × Boundaries (saying no, protecting time, limits). */
internal object StoicBoundariesLines {

    private const val A = "STOIC"
    private const val T = "BOUNDARIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("stbo_first_ever", A,
            "Your limits are yours. State them — clearly, once. The rest follows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("stbo_morning", A,
            "Morning. One 'no' planned for today — name it. Then keep it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "stbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stbo_morning_early", A,
            "Up early. Do not answer email yet — the day is yours until you decide otherwise.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "stbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stbo_afternoon", A,
            "Mid-day. The 'just one more' request — that is the one to refuse.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "stbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stbo_evening", A,
            "Evening. Work is done. Notifications off. The day belongs to you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "stbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stbo_night_late", A,
            "Late. Anyone asking now does not respect your hours — answer tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "stbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("stbo_post_apotheosis", A,
            "Block done. The next 'yes' is the test — pause before agreeing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("stbo_monday", A,
            "Monday. Audit the week — what got added without your consent? Cut it now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "stbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stbo_friday", A,
            "Friday. Weekend belongs to you — refuse the late work-creep. Out of office now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "stbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("stbo_weekend", A,
            "Weekend. The phone is on silent for the family hours — that is non-negotiable.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "stbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("stbo_level_1_reached", A,
            "First tier. One real 'no' kept this week — the world did not end. Mark it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "stbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stbo_level_2_reached", A,
            "Second tier. The limits hold without rehearsal — others learn them. Keep them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "stbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stbo_level_3_reached", A,
            "Third tier. People stop asking the wrong way — the boundary did the teaching.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "stbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("stbo_level_4_reached", A,
            "Highest tier. Years of clean limits — the calendar is yours. Defend daily.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "stbo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("stbo_attention_loss_mild", A,
            "Three days of yes-to-everything. The body knows — refuse one thing today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "stbo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("stbo_attention_loss_hard", A,
            "Two weeks of collapse. The calendar is not yours — reclaim one block today. The hard one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stbo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("stbo_after_lapse", A,
            "Yesterday you said yes when you meant no. Today is in your control — refuse one thing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Understood", null)), theme = T),
        DialogueLine("stbo_mid_day_return", A,
            "Halftime. Calendar full of other people's work — block one hour now. For you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("stbo_wishes_pending", A,
            "Reward accumulated. Spend it on a real day off — not another favour for someone else.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "stbo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("stbo_mid_streak", A,
            "Three days holding limits. Quieter, clearer — do not give it back tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stbo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("stbo_sant_jordi", A,
            "Sant Jordi. The day is for the streets — work emails wait. Out of office.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_la_merce", A,
            "Mercè. You are off — say so out loud once. Then turn off the phone.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_sant_joan", A,
            "Sant Joan. No work tonight. Tomorrow is yours too — refuse the early call.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_diada", A,
            "Diada. The day is yours — others will ask anyway. Politely refuse.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_nadal", A,
            "Nadal. Family hours — phone in another room. That is the limit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_cap_d_any", A,
            "New year. Audit commitments — cut two that were never yours. Name them today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stbo_reis", A,
            "Reis. Family-only day — work asks anyway. Decline once, clearly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_carnaval", A,
            "Carnaval. Saying no to one party preserves the next two — quality over count.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_divendres_sant", A,
            "Quiet day. The city models the limit — copy it. No work today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_pasqua", A,
            "Pasqua Monday. Refuse to make up Friday's missed work — the calendar agreed already.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_festa_del_treball", A,
            "Workers' day. The limit between labour and rest — observe it. No work today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_festa_major_gracia", A,
            "Gràcia. Pick the two nights — refuse the rest. You cannot give all of yourself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_assumpcio", A,
            "August. The city closes — copy it. Out of office for real. No exceptions.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_hispanitat", A,
            "Bridge day. Defend it — colleagues will ask anyway. Politely refuse.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_castanyada", A,
            "Castanyada. Year-end pressure starts — refuse the early scope-creep now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_constitucio", A,
            "Bridge weekend. Two days, no work — say it out loud. Hold the line.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_immaculada", A,
            "Pont. Five days. Refuse the 'quick favour' email today — set the limit early.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_sant_esteve", A,
            "Day after. Family heavy — slip away for an hour. That counts as a 'no'.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_cap_d_any_eve", A,
            "Last day. The year's commitments — three to drop. Name them tonight.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "stbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("stbo_birthday", A,
            "Your day. Refuse one obligation tonight — that is the gift you give yourself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "stbo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_personal_date", A,
            "You marked this day: {label}. Refuse the noise — this hour is yours, fully.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "stbo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("stbo_complete_1", A, "No said. Done. Hour reclaimed.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stbo_complete_2", A, "Limit held. The calendar agrees.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stbo_complete_3", A, "Done. One thing refused — that is the work.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("stbo_complete_first_today", A,
            "First refusal. The sky did not fall — note that for next time.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "stbo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("stbo_complete_second_today", A,
            "Two limits held. Pattern forming — others are learning. Keep it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "stbo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("stbo_complete_third_today", A,
            "Three. Day is quieter — defended, not earned. Different thing.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "stbo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("stbo_complete_fourth_today", A,
            "Four. A heavy day for limits — or you are picking fights. Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "stbo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("stbo_complete_fifth_today", A,
            "Five. Boundaries are not a war — note the count, then stop counting.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "stbo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("stbo_complete_after_streak", A,
            "Day three of clear limits. Calendar honest now — hold the line.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "stbo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("stbo_apotheosis_1", A,
            "Block done. The next 'yes' is the test — pause first. Always.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stbo_apotheosis_2", A,
            "Cycle closed. Limits do not graduate — defend the next one too.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stbo_apotheosis_3", A,
            "Done. The boundary is the practice — there is no off-day. Maintain.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("stbo_apotheosis_first_ever", A,
            "First block holding limits. The yes-to-everything loop is broken — keep the rhythm.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("stbo_apotheosis_1", "stbo_apotheosis_2", "stbo_apotheosis_3"),
            theme = T),
        DialogueLine("stbo_apotheosis_at_level_2", A,
            "Promoted. The calendar is yours — defend it from the new request that just arrived.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "stbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stbo_apotheosis_at_level_3", A,
            "Senior tier. Others learn the limits without asking — be the example. Quietly.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "stbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("stbo_apotheosis_at_level_4", A,
            "Highest tier. Years of clean limits — the calendar tells your story. Hold daily.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "stbo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("stbo_nudge_morning", A,
            "Morning. Name one 'no' for today before email opens.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "stbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stbo_nudge_afternoon_zero", A,
            "Halftime. Calendar swallowed your day — block one hour back. Now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "stbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stbo_nudge_evening", A,
            "Evening. Notifications off — work is done. Hold the line.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "stbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("stbo_nudge_lapse", A,
            "Yesterday you said yes when you meant no. Today — refuse one. Non-negotiable.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("stbo_nudge_attention_loss", A,
            "Calendar collapsed. Reclaim one block today — the hard one. Not optional.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "stbo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
