package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Therapist × Exercise — caring inquiry, body-as-companion. */
internal object TherapistExerciseLines {

    private const val A = "THERAPIST"
    private const val T = "EXERCISE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("thex_first_ever", A,
            "What would feel kind to your body today? No wrong answer.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("thex_morning", A,
            "What does your body actually want right now — a walk, a stretch, or stillness?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "thex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thex_morning_early", A,
            "Up before most people. How is your body greeting the day?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "thex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thex_afternoon", A,
            "Could a small movement break shift something for you right now?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "thex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thex_evening", A,
            "As the day winds down, what would a kind movement look like — gentle, slow, brief?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "thex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thex_night_late", A,
            "This late, the body has usually done enough. Soft stretches only, if anything at all.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "thex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thex_post_apotheosis", A,
            "Something big just closed. Sit with it. The body remembers — small movement tomorrow is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("thex_monday", A,
            "A new week ahead. What's one kind movement you'd actually like to keep in it?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "thex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thex_friday", A,
            "As the week closes, what is your body actually asking for?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "thex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thex_weekend", A,
            "A slower pace still counts as movement, you know. What feels right today?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "thex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("thex_level_1_reached", A,
            "A week of moving now, however small. What's changing in how you feel?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "thex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thex_level_2_reached", A,
            "A month of this now. What does your body know that it didn't before?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "thex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thex_level_3_reached", A,
            "You're showing up reliably. What does that say about you?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "thex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thex_level_4_reached", A,
            "Years of kindness to your body now. What a long, quiet practice that turned out to be.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "thex_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("thex_attention_loss_mild", A,
            "A few rest days now. What feels true about that, actually? A small walk today could be enough.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "thex_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("thex_attention_loss_hard", A,
            "It's been a while since you moved. No judgment. Five minutes today — what feels possible?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thex_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("thex_mid_day_return", A,
            "Halfway through the day. Could a five-minute walk help you reset?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("thex_wishes_pending", A,
            "You've earned something. What would feel like a kind reward?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "thex_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("thex_mid_streak", A,
            "Three days of moving. How does the body feel held by that?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thex_streak", cooldownPicks = 5, theme = T),

        DialogueLine("thex_sant_jordi", A,
            "Sant Jordi tends to move you around the city all day. Pace yourself — sit when you need to.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_la_merce", A,
            "La Mercè has dancing in the streets. That counts too — listen to what your body wants.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_sant_joan", A,
            "Sant Joan — beach, sand, sea air tonight. Your body will probably know what to do with it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_diada", A,
            "Diada could be a walk through the city. What would feel meaningful to move toward?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_nadal", A,
            "Nadal has that post-lunch walk tradition. A long, kind one. Let it carry you today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_cap_d_any", A,
            "The new year opens. What's one kind movement intention — small enough to actually keep?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thex_reis", A,
            "Reis, and probably a lot of sugar. A walk with the kids after — let them set the pace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_carnaval", A,
            "Carnaval — costume, parade, dancing. The body gets to just play today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_divendres_sant", A,
            "A quiet day. A slow walk by the water can be very kind.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_pasqua", A,
            "Pasqua. A trail with mona in the bag. What pace feels right today?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_festa_del_treball", A,
            "It's Workers' Day. Your body is also a worker, in its way — give it a soft kind day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_festa_major_gracia", A,
            "Gràcia's paper-flower streets. Walking street to street is enough — the body fills up on it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_assumpcio", A,
            "August has that slow, half-empty city feel. Slow movement suits it. Let the heat set the pace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_hispanitat", A,
            "A day off today. A hill walk, maybe — what would the view actually be for you?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_castanyada", A,
            "Castanyada, and leaves crunching underfoot. The body has its own way of remembering autumn.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_constitucio", A,
            "A bridge weekend. One walk, maybe two. What can your body actually handle joyfully?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_immaculada", A,
            "A long weekend — one hike, the rest soft. What balance feels honest to you?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_sant_esteve", A,
            "The day after Nadal. A soft walk can let yesterday settle in the body.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_cap_d_any_eve", A,
            "The year's last day. A walk to close it out, maybe — what would you carry into the next one?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "thex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thex_birthday", A,
            "It's your birthday. A walk somewhere you love, maybe. What gift does the body deserve today?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "thex_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("thex_personal_date", A,
            "Today is {label} — you marked it yourself. Move through it kindly. The body remembers.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "thex_personal", cooldownPicks = 1, theme = T),

        DialogueLine("thex_complete_1", A, "Movement taken. Notice how that actually feels in the body.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thex_complete_2", A, "Done. The body got listened to, for once.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thex_complete_3", A, "Logged. A small kind act toward yourself.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thex_complete_first_today", A,
            "First movement. How is the day different now?",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "thex_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("thex_complete_second_today", A,
            "Two now. The body's actually being attended to today.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "thex_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("thex_complete_third_today", A,
            "Three. Drink some water. How is the body holding the day?",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "thex_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("thex_complete_fourth_today", A,
            "Four. Is the body asking for rest now? Listen for it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "thex_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("thex_complete_fifth_today", A,
            "Five. Notice if this is moving from joy to obligation. Sit.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "thex_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("thex_complete_after_streak", A,
            "Three days of moving. What's that doing for you?",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thex_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("thex_apotheosis_1", A,
            "A cycle of movement closes here. Pause a moment. What did your body end up teaching you?",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thex_apotheosis_2", A,
            "Completed. The next chapter can be smaller, kinder.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thex_apotheosis_3", A,
            "Closed. The body knows. Trust that knowing.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thex_apotheosis_first_ever", A,
            "Your first real block closed. What did you discover about how you take care of yourself?",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("thex_apotheosis_1", "thex_apotheosis_2", "thex_apotheosis_3"),
            theme = T),
        DialogueLine("thex_apotheosis_at_level_2", A,
            "You trust the body a bit more now. That's significant, actually. Hold it gently.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "thex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thex_apotheosis_at_level_3", A,
            "Others see how you care for your body. They learn from it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "thex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thex_apotheosis_at_level_4", A,
            "Years of caring for the body as a practice now. A long, kind way to have lived it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "thex_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("thex_nudge_morning", A,
            "What movement would feel kind right now? Five minutes is plenty.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "thex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thex_nudge_afternoon_zero", A,
            "Notice the body's pulse. A short walk might reset things.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "thex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thex_nudge_evening", A,
            "Evening movement can be a quiet thing. What would actually feel restorative right now?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "thex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thex_nudge_attention_loss", A,
            "Five minutes of walking. No judgment — what's possible from where you are?",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thex_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
