package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Therapist × Writing — caring inquiry, the inner voice. */
internal object TherapistWritingLines {

    private const val A = "THERAPIST"
    private const val T = "WRITING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("thwr_first_ever", A,
            "Welcome. The page is a safe room. What's been waiting to be said?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("thwr_morning", A,
            "Three pages, or just one true scene — the mind tends to be closest to itself first thing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "thwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thwr_morning_early", A,
            "Up before you needed to be. It's quiet enough to set down just one word, if that's all there is.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "thwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thwr_afternoon", A,
            "A thirty-minute sprint this afternoon — coffee and words. What wants out today?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "thwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thwr_evening", A,
            "Soft journaling tonight, maybe. One honest sentence is enough.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "thwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thwr_night_late", A,
            "It's late. The brain is soft. One line, then sleep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "thwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thwr_post_apotheosis", A,
            "Big moment. Keep the ritual — the cursor stays kind when it's used.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("thwr_monday", A,
            "New week. A small word count — what feels honest to keep?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "thwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thwr_friday", A,
            "Friday. Read what you wrote. One sentence holds — mark it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "thwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thwr_weekend", A,
            "Weekend. A long-write — café, notebook, hours. The line lengthens.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "thwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("thwr_level_1_reached", A,
            "Daily writing for a month. What is the voice teaching you about yourself?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "thwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thwr_level_2_reached", A,
            "You finish drafts now. What does that feel like to claim?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "thwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thwr_level_3_reached", A,
            "People share your work. Notice the response without rushing to manage it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "thwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thwr_level_4_reached", A,
            "Years of pages. The voice is yours. Be steady with it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "thwr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("thwr_attention_loss_mild", A,
            "Skipped days. What's been pulling you elsewhere? One paragraph today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "thwr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("thwr_attention_loss_hard", A,
            "The page has waited. One line today — softly. No grandeur required.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thwr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("thwr_mid_day_return", A,
            "Twenty-minute sprint. Phone away. The line forms in silence.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("thwr_wishes_pending", A,
            "You've earned a notebook, a pen, ink. Bring it to the page.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "thwr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("thwr_mid_streak", A,
            "Three days of pages. What does the voice know about you now?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thwr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("thwr_sant_jordi", A,
            "Sant Jordi. Write a small love letter to someone — hand-deliver it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_la_merce", A,
            "Mercè. Capture one street-scene. One paragraph. Field notes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_sant_joan", A,
            "Sant Joan. Notes by the fire. Write tomorrow — tonight just show up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_diada", A,
            "Diada. Slow morning, long-write. Café and a notebook.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_nadal", A,
            "Nadal. Christmas cards — real handwriting. A small old practice.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_cap_d_any", A,
            "New year. A small word-count vow — kept honestly is better than large.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thwr_reis", A,
            "Reis. Thank-you notes — by hand. Real and small.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_carnaval", A,
            "Carnaval. A character-sketch from the street — writer-watch.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_divendres_sant", A,
            "Quiet day. Long-form. Deep write. The room is a chapel.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_pasqua", A,
            "Pasqua. Field-notes on the hike. The trail is the prompt.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_festa_del_treball", A,
            "Workers' day. Morning-pages. Free thinking — the hand listens.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_festa_major_gracia", A,
            "Gràcia. Notes on the decorated streets — the neighbours wrote them first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_assumpcio", A,
            "August. Slow city. Writer-summer. Long mornings. The pages come.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_hispanitat", A,
            "A day off. A slow writing session. The hand teaches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_castanyada", A,
            "Castanyada. Long evenings. Page-flow weather — the lamp helps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_constitucio", A,
            "Bridge weekend. A long-write — two hours. The page receives.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_immaculada", A,
            "Pont. Finish a draft. The slow days allow the deep work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_sant_esteve", A,
            "Day after. Journal entry — what mattered yesterday? Three lines.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_cap_d_any_eve", A,
            "Last day. Year-in-review pages. Honest. The lamp helps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "thwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thwr_birthday", A,
            "Your day. A letter to future-you. One year ahead. What do you want to know?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "thwr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_personal_date", A,
            "Today is meaningful: {label}. Three lines about today — hold the date in ink.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "thwr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("thwr_complete_1", A, "Wrote. Notice how it lands.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thwr_complete_2", A, "Pages set down. Good.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thwr_complete_3", A, "Words held. Small honest act.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thwr_complete_first_today", A,
            "First pages. The voice loosens.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "thwr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("thwr_complete_second_today", A,
            "Two. The line lengthens. Stay with it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "thwr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("thwr_complete_third_today", A,
            "Three. The brain is in flow — what's it telling you?",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "thwr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("thwr_complete_fourth_today", A,
            "Four. A big draft day, or running from something? Hydrate either way.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "thwr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("thwr_complete_fifth_today", A,
            "Five. Close the file. Body and brain both need a walk.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "thwr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("thwr_complete_after_streak", A,
            "Three days of pages. The voice tightens. The hand is fluent.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thwr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("thwr_apotheosis_1", A,
            "A cycle of pages closes. What did the voice teach you about yourself?",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thwr_apotheosis_2", A,
            "Completed. The next small goal — smaller, kinder, weirder.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thwr_apotheosis_3", A,
            "Closed. The page is wider now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thwr_apotheosis_first_ever", A,
            "First block. What did you discover about what you have to say?",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("thwr_apotheosis_1", "thwr_apotheosis_2", "thwr_apotheosis_3"),
            theme = T),
        DialogueLine("thwr_apotheosis_at_level_2", A,
            "You finish drafts now. Keep the rhythm — the voice trusts itself more.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "thwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thwr_apotheosis_at_level_3", A,
            "People share your work. Receive the response — don't apologise for it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "thwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thwr_apotheosis_at_level_4", A,
            "Years of pages. The voice is yours. Steady.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "thwr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("thwr_nudge_morning", A,
            "Three pages. The brain is freshest. Don't dramatize.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "thwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thwr_nudge_afternoon_zero", A,
            "Twenty-minute sprint. Phone away — the line forms in silence.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "thwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thwr_nudge_evening", A,
            "One journal line. That is enough today.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "thwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thwr_nudge_attention_loss", A,
            "One line today. The page has waited — softly.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thwr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
