package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Therapist × Family — caring inquiry, the inherited bond. */
internal object TherapistFamilyLines {

    private const val A = "THERAPIST"
    private const val T = "FAMILY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("thfa_first_ever", A,
            "Welcome. Family is complicated and worth tending. What feels possible today?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("thfa_morning", A,
            "Morning. A good-morning text to one family member — small, kind.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "thfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thfa_morning_early", A,
            "Up early. A voice note to mom, dad, sibling — the day inherits it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "thfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thfa_afternoon", A,
            "Afternoon. A two-minute call — drop in. No rehearsal needed.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "thfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thfa_evening", A,
            "Evening. A call — eat dinner over the phone. Awkward and tender are okay.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "thfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thfa_night_late", A,
            "It's late. One good-night text — a small lamp left on for them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "thfa_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thfa_post_apotheosis", A,
            "Big moment. Keep the small rhythms — the line wants the small kindness.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("thfa_monday", A,
            "New week. A weekly call slot — what feels honest to keep?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "thfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thfa_friday", A,
            "Friday. A check-in. They miss you — that doesn't go away.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "thfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thfa_weekend", A,
            "Weekend. A Sunday call. The old line kept by phone.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "thfa_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("thfa_level_1_reached", A,
            "A monthly rhythm. What's the line teaching you about belonging?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "thfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thfa_level_2_reached", A,
            "Visits scheduled. Cards sent. What does that say about how you show up now?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "thfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thfa_level_3_reached", A,
            "Family relies on you for the connecting. Iconic burden — carry it gently.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "thfa_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thfa_level_4_reached", A,
            "Years of family rituals. The bonds are strong. The line is kept.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "thfa_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("thfa_attention_loss_mild", A,
            "Few quiet days. The other side noticed. Call now — don't draft.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "thfa_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("thfa_attention_loss_hard", A,
            "Two weeks silent. They've waited. One text today — softly back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thfa_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("thfa_mid_day_return", A,
            "A three-minute family call. Don't overthink — dial.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("thfa_wishes_pending", A,
            "You've earned a visit — plan one. The line is the gift.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "thfa_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("thfa_mid_streak", A,
            "Three days of family contact. The bonds breathe.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thfa_streak", cooldownPicks = 5, theme = T),

        DialogueLine("thfa_sant_jordi", A,
            "Sant Jordi. Send a book and rose to family — the lore travels.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_la_merce", A,
            "Mercè. Take the family. Castellers — the old human poem.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_sant_joan", A,
            "Sant Joan. Beach with family or cousins. The fire is the photo.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_diada", A,
            "Diada. A long family lunch. The old line kept at the table.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_nadal", A,
            "Nadal. The family day. Be present — phone face down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_cap_d_any", A,
            "New year. Call every family member tomorrow. The ritual holds.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thfa_reis", A,
            "Reis. The family day. Kids first — the old line keeps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_carnaval", A,
            "Carnaval. A family costume. The photo will outlive the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_divendres_sant", A,
            "Quiet day. Slow lunch with family. The room is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_pasqua", A,
            "Pasqua. Mona and hike with family — a shared memory in the making.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_festa_del_treball", A,
            "Workers' day. A family BBQ — the old line kept by smoke.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_festa_major_gracia", A,
            "Gràcia. Take the cousins to see the streets. The neighbourhood teaches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_assumpcio", A,
            "August. A long family week. Slow. The line breathes in summer.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_hispanitat", A,
            "A day off. Family lunch — the room is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_castanyada", A,
            "Castanyada. A family chestnut night — the smell is the inheritance.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_constitucio", A,
            "Bridge weekend. A family trip away — two days, one shared room.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_immaculada", A,
            "Pont. Visit a family member. Bring nothing — the visit is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_sant_esteve", A,
            "Day after. A leftover meal with the rest of the cast — iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_cap_d_any_eve", A,
            "Last day. Big family dinner. Grapes. The line closes the year.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "thfa_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thfa_birthday", A,
            "Your day. Family calls will come. Receive them — they wrote you here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "thfa_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_personal_date", A,
            "Today is meaningful: {label}. Tell one family member — the line travels.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "thfa_personal", cooldownPicks = 1, theme = T),

        DialogueLine("thfa_complete_1", A, "Called. The line landed.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thfa_complete_2", A, "Message sent. Small. Honest.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thfa_complete_3", A, "Family-glow. Real.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thfa_complete_first_today", A,
            "First family-act. Notice the heart soften.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "thfa_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("thfa_complete_second_today", A,
            "Two. The cast notices. The line lengthens.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "thfa_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("thfa_complete_third_today", A,
            "Three. They know you're around. The page is shared.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "thfa_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("thfa_complete_fourth_today", A,
            "Four. A big family day, or a crisis arc. Be soft with yourself either way.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "thfa_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("thfa_complete_fifth_today", A,
            "Five. A giver-day. Rest — the cast can wait.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "thfa_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("thfa_complete_after_streak", A,
            "Three days of rituals. The bonds breathe.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thfa_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("thfa_apotheosis_1", A,
            "A cycle closes. What did the small rhythms teach you about family?",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thfa_apotheosis_2", A,
            "Completed. The next small ritual is waiting — specific, quiet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thfa_apotheosis_3", A,
            "Closed. The family bond is also a writing practice.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thfa_apotheosis_first_ever", A,
            "First block. What did you discover about who you are to them?",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("thfa_apotheosis_1", "thfa_apotheosis_2", "thfa_apotheosis_3"),
            theme = T),
        DialogueLine("thfa_apotheosis_at_level_2", A,
            "Visits scheduled, cards sent. A small giver — keep keeping.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "thfa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thfa_apotheosis_at_level_3", A,
            "You're the family glue. Iconic burden — carry it gently. Ask for help.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "thfa_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thfa_apotheosis_at_level_4", A,
            "Years of rituals. The bonds are strong. The line is kept.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "thfa_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("thfa_nudge_morning", A,
            "A good-morning to family. Don't draft — send.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "thfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thfa_nudge_afternoon_zero", A,
            "Three-minute family call. Now. Don't draft.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "thfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thfa_nudge_evening", A,
            "A call. They miss you — trust that.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "thfa_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thfa_nudge_attention_loss", A,
            "One text today. The cast has waited — softly.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thfa_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
