package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Therapist × Gratitude — caring inquiry, the noticed line. */
internal object TherapistGratitudeLines {

    private const val A = "THERAPIST"
    private const val T = "GRATITUDE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("thgr_first_ever", A,
            "Gratitude is really just what gets noticed. Name one thing, even something small.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("thgr_morning", A,
            "Three small things, right now. Notice how the day already brightens a shade because of it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "thgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thgr_morning_early", A,
            "This early quiet is its own thing. Notice it — the day tends to carry that forward.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "thgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thgr_afternoon", A,
            "One thing that went right today. Note it — no need to make it bigger than it is.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "thgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thgr_evening", A,
            "A three-thing list before sleep, like credits rolling on the day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "thgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thgr_night_late", A,
            "This late, one good thing from today is plenty. Just one. Let yourself sleep with it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "thgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thgr_post_apotheosis", A,
            "Something big just closed. Keep the daily list going — it brightens the more you actually use it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("thgr_monday", A,
            "A new week. Three things to look forward to, specifically — no need to gild them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "thgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thgr_friday", A,
            "As the week closes, three moments from it. Be specific — honest tends to be kind here too.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "thgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thgr_weekend", A,
            "A slower kind of noticing today. Small things. The eye warms up with practice.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "thgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("thgr_level_1_reached", A,
            "A month of these lists now. What's actually different in how you see the day?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "thgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thgr_level_2_reached", A,
            "You catch yourself smiling at small things. What's underneath that?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "thgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thgr_level_3_reached", A,
            "Others notice the warmth. They learn from it — what does that feel like?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "thgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thgr_level_4_reached", A,
            "Years of this noticing now. Whatever glow that's given you is real, if quiet.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "thgr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("thgr_attention_loss_mild", A,
            "A few flat days now. One thing today, even the coffee — it still counts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "thgr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("thgr_attention_loss_hard", A,
            "It's been a heavy stretch. One small thing today — even the window light. No pressure on it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thgr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("thgr_mid_day_return", A,
            "Look up for a second. One thing visible right now. Note it — no need to make it more than it is.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("thgr_wishes_pending", A,
            "You've earned a small kindness to yourself. What would it actually feel like to receive it?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "thgr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("thgr_mid_streak", A,
            "Three days of these lists now. Notice if the mood feels a little steadier than it was.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thgr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("thgr_sant_jordi", A,
            "Sant Jordi's book and rose. Notice them for what they are. Let yourself hold onto that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_la_merce", A,
            "La Mercè fills the streets today. One moment from it, noticed and held, is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_sant_joan", A,
            "Sant Joan — sparks, sea, friends. Note one of them. It keeps better that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_diada", A,
            "Diada can be a long day. One small thing in it, held onto, is enough.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_nadal", A,
            "Nadal, and probably a lot of family moments to choose from. Pick one and hold it close.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_cap_d_any", A,
            "The new year opens. A year-of-wins list, if you want it — specific, and just for you to read back.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thgr_reis", A,
            "Reis, and gifts to note. A thank-you sent lands further than you'd think.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_carnaval", A,
            "Carnaval — the belly-laughs mostly write themselves in. Just notice them as they land.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_divendres_sant", A,
            "A quiet day, the city paused. The silence itself is worth noticing — it's the gift here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_pasqua", A,
            "Pasqua, maybe a moment on a trail somewhere. Notice it, hold onto it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_festa_del_treball", A,
            "It's Workers' Day. The day off itself is worth noting — that's a gift too, easy to overlook.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_festa_major_gracia", A,
            "Gràcia's paper-flower streets — the neighbors worked for weeks on those. Worth noticing that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_assumpcio", A,
            "August's slow, half-empty city. One warm thing from it, noticed and held onto.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_hispanitat", A,
            "A day off today. One small joy in it, noticed and held onto.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_castanyada", A,
            "Castanyada has a very particular autumn smell. Worth noticing it while the season lasts.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_constitucio", A,
            "A bridge weekend — two whole free days. Worth noticing them as the gift they are.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_immaculada", A,
            "A long weekend. An appreciation list, maybe — small, exact, worth keeping.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_sant_esteve", A,
            "The day after Nadal. A leftover moment from it, noticed and held onto.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_cap_d_any_eve", A,
            "The year's last day. A list of its warm moments — a kind way to close it out.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "thgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thgr_birthday", A,
            "It's your birthday. One good thing from each year you've had — specific, small. Hold onto them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "thgr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_personal_date", A,
            "Today is {label} — you marked it yourself. Note one thing from that original moment. Hold it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "thgr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("thgr_complete_1", A, "Noted. Something in the day warms a little because of it.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thgr_complete_2", A, "A small joy, logged quietly.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thgr_complete_3", A, "A small noticing. Real, however brief.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thgr_complete_first_today", A,
            "A first gratitude for today. Notice the mood lift at its own pace, not on command.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "thgr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("thgr_complete_second_today", A,
            "Two now. Small joys have a way of compounding when you actually track them.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "thgr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("thgr_complete_third_today", A,
            "Three. The eye starts to warm — that's the practice actually working.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "thgr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("thgr_complete_fourth_today", A,
            "Four. Is this a genuinely bright day, or are you forcing the noticing? Be honest with yourself.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "thgr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("thgr_complete_fifth_today", A,
            "Five. Maybe stop counting the joy now and just let yourself be in it.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "thgr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("thgr_complete_after_streak", A,
            "Three days of these lists now. The mood seems steadier than it was.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thgr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("thgr_apotheosis_1", A,
            "A cycle of noticing closes here. What did the eye actually learn?",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thgr_apotheosis_2", A,
            "It's complete. Whatever small list comes next, let it be specific, quiet.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thgr_apotheosis_3", A,
            "Closed. Turns out that glow was its own kind of writing practice all along.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thgr_apotheosis_first_ever", A,
            "Your first real block closed. What did you discover about what you'd been missing?",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("thgr_apotheosis_1", "thgr_apotheosis_2", "thgr_apotheosis_3"),
            theme = T),
        DialogueLine("thgr_apotheosis_at_level_2", A,
            "You catch small joys without even trying now. That's a kind of grace — let yourself receive it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "thgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thgr_apotheosis_at_level_3", A,
            "Others notice the warmth in you now. They pick it up without you having to teach it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "thgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thgr_apotheosis_at_level_4", A,
            "Years of this noticing now. Whatever glow that's given you is real, if quiet.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "thgr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("thgr_nudge_morning", A,
            "Three things, quickly. No need to dramatize any of them.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "thgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thgr_nudge_afternoon_zero", A,
            "Look up for a second. One thing right now, noticed and held.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "thgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thgr_nudge_evening", A,
            "A three-thing list before sleep, like credits rolling on the day.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "thgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thgr_nudge_attention_loss", A,
            "One small good thing today, whenever it appears — even the light. No pressure on finding it.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thgr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
