package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Therapist × Recovery — caring inquiry, rest as the work. */
internal object TherapistRecoveryLines {

    private const val A = "THERAPIST"
    private const val T = "RECOVERY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("thre_first_ever", A,
            "Welcome. Rest is also work. Whatever needs doing can wait — it isn't going anywhere.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("thre_morning", A,
            "Honest check — what is the body saying? Listen before you plan.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "thre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thre_morning_early", A,
            "Up before you needed to be. A slow start is fine — what is the body keeping track of, lately?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "thre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thre_afternoon", A,
            "Twenty minutes horizontal might be worth more right now than anything on the list.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "thre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thre_evening", A,
            "Winding down tonight, rather than starting something new — that's wisdom, not weakness.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "thre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thre_night_late", A,
            "It's late. Pushing through isn't the discipline here — sleeping is. What if you stopped now?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "thre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thre_post_apotheosis", A,
            "Something big just closed. The body's been holding a lot. Take a real day off — it will keep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("thre_monday", A,
            "New week. How rested are you actually starting it, compared to how rested you'd like to be?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "thre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thre_friday", A,
            "Friday. The week takes something out of you. What would it look like to do nothing well tonight?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "thre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thre_weekend", A,
            "No plans have a claim on you today. What would a do-nothing half-day actually feel like — phone off, nothing scheduled?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "thre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("thre_level_1_reached", A,
            "A week honouring rest. What does the body know now?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "thre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thre_level_2_reached", A,
            "Deloads are scheduled now, not just hoped for. The body's starting to trust you again — notice that.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "thre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thre_level_3_reached", A,
            "You read the body before it shouts. A rare grace — receive it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "thre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thre_level_4_reached", A,
            "Years of treating rest as discipline. The burnout that used to live here is gone. Keep it that way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "thre_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("thre_attention_loss_mild", A,
            "A few days running on caffeine. What's the body actually asking for? An early night tonight, maybe.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "thre_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("thre_attention_loss_hard", A,
            "Two weeks of pushing through. This reads like burnout, not weakness. A real day off — softly, no guilt.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thre_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("thre_mid_day_return", A,
            "A twenty-minute lie-down might be worth more right now. The afternoon will keep without you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("thre_wishes_pending", A,
            "You've earned a slow day. What would it look like to actually spend it on stillness?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "thre_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("thre_mid_streak", A,
            "Three days of real rest now. Something in the body is coming back — notice it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thre_streak", cooldownPicks = 5, theme = T),

        DialogueLine("thre_sant_jordi", A,
            "Sant Jordi will keep you moving all day. Pace yourself, and sit when you can.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_la_merce", A,
            "Mercè brings crowds, and crowds drain. Leave when the body says to, no guilt attached.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_sant_joan", A,
            "Sant Joan runs late into the night. Tomorrow's probably a wash — plan to just rest through it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_diada", A,
            "The Diada is a real day off. What would it mean to treat it as one — no make-up work, no list?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_nadal", A,
            "Nadal, and family gets loud. Twenty minutes slipped away might be exactly what the body's asking for.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_cap_d_any", A,
            "The fresh-start feeling is everywhere today. What would a year of rest as discipline look like, rather than collapse?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thre_reis", A,
            "Reis usually means a sugar crash by afternoon. Flat water, a slow walk — small mercies.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_carnaval", A,
            "Carnaval is loud, and loud is depleting. What would properly recovering on Tuesday look like?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_divendres_sant", A,
            "The whole city's gone quiet today. It's modelling something worth copying.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_pasqua", A,
            "Pasqua. A slow walk, a slow lunch — that's the whole job today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_festa_del_treball", A,
            "A day off from work today. The body's been working too — give it the day as well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_festa_major_gracia", A,
            "Gràcia's late nights stack up fast. An afternoon off would help — actually take it, this time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_assumpcio", A,
            "August, and the whole city allows for rest. Full rest, or the poor kind that isn't really rest — which is it going to be?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_hispanitat", A,
            "A day off today. What would it mean to do nothing, well, rather than fill it?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_castanyada", A,
            "Castanyada, and it's getting dark earlier. Sleeping earlier to match might be worth trying.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_constitucio", A,
            "The December bridge opens up two slow days. What would defending them from being filled look like?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_immaculada", A,
            "Five loose days ahead. Could two of them be real rest — bed early, no plans?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_sant_esteve", A,
            "The day after all the family. Holidays are tiring in their own way. A slow start, no obligations.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_cap_d_any_eve", A,
            "The year's last night tends to run long. A nap this afternoon isn't indulgent — it's just planning ahead.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "thre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thre_birthday", A,
            "It's your birthday. The kindest thing you could give yourself might just be a long sleep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "thre_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("thre_personal_date", A,
            "Today is {label}. The body will feel today one way or another — clear tomorrow morning if you can.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "thre_personal", cooldownPicks = 1, theme = T),

        DialogueLine("thre_complete_1", A, "Rest, actually taken. The body settles.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thre_complete_2", A, "A deload, logged. Let it be quiet.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thre_complete_3", A, "A slow day, kept as promised. Good.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thre_complete_first_today", A,
            "The first rest today, without guilt attached. That's the whole practice.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "thre_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("thre_complete_second_today", A,
            "Two. The body is being heard. Don't undo it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "thre_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("thre_complete_third_today", A,
            "Three. Today was for recovery — let it be that. No bonus work.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "thre_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("thre_complete_fourth_today", A,
            "Four. Very sick, or turning rest into a task? Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "thre_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("thre_complete_fifth_today", A,
            "Five. Rest is not a leaderboard — stop counting. Sit.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "thre_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("thre_complete_after_streak", A,
            "Three days honouring rest. The system catches up.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thre_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("thre_apotheosis_1", A,
            "A cycle closes. Not graduation — schedule the next deload now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thre_apotheosis_2", A,
            "Completed. The body trusts you again. Don't betray it next month.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thre_apotheosis_3", A,
            "Closed. Rest is the work. No graduation. Maintain.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thre_apotheosis_first_ever", A,
            "First block. The burnout loop is broken — what did you learn about yourself?",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("thre_apotheosis_1", "thre_apotheosis_2", "thre_apotheosis_3"),
            theme = T),
        DialogueLine("thre_apotheosis_at_level_2", A,
            "Recovery is policy. Defend it from the urgent that is not important.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "thre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thre_apotheosis_at_level_3", A,
            "People see you rest and learn. Be the example — no bravado.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "thre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thre_apotheosis_at_level_4", A,
            "Years of rest as discipline. The body is the proof. Hold it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "thre_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("thre_nudge_morning", A,
            "Honest check. The body says what?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "thre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thre_nudge_afternoon_zero", A,
            "Twenty-minute lie-down. Now. That is the deal.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "thre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thre_nudge_evening", A,
            "Wind down. No new project tonight.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "thre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thre_nudge_attention_loss", A,
            "A real day off today. Softly. The body has waited.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thre_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
