package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Therapist × Boundaries — caring inquiry, the kept margin. */
internal object TherapistBoundariesLines {

    private const val A = "THERAPIST"
    private const val T = "BOUNDARIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("thbo_first_ever", A,
            "Welcome. Your limits are yours to name. What would feel honest today?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("thbo_morning", A,
            "Is there one “no” today deserves? Naming it before the email opens tends to make it easier to keep.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "thbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thbo_morning_early", A,
            "The email can't reach you until you let it in. This early hour is yours — what if it stayed that way?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "thbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thbo_afternoon", A,
            "Somewhere in this afternoon lives a “just one more”. That's usually the one worth refusing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "thbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thbo_evening", A,
            "The work part of the day is over. What would it take to turn the notifications off and believe that?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "thbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thbo_night_late", A,
            "Whoever's asking at this hour can hear from you tomorrow. What would it mean to let that be true?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "thbo_greet", cooldownPicks = 3, theme = T),
        DialogueLine("thbo_post_apotheosis", A,
            "The margin held. The next “yes” someone asks of you will be the real test — I wonder if you'll pause first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("thbo_monday", A,
            "Looking at the week ahead — what's on it that got added without your consent? It can still come off.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "thbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thbo_friday", A,
            "The weekend is almost yours. The late work-creep will test that tonight — how do you want to answer it?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "thbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("thbo_weekend", A,
            "What would it be like to put the phone on silent for the family hours today — and actually mean it?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "thbo_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("thbo_level_1_reached", A,
            "One real “no”, kept all week. And the world didn't end. That's worth sitting with, isn't it?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "thbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thbo_level_2_reached", A,
            "Your limits hold without rehearsal now. People are learning them — did you notice when that started?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "thbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thbo_level_3_reached", A,
            "People have stopped asking the wrong way. The boundary did the teaching — you just kept it steady.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "thbo_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("thbo_level_4_reached", A,
            "Years of kept limits, and the calendar is finally yours. Notice how much wider the days feel.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "thbo_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("thbo_attention_loss_mild", A,
            "A few days of yes-to-everything. No judgment — I'm just curious what one soft “no” might feel like today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_3),
            cooldownGroup = "thbo_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("thbo_attention_loss_hard", A,
            "Two weeks of the line giving way. It happens. What's one block you could quietly take back today?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thbo_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("thbo_mid_day_return", A,
            "The calendar looks full of other people's work. Would one blocked hour, just for you, fit somewhere?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("thbo_wishes_pending", A,
            "You've earned a real day off — not another favour for someone else.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "thbo_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("thbo_mid_streak", A,
            "Three days of held limits. Things sound quieter, don't they? The line is settling in.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thbo_streak", cooldownPicks = 5, theme = T),

        DialogueLine("thbo_sant_jordi", A,
            "Sant Jordi — roses, books, crowds. Being out of office is the whole job today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_la_merce", A,
            "It's La Mercè, and you are off. How would it feel to say that out loud — and leave the phone behind?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_sant_joan", A,
            "Sant Joan — the fires go late tonight. Tomorrow morning is yours too; the early call can be refused.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_diada", A,
            "The Diada is a held day. If asks arrive, a polite no keeps it whole — how does that sit with you?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_nadal", A,
            "Nadal, and the family hours. What if the phone spent them in another room? That's the whole limit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_cap_d_any", A,
            "A new year. Are any commitments on your list that were never really yours? Today's a good day to name two.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thbo_reis", A,
            "Reis is a family day. If something else asks for it, one clear decline is enough — then let it go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_carnaval", A,
            "Carnaval asks for everything. Skipping one party might be what keeps the next two good — quality over count.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_divendres_sant", A,
            "The city has gone quiet today — it's modelling the limit for you. Would copying it feel possible? No work.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_pasqua", A,
            "Pasqua Monday. There may be a pull to make up Friday's missed work — I wonder what refusing it would feel like.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_festa_del_treball", A,
            "A day named for labour, kept by resting. The line between work and rest is the oldest boundary there is.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_festa_major_gracia", A,
            "Gràcia runs all week. What if you picked two nights and let the rest go? You can't give all of yourself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_assumpcio", A,
            "The city itself closes in August. What would a real out-of-office look like for you — the kind you believe?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_hispanitat", A,
            "A bridge day, and it's yours. If someone reaches for it, a polite no is a complete sentence.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_castanyada", A,
            "Castanyada — chestnuts out, and year-end pressure warming up. The scope-creep starts small; so can the no.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_constitucio", A,
            "Two bridge days ahead with no work in them. Does saying that out loud make it feel more true?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_immaculada", A,
            "The pont brings the “quick favour” emails. I wonder if setting the limit early would spare the whole week.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_sant_esteve", A,
            "Sant Esteve can be a lot of family. Slipping away for one hour counts as a “no” — a kind one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_cap_d_any_eve", A,
            "The year's last evening. If three commitments could stay behind in it, which ones would you name?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "thbo_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("thbo_birthday", A,
            "It's your birthday. Would refusing one obligation tonight feel like a gift you could give yourself?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "thbo_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_personal_date", A,
            "Today is {label}. The noise can be refused for an hour — this one is yours, fully.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "thbo_personal", cooldownPicks = 1, theme = T),

        DialogueLine("thbo_complete_1", A, "The “no” is said. Can you feel the line steadying under you?",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thbo_complete_2", A, "The limit held. Hear how much quieter it is on this side of it?",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thbo_complete_3", A, "An hour, quietly reclaimed. What will you let it hold?",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("thbo_complete_first_today", A,
            "The first refusal is down. The sky didn't fall — worth remembering next time it threatens to.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "thbo_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("thbo_complete_second_today", A,
            "Two limits held today. A pattern is forming, and other people are quietly learning it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "thbo_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("thbo_complete_third_today", A,
            "Three. Notice how much quieter the day is — you defended that quiet; it didn't just happen.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "thbo_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("thbo_complete_fourth_today", A,
            "Four today. A heavy day for limits — or is something in you spoiling for a fight? Just wondering.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "thbo_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("thbo_complete_fifth_today", A,
            "Five. I wonder if the counting itself has become the fight. Boundaries aren't a war to win.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "thbo_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("thbo_complete_after_streak", A,
            "Three days of clear limits, and an honest calendar. The line is holding — you're the one holding it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "thbo_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("thbo_apotheosis_1", A,
            "Something real just closed. The next “yes” someone asks of you is the test — the pause before it is yours.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thbo_apotheosis_2", A,
            "It's complete. Limits don't graduate, though — the next one will still ask to be kept.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thbo_apotheosis_3", A,
            "Closed. And the boundary was never the finish line — it's the practice itself, day after ordinary day.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("thbo_apotheosis_first_ever", A,
            "Your first real close. I'm curious — what did all that saying no teach you about yourself?",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("thbo_apotheosis_1", "thbo_apotheosis_2", "thbo_apotheosis_3"),
            theme = T),
        DialogueLine("thbo_apotheosis_at_level_2", A,
            "The calendar is yours now. A new request is probably already arriving — what do you want to do with it?",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "thbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thbo_apotheosis_at_level_3", A,
            "People honour your limits without being told now. Staying steady is what taught them.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "thbo_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("thbo_apotheosis_at_level_4", A,
            "Years of kept limits. Look at the calendar — it tells your story now, not everyone else's.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "thbo_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("thbo_nudge_morning", A,
            "Before the email opens — is there one “no” worth naming for today?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "thbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thbo_nudge_afternoon_zero", A,
            "Nothing reclaimed yet today — that's just information. Would blocking back a single hour feel possible?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "thbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thbo_nudge_evening", A,
            "The work is done for today. The notifications could be, too.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "thbo_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("thbo_nudge_attention_loss", A,
            "No rush from me. One block taken quietly back today would be plenty — maybe the hard one, maybe not.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLostGentle_10),
            cooldownGroup = "thbo_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
