package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Gratitude — sardonic, meta, "the credits exist". */
internal object TricksterGratitudeLines {

    private const val A = "TRICKSTER"
    private const val T = "GRATITUDE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trgr_first_ever", A,
            "Oh good, the gratitude arc. Spoiler — the credits exist whether you read them or not.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trgr_morning", A,
            "Three things to be grateful for, right now. Don't theatre it — just the honest three.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_morning_early", A,
            "Up early, and it's quiet — worth noting. The credits roll on small things like this one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_afternoon", A,
            "Something's gone right today, somewhere in the mess. Note it down. Iconic restraint, not settling for zero.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_evening", A,
            "Before sleep tonight, the three-thing list. The credits roll quietly, whether you watch them or not.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_night_late", A,
            "It's late — just one good thing from today, that's all I'm asking. Sleep on it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_post_apotheosis", A,
            "Plot twist: you're actually noticing things now. Keep the daily list going — don't let the bit lapse.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trgr_monday", A,
            "New week — three things to look forward to, and specific ones. No gold-plating the mundane.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trgr_friday", A,
            "The week's wrapping up — name three iconic moments from it. Specific ones, no vague summaries.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trgr_weekend", A,
            "Weekend pace — slow noticing, the small things nobody else is clocking. Very cinematic of you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trgr_level_1_reached", A,
            "First tier — a month of lists kept. The mood's up, and the lore itself has filed a thank-you note.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trgr_level_2_reached", A,
            "Second tier. You're catching yourself smiling at small things now. Deeply suspicious of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trgr_level_3_reached", A,
            "Third tier. People are noticing the warmth now. Iconic. Don't admit to the training.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trgr_level_4_reached", A,
            "Final tier. Years of noticing later, and the glow is genuinely real now. Just keep tending it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trgr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trgr_attention_loss_mild", A,
            "A few flat days in a row. One thing today — note it down, no need to theatre it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trgr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trgr_attention_loss_hard", A,
            "Two weeks of heaviness now. One small thing today — even good coffee counts. Curtain on the flat streak.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trgr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trgr_after_lapse", A,
            "Yesterday nothing got noticed at all. Today, one thing — don't argue, just note it down.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trgr_mid_day_return", A,
            "We're at halftime — look up from whatever you're doing. One thing visible right now. Note it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trgr_wishes_pending", A,
            "Earned coupons from the noticing gods. Spend one — treat.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trgr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trgr_mid_streak", A,
            "Three days of lists kept in a row. The mood's steadier — a suspicious kind of calm, but I'll allow it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trgr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trgr_sant_jordi", A,
            "It's Sant Jordi — if a book or rose came your way, actually notice it. Hold onto that one. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_la_merce", A,
            "Mercè's got moments everywhere today — pick one, hold onto it. Iconic, and it costs nothing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_sant_joan", A,
            "Bonfire night — sparks, sea, friends, take your pick. Note one of them down. Very cinematic material.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_diada", A,
            "Diada's a long day off — one small thing worth noticing in it. Iconic, don't let it pass unremarked.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_nadal", A,
            "It's Nadal — one family moment worth noticing today. Hold onto it. Iconic, and worth remembering later.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_cap_d_any", A,
            "New year, blank scoreboard — write the year-of-wins list. Specific ones, no modesty allowed here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trgr_reis", A,
            "It's Reis — if a gift landed, send an actual thank-you. Iconic restraint over the group-chat sticker reply.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_carnaval", A,
            "Carnaval's got belly-laughs on offer — notice one of them properly. Iconic day for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_divendres_sant", A,
            "The city's gone quiet today. The silence itself is worth noting. Iconic, in its own understated way.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_pasqua", A,
            "Pasqua tradition brings a trail moment worth noting — pick one. Iconic, save it for later.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_festa_del_treball", A,
            "It's Workers' Day — note the day off itself, that's the gratitude prompt. Cinematic simplicity.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_festa_major_gracia", A,
            "Gràcia's decorations are up — the neighbours actually built THAT with their bare hands. Iconic, notice it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_assumpcio", A,
            "August slows the whole city down — note one warm thing in the middle of it. Iconic, unhurried.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_hispanitat", A,
            "Another day off — one small joy worth noticing in it. Iconic, don't let it slide by unnamed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_castanyada", A,
            "Castanyada smells like the whole season — chestnut smoke on the air. Note it down. Iconic little detail.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_constitucio", A,
            "Bridge weekend hands you two whole free days — note them properly. Iconic, don't take the gift for granted.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_immaculada", A,
            "The pont hands you extra days — a proper appreciate-list fits right in. Iconic use of found time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_sant_esteve", A,
            "The day after the feast has its own quiet moment worth noticing. Iconic sequel, honestly underrated.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_cap_d_any_eve", A,
            "Last day of the year — write the year-of-cute-moments list. Iconic close to the whole run.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trgr_birthday", A,
            "Birthday. One good thing per year you've had. Specific. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trgr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_personal_date", A,
            "You marked this date: {label}. Note one thing from the original. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trgr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trgr_complete_1", A, "Noted. The credits roll.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trgr_complete_2", A, "Joy logged. Iconic restraint.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trgr_complete_3", A, "Glow-noticing WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trgr_complete_first_today", A,
            "First gratitude. Mood lifted. Suspicious.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trgr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trgr_complete_second_today", A,
            "Two. Compound joy. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trgr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trgr_complete_third_today", A,
            "Three. Iconic glow.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trgr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trgr_complete_fourth_today", A,
            "Four. Big-glow day or forcing it? Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trgr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trgr_complete_fifth_today", A,
            "Five. Stop counting joy — be in it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trgr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_complete_after_streak", A,
            "Three days of lists. Mood steadier. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trgr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trgr_apotheosis_1", A,
            "Block done. Noticing glowing. Don't lapse the bit.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trgr_apotheosis_2", A,
            "Cycle wrapped. Next gratitude goal — small one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trgr_apotheosis_3", A,
            "Closed. Glow-noticing WIN. Continue.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trgr_apotheosis_first_ever", A,
            "First block. Daily gratitude is canon. Inconvenient. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trgr_apotheosis_1", "trgr_apotheosis_2", "trgr_apotheosis_3"),
            theme = T),
        DialogueLine("trgr_apotheosis_at_level_2", A,
            "Promoted. You catch small joys without thinking. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_apotheosis_at_level_3", A,
            "Senior tier. People notice the warmth. Iconic. Don't gloat.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_apotheosis_at_level_4", A,
            "Top tier. Years of noticing. The glow is real. Maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trgr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trgr_nudge_morning", A,
            "Three things. Quick. Don't theatre.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trgr_nudge_afternoon_zero", A,
            "Look up. One thing right now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trgr_nudge_evening", A,
            "Three-thing list before sleep. The credits roll.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trgr_nudge_lapse", A,
            "Yesterday: zero notice. Today: one thing. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trgr_nudge_attention_loss", A,
            "Bit got dark. One small good thing today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trgr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
