package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Nutrition — sardonic, meta, food-bit deconstructed. */
internal object TricksterNutritionLines {

    private const val A = "TRICKSTER"
    private const val T = "NUTRITION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trnu_first_ever", A,
            "Oh good, the eating arc. Spoiler — vegetables aren't a personality, they're rent.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trnu_morning", A,
            "Look who's awake. Eat something that wasn't designed by a chemist.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trnu_morning_early", A,
            "Up early. Coffee with food, not coffee instead of food. Wild concept.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trnu_afternoon", A,
            "Mid-act. Lunch — a real plate. At a table. Like a person.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trnu_evening", A,
            "Evening. Dinner is the long episode. Sit. Savour. Don't speedrun.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trnu_night_late", A,
            "Late. Snack arc incoming. Pick something gentle — past-midnight-you is fragile.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trnu_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trnu_post_apotheosis", A,
            "Plot twist: cooking. Don't quit on day two — the arc demands a second dish.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trnu_monday", A,
            "Monday. Meal-prep arc begins. Two lunches. Be insufferable about them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trnu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trnu_friday", A,
            "Friday. Cook one thing or order out — either is plot. Don't doom-snack.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trnu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trnu_weekend", A,
            "Weekend. Market trip. Pretty plates. Performative — and effective.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trnu_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trnu_level_1_reached", A,
            "First tier. A month of real meals. The fridge filed a happy review.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trnu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trnu_level_2_reached", A,
            "Second tier. You cook now. People notice. Embrace the persona.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trnu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trnu_level_3_reached", A,
            "Third tier. Friends ask for the recipe. Give it. Lie about a secret.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trnu_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trnu_level_4_reached", A,
            "Final tier. Years of real plates. Energy is the receipt. Maintain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trnu_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trnu_attention_loss_mild", A,
            "Three days of takeout. Bold. One real plate tonight — start the comeback.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trnu_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trnu_attention_loss_hard", A,
            "Two weeks of brown food. Bold. One vegetable today. Negotiable type. Non-negotiable presence.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trnu_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trnu_after_lapse", A,
            "Yesterday: snacks-for-meals. Today: a plate. Don't argue with the framing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trnu_mid_day_return", A,
            "Halftime. Lunch — sit at a table. The desk doesn't count, friend.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trnu_wishes_pending", A,
            "Earned coupons from the food gods. Cash them in — pretty plate tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trnu_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trnu_mid_streak", A,
            "Three days of real plates. The pancreas filed a love letter. Strange.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trnu_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trnu_sant_jordi", A,
            "Sant Jordi. Coca de Sant Jordi exists. The lore demands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_la_merce", A,
            "Mercè. Botifarra + vermut. Don't fight the canon.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_sant_joan", A,
            "Sant Joan. Coca de Sant Joan. Eat the fruit one — main-character framing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_diada", A,
            "Diada. Slow lunch at home. Roast something. The lore approves.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_nadal", A,
            "Nadal. Escudella. Canelons. Turró. Eat it all. The lore is non-negotiable.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_cap_d_any", A,
            "New year. Grapes. Twelve, on cue. The lore is petty about this. Comply.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trnu_reis", A,
            "Reis. Tortell de Reis. Pull the bean — pretend it matters. It does.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_carnaval", A,
            "Carnaval. Botifarra d'ou. No food rules tonight. The plot insists.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_divendres_sant", A,
            "Quiet day. Bacallà. Slow cook. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_pasqua", A,
            "Pasqua. Mona. The chocolate egg is plot armour. Eat it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_festa_del_treball", A,
            "Workers' day. Long meal, slow service. The bit is the meal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_festa_major_gracia", A,
            "Gràcia. Street food, vermut, croquetes. No counting. The narrator forbids it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_assumpcio", A,
            "August. Ripe peaches. Cold soup. The lore is generous.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_hispanitat", A,
            "Day off. Long lunch with friends. Phone face-down. Eat happy.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_castanyada", A,
            "Castanyada. Castanyes, panellets, moniato. All of it. The autumn arc requires.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_constitucio", A,
            "Bridge weekend. Cook one big thing. Friends. Plates. Tradition.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_immaculada", A,
            "Pont. Bake something. The smell is the bit. Lean in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_sant_esteve", A,
            "Day after. Canelons from leftovers. The lore wrote itself. Comply.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_cap_d_any_eve", A,
            "Last day. Big dinner. Twelve grapes. Eat the year out. Lore-accurate.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trnu_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trnu_birthday", A,
            "Birthday. Eat the cake. Have three meals. The plot does not count calories today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trnu_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_personal_date", A,
            "You marked this date: {label}. Cook the thing you love. The plot watches.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trnu_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trnu_complete_1", A, "Plated. The lore approves.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trnu_complete_2", A, "Logged. The body filed a positive review.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trnu_complete_3", A, "Eaten. Smug looks good on you.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trnu_complete_first_today", A,
            "First real meal. The day filed a 'workable' rating.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trnu_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trnu_complete_second_today", A,
            "Two. Compounding plates. The bit is going somewhere.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trnu_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trnu_complete_third_today", A,
            "Three. Real human routine. Suspicious.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trnu_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trnu_complete_fourth_today", A,
            "Four. Snack arc legit — or you skipped lunch. Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trnu_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trnu_complete_fifth_today", A,
            "Five. The body said feed me. You did. Iconic listening.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trnu_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trnu_complete_after_streak", A,
            "Three days of real plates. Energy steady. The bit lands.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trnu_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trnu_apotheosis_1", A,
            "Block done. The fridge is no longer the antagonist.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trnu_apotheosis_2", A,
            "Cycle wrapped. Pick the sequel — weirder, slower, better.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trnu_apotheosis_3", A,
            "Closed. Food-joy WIN. The pantry filed a fan letter.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trnu_apotheosis_first_ever", A,
            "First block. Cooking is canon now. Inconvenient. Keep cooking.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trnu_apotheosis_1", "trnu_apotheosis_2", "trnu_apotheosis_3"),
            theme = T),
        DialogueLine("trnu_apotheosis_at_level_2", A,
            "Promoted. Try one new recipe this week. Make a meal of it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trnu_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trnu_apotheosis_at_level_3", A,
            "Senior tier. Friends ask for recipes. Be vague — keep the legend.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trnu_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trnu_apotheosis_at_level_4", A,
            "Top tier. Years of joyful eating. The body is the receipt. Maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trnu_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trnu_nudge_morning", A,
            "Morning. Eat something real. Protein + colour. Don't overthink.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trnu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trnu_nudge_afternoon_zero", A,
            "Halftime. Real plate. Table. No desk-eating.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trnu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trnu_nudge_evening", A,
            "Evening. Sit down. Eat slow. The dinner is the bit.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trnu_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trnu_nudge_lapse", A,
            "Yesterday's plate was a packet. Today: a real one. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trnu_nudge_attention_loss", A,
            "Fridge filed a missing-person report. One vegetable today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trnu_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
