package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Exercise — sardonic, meta, gym-bro deconstructed. */
internal object TricksterExerciseLines {

    private const val A = "TRICKSTER"
    private const val T = "EXERCISE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trex_first_ever", A,
            "Oh good, the workout arc begins. Spoiler — there's no montage music.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trex_morning", A,
            "Look who's awake AND moving. Suspicious. Keep going.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trex_morning_early", A,
            "Pre-sunrise cardio. Insufferable. Continue.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trex_afternoon", A,
            "Mid-act. The body has notes. Address them with a ten-minute walk.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trex_evening", A,
            "Twilight movement era. Heroic. Or fake. Either way, move.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trex_night_late", A,
            "Goblin hours. No PRs at this hour — stretch and skulk.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trex_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trex_post_apotheosis", A,
            "Plot twist: muscles. Keep the show going — small move today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trex_monday", A,
            "Monday. The training arc starts at chapter one again. Annoying. Lace up.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trex_friday", A,
            "Friday. Season finale. End it with movement — or season-two-you holds a grudge.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trex_weekend", A,
            "Weekend. The protagonist either climbs a hill or watches one. Pick.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trex_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trex_level_1_reached", A,
            "First tier. A whole week of moving. Sourceable on Wikipedia now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trex_level_2_reached", A,
            "Second tier. The body acknowledges the bit. Keep it going.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trex_level_3_reached", A,
            "Third tier. People ask for your routine. Make one up. Be vague.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trex_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trex_level_4_reached", A,
            "Final tier. The body is a long-running joke that landed. Maintain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trex_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trex_attention_loss_mild", A,
            "A few rest days. Calling it 'periodization' was generous. Walk today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trex_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trex_attention_loss_hard", A,
            "Two-week sabbatical from your own body. Bold. Five-minute walk — start the comeback.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trex_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trex_after_lapse", A,
            "Yesterday: zero squats, zero steps, much vibes. Today — one walk. Curtain up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trex_mid_day_return", A,
            "Halfway through the episode. Zero movement. Plot demands a walk.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trex_wishes_pending", A,
            "Earned coupons from the exercise gods. Use them or it's just data.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trex_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trex_mid_streak", A,
            "Three-day move streak. Suspicious. Keep being suspicious.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trex_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trex_sant_jordi", A,
            "Sant Jordi. Walking the streets counts as cardio. The dragon agrees.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_la_merce", A,
            "Mercè. Dance counts. Standing in line for a vermut does not.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_sant_joan", A,
            "Sant Joan. Running from sparks counts. Cinematic. Move.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_diada", A,
            "Diada. Walk the city. Be insufferable about your steps after. Tradition.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_nadal", A,
            "Nadal. Post-lunch walk. The grandmothers invented it. Don't break the lore.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_cap_d_any", A,
            "New year. Same body. Take it for a walk — without announcing it. Quietly heroic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trex_reis", A,
            "Reis. Sugar tsunami coming. Walk it off with the kids — they're faster anyway.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_carnaval", A,
            "Carnaval. Costume + parade = full-body workout in disguise. Plot loves it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_divendres_sant", A,
            "Quiet day. Long slow walk by the water — main-character framing. Use it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_pasqua", A,
            "Pasqua. Hike with mona in the bag. Lore-accurate. Move.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_festa_del_treball", A,
            "Workers' day. The body is also a worker. Negotiate — a walk for its rights.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_festa_major_gracia", A,
            "Gràcia. Walk every decorated street. Free museum, free cardio.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_assumpcio", A,
            "August. The city left. Use the empty streets — long lonely walks. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_hispanitat", A,
            "Day off. Hill walk. One hour out. The plot loves a vista.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_castanyada", A,
            "Castanyada. Crunchy-leaf walk. The autumn aesthetic demands it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_constitucio", A,
            "Bridge weekend. Two days, one long walk. Don't make it three excuses.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_immaculada", A,
            "Pont. Five days. Pick one hike. The other four can be naps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_sant_esteve", A,
            "Day after. Soft walk. Don't try a 10K. The plot wouldn't believe it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_cap_d_any_eve", A,
            "Last day. Walk the year out. Closing montage. Make it count.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trex_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trex_birthday", A,
            "Birthday. Walk to your favourite place — the universe owes you the route.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trex_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trex_personal_date", A,
            "You marked this date: {label}. Mark it with movement. Even ten minutes. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trex_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trex_complete_1", A, "Moved. The lore advances.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trex_complete_2", A, "Logged. Smug looks good on you.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trex_complete_3", A, "Steps acquired. Plot satisfied.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trex_complete_first_today", A,
            "First move of the day. The exposition is over. Onward.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trex_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trex_complete_second_today", A,
            "Two. Suspicious efficiency. Drink water before the third.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trex_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trex_complete_third_today", A,
            "Three. The body filed a positive review. Rare.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trex_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trex_complete_fourth_today", A,
            "Four. Bargaining with the body or showing off? Hydrate either way.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trex_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trex_complete_fifth_today", A,
            "Five. The bit has gone on too long. Sit. Eat.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trex_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trex_complete_after_streak", A,
            "Day three of moving. The arc is consistent. Strange.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trex_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trex_apotheosis_1", A,
            "Block done. The training arc closes. Briefly. There's a next one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trex_apotheosis_2", A,
            "Cycle wrapped. Pick the sequel — smaller, weirder, better.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trex_apotheosis_3", A,
            "Closed. The body is the bit's loyalest fan. Reward it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trex_apotheosis_first_ever", A,
            "First block. The pilot is a hit. Annoying — now you have to keep doing it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trex_apotheosis_1", "trex_apotheosis_2", "trex_apotheosis_3"),
            theme = T),
        DialogueLine("trex_apotheosis_at_level_2", A,
            "Promoted. The plot does not slow down. Keep walking.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trex_apotheosis_at_level_3", A,
            "Senior tier. People imitate the bit now. Be the original. Keep moving.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trex_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trex_apotheosis_at_level_4", A,
            "Top tier. The body is a long-running gag that aged well. Maintain it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trex_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trex_nudge_morning", A,
            "Morning. The body filed a request. Walk five minutes.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trex_nudge_afternoon_zero", A,
            "Halftime. Movement count: zero. Plot demands a walk.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trex_nudge_evening", A,
            "Evening. One walk. Even sad-girl pacing. Move.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trex_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trex_nudge_lapse", A,
            "Yesterday skipped. Today — one walk. Curtain up. Move.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trex_nudge_attention_loss", A,
            "The body filed a grievance. Move five minutes. Not optional.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trex_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
