package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Recovery — sardonic, meta, rest-as-arc. */
internal object TricksterRecoveryLines {

    private const val A = "TRICKSTER"
    private const val T = "RECOVERY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trre_first_ever", A,
            "Oh good, the rest arc. Spoiler — the protagonist also naps. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trre_morning", A,
            "Honest check — body says what? Listen before you plan.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_morning_early", A,
            "Up early. Slow start. Not optional. The body keeps the ledger.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_afternoon", A,
            "Mid-act. Twenty-minute lie-down. Or a walk in shade. Pick one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_evening", A,
            "Evening. Wind down. No new project tonight — that's wisdom, not laziness.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_night_late", A,
            "Late. Push-through is not the discipline — sleeping is. Down tools.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_post_apotheosis", A,
            "Plot twist: rested. Take a real day off — not a soft one. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trre_monday", A,
            "Monday. The week starts at the recovery from the weekend. Note the deficit.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trre_friday", A,
            "Friday. The week leaves a tax. Plan tonight to do nothing well.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trre_weekend", A,
            "Weekend. Do-nothing half-day. Phone off. No plans. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trre_level_1_reached", A,
            "First tier. A week honouring rest. Sleep already deeper. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trre_level_2_reached", A,
            "Second tier. Deloads scheduled. Body trusts you again. Suspicious.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trre_level_3_reached", A,
            "Third tier. You read the body before it shouts. Iconic skill.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trre_level_4_reached", A,
            "Final tier. Years of rest as discipline. Iconic. Maintain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trre_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trre_attention_loss_mild", A,
            "Three days on caffeine. The body files the ledger. Pay it back tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trre_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trre_attention_loss_hard", A,
            "Two weeks pushing. This is burnout — not weakness. A real day off. Today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trre_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trre_after_lapse", A,
            "Yesterday: skipped rest. Today: bed by ten. Don't argue.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trre_mid_day_return", A,
            "Halftime. Twenty-minute lie-down. Now. The narrator times.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trre_wishes_pending", A,
            "Earned coupons from the body gods. Spend one on a slow day. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trre_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trre_mid_streak", A,
            "Three days of real rest. Body returning. The bit lands.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trre_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trre_sant_jordi", A,
            "Sant Jordi. Pace it. Sit when you can. Iconic restraint.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_la_merce", A,
            "Mercè. Crowds drain. Leave when the body says. No guilt.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_sant_joan", A,
            "Sant Joan. Late night = tomorrow lost. Tomorrow: rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_diada", A,
            "Diada. Day off. No make-up work. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_nadal", A,
            "Nadal. Family loud. Slip away twenty minutes. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_cap_d_any", A,
            "New year. Year of rest as discipline — not as collapse. Plan deloads now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trre_reis", A,
            "Reis. Sugar crash by afternoon. Flat water, slow walk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_carnaval", A,
            "Carnaval. Loud is depleting. Recover Tuesday properly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_divendres_sant", A,
            "Quiet day. The city models rest. Copy it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_pasqua", A,
            "Pasqua Monday. Slow walk, slow lunch. That is the work today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_festa_del_treball", A,
            "Workers' day. The body is also a worker. Give it the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_festa_major_gracia", A,
            "Gràcia. Late nights stack. Plan an afternoon off — actually do it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_assumpcio", A,
            "August. Rest fully or rest poorly. Pick. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_hispanitat", A,
            "Day off. Do-nothing maintenance. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_castanyada", A,
            "Castanyada. Dark earlier = sleep earlier. Match the season.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_constitucio", A,
            "Bridge weekend. Two slow days. Defend them from being filled.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_immaculada", A,
            "Pont. Five days. Two of them, real rest. Bed early. No plans.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_sant_esteve", A,
            "Day after. Holidays are tiring. Slow start. No obligations.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_cap_d_any_eve", A,
            "Last day. Long night ahead. Nap this afternoon. Not optional.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trre_birthday", A,
            "Birthday. The kindest thing — a long sleep. Plan it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trre_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_personal_date", A,
            "You marked this date: {label}. Body will feel it. Clear tomorrow morning.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trre_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trre_complete_1", A, "Rested. Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trre_complete_2", A, "Deload logged. The week is wiser.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trre_complete_3", A, "Slow-day WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trre_complete_first_today", A,
            "First rest — without guilt. That's the practice.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trre_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trre_complete_second_today", A,
            "Two. Body being heard. Don't undo it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trre_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trre_complete_third_today", A,
            "Three. Today was for recovery. Let it be that. No bonus work.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trre_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trre_complete_fourth_today", A,
            "Four. Very sick or turning rest into a task? Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trre_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trre_complete_fifth_today", A,
            "Five. Rest is not a leaderboard. Stop counting. Sit.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trre_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trre_complete_after_streak", A,
            "Three days honouring rest. The system catches up. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trre_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trre_apotheosis_1", A,
            "Block done. Not graduation — schedule the next deload now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trre_apotheosis_2", A,
            "Cycle wrapped. Body trusts you again. Don't betray it next month.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trre_apotheosis_3", A,
            "Closed. Rest is the work. No graduation. Maintain.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trre_apotheosis_first_ever", A,
            "First block. Rest is canon. Inconvenient. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trre_apotheosis_1", "trre_apotheosis_2", "trre_apotheosis_3"),
            theme = T),
        DialogueLine("trre_apotheosis_at_level_2", A,
            "Promoted. Recovery is policy. Defend it from the urgent that is not important.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trre_apotheosis_at_level_3", A,
            "Senior tier. People see you rest and learn. Be the example. No bravado.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trre_apotheosis_at_level_4", A,
            "Top tier. Years of rest as discipline. The body is the proof. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trre_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trre_nudge_morning", A,
            "Honest check. Body says what?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trre_nudge_afternoon_zero", A,
            "Twenty-minute lie-down. Now. That's the deal.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trre_nudge_evening", A,
            "Wind down. No new project tonight.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trre_nudge_lapse", A,
            "Yesterday: skipped. Tonight: bed by ten. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trre_nudge_attention_loss", A,
            "Burnout signal loud. A real day off — today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trre_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
