package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Hobbies — sardonic, meta, the B-plot is the real plot. */
internal object TricksterHobbiesLines {

    private const val A = "TRICKSTER"
    private const val T = "HOBBIES"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trho_first_ever", A,
            "Oh good, the hobby arc. Spoiler — the B-plot is the real plot.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trho_morning", A,
            "Sneak in hobby time now, before the day finds and eats it. Iconic little heist.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trho_morning_early", A,
            "Up early for a quiet hobby session? Suspiciously productive of you. I'm not complaining.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trho_afternoon", A,
            "Twenty minutes on the hobby this afternoon — no multitasking, no side quests. Just the bit, pure.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trho_evening", A,
            "Tonight the hobby beats TV — even thirty minutes of it. The plot takes a bow every time.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trho_night_late", A,
            "It's late — soft hobby only. Absolutely no starting a new project at this hour, friend. I know you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trho_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trho_post_apotheosis", A,
            "Plot twist: actual skill. Keep the daily slot sacred — nobody wants a sequel that's just slop.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trho_monday", A,
            "New week — schedule the hobby slots now and defend them like territory. Iconic if you hold the line.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trho_friday", A,
            "The week's done — a long hobby slot tonight is the correct reward. Iconic choice, obviously.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trho_weekend", A,
            "Weekend's here — the hours-long hobby session finally fits. Very cinematic of you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trho_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trho_level_1_reached", A,
            "First tier — a monthly hobby rhythm's taken hold, and the skill's quietly growing. Suspicious of you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trho_level_2_reached", A,
            "Second tier. You actually finish projects now — a plot twist nobody saw coming. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trho_level_3_reached", A,
            "Third tier. Friends are asking about the hobby now. Be vague, keep the bit — mystery is half the craft.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trho_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trho_level_4_reached", A,
            "Final tier. Years of joyful play, and the identity itself is the punchline now. Keep playing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trho_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trho_attention_loss_mild", A,
            "A few skipped hobby days in a row. A fifteen-minute session right now — no theatrics, just hands on it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trho_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trho_attention_loss_hard", A,
            "Two weeks of ghosting your own hobby — bold arc choice. One small session today, and curtain on it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trho_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trho_after_lapse", A,
            "Yesterday had zero play in it. Today, fifteen minutes on the hobby — don't argue with the narrator.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trho_mid_day_return", A,
            "We're at halftime. A twenty-minute hobby reset would flip the whole mood — iconic little trick.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trho_wishes_pending", A,
            "Earned coupons from the play gods. Spend one — hobby supply treat.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trho_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trho_mid_streak", A,
            "Three days of hobby in a row — the skill's growing and you keep slipping into flow-state. Suspicious.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trho_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trho_sant_jordi", A,
            "It's Sant Jordi — the whole city's an excuse to buy that craft book you've been circling. Iconic purchase.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_la_merce", A,
            "Mercè's a whole cultural buffet out there — pure hobby fuel if you walk through with your eyes open.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_sant_joan", A,
            "Bonfire night — go to the beach, the hobby will still be here tomorrow. Iconic restraint, letting it wait.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_diada", A,
            "Diada. Long hobby slot. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_nadal", A,
            "Nadal. Show family what you made. Iconic share.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_cap_d_any", A,
            "New year. One hobby goal. Specific. Don't theatre.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trho_reis", A,
            "Reis. New tool gifted? Crack it open. The lore demands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_carnaval", A,
            "Carnaval. Costume-craft hobby moment. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_divendres_sant", A,
            "Quiet day. Long hobby session. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_pasqua", A,
            "Pasqua. Outdoor sketching maybe. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_festa_del_treball", A,
            "Workers' day. Slow hobby morning. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_festa_major_gracia", A,
            "Gràcia. Photo-walks. Iconic hobby-fuel week.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_assumpcio", A,
            "August. Summer hobby era. Hours of play. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_hispanitat", A,
            "Day off. Long hobby session. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_castanyada", A,
            "Castanyada. Long-evening hobby. Cosy. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_constitucio", A,
            "Bridge weekend. Deep-hobby hours. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_immaculada", A,
            "Pont. Finish a project. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_sant_esteve", A,
            "Day after. Slow hobby. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_cap_d_any_eve", A,
            "Last day. Year-of-hobby-wins list. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trho_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trho_birthday", A,
            "Birthday. Hobby gift to yourself. Iconic. Steal the bit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trho_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trho_personal_date", A,
            "You marked this date: {label}. Hobby moment to mark it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trho_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trho_complete_1", A, "Played. The B-plot advanced.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trho_complete_2", A, "Made. Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trho_complete_3", A, "Hobby WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trho_complete_first_today", A,
            "First session. Mood lifted. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trho_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trho_complete_second_today", A,
            "Two. Compound joy. The B-plot lands.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trho_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trho_complete_third_today", A,
            "Three. Flow-day. Skill glowing.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trho_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trho_complete_fourth_today", A,
            "Four. Hydrate, eat — body interrupts the plot.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trho_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trho_complete_fifth_today", A,
            "Five. Big play day. Stop and rest. Iconic restraint.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trho_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trho_complete_after_streak", A,
            "Three days of hobby. Skill growing. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trho_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trho_apotheosis_1", A,
            "Block done. Hobby-glow real. Don't ghost the bit.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trho_apotheosis_2", A,
            "Cycle wrapped. Next hobby goal — small one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trho_apotheosis_3", A,
            "Closed. Play WIN. Continue.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trho_apotheosis_first_ever", A,
            "First block. Hobby is canon. Inconvenient. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trho_apotheosis_1", "trho_apotheosis_2", "trho_apotheosis_3"),
            theme = T),
        DialogueLine("trho_apotheosis_at_level_2", A,
            "Promoted. You finish projects now. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trho_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trho_apotheosis_at_level_3", A,
            "Senior tier. Friends ask. Be vague. Keep the legend.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trho_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trho_apotheosis_at_level_4", A,
            "Top tier. Years of joyful play. The B-plot is the real plot. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trho_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trho_nudge_morning", A,
            "Hobby slot before the day. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trho_nudge_afternoon_zero", A,
            "Twenty minutes. Now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trho_nudge_evening", A,
            "Hobby beats TV. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trho_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trho_nudge_lapse", A,
            "Yesterday: zero play. Today: fifteen minutes. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trho_nudge_attention_loss", A,
            "B-plot stalled. One small session today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trho_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
