package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Gratitude — sardonic, meta, "the credits exist". */
internal object TricksterGratitudeLines {

    private const val A = "TRICKSTER"
    private const val T = "GRATITUDE"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trgr_first_ever", A,
            "Oh good, the gratitude arc. Spoiler — the credits exist whether you read them or not.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trgr_morning", A,
            "Three things to be grateful for. Now. Don't theatre — just three.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_morning_early", A,
            "Up early. Quiet — note it. The credits roll on small things.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_afternoon", A,
            "Mid-act. One thing that went right. Note it. Iconic restraint.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_evening", A,
            "Evening. Three-thing list before sleep. The credits roll quietly.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_night_late", A,
            "Late. One good thing today. Just one. Sleep on it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trgr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_post_apotheosis", A,
            "Plot twist: noticing. Keep the daily list — don't let the bit lapse.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trgr_monday", A,
            "Monday. Three things to look forward to. Specific. Don't gold-plate.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trgr_friday", A,
            "Friday. Three iconic moments from the week. Be specific.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trgr_weekend", A,
            "Weekend. Slow noticing. The small things. Cinematic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trgr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trgr_level_1_reached", A,
            "First tier. A month of lists. Mood up. The lore filed a thank-you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trgr_level_2_reached", A,
            "Second tier. You catch yourself smiling at small things. Suspicious.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trgr_level_3_reached", A,
            "Third tier. People notice the warmth. Iconic. Don't admit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trgr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trgr_level_4_reached", A,
            "Final tier. Years of noticing. The glow is real. Maintain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trgr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trgr_attention_loss_mild", A,
            "Few flat days. One thing today — note it. Don't theatre.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trgr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trgr_attention_loss_hard", A,
            "Two-week heavy era. One small thing today. Even coffee counts. Curtain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trgr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trgr_after_lapse", A,
            "Yesterday: zero notice. Today: one thing. Don't argue. Note.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trgr_mid_day_return", A,
            "Halftime. Look up. One thing visible right now. Note it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trgr_wishes_pending", A,
            "Earned coupons from the noticing gods. Spend one — treat.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trgr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trgr_mid_streak", A,
            "Three days of lists. Mood steadier. Suspicious calm.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trgr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trgr_sant_jordi", A,
            "Sant Jordi. Book + rose received? Notice it. Hold it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_la_merce", A,
            "Mercè. Note one moment. Hold it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_sant_joan", A,
            "Sant Joan. Sparks. Sea. Friends. Note one. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_diada", A,
            "Diada. Long-day notice. One small thing. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_nadal", A,
            "Nadal. One family moment to notice. Hold it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_cap_d_any", A,
            "New year. Year-of-wins list. Specific. Don't be modest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trgr_reis", A,
            "Reis. Gift received? Send a thank-you. Iconic restraint.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_carnaval", A,
            "Carnaval. Belly-laughs to notice. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_divendres_sant", A,
            "Quiet day. Silence itself — note it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_pasqua", A,
            "Pasqua. Trail moment. Note one. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_festa_del_treball", A,
            "Workers' day. Note the day off itself. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_festa_major_gracia", A,
            "Gràcia. Decorations — the neighbours did THAT. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_assumpcio", A,
            "August. Slow city. Note one warm thing. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_hispanitat", A,
            "Day off. Rest-day notice. One small joy. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_castanyada", A,
            "Castanyada. Autumn smell. Chestnuts. Note it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_constitucio", A,
            "Bridge weekend. Two whole free days — note them. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_immaculada", A,
            "Pont. Appreciate-list. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_sant_esteve", A,
            "Day after. Leftover moment to notice. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_cap_d_any_eve", A,
            "Last day. Year-of-cute-moments list. Iconic close.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trgr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trgr_birthday", A,
            "Birthday. One good thing per year you've had. Specific. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trgr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_personal_date", A,
            "You marked this date: {label}. Note one thing from the original. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trgr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trgr_complete_1", A, "Noted. The credits roll.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trgr_complete_2", A, "Joy logged. Iconic restraint.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trgr_complete_3", A, "Glow-noticing WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trgr_complete_first_today", A,
            "First gratitude. Mood lifted. Suspicious.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trgr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trgr_complete_second_today", A,
            "Two. Compound joy. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trgr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trgr_complete_third_today", A,
            "Three. Iconic glow.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trgr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trgr_complete_fourth_today", A,
            "Four. Big-glow day or forcing it? Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trgr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trgr_complete_fifth_today", A,
            "Five. Stop counting joy — be in it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trgr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trgr_complete_after_streak", A,
            "Three days of lists. Mood steadier. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trgr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trgr_apotheosis_1", A,
            "Block done. Noticing glowing. Don't lapse the bit.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trgr_apotheosis_2", A,
            "Cycle wrapped. Next gratitude goal — small one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trgr_apotheosis_3", A,
            "Closed. Glow-noticing WIN. Continue.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trgr_apotheosis_first_ever", A,
            "First block. Daily gratitude is canon. Inconvenient. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trgr_apotheosis_1", "trgr_apotheosis_2", "trgr_apotheosis_3"),
            theme = T),
        DialogueLine("trgr_apotheosis_at_level_2", A,
            "Promoted. You catch small joys without thinking. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_apotheosis_at_level_3", A,
            "Senior tier. People notice the warmth. Iconic. Don't gloat.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trgr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trgr_apotheosis_at_level_4", A,
            "Top tier. Years of noticing. The glow is real. Maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trgr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trgr_nudge_morning", A,
            "Three things. Quick. Don't theatre.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trgr_nudge_afternoon_zero", A,
            "Look up. One thing right now.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trgr_nudge_evening", A,
            "Three-thing list before sleep. The credits roll.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trgr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trgr_nudge_lapse", A,
            "Yesterday: zero notice. Today: one thing. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trgr_nudge_attention_loss", A,
            "Bit got dark. One small good thing today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trgr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
