package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Writing — sardonic, meta, the bit literally writes itself. */
internal object TricksterWritingLines {

    private const val A = "TRICKSTER"
    private const val T = "WRITING"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trwr_first_ever", A,
            "Oh good, the writing arc. Spoiler — the blinking cursor wins if you let it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trwr_morning", A,
            "Three pages or one tiny scene. Brain is freshest. Don't waste the act.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trwr_morning_early", A,
            "Up early. Best writing brain of the day. Use it. Smug.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trwr_afternoon", A,
            "Mid-act. Thirty-minute sprint. Coffee + words. Don't theatre.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trwr_evening", A,
            "Evening. Soft journaling. Even one line counts. Plot satisfied.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trwr_night_late", A,
            "Late. Brain too soft for real writing. One line — sleep on the rest.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trwr_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trwr_post_apotheosis", A,
            "Plot twist: pages. Keep the ritual. Don't ghost the page.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trwr_monday", A,
            "Monday. Word count for the week. Small. Specific. Annoying. Right.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trwr_friday", A,
            "Friday. Read what you wrote. One good sentence? Plot satisfied.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trwr_weekend", A,
            "Weekend. Long-write era. Café. Hours of words. Cinematic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trwr_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trwr_level_1_reached", A,
            "First tier. Daily writing for a month. The voice is forming. Suspicious.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trwr_level_2_reached", A,
            "Second tier. You finish drafts now. Real-writer behaviour. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trwr_level_3_reached", A,
            "Third tier. People share your work. Don't reply yet. Keep the mystery.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trwr_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trwr_level_4_reached", A,
            "Final tier. Years of pages. The voice is yours. Maintain. Don't sequel.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trwr_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trwr_attention_loss_mild", A,
            "Few skipped days. The cursor missed you. One paragraph today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trwr_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trwr_attention_loss_hard", A,
            "Two-week ghosting of the page. Bold arc. One line today. Curtain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trwr_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trwr_after_lapse", A,
            "Yesterday: cursor 1, you 0. Today: one paragraph. Don't argue.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trwr_mid_day_return", A,
            "Halftime. Twenty-minute sprint. Phone away. The narrator times.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trwr_wishes_pending", A,
            "Earned coupons from the page-gods. Spend one — notebook, pen, treat.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trwr_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trwr_mid_streak", A,
            "Three days of pages. The voice tightened. Suspicious.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trwr_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trwr_sant_jordi", A,
            "Sant Jordi. Book day. Write a tiny love letter to someone. The lore demands.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_la_merce", A,
            "Mercè. Capture one street-scene. One paragraph. Field notes.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_sant_joan", A,
            "Sant Joan. Notes by the fire. Show up — write tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_diada", A,
            "Diada. Slow morning, long write. Café session — iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_nadal", A,
            "Nadal. Christmas cards. Handwritten. The grandmothers approve.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_cap_d_any", A,
            "New year. Year-of-writing intention. Small word count. Don't theatre.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trwr_reis", A,
            "Reis. Thank-you notes. Real handwriting. The lore is exact.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_carnaval", A,
            "Carnaval. Character-sketch from the street. Writer-watch. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_divendres_sant", A,
            "Quiet day. Long-form day. Deep write. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_pasqua", A,
            "Pasqua. Field-notes on the hike. Two-for-one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_festa_del_treball", A,
            "Workers' day. Morning-pages session. Free thinking. Smug.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_festa_major_gracia", A,
            "Gràcia. Notes on the decorated streets. Immersion. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_assumpcio", A,
            "August. Slow city. Writer-summer. Long mornings. Pages.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_hispanitat", A,
            "Day off. Slow writing session. Iconic restraint.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_castanyada", A,
            "Castanyada. Long evenings = page-flow era. The plot endorses.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_constitucio", A,
            "Bridge weekend. Long-write. Two hours. The narrator bows.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_immaculada", A,
            "Pont. Finish a draft. Iconic restraint required.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_sant_esteve", A,
            "Day after. Journal entry — what mattered yesterday. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_cap_d_any_eve", A,
            "Last day. Year-in-review pages. Reflection. Don't be modest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trwr_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trwr_birthday", A,
            "Birthday. Letter to future-you. One year ahead. Smug.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trwr_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_personal_date", A,
            "You marked this date: {label}. Three lines about today. Mark it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trwr_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trwr_complete_1", A, "Wrote. The cursor surrendered.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trwr_complete_2", A, "Pages down. Smug.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trwr_complete_3", A, "Words WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trwr_complete_first_today", A,
            "First pages. Voice loosening. The bit is warming up.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trwr_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trwr_complete_second_today", A,
            "Two. Compound writing. The bit is going somewhere.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trwr_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trwr_complete_third_today", A,
            "Three. Brain in flow. Stay there.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trwr_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trwr_complete_fourth_today", A,
            "Four. Big draft day or running from something? Hydrate either way.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trwr_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trwr_complete_fifth_today", A,
            "Five. Close the file. Body needs a walk. Brain too.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trwr_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trwr_complete_after_streak", A,
            "Three days of pages. Voice tightening. The bit lands.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trwr_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trwr_apotheosis_1", A,
            "Block done. Voice growing. The cursor filed a positive review.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trwr_apotheosis_2", A,
            "Cycle wrapped. Pick the next writing goal — smaller, weirder, better.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trwr_apotheosis_3", A,
            "Closed. Writing-glow WIN. Don't ghost the page next week.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trwr_apotheosis_first_ever", A,
            "First block. Daily writing is canon. Inconvenient. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trwr_apotheosis_1", "trwr_apotheosis_2", "trwr_apotheosis_3"),
            theme = T),
        DialogueLine("trwr_apotheosis_at_level_2", A,
            "Promoted. You finish drafts now. Iconic. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trwr_apotheosis_at_level_3", A,
            "Senior tier. People share your work. Be vague — keep the legend.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trwr_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trwr_apotheosis_at_level_4", A,
            "Top tier. Years of pages. The voice is yours. Maintain. Don't sequel into slop.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trwr_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trwr_nudge_morning", A,
            "Morning. Three pages. Brain is fresh. Don't dramatize.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trwr_nudge_afternoon_zero", A,
            "Twenty-minute sprint. Phone away. The narrator times.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trwr_nudge_evening", A,
            "One journal line. That's it. Don't gold-plate.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trwr_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trwr_nudge_lapse", A,
            "Yesterday: cursor won. Today: one line. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trwr_nudge_attention_loss", A,
            "The page missed you. One line — today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trwr_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
