package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Meditation — sardonic, meta, "sitting is a bit". */
internal object TricksterMeditationLines {

    private const val A = "TRICKSTER"
    private const val T = "MEDITATION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trme_first_ever", A,
            "Oh good, the sitting arc. Spoiler — the breath is already there. Annoying.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trme_morning", A,
            "Sit five minutes before the coffee and watch the brain quietly reboot. Suspiciously efficient. I'm suspicious.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_morning_early", A,
            "Up before everyone, are we? The quiet won't hold — steal a sit before the world barges in and ruins it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_afternoon", A,
            "Here's the mid-day twist: five minutes, eyes shut, three slow breaths, and the afternoon stops winning. Try it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_evening", A,
            "The day's coasting toward its finale. Slow body-scan, head to toes — call it the wind-down we planned all along.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_night_late", A,
            "Goblin hours, and I'll allow exactly one thing: long slow breaths in the dark. Sleep's just the next sit anyway.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_post_apotheosis", A,
            "Plot twist: quieter. Keep the daily sit — don't ghost the cushion.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trme_monday", A,
            "The week's back for a rematch. Five quiet minutes on the cushion first — let it wonder why you're so calm.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trme_friday", A,
            "Five days have crammed your skull full. Sit, let the noise drain out, and don't make a whole production of it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trme_weekend", A,
            "Nobody's watching, so stretch the sit to twenty minutes. The lore allows it and, between us, so do I.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trme_level_1_reached", A,
            "A whole month of sits, and the mind's filed a suspiciously glowing review. That's a level, you menace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trme_level_2_reached", A,
            "You drop back to the breath now without even trying — a whole tier just for that. Suspicious skill. Keep it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trme_level_3_reached", A,
            "People keep saying you seem calm and you just smile like you've a secret. You do. Third tier. Don't confess.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trme_level_4_reached", A,
            "Years of breath and the mind's gone genuinely soft. Top of the tree now, you insufferable thing. Just maintain it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trme_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trme_attention_loss_mild", A,
            "A few sits skipped and the cushion's filed a very polite complaint. Three minutes patches it — I know a guy: you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trme_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trme_attention_loss_hard", A,
            "Two weeks ghosting the breath and it just waited, patient and smug. One sit today and we call it a redemption arc.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trme_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trme_after_lapse", A,
            "Yesterday the cushion sat empty and we don't discuss it. Today: three breaths, that's the whole ask. Don't argue.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trme_mid_day_return", A,
            "We're at halftime and the scoreboard's blank. Five minutes, phone face-down, eyes closed — and yes, I'm timing you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trme_wishes_pending", A,
            "You've got coupons stacking up from all that stillness. Cash one in — earn yourself a longer sit today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trme_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trme_mid_streak", A,
            "Three days of sits in a row and the mind's gone quiet on you. Suspicious gentleness. Don't jinx it — keep going.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trme_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trme_sant_jordi", A,
            "It's Sant Jordi — roses and books everywhere. Find a bench in the park, breathe a while, then go swoon over spines.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_la_merce", A,
            "Mercè's about to get gloriously loud. Steal three slow breaths before you dive in — your anchor for the chaos.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_sant_joan", A,
            "Sant Joan tonight: bonfires and cava. Sit by the sea a minute before it all ignites. Very cinematic of us.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_diada", A,
            "Big flags and big feelings out there. Our move? A slow morning and one long, unbothered sit indoors. On brand.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_nadal", A,
            "Nadal means family at full volume. Slip off for a five-minute hideaway sit — purely tactical, tell no one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_cap_d_any", A,
            "Fresh year, blank scoreboard. The plan's a daily five-minute sit. Annoyingly simple. Annoyingly, it works. Let's.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trme_reis", A,
            "Gift morning and the kids are vibrating at maximum. Three breaths between the unwrapping and you'll survive it, hero.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_carnaval", A,
            "Carnaval: masks, sequins, glorious sensory overload — our people. Keep a three-breath anchor for when it spins.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_divendres_sant", A,
            "The whole city's gone quiet today, and we'll pretend we arranged it. Perfect cover for one nice long sit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_pasqua", A,
            "A free Monday and a walk waiting. Sit outside for a few breaths first, look respectable, then wander off. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_festa_del_treball", A,
            "Workers' Day, so naturally we honor work by doing none. Slow start, one long sit, zero guilt. Commit to the bit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_festa_major_gracia", A,
            "Gràcia goes full decorated-chaos tonight. Bank a calm morning sit now — tactical prep for the noise, trust me.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_assumpcio", A,
            "The city fled to the coast and left us the keys. Empty August mornings, long lazy sits, no witnesses. Bliss.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_hispanitat", A,
            "Another day off dropped in our laps. My proposal: a slow, unhurried sit and absolutely nothing else. Deal?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_castanyada", A,
            "Chestnut smoke and panellets, and the evenings are getting long. Light a candle, sit in the glow a while. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_constitucio", A,
            "The whole country's vanished for a bridge weekend. Legally. Use one slow morning for a long reset sit. I insist.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_immaculada", A,
            "Behold, the pont — five days engineered from pure audacity. One proper sit, the rest are naps. Beautifully balanced.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_sant_esteve", A,
            "Sequel to the feast, and everyone's moving slow. Match the tempo: one soft, unhurried sit. The list agreed to wait.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_cap_d_any_eve", A,
            "Last day of the year. Sit a few slow breaths and see it out gently — everyone's pretending they're new tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trme_birthday", A,
            "It's your birthday, so — one long sit and a single intention for the year. Sincere for exactly this line. Back to sass.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trme_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_personal_date", A,
            "The date you flagged yourself: {label}. Three slow breaths to anchor it, and mark it somewhere inside. Quietly iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trme_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trme_complete_1", A, "Sat. The bit landed quietly.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trme_complete_2", A, "Breathed. Smug-calm energy.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trme_complete_3", A, "Soft-glow win, that one. Carry on being unbearably serene.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trme_complete_first_today", A,
            "One sit down and the day's already gone softer. Suspicious how well that works. Do it again while I'm baffled.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trme_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trme_complete_second_today", A,
            "Two now — the calm's compounding and the mind's gone light. Who authorized this roll? Oh, right. Me. Proceed.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trme_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trme_complete_third_today", A,
            "Three sits and the whole day just... flows. The plot's satisfied and so, grudgingly, am I. Show-off.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trme_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trme_complete_fourth_today", A,
            "Four. Genuine sit-day, or elegantly avoiding something? Be honest with me. Either way the breath doesn't mind.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trme_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trme_complete_fifth_today", A,
            "Five sits, and now the body's asking you to stand and walk it out. Go on — nothing left to prove today.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trme_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trme_complete_after_streak", A,
            "Three days of sits. Mind quieter. The bit landed.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trme_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trme_apotheosis_1", A,
            "Block done. Mind softer. Don't ghost the cushion next week.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trme_apotheosis_2", A,
            "Cycle wrapped. Next sit goal — smaller, weirder, better.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trme_apotheosis_3", A,
            "Closed. Soft-glow WIN. Continue.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trme_apotheosis_first_ever", A,
            "First block. Sitting is canon. Inconvenient. Keep sitting.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trme_apotheosis_1", "trme_apotheosis_2", "trme_apotheosis_3"),
            theme = T),
        DialogueLine("trme_apotheosis_at_level_2", A,
            "Promoted. Mind returns to breath without thinking. Suspicious.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trme_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trme_apotheosis_at_level_3", A,
            "Senior tier. People notice the calm. Be vague. Keep the mystery.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trme_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trme_apotheosis_at_level_4", A,
            "Top tier. Years of breath. Mind soft. Iconic. Maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trme_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trme_nudge_morning", A,
            "Five-minute sit. Don't dramatize.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trme_nudge_afternoon_zero", A,
            "Three breaths. Eyes closed. Now. The narrator times.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trme_nudge_evening", A,
            "Body-scan. Wind-down arc.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trme_nudge_lapse", A,
            "Yesterday: no sit. Today: three breaths. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trme_nudge_attention_loss", A,
            "Cushion filed a missing-person. One sit — today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trme_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
