package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Meditation — sardonic, meta, "sitting is a bit". */
internal object TricksterMeditationLines {

    private const val A = "TRICKSTER"
    private const val T = "MEDITATION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trme_first_ever", A,
            "Oh good, the sitting arc. Spoiler — the breath is already there. Annoying.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trme_morning", A,
            "Five-minute sit before coffee. Brain reboots. Suspicious efficiency.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_morning_early", A,
            "Up early. Quiet hour. Sit before the world ruins it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_afternoon", A,
            "Mid-act. Five-minute reset. Eyes closed. Three breaths. The lore is gentle.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_evening", A,
            "Evening. Slow body-scan. Wind-down arc.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_night_late", A,
            "Late. Long breaths in bed. Sleep is the next sit.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trme_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trme_post_apotheosis", A,
            "Plot twist: quieter. Keep the daily sit — don't ghost the cushion.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trme_monday", A,
            "Monday. Reset-week sit. Five minutes. Don't theatre.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trme_friday", A,
            "Friday. Brain is full. Sit. Empty-time. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trme_weekend", A,
            "Weekend. Longer sit — twenty minutes. The lore allows it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trme_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trme_level_1_reached", A,
            "First tier. A month of sits. The mind filed a positive review. Wild.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trme_level_2_reached", A,
            "Second tier. You return to breath without thinking. Suspicious skill.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trme_level_3_reached", A,
            "Third tier. People notice the calm. Don't admit. Mystery.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trme_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trme_level_4_reached", A,
            "Final tier. Years of breath. Mind soft. Maintain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trme_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trme_attention_loss_mild", A,
            "Few skipped sits. The cushion filed a polite complaint. Three minutes today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trme_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trme_attention_loss_hard", A,
            "Two weeks ghosting the practice. The breath waited. One sit today. Curtain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trme_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trme_after_lapse", A,
            "Yesterday: no sit. Today: three breaths. Don't argue.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trme_mid_day_return", A,
            "Halftime. Five-minute sit. Phone aside. Eyes closed. The narrator times.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trme_wishes_pending", A,
            "Earned coupons from the breath gods. Spend one — sit longer today.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trme_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trme_mid_streak", A,
            "Three days of sits. The mind quieter. Suspicious gentleness.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trme_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trme_sant_jordi", A,
            "Sant Jordi. Book-in-park sit. The lore approves.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_la_merce", A,
            "Mercè. Loud day. Three breaths before going out. Iconic anchor.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_sant_joan", A,
            "Sant Joan. Sit by the sea before the fire. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_diada", A,
            "Diada. Slow morning. Long sit. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_nadal", A,
            "Nadal. Family chaos = five-minute hideaway sit. Tactical.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_cap_d_any", A,
            "New year. Daily sit goal. Five minutes. Annoying. Right.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trme_reis", A,
            "Reis. Excited kids. Three-breath reset. Iconic between things.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_carnaval", A,
            "Carnaval. Big sensory. Three-breath anchor. Tactical.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_divendres_sant", A,
            "Quiet day. Long sit. The city helps.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_pasqua", A,
            "Pasqua. Outdoor sit before the walk. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_festa_del_treball", A,
            "Workers' day. Slow start. Long sit. Iconic rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_festa_major_gracia", A,
            "Gràcia. Morning sit before the noisy night. Tactical prep.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_assumpcio", A,
            "August. Slow city. Long sits. Cosy mornings. Soft arc.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_hispanitat", A,
            "Day off. Slow sit. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_castanyada", A,
            "Castanyada. Candle sit. Long-evening glow. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_constitucio", A,
            "Bridge weekend. Long sit. Reset. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_immaculada", A,
            "Pont. One longer practice. The rest are naps. The lore is balanced.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_sant_esteve", A,
            "Day after. Slow sit. Soft. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_cap_d_any_eve", A,
            "Last day. Year-out sit. Soft. Iconic close.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trme_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trme_birthday", A,
            "Birthday. Long sit today. One intention for the year. The lore listens.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trme_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trme_personal_date", A,
            "You marked this date: {label}. Three-breath anchor. Mark it inside.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trme_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trme_complete_1", A, "Sat. The bit landed quietly.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trme_complete_2", A, "Breathed. Smug-calm energy.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trme_complete_3", A, "Soft-glow WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trme_complete_first_today", A,
            "First sit. Day already softer. Suspicious.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trme_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trme_complete_second_today", A,
            "Two. Compound. Mind light.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trme_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trme_complete_third_today", A,
            "Three. Day flows. Plot satisfied.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trme_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trme_complete_fourth_today", A,
            "Four. Big sit-day or avoiding? Honest check.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trme_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trme_complete_fifth_today", A,
            "Five. Body says move. Walk it out.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trme_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trme_complete_after_streak", A,
            "Three days of sits. Mind quieter. The bit landed.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trme_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trme_apotheosis_1", A,
            "Block done. Mind softer. Don't ghost the cushion next week.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trme_apotheosis_2", A,
            "Cycle wrapped. Next sit goal — smaller, weirder, better.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trme_apotheosis_3", A,
            "Closed. Soft-glow WIN. Continue.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trme_apotheosis_first_ever", A,
            "First block. Sitting is canon. Inconvenient. Keep sitting.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trme_apotheosis_1", "trme_apotheosis_2", "trme_apotheosis_3"),
            theme = T),
        DialogueLine("trme_apotheosis_at_level_2", A,
            "Promoted. Mind returns to breath without thinking. Suspicious.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trme_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trme_apotheosis_at_level_3", A,
            "Senior tier. People notice the calm. Be vague. Keep the mystery.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trme_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trme_apotheosis_at_level_4", A,
            "Top tier. Years of breath. Mind soft. Iconic. Maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trme_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trme_nudge_morning", A,
            "Five-minute sit. Don't dramatize.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trme_nudge_afternoon_zero", A,
            "Three breaths. Eyes closed. Now. The narrator times.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trme_nudge_evening", A,
            "Body-scan. Wind-down arc.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trme_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trme_nudge_lapse", A,
            "Yesterday: no sit. Today: three breaths. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trme_nudge_attention_loss", A,
            "Cushion filed a missing-person. One sit — today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trme_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
