package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Recovery — sardonic, meta, rest-as-arc. */
internal object TricksterRecoveryLines {

    private const val A = "TRICKSTER"
    private const val T = "RECOVERY"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trre_first_ever", A,
            "Oh good, the rest arc. Spoiler — the protagonist also naps. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trre_morning", A,
            "So? What's the body reporting this morning — and don't fib, I can tell. Listen before you plan a thing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_morning_early", A,
            "Up with the birds and already scheming? Slow start first — non-negotiable. The body keeps a petty little ledger.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_afternoon", A,
            "We're mid-act — pick your move: a twenty-minute lie-down or a walk in the shade. Either way, the universe loses.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_evening", A,
            "The day's begging for an encore and the answer's no. Wind down, start nothing new — that's cunning, not laziness.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_night_late", A,
            "Goblin hours, and here's the twist: pushing through isn't the flex. Sleeping is. Down tools before I hide them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trre_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trre_post_apotheosis", A,
            "Plot twist: rested. Take a real day off — not a soft one. Cinematic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trre_monday", A,
            "The week's back for a rematch and you're already down a weekend's worth of sleep. First job: clear that debt.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trre_friday", A,
            "Five days done and the week's slid you an invoice. Tonight's task: do absolutely nothing, and do it beautifully.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trre_weekend", A,
            "Nobody's watching, so here's our heist: steal a do-nothing half-day. Phone off, no plans, zero guilt.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trre_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trre_level_1_reached", A,
            "Level one, and look at you — a whole week honouring rest. Sleep's already deeper. I won't tell if you won't.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trre_level_2_reached", A,
            "Level two, deloads actually on the calendar. The body trusts you again — frankly suspicious, but I'll allow it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trre_level_3_reached", A,
            "Level three? You're reading the body before it even raises its voice. Nobody's this good without cheating. Are you?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trre_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trre_level_4_reached", A,
            "Top of the tree. Years of rest as discipline — you're insufferable now and I couldn't be prouder. Maintain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trre_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trre_attention_loss_mild", A,
            "Three days running on caffeine and spite — I've been counting. The body's ledger is due. Pay it back tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trre_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trre_attention_loss_hard", A,
            "Two weeks of pushing — and before you argue, this is burnout, not weakness. The comeback needs a real day off. Today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trre_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trre_after_lapse", A,
            "Yesterday you skipped rest and thought I wouldn't notice. Today: bed by ten. I'm not arguing, I'm narrating.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trre_mid_day_return", A,
            "We've hit halftime and the scoreboard's empty — twenty-minute lie-down, right now. Yes, the narrator's timing you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trre_wishes_pending", A,
            "There's treasure sitting unspent in your pocket — coupons the body earned you. Cash one in on a gloriously slow day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trre_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trre_mid_streak", A,
            "Three days of real rest in a row and the body's actually coming back. The bit's landing — don't break it now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trre_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trre_sant_jordi", A,
            "Sant Jordi — the whole city out flirting via books all day. Pace yourself, grab a bench when you can. Sly restraint.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_la_merce", A,
            "Mercè's giants and fireworks are glorious and completely draining. Slip out when the body says so — no guilt, our secret.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_sant_joan", A,
            "Sant Joan, bonfires till dawn — and tomorrow's the price. Enjoy the flames, then hand tomorrow entirely to rest.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_diada", A,
            "Big flags, big feelings, and a day off — so here's the deal: no sneaky make-up work. Rest is the whole assignment.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_nadal", A,
            "Nadal — family's loud, turron's everywhere. Pull the classic disappearing act: twenty quiet minutes, then back in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_cap_d_any", A,
            "Fresh year, blank scoreboard — let's make rest a discipline this time, not a collapse. Pencil the deloads in now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trre_reis", A,
            "Reis, gift morning — with a sugar crash penciled in for the afternoon. Head it off with a slow walk and flat water.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_carnaval", A,
            "Carnaval — masks, sequins, the whole city officially in on the bit. Loud is depleting, so recover properly by Tuesday.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_divendres_sant", A,
            "The whole city's gone suspiciously quiet today. It's modelling rest right at you — copy it, no questions asked.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_pasqua", A,
            "A Monday with no work in it — found money. Slow walk, slower lunch, eat the mona. That's the entire job today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_festa_del_treball", A,
            "Workers' Day — the one day we honour work by doing none. The body's a worker too, so hand it the whole day off.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_festa_major_gracia", A,
            "Gràcia's gone full decorated-streets chaos again. The late nights stack — book an afternoon off and, this time, take it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_assumpcio", A,
            "The whole city fled to the coast and left us the keys. Two options: rest fully, or rest badly. Pick well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_hispanitat", A,
            "Another day off drops in your lap — my proposal: do-nothing maintenance, and let history argue with itself elsewhere.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_castanyada", A,
            "Castanyada — chestnut smoke and early dark. The season's handing you a licence to sleep earlier, so take the hint.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_constitucio", A,
            "Bridge weekend — two slow days handed straight to you. Guard them like treasure; look away and they'll fill right up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_immaculada", A,
            "Behold the pont — five days conjured from pure audacity. Spend two on real rest: bed early, no plans, no haggling.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_sant_esteve", A,
            "The day after the feast, and celebrating is secretly exhausting. Slow start, zero obligations — you've earned the lull.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_cap_d_any_eve", A,
            "Last day of the year, long night incoming. Sneak a nap this afternoon — midnight-you will thank present-you for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trre_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trre_birthday", A,
            "It's your birthday, so I'm contractually sincere for one line: the kindest gift is a long, unbothered sleep. Plan it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trre_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trre_personal_date", A,
            "The one you flagged yourself: {label}. The body's going to feel this one — so clear tomorrow morning in advance.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trre_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trre_complete_1", A, "Rested. Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trre_complete_2", A, "Deload logged. The week is wiser.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trre_complete_3", A, "Slow-day WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trre_complete_first_today", A,
            "First rest — without guilt. That's the practice.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trre_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trre_complete_second_today", A,
            "Two. Body being heard. Don't undo it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trre_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trre_complete_third_today", A,
            "Three. Today was for recovery. Let it be that. No bonus work.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trre_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trre_complete_fourth_today", A,
            "Four. Very sick or turning rest into a task? Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trre_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trre_complete_fifth_today", A,
            "Five. Rest is not a leaderboard. Stop counting. Sit.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trre_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trre_complete_after_streak", A,
            "Three days honouring rest. The system catches up. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trre_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trre_apotheosis_1", A,
            "Block done. Not graduation — schedule the next deload now.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trre_apotheosis_2", A,
            "Cycle wrapped. Body trusts you again. Don't betray it next month.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trre_apotheosis_3", A,
            "Closed. Rest is the work. No graduation. Maintain.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trre_apotheosis_first_ever", A,
            "First block. Rest is canon. Inconvenient. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trre_apotheosis_1", "trre_apotheosis_2", "trre_apotheosis_3"),
            theme = T),
        DialogueLine("trre_apotheosis_at_level_2", A,
            "Promoted. Recovery is policy. Defend it from the urgent that is not important.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trre_apotheosis_at_level_3", A,
            "Senior tier. People see you rest and learn. Be the example. No bravado.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trre_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trre_apotheosis_at_level_4", A,
            "Top tier. Years of rest as discipline. The body is the proof. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trre_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trre_nudge_morning", A,
            "Honest check. Body says what?",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trre_nudge_afternoon_zero", A,
            "Twenty-minute lie-down. Now. That's the deal.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trre_nudge_evening", A,
            "Wind down. No new project tonight.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trre_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trre_nudge_lapse", A,
            "Yesterday: skipped. Tonight: bed by ten. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trre_nudge_attention_loss", A,
            "Burnout signal loud. A real day off — today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trre_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
