package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Hydration — sardonic, meta, water-as-character-arc. */
internal object TricksterHydrationLines {

    private const val A = "TRICKSTER"
    private const val T = "HYDRATION"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trhy_first_ever", A,
            "Oh good, the hydration arc. Spoiler — your skin's been quietly suing you for years.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trhy_morning", A,
            "Look who's awake. Water first, coffee second. The order matters. Wild.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trhy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trhy_morning_early", A,
            "Up early — big glass, no negotiating. The cells filed a memo overnight and they want compliance.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trhy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trhy_afternoon", A,
            "Refill time — and I mean actual water, not the vibes you've been running on all afternoon.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trhy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trhy_evening", A,
            "Evening. One more glass with dinner. The skin will write you a thank-you card.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trhy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trhy_night_late", A,
            "It's late — small sip only. A big one now is just a bathroom trip in disguise. The narrator has spoken.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trhy_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trhy_post_apotheosis", A,
            "Plot twist: hydrated. Keep the bottle nearby — don't break the bit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trhy_monday", A,
            "New week — bottle on the desk, all day. Refills beat coffee. Annoying, I know. Also right.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trhy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trhy_friday", A,
            "Vermut tonight? One water between rounds — that's the deal. Saturday-you will bow to you for it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trhy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trhy_weekend", A,
            "Weekend brunch is hot coffee and cold water — the full kit. Don't you dare skip the second part.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trhy_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trhy_level_1_reached", A,
            "First tier — a whole week of bottles. Your skin has filed a genuinely positive review. Rare.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trhy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trhy_level_2_reached", A,
            "Second tier. The body's started craving water over caffeine now. That's a genuine plot twist.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trhy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trhy_level_3_reached", A,
            "Third tier. You've become the bottle-everywhere friend now. Own it — lean all the way in.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trhy_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trhy_level_4_reached", A,
            "Final tier. Years of bottles, and the skin's become a long-running joke that finally landed. Keep it up.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trhy_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trhy_attention_loss_mild", A,
            "Three dry days in a row — suspicious. Glass on the desk, right now, no debate.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trhy_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trhy_attention_loss_hard", A,
            "Two weeks of mystery hydration and the cells have filed a class action. Big glass, now, before they win.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trhy_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trhy_after_lapse", A,
            "Yesterday: coffee, beer, vibes. Today: water. The order is the point.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trhy_mid_day_return", A,
            "We're at halftime — refill the bottle. And yes, the narrator is absolutely timing you on this.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trhy_wishes_pending", A,
            "Earned coupons from the cells. Cash one in — drink today, treat tonight.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trhy_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trhy_mid_streak", A,
            "Three days of refills in a row — the skin's secretary called with a glowing review. Keep it going.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trhy_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trhy_sant_jordi", A,
            "It's Sant Jordi — you'll be walking in the sun all day. Bottle in the bag, and the fountains are free.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_la_merce", A,
            "Mercè means vermut tonight — one water between rounds. Tomorrow-you is already trying to bargain with you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_sant_joan", A,
            "Bonfire night — cava, beach, and sweat all at once. Water between every bit of it. The plot insists.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_diada", A,
            "Diada's a long walking day — bottle in the bag, and there are fountains the whole route. No excuses.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_nadal", A,
            "Nadal brings a very salty meal — keep a big water glass next to the wine and pace yourself through it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_cap_d_any", A,
            "New year — leave a bottle by the bed tonight. Tomorrow's protagonist is going to be extremely fragile.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trhy_reis", A,
            "Reis brings the sugar coma — big water and a walk is the only known cure. I hate that this is the lore.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_carnaval", A,
            "Carnaval is a full costume-plus-dancing dehydration arc waiting to happen. Bottle after every set.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_divendres_sant", A,
            "The city's quiet today — soft sips all day. Tea, water, tea, repeat. The plot is being gentle for once.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_pasqua", A,
            "Pasqua means a hike — two bottles in the bag, not one. The lore is genuinely unforgiving on this point.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_festa_del_treball", A,
            "It's Workers' Day — a long brunch outside. Water with everything, and pace yourself, we've got all day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_festa_major_gracia", A,
            "Gràcia's all hot streets and beer tents this week — water between everything, every single time.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_assumpcio", A,
            "August, and the heat is the clear antagonist. Big bottle, fountain refills, and we both survive it. Deal?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_hispanitat", A,
            "Another day off, another long lunch — keep a big glass on the table the whole time. The lore allows it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_castanyada", A,
            "Castanyada's salty chestnuts and sweet wine — water between the two. The lore is very exact here.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_constitucio", A,
            "Bridge weekend, and the heater's drying out the air. Sip all day — a cute mug works just as well.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_immaculada", A,
            "The pont gives you five days — bottle in the bag for every outing. Lore-accurate, non-negotiable.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_sant_esteve", A,
            "The day after the feast — big glass and a slow morning. The hangover arc has rules, and I wrote them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_cap_d_any_eve", A,
            "Last day of the year — cava, then cava, then cava. One big water before bed. Tomorrow-you is begging.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trhy_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trhy_birthday", A,
            "It's your birthday — one big glass before the very first toast. Lore-accurate, and I'd love your compliance.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trhy_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_personal_date", A,
            "You flagged this one yourself: {label}. Start it with a big glass — a tiny ritual, but an iconic one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trhy_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trhy_complete_1", A, "Sipped. The cells filed a positive note.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trhy_complete_2", A, "Refilled. The bottle-bit lives on.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trhy_complete_3", A, "You drank it. Smug looks good on you — keep going.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trhy_complete_first_today", A,
            "First refill down, and the whole body just acknowledged it. Annoyingly effective.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trhy_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trhy_complete_second_today", A,
            "Two — the sips are compounding. Bottle-queen behaviour, and I'm here for it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trhy_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trhy_complete_third_today", A,
            "Three — the skin filed a thank-you note. Mildly invasive of it, but I'll accept the compliment.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trhy_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trhy_complete_fourth_today", A,
            "Four. Slow down — gentle sips after this. Don't flush the salts.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trhy_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trhy_complete_fifth_today", A,
            "Five. The bit's officially waterlogged now — stop counting and go be smug. Iconic.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trhy_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trhy_complete_after_streak", A,
            "Day three of refills in a row — the skin filed a genuinely flattering one-pager about you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trhy_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trhy_apotheosis_1", A,
            "Block done. The bottle is canon now — it goes everywhere you do.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trhy_apotheosis_2", A,
            "Cycle wrapped. Bigger bottle, smaller cup? Pick the sequel — I'm curious.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trhy_apotheosis_3", A,
            "Closed. Hydration WIN — and the body filed a fan letter.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trhy_apotheosis_first_ever", A,
            "Your first closed block. The bottle goes everywhere with you now — inconvenient, and iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trhy_apotheosis_1", "trhy_apotheosis_2", "trhy_apotheosis_3"),
            theme = T),
        DialogueLine("trhy_apotheosis_at_level_2", A,
            "Promoted, essentially. Two bottles a day, no thinking required. Keep earning it.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trhy_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trhy_apotheosis_at_level_3", A,
            "Senior tier. People are noticing the glow now — don't you dare tell them it's just water.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trhy_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trhy_apotheosis_at_level_4", A,
            "Top tier. Years of bottles, and the skin's become the punchline. Keep the joke running.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trhy_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trhy_nudge_morning", A,
            "Water first, coffee second — the list is watching, so don't be a heathen about the order.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trhy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trhy_nudge_afternoon_zero", A,
            "Scoreboard's dry this afternoon. Bottle, full, now — the narrator is timing you.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trhy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trhy_nudge_evening", A,
            "Last glass of the day goes with dinner. Don't make a whole scene out of it — just drink.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trhy_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trhy_nudge_lapse", A,
            "Yesterday was coffee and vibes. Today it's water — glass on the desk. Curtain on the drought.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trhy_nudge_attention_loss", A,
            "The cells have filed a class action against you. Full glass today — this part isn't optional.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trhy_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
