package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Digital — sardonic, meta, screen-time as bit. */
internal object TricksterDigitalLines {

    private const val A = "TRICKSTER"
    private const val T = "DIGITAL"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trdi_first_ever", A,
            "Oh good, the screen-balance arc. Spoiler — the phone is not the protagonist.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trdi_morning", A,
            "Phone face-down first hour. Wild concept. Try it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trdi_morning_early", A,
            "Up early. Don't doom-scroll the morning, friend. Slow coffee. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trdi_afternoon", A,
            "Mid-act. Screen-time glance. Honest pricing.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trdi_evening", A,
            "Evening. Phone in another room at dinner. Eyes up. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trdi_night_late", A,
            "Late. Phone out of bedroom. Tomorrow-you begs. Comply.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trdi_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trdi_post_apotheosis", A,
            "Plot twist: less scroll. Keep the caps — don't sequel into doom.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trdi_monday", A,
            "Monday. Screen-time target for the week. Lower it a touch. Annoying. Right.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trdi_friday", A,
            "Friday. Phone-free dinner tonight. Friends-first. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trdi_weekend", A,
            "Weekend. Half-day phone-off — in another room. Forget it. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trdi_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trdi_level_1_reached", A,
            "First tier. A week of morning-no-scroll. The brain noticed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trdi_level_2_reached", A,
            "Second tier. Screen-time down. Hour reclaimed. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trdi_level_3_reached", A,
            "Third tier. Friends notice the eye contact. Don't admit. Mystery.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trdi_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trdi_level_4_reached", A,
            "Final tier. Years of balance. Phone is a tool. Maintain.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trdi_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trdi_attention_loss_mild", A,
            "Few scroll-heavy days. Phone out of bedroom tonight. Curtain.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trdi_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trdi_attention_loss_hard", A,
            "Two-week doomscroll arc. Bold. Uninstall ONE app today. The hard one.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trdi_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trdi_after_lapse", A,
            "Yesterday: feed-as-life. Today: phone out of bedroom. Don't argue.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trdi_mid_day_return", A,
            "Halftime. Phone in drawer one hour. Iconic mood-shift.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trdi_wishes_pending", A,
            "Earned coupons from the eye-contact gods. Spend one — treat, not a new app.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trdi_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trdi_mid_streak", A,
            "Three days low scroll. Brain quieter. Suspicious.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trdi_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trdi_sant_jordi", A,
            "Sant Jordi. Phone in pocket today. Eyes up. The lore is exact.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_la_merce", A,
            "Mercè. Don't film the whole thing. Watch it. Iconic presence.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_sant_joan", A,
            "Sant Joan. Phone in bag. Be at the beach.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_diada", A,
            "Diada. Day off the news cycle. Phone in drawer half the day. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_nadal", A,
            "Nadal. Phone in bag at table. Family > scrolling. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_cap_d_any", A,
            "New year. App-audit day. Delete two. Iconic year-of-clarity.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trdi_reis", A,
            "Reis. Set the kid-screen rules — for you first.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_carnaval", A,
            "Carnaval. Phone away. Watch the parade. Iconic eyes-up day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_divendres_sant", A,
            "Quiet day. Phone-off two-hour block. The city helps. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_pasqua", A,
            "Pasqua Monday. Reset notifications. Three apps only. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_festa_del_treball", A,
            "Workers' day. Work-phone off. Iconic. Don't peek.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_festa_major_gracia", A,
            "Gràcia. Eyes-up nights. Streets are art. Don't lens it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_assumpcio", A,
            "August. Notifications-off week. The city signs the permission slip.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_hispanitat", A,
            "Day off. Screen-time audit. Honest. Don't lie.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_castanyada", A,
            "Castanyada. Long evenings. Don't fill them all with scroll. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_constitucio", A,
            "Bridge weekend. Phone-off full day. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_immaculada", A,
            "Pont. Five days. Two of them, phone-light. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_sant_esteve", A,
            "Day after. Phone in another room. Family chaos. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_cap_d_any_eve", A,
            "Last day. Twelve grapes — eyes up. Phone away. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trdi_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trdi_birthday", A,
            "Birthday. Phone off tonight. The room is the gift. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trdi_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_personal_date", A,
            "You marked this date: {label}. Phone in pocket. Eyes on what's here. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trdi_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trdi_complete_1", A, "Phone down. Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trdi_complete_2", A, "Screen-discipline logged.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trdi_complete_3", A, "Eyes-up WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trdi_complete_first_today", A,
            "First boundary held. Hour reclaimed.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trdi_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trdi_complete_second_today", A,
            "Two. Compound brain-glow. Suspicious calm.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trdi_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trdi_complete_third_today", A,
            "Three. Hours reclaimed. Notice what you did with them.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trdi_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trdi_complete_fourth_today", A,
            "Four. Sick day or hiding from phone? Honest check.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trdi_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trdi_complete_fifth_today", A,
            "Five. Iconic boundary day. Stop counting. Just exist.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trdi_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trdi_complete_after_streak", A,
            "Three days low scroll. Brain quieter. The bit lands.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trdi_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trdi_apotheosis_1", A,
            "Block done. Caps stay. Don't sequel into doomscroll.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trdi_apotheosis_2", A,
            "Cycle wrapped. Audit again — cut one more app. Always cut.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trdi_apotheosis_3", A,
            "Closed. Eyes-up WIN. Phone is a tool, not a leash.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trdi_apotheosis_first_ever", A,
            "First block. Phone-free hours are canon. Inconvenient. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trdi_apotheosis_1", "trdi_apotheosis_2", "trdi_apotheosis_3"),
            theme = T),
        DialogueLine("trdi_apotheosis_at_level_2", A,
            "Promoted. Phone is a tool now. Defend it from the next app colonizing you.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trdi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trdi_apotheosis_at_level_3", A,
            "Senior tier. Friends notice the presence. Iconic role.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trdi_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trdi_apotheosis_at_level_4", A,
            "Top tier. Years of clear attention. Iconic. Maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trdi_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trdi_nudge_morning", A,
            "Phone face-down first hour. Don't break the bit.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trdi_nudge_afternoon_zero", A,
            "Phone in drawer one hour. Iconic mood-shift.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trdi_nudge_evening", A,
            "Phone in kitchen. Bedroom stays clean.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trdi_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trdi_nudge_lapse", A,
            "Yesterday: feed-as-life. Today: phone out of bedroom. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trdi_nudge_attention_loss", A,
            "Doomscroll's back. Uninstall ONE app — today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trdi_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
