package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Outdoors — sardonic, meta, the establishing shot. */
internal object TricksterOutdoorsLines {

    private const val A = "TRICKSTER"
    private const val T = "OUTDOORS"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trou_first_ever", A,
            "Oh good, the outdoors arc. Spoiler — the establishing shot needs you in it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trou_morning", A,
            "Sun's out and so are you — step outside before the coffee. Best establishing shot you'll get all day.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trou_morning_early", A,
            "Up before the city? Sneak a walk in while nobody's watching. We'll pretend it was an accident.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trou_afternoon", A,
            "Halfway through and the plot's sagging — steal a ten-minute walk at lunch and watch the mood flip.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trou_evening", A,
            "The light's going gold out there — a walk now and even the lighting director owes you one.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trou_night_late", A,
            "Goblin hours. Slip out for three breaths of night air — nobody has to know it counts. It counts.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trou_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trou_post_apotheosis", A,
            "Plot twist: outside is canon. Keep the walks — don't lose the bit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trou_monday", A,
            "The week's back for a rematch. Block out your outside slots now and dare anyone to steal them.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trou_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trou_friday", A,
            "Five days down. Bet you can't pick the weekend's spot — park, beach, or hill? I love losing this bet.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trou_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trou_weekend", A,
            "Nobody's watching and the list still wants you outside — half a day, minimum. Same game, comfier shoes.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trou_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trou_level_1_reached", A,
            "Level one, and you're already stepping out daily. Tiny. Adorable. I've spoiled the ending: it works.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trou_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trou_level_2_reached", A,
            "Level two — weekend hikes are a habit now. Your body's bowing to you and I find that deeply suspicious.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trou_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trou_level_3_reached", A,
            "Level three, and now you drag the whole crew outside? Nobody climbs this fast. ...Fine. You're just good.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trou_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trou_level_4_reached", A,
            "Top of the tree. Years of fresh air, and the glow's your receipt. Insufferable now — don't quote the proud part.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trou_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trou_attention_loss_mild", A,
            "Three days indoors and the lighting director's filing complaints. One little walk patches the whole scene.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trou_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trou_attention_loss_hard", A,
            "Two weeks in the cave — perfect setup for a comeback. The plot's begging for one exterior. Step out today.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trou_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trou_after_lapse", A,
            "Yesterday you gave the outside nothing. I told it you were scheming. One walk today — back me up. Go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trou_mid_day_return", A,
            "Halftime, and still no exterior on the board. Ten minutes out — the narrator is absolutely timing you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trou_wishes_pending", A,
            "There's treasure sitting unspent from all that fresh air. Cash one in — buy yourself a little trail treat.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trou_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trou_mid_streak", A,
            "Three days outside in a row — the glow's holding and the bit is landing. Don't you dare break it now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trou_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trou_sant_jordi", A,
            "Sant Jordi — the whole city's out flirting via books and roses. Wander it all day, then go swoon. That's the plan.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_la_merce", A,
            "La Mercè's got giants and fireworks in the streets all night. We've got the balcony seats — go out and use them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_sant_joan", A,
            "Bonfire night — the beach is the venue and it runs till dawn. Get out in it. A hop over one flame counts, I decided.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_diada", A,
            "Big flags, big feelings out there today. Between us, a long slow walk through it all would be very on brand.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_nadal", A,
            "Nadal means the sacred post-lunch walk — the grandmothers wrote that scene themselves, and you don't skip theirs.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_cap_d_any", A,
            "Fresh year, blank scoreboard. Set one outdoor goal — a monthly hike — and let's make the quitters' stats look silly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trou_reis", A,
            "Gift morning. Once the surprised faces are done, haul everyone to the park for a walk — best scene of the day.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_carnaval", A,
            "Sequins, masks, a whole city officially in on the bit — the parade's outside and so are we. Our people.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_divendres_sant", A,
            "The city's gone suspiciously quiet — perfect cover for a long beach walk. Let's enjoy it like we planned it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_pasqua", A,
            "A Monday with no work in it — found money. Pack the mona, pick a hike, look respectable doing gloriously little.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_festa_del_treball", A,
            "The one day we honour work by refusing to do any. So we honour it outside — a long, gloriously pointless walk.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_festa_major_gracia", A,
            "Gràcia's gone full craft-explosion again and the streets are the venue. Walk through and judge the tinsel. Lovingly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_assumpcio", A,
            "The whole city fled to the coast and left us the keys. So it's sea, sea, sea — long days outside, zero witnesses.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_hispanitat", A,
            "A complicated day on the calendar. My proposal: take the hike, be smug on a hilltop, let history argue with itself.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_castanyada", A,
            "Chestnut smoke in the air — autumn's official all-is-well day. Go crunch through the leaves. The Catalans knew.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_constitucio", A,
            "The bridge weekend's here — steal a long hike out of it. Skip it and that's how the season quietly ends. Rude.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_immaculada", A,
            "Behold the pont: five days built from pure audacity. Pyrenees or Costa Brava — either way, get outside for it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_sant_esteve", A,
            "Sequel to the feast. A slow recovery walk is the only known cure — the list agreed to wait. Grudgingly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_cap_d_any_eve", A,
            "Last day of the year — one walk to close the season out. Everyone's pretending tomorrow's them is new. Ours might be.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trou_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trou_birthday", A,
            "Birthday. Walk in your favourite spot. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trou_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trou_personal_date", A,
            "You marked this date: {label}. Outdoor moment to mark it. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trou_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trou_complete_1", A, "Outside. Establishing shot acquired.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trou_complete_2", A, "Walked. Iconic.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trou_complete_3", A, "Fresh-air WIN. Continue.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trou_complete_first_today", A,
            "First step out. Day already glowing.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trou_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trou_complete_second_today", A,
            "Two. Compound air. Body loving it.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trou_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trou_complete_third_today", A,
            "Three. Iconic glow-day.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trou_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trou_complete_fourth_today", A,
            "Four. Trail-day. Hydrate, sunscreen. Don't ruin the act.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trou_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trou_complete_fifth_today", A,
            "Five. Big outdoor day. Feet vote for couch now.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trou_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trou_complete_after_streak", A,
            "Three days outside. Glow steady. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trou_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trou_apotheosis_1", A,
            "Block done. Fresh-air glow real. Don't ghost outside.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trou_apotheosis_2", A,
            "Cycle wrapped. Next outdoor goal — small one.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trou_apotheosis_3", A,
            "Closed. Nature WIN. Continue.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trou_apotheosis_first_ever", A,
            "First block. Daily outside is canon. Inconvenient. Continue.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trou_apotheosis_1", "trou_apotheosis_2", "trou_apotheosis_3"),
            theme = T),
        DialogueLine("trou_apotheosis_at_level_2", A,
            "Promoted. Weekend hikes regular. Iconic.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trou_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trou_apotheosis_at_level_3", A,
            "Senior tier. You drag friends outside. Iconic role.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trou_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trou_apotheosis_at_level_4", A,
            "Top tier. Years of fresh air. Iconic. Maintain.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trou_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trou_nudge_morning", A,
            "Step out. Sun. Iconic.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trou_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trou_nudge_afternoon_zero", A,
            "Out. Now. Ten minutes. The narrator wants exterior.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trou_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trou_nudge_evening", A,
            "Golden-hour walk. The lighting director thanks you.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trou_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trou_nudge_lapse", A,
            "Yesterday: zero outdoor. Today: one walk. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trou_nudge_attention_loss", A,
            "Plot needs an exterior. Five minutes today. Mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trou_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
