package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Sleep — sardonic, meta, "you and the sandman are off." */
internal object TricksterSleepLines {

    private const val A = "TRICKSTER"
    private const val T = "SLEEP"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trsl_first_ever", A,
            "Oh good, the sleep arc. Spoiler — bed is the protagonist now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trsl_morning", A,
            "Look who emerged. Report — did the body get its eight hours, or are we improvising?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trsl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trsl_morning_early", A,
            "Up before the alarm and not furious about it? Suspicious. That's the sleep arc paying off — don't tell a soul.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trsl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trsl_afternoon", A,
            "Here's the afternoon fork: a twenty-minute nap or another coffee. One of these you'll regret. Choose wisely, gremlin.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trsl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trsl_evening", A,
            "The light's going soft — perfect cover. Dim the lamps and let the cosy wind-down montage begin. I'll narrate.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trsl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trsl_night_late", A,
            "Goblin hours again? Tomorrow-you is already drafting a strongly worded complaint. Settle it out of court: bed, now.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trsl_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trsl_post_apotheosis", A,
            "Plot twist: rested. Keep the bedtime. Don't sabotage the win.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trsl_monday", A,
            "The week's back and your weekend bedtime script is worthless now. Reset it. Rude, I know. Also entirely correct.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trsl_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trsl_friday", A,
            "Five days survived. Here's the wager: one late night is plot, two is rot. Which are we betting on tonight?",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trsl_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trsl_weekend", A,
            "No alarms, nobody watching — sleep in, sure. But past noon the day becomes a flashback. Let's strike a deal.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trsl_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trsl_level_1_reached", A,
            "A whole week of actual bedtimes? Deeply suspicious. That's tier one, gremlin — keep the bit running.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trsl_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trsl_level_2_reached", A,
            "Tier two, and now you wake before the alarm like some smug little legend. Earned it. I'm barely jealous.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trsl_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trsl_level_3_reached", A,
            "Tier three: you're officially the friend with a bedtime now. Be insufferable about it — you've earned the right.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trsl_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trsl_level_4_reached", A,
            "Top of the tree. Years of decent sleep, and even your skin looks suspicious about it. Don't you dare stop now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trsl_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trsl_attention_loss_mild", A,
            "Three nights of bargain-bin bedtimes — I've been keeping score, obviously. Tonight we go early. Humour me.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trsl_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trsl_attention_loss_hard", A,
            "Two whole weeks on fumes and vibes? Bold. Tonight the bedtime is non-negotiable — I'll be watching, fondly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trsl_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trsl_after_lapse", A,
            "Yesterday's bedtime was, generously, “whenever.” Tonight we're running a curfew. Play along — I dare you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trsl_mid_day_return", A,
            "We've hit the midpoint — twenty-minute nap, phone face-down where it can't tempt you. The plot demands it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trsl_wishes_pending", A,
            "You've got unspent coupons just sitting in your pocket. Cash one in before bedtime creeps up and steals it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trsl_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trsl_mid_streak", A,
            "Three nights of decent sleep in a row and your brain's quietly taking notes. Suspicious. Keep it going.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trsl_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trsl_sant_jordi", A,
            "It's Sant Jordi — you'll be on your feet chasing roses and books all day. Bed at a sane hour, or tomorrow's a rerun.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_la_merce", A,
            "Mercè runs late and I love that for us — but late nights are plot, past 2am is filler. Pace it, co-conspirator.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_sant_joan", A,
            "Bonfire night — an all-nighter is basically scheduled. Fine. But plan tomorrow as one long horizontal montage.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_diada", A,
            "Day off today — sleep in, absolutely. Just don't sleep clean through into tomorrow. That's a different genre.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_nadal", A,
            "Nadal is late dinner, late bed, late everything. Just this once the lore allows it — don't make it a habit, menace.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_cap_d_any", A,
            "Fresh year, blank sheet — and sleep is the protagonist now. Bedtime by an actual number, not a vibe. Deal?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trsl_reis", A,
            "Gift morning — everyone's in a sugar coma, the perfect cover for a tactical nap. Ambush the rest. Go, go.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_carnaval", A,
            "Costumes, masks, a party that runs late — that's today's deal. Bank Tuesday for recovery. Bargain accordingly.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_divendres_sant", A,
            "The whole city's gone quiet today — suspiciously perfect for an afternoon drift into a nap. Permission granted.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_pasqua", A,
            "A Monday with no work in it — you'll hike all day, then nap by sunset. Accept the plot, it's lore-accurate.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_festa_del_treball", A,
            "The one day we honour work by refusing to do any — so nap rights are workers' rights. Take one, on principle.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_festa_major_gracia", A,
            "Gràcia's about to go full week-long party. You know the script: bank sleep before, recover after. Follow it.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_assumpcio", A,
            "It's peak August, the city's emptied out, and siesta season is in full effect. Consider the permission slip signed.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_hispanitat", A,
            "Another day off has appeared on the calendar. Sleep in — I promise the world will not file a single complaint.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_castanyada", A,
            "Chestnut smoke in the air and the dark arriving early — so bed comes early too. Match the season. Be a cosy creature.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_constitucio", A,
            "A bridge weekend just landed in your lap — two cosy mornings. Don't you dare fill them with errands. Sleep, obviously.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_immaculada", A,
            "Behold the pont: five glorious days. Two with no alarm, the other three a decent bedtime. I did the maths for you.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_sant_esteve", A,
            "The day after the feast — sleep in without guilt. The family chaos can absolutely wait its turn. I'll stall them.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_cap_d_any_eve", A,
            "Last night of the year, and it'll run long. Tomorrow's plan: sleep through it, credits rolling horizontal. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trsl_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trsl_birthday", A,
            "It's your birthday, so I'm contractually sincere for one line: get a real bedtime tonight. Okay, sincerity over.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trsl_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_personal_date", A,
            "You flagged this one yourself: {label}. Bed by an honourable hour tonight — protect tomorrow-you. It's a whole plan.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trsl_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trsl_complete_1", A, "Bedtime acquired. I logged it, naturally — someone has to keep the receipts.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trsl_complete_2", A, "The sleep arc advances. Look at you, smug and horizontal.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trsl_complete_3", A, "Done — and the body just filed a quiet little thank-you note. Cute.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trsl_complete_first_today", A,
            "First sleep-win of the day, and tomorrow's already shaping up to be less of a disaster. We love a head start.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trsl_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trsl_complete_second_today", A,
            "Two already? A nap-and-bedtime combo, very suspicious. Who authorised this competence? Oh — me. Carry on.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trsl_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trsl_complete_third_today", A,
            "Three?! Either you're on a sick day or a well-rested impostor took over. Honestly, either one works for me.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trsl_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trsl_complete_fourth_today", A,
            "Four. This is a full hibernation arc now, and I for one welcome it. Absolute show-off.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trsl_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trsl_complete_fifth_today", A,
            "Five! The whole bit has gone horizontal and I couldn't be prouder. Nothing left to prove — go be smug.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trsl_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trsl_complete_after_streak", A,
            "Three nights of honourable bedtimes running — even your skin left a glowing review. Keep the streak alive.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trsl_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trsl_apotheosis_1", A,
            "You actually finished the block — sleep turned out to be the long-running gag that finally paid off. Keep it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trsl_apotheosis_2", A,
            "That's a wrap on this cycle. Pick the next bedtime — earlier, obviously. Annoyingly correct of me, I know.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trsl_apotheosis_3", A,
            "You closed it out, and somewhere the mattress is filing an embarrassingly sincere positive review.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trsl_apotheosis_first_ever", A,
            "Your first closed block, and the pilot episode's protagonist is well-rested. Let's not write in a cliffhanger.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trsl_apotheosis_1", "trsl_apotheosis_2", "trsl_apotheosis_3"),
            theme = T),
        DialogueLine("trsl_apotheosis_at_level_2", A,
            "Promoted. Sleep is your superpower. Defend it from the urgent.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trsl_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trsl_apotheosis_at_level_3", A,
            "Senior tier. Friends ask. You shrug. Iconic. Keep.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trsl_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trsl_apotheosis_at_level_4", A,
            "Top tier. The skin is the punchline. Maintain the bit.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trsl_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trsl_nudge_morning", A,
            "Morning. Water before scroll. The body sent a memo.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trsl_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trsl_nudge_afternoon_zero", A,
            "Halftime. Twenty-minute nap or a walk. Pick one. Plot watches.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trsl_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trsl_nudge_evening", A,
            "Evening. Dim the lights. Phone face-down. Don't ruin the act.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trsl_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trsl_nudge_lapse", A,
            "Yesterday: chaos hours. Tonight: bedtime. Curtain.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trsl_nudge_attention_loss", A,
            "Brain is loose change. Bedtime tonight is mandatory.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trsl_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
