package com.grcarmenaty.lifegame.domain.dialogue.lines.themed

import com.grcarmenaty.lifegame.domain.dialogue.*

/** Trickster × Tidyness — sardonic, meta, set-dressing arc. */
internal object TricksterTidynessLines {

    private const val A = "TRICKSTER"
    private const val T = "TIDYNESS"

    val all: List<DialogueLine> = listOf(

        DialogueLine("trti_first_ever", A,
            "Oh good, the set-dressing arc. Spoiler — the protagonist's apartment is the antagonist.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, stateRequirements = listOf(FirstConversation), theme = T),
        DialogueLine("trti_morning", A,
            "Bed made, mug rinsed, and suddenly the whole place behaves? Two minutes of theft from chaos. I love a heist.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning),
            cooldownGroup = "trti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trti_morning_early", A,
            "Awake before the kettle? Sneak a kitchen wipe in before coffee — the mess won't even see it coming.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Morning, IsWeekday),
            cooldownGroup = "trti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trti_afternoon", A,
            "Halfway through and the surfaces are winning. Clear one — just one — and tonight-you will owe me a favour.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Afternoon),
            cooldownGroup = "trti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trti_evening", A,
            "The day's nearly done. Ten-minute sweep now, and you wake up to a non-disaster? Devious little plot twist.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Evening),
            cooldownGroup = "trti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trti_night_late", A,
            "It's late and I can see you eyeing the whole bookshelf. No. Just the dishes, you gremlin. We reorganise tomorrow.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(TimeOfDay_Night),
            cooldownGroup = "trti_greet", cooldownPicks = 3, theme = T),
        DialogueLine("trti_post_apotheosis", A,
            "Plot twist: the apartment is liveable. Keep the ten-minute habit.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterApotheosis_24h), theme = T),

        DialogueLine("trti_monday", A,
            "The week's back for round two. Living room first, two surfaces — let's ambush it before it's had its coffee.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsMonday, TimeOfDay_Morning),
            cooldownGroup = "trti_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trti_friday", A,
            "Five days survived. A twenty-minute sweep now, and weekend-you gets to lounge somewhere that isn't a crime scene.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsFriday),
            cooldownGroup = "trti_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.THIS_WEEK, theme = T),
        DialogueLine("trti_weekend", A,
            "Nobody's watching and the list still exists — rude. One deep-clean, bathroom or kitchen. Pick. Not both, hero.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(IsWeekend),
            cooldownGroup = "trti_weekmarker", cooldownPicks = 1,
            recencyKey = RecencyKey.TODAY, theme = T),

        DialogueLine("trti_level_1_reached", A,
            "A whole week of rituals and the apartment's stopped being a hazard? Level one, and I called it. Obviously.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_1),
            cooldownGroup = "trti_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trti_level_2_reached", A,
            "Level two, and now friends notice the vibes. Say nothing, look mysterious — let them think you were born like this.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_2),
            cooldownGroup = "trti_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trti_level_3_reached", A,
            "Level three? You're officially the friend whose place is always guest-ready. What a magnificent con. I'm proud.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_3),
            cooldownGroup = "trti_level_xform", cooldownPicks = 999, theme = T),
        DialogueLine("trti_level_4_reached", A,
            "Top of the tree — years of clear space and the mind to match. You're insufferable now, and I couldn't be prouder.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            lifeEvent = true, recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(LevelExactly_4),
            cooldownGroup = "trti_level_xform", cooldownPicks = 999, theme = T),

        DialogueLine("trti_attention_loss_mild", A,
            "Three days and the pile's been quietly gloating. Rude. A two-minute counter wipe wipes the smirk right off it.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_3),
            cooldownGroup = "trti_atten_loss", cooldownPicks = 2, theme = T),
        DialogueLine("trti_attention_loss_hard", A,
            "Two weeks of glorious chaos — the makings of a comeback nobody saw coming. One surface today starts the reversal.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trti_atten_loss", cooldownPicks = 2, theme = T),

        DialogueLine("trti_after_lapse", A,
            "Yesterday you tidied precisely nothing. Bold. Today we do one surface and pretend it was the plan all along.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.SCREEN,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true,
            choices = listOf(DialogueChoice("Fine, narrator", null)), theme = T),
        DialogueLine("trti_mid_day_return", A,
            "We've hit halftime and the scoreboard's blank. Ten-minute timer, one room — and yes, I'm absolutely timing you.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            preferredSurface = PreferredSurface.INLINE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, ForegroundFloor_3h),
            cooldownGroup = "mid_day_return", cooldownPicks = 2, theme = T),
        DialogueLine("trti_wishes_pending", A,
            "Earned coupons from the set-decorator gods. Spend one — buy something cute.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(WishesAvailable_1),
            cooldownGroup = "trti_wish_nudge", cooldownPicks = 4, theme = T),
        DialogueLine("trti_mid_streak", A,
            "Three days running and the apartment sent a thank-you note. Deeply weird. Don't stop — you've got it spooked.",
            LineTier.CONTEXTUAL, LineCategory.OPENER,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trti_streak", cooldownPicks = 5, theme = T),

        DialogueLine("trti_sant_jordi", A,
            "It's Sant Jordi, roses incoming from every direction. Clear the entrance first — nowhere to put a bouquet is tragic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJordi),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_la_merce", A,
            "Mercè means you're out all night. Clear one surface before you bolt, and 3am-you will practically weep with gratitude.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnLaMerce),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_sant_joan", A,
            "Bonfire night — beach bag packed, towel already hung to dry? That's not chores, that's plot armour. We plan ahead.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantJoan),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_diada", A,
            "Big flags, long day out there. A sneaky twenty-minute reset before you leave — suspiciously efficient of us, no?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDiada),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_nadal", A,
            "Nadal, and the family's about to descend. Reset the living room — let them think this effortless glow is just how you live.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnNadal),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_cap_d_any", A,
            "Fresh year, blank slate — the stats say resolutions die by the 12th. A big two-day sweep to make the stats look stupid?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAny),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trti_reis", A,
            "Gift morning, and the floor's now mostly wrapping and toys. One sweep before bed — purely tactical, I promise.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnReis),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_carnaval", A,
            "Carnaval — the whole city's officially in costume. The pile will erupt; just note it tonight, sort it tomorrow.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCarnaval),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_divendres_sant", A,
            "The whole city's gone quiet today — suspicious. Let's use it: one drawer, slow and smug. Absurdly satisfying.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnDivendresSant),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_pasqua", A,
            "Pasqua means a hike. Prep the bag, tidy before you bolt — come home to a clean place like the reliable genius you are.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnPasqua),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_festa_del_treball", A,
            "Workers' Day — we honour work by doing none of it. Except one sneaky home-office reset, so tomorrow-you wins big.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaDelTreball),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_festa_major_gracia", A,
            "Gràcia's gone full craft-explosion again. The entrance will take the hit — a daily sweep keeps it from staging a coup.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnFestaMajorGracia),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_assumpcio", A,
            "The whole city fled to the coast and left us the keys. Closet sweep, donate the regrets — deliciously cleansing.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnAssumpcio),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_hispanitat", A,
            "A free day handed to us on a plate. One drawer, slow and satisfying — practically cinematic. Nobody has to know.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnHispanitat),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_castanyada", A,
            "Chestnut smoke in the air — autumn's here. Swap the textiles and the cosy era loads right in. Our little seasonal heist.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCastanyada),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_constitucio", A,
            "One nod at a document and the country vanishes for a bridge weekend. Two hours, loud music, kitchen deep-clean. In?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnConstitucio),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_immaculada", A,
            "Behold the pont — five days conjured from pure audacity. One full room reset earns you the other four as naps. Deal?",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnImmaculada),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_sant_esteve", A,
            "Sequel to the feast: leftovers reign and the wrapping needs recycling. Clear it and watch the room re-emerge. Magic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnSantEsteve),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_cap_d_any_eve", A,
            "Last day of the year, guests inbound. A ten-minute sweep, and you close the whole thing out on a clean stage. Iconic.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(OnCapDAnyEve),
            cooldownGroup = "trti_holiday", cooldownPicks = 1, theme = T),

        DialogueLine("trti_birthday", A,
            "It's your birthday, so one line of sincerity: clear a single surface, then sit and be the protagonist. Back to sass now.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsBirthday),
            cooldownGroup = "trti_birthday", cooldownPicks = 1, theme = T),
        DialogueLine("trti_personal_date", A,
            "Ah, the one you flagged: {label}. Reset your favourite room to mark it — I prepared zero jokes about it. You're welcome.",
            LineTier.ESSENTIAL, LineCategory.OPENER,
            recencyKey = RecencyKey.TODAY, lifeEvent = true,
            stateRequirements = listOf(IsPersonalDate),
            cooldownGroup = "trti_personal", cooldownPicks = 1, theme = T),

        DialogueLine("trti_complete_1", A, "You tidied it. Set-dressing officially acquired for the next scene.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trti_complete_2", A, "Surface slayed. The narrator approves.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trti_complete_3", A, "Done, and the set just filed a quietly glowing review.",
            LineTier.FILLER, LineCategory.COMPLETION, theme = T),
        DialogueLine("trti_complete_first_today", A,
            "First reset. The vibe shifted. I felt it through the screen.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_1),
            cooldownGroup = "trti_first_today", cooldownPicks = 6, theme = T),
        DialogueLine("trti_complete_second_today", A,
            "Two resets already — compound order is forming, and it's suspiciously productive of you.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_2),
            cooldownGroup = "trti_2_today", cooldownPicks = 6, theme = T),
        DialogueLine("trti_complete_third_today", A,
            "Three, and the mind's finally matching the room. The bit is genuinely paying off.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_3),
            cooldownGroup = "trti_3_today", cooldownPicks = 6, theme = T),
        DialogueLine("trti_complete_fourth_today", A,
            "Four? Either it's a big sweep day or you're procrastinating something bigger. Be honest.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(MinorsToday_4),
            cooldownGroup = "trti_4_today", cooldownPicks = 6, theme = T),
        DialogueLine("trti_complete_fifth_today", A,
            "Five. The place is glowing now — sit down, put your feet up, enjoy the set you built.",
            LineTier.ESSENTIAL, LineCategory.COMPLETION,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(MinorsToday_5),
            cooldownGroup = "trti_5_today", cooldownPicks = 1, theme = T),
        DialogueLine("trti_complete_after_streak", A,
            "Three days of rituals running, and the place is thriving. The mind followed right along.",
            LineTier.CONTEXTUAL, LineCategory.COMPLETION,
            stateRequirements = listOf(Streak_3),
            cooldownGroup = "trti_streak_complete", cooldownPicks = 4, theme = T),

        DialogueLine("trti_apotheosis_1", A,
            "You actually finished the block — the set's become the bit's most loyal fan. Reward it.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trti_apotheosis_2", A,
            "That's a wrap on this cycle. Pick the next tidy goal — smaller, weirder, better.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trti_apotheosis_3", A,
            "You closed it out — clear-space WIN, and the narrator is nodding, however briefly.",
            LineTier.CONTEXTUAL, LineCategory.APOTHEOSIS, theme = T),
        DialogueLine("trti_apotheosis_first_ever", A,
            "Your first closed block, and the ten-minute tidy is canon now. Wildly inconvenient. Keep going.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            lifeEvent = true, stateRequirements = listOf(MajorsClosed_1),
            forbids = listOf("trti_apotheosis_1", "trti_apotheosis_2", "trti_apotheosis_3"),
            theme = T),
        DialogueLine("trti_apotheosis_at_level_2", A,
            "Basically a promotion — the house is always guest-ready now. Defend that ritual fiercely.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_2),
            cooldownGroup = "trti_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trti_apotheosis_at_level_3", A,
            "You've hit senior tier. Friends ask how, and you invent a secret — keep the legend alive.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_3),
            cooldownGroup = "trti_apotheosis_levelband", cooldownPicks = 3, theme = T),
        DialogueLine("trti_apotheosis_at_level_4", A,
            "Top tier, after years of clear space — the mind and the room have finally started agreeing.",
            LineTier.ESSENTIAL, LineCategory.APOTHEOSIS,
            stateRequirements = listOf(Level_4),
            cooldownGroup = "trti_apotheosis_levelband", cooldownPicks = 3, theme = T),

        DialogueLine("trti_nudge_morning", A,
            "A two-minute kitchen reset starts the day non-feral — small heist, big difference by tonight.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Morning, HasOpenMajors),
            cooldownGroup = "trti_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trti_nudge_afternoon_zero", A,
            "Ten-minute timer, one room, go — and yes, the narrator is absolutely timing this.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Afternoon, MinorsCompletedTodayIsZero, HasOpenMajors),
            cooldownGroup = "trti_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trti_nudge_evening", A,
            "Ten-minute sweep before bed. Tomorrow's opening shot deserves better.",
            LineTier.CONTEXTUAL, LineCategory.NUDGE,
            stateRequirements = listOf(TimeOfDay_Evening, HasOpenMajors),
            cooldownGroup = "trti_nudge", cooldownPicks = 1, crossSurfaceCooldown = true,
            theme = T),
        DialogueLine("trti_nudge_lapse", A,
            "Yesterday got skipped entirely. Today, one surface — the curtain rises on a much better scene.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AfterLapse_1),
            cooldownGroup = LAPSE_REACTIVE_COOLDOWN,
            cooldownPicks = 1, crossSurfaceCooldown = true, theme = T),
        DialogueLine("trti_nudge_attention_loss", A,
            "The set decorator's filed a missing-person report on you. One surface today closes the case.",
            LineTier.ESSENTIAL, LineCategory.NUDGE,
            recencyKey = RecencyKey.TODAY,
            stateRequirements = listOf(AttentionLost_10),
            cooldownGroup = "trti_loss_nudge",
            cooldownPicks = 2, crossSurfaceCooldown = true, theme = T),
    )
}
